/**
 * Shared blog data for sitemap, structured data, and blog index.
 * Single source of truth for blog post slugs.
 */

export type BlogPostMeta = {
  slug: string;
  title: string;
  date: string;
  category: string;
};

/** All blog post slugs for sitemap and routing */
export const BLOG_SLUGS = [
  '5-proven-ai-automation-strategies-for-enterprise-workflow-optimization',
  'agentic-ai-autonomous-agents-enterprise-2026',
  'ai-agent-frameworks-for-business-automation',
  'ai-customer-support-playbook',
  'ai-driven-customer-experience-from-chatbots-to-hyper-personalization',
  'ai-finops-and-cloud-cost-optimization-with-machine-learning',
  'ai-for-agriculture-and-agritech',
  'ai-for-audit-and-compliance-automation',
  'ai-for-blockchain-and-web3-operations',
  'ai-for-climate-tech-and-sustainability-operations',
  'ai-for-compliance-and-regulatory-reporting',
  'ai-for-conversation-and-customer-analytics',
  'ai-for-customer-service-and-support-automation',
  'ai-for-cybersecurity-operations-and-threat-hunting',
  'ai-for-cybersecurity-threat-detection',
  'ai-for-digital-transformation-and-change-management',
  'ai-for-document-intelligence-and-intelligent-automation',
  'ai-for-financial-services-automating-risk-compliance-and-customer-growth',
  'ai-for-fintech-and-digital-banking-operations',
  'ai-for-fleet-and-logistics-operations',
  'ai-for-fleet-management-and-logistics-optimization',
  'ai-for-food-and-beverage-operations',
  'ai-for-gaming-and-esports',
  'ai-for-government-services-and-public-sector-automation',
  'ai-for-healthcare-analytics-and-clinical-decision-support',
  'ai-for-hr-and-talent-acquisition-streamlining-recruitment',
  'ai-for-insurance-claims-and-underwriting',
  'ai-for-insurance-underwriting-and-claims-automation',
  'ai-for-legal-tech-and-contract-intelligence',
  'ai-for-media-and-content-production',
  'ai-for-mining-and-natural-resources-operations',
  'ai-for-procurement-and-vendor-management',
  'ai-for-product-development-and-innovation',
  'ai-for-quantum-computing-and-hybrid-workloads',
  'ai-for-real-estate-and-property-management',
  'ai-for-retail-analytics-and-personalization',
  'ai-for-sales-enablement-and-revenue-operations',
  'ai-for-social-good-success-stories-and-best-practices',
  'ai-for-warehousing-and-inventory-optimization',
  'ai-governance-and-responsible-ai-a-practical-enterprise-framework',
  'ai-in-aviation-and-aerospace-operations',
  'ai-in-construction-and-project-management',
  'ai-in-education-and-learning-systems',
  'ai-in-healthcare-how-intelligent-automation-is-transforming-patient-care-in-2026',
  'ai-in-legal-professional-services-automating-contract-review',
  'ai-in-logistics-and-supply-chain-cutting-costs-and-improving-visibility',
  'ai-in-pharmaceuticals-and-life-sciences',
  'ai-in-supply-chain-predictive-inventory-and-demand-forecasting',
  'ai-in-sustainability-and-esg-reporting',
  'ai-observability-and-mlops-best-practices',
  'ai-pilot-to-production',
  'ai-powered-customer-success-reducing-churn-and-driving-expansion',
  'ai-powered-devops-automating-the-entire-software-delivery-lifecycle',
  'ai-security-best-practices-protecting-your-ai-systems-from-emerging-threats',
  'ai-voice-agents-and-conversational-automation',
  'autonomous-ai-agents-the-next-frontier-in-enterprise-automation',
  'building-a-data-driven-culture-with-ai-powered-analytics',
  'building-a-tailored-implementation-roadmap-from-proof-of-concept-to-full-deployment',
  'building-a-winning-ai-team-roles-skills-and-organizational-structure',
  'building-resilient-automation',
  'building-your-first-ai-chatbot-a-step-by-step-technical-guide',
  'cloud-migration-and-ai-modernizing-infrastructure-for-intelligent-workloads',
  'crm-automation-trends-2026-ai-driven-customer-journey-personalization',
  'data-strategy-for-ai-building-the-foundation-for-machine-learning-success',
  'devops-ai-integration',
  'devops-automation-with-ai-reducing-deployment-failures-by-60',
  'edge-ai-and-iot-deploying-models-at-the-edge',
  'generative-ai-for-content-and-creative-workflows',
  'how-to-calculate-ai-roi-a-framework-for-enterprise-decision-makers',
  'implementing-ai-powered-document-processing-from-paper-to-insights',
  'low-code-and-no-code-ai-for-rapid-deployment',
  'measuring-ai-roi',
  'migrating-to-cloud-native-ai-a-step-by-step-guide',
  'multimodal-ai-vision-and-language-models-in-enterprise',
  'rag-for-enterprise-knowledge-bases',
  'responsible-ai-practices-for-enterprise-deployment',
  'retail-ai-playbook-personalization-inventory-and-customer-experience-at-scale',
  'securing-ai-models-a-practical-guide-to-threat-mitigation-in-production',
  'security-first-ai-deployment',
  'small-business-ai-adoption-guide-start-fast-scale-smart',
  'smart-manufacturing-how-ai-is-powering-the-next-industrial-revolution',
  'the-complete-guide-to-ai-powered-predictive-analytics-for-business',
  'the-future-of-work-how-ai-is-redefining-every-role-in-the-enterprise',
  'the-future-of-work-how-ai-is-revolutionizing-the-job-market',
  'the-role-of-explainable-ai-in-regulatory-compliance',
  'top-10-ai-trends-reshaping-enterprise-technology-in-2026',
  'vector-databases-and-enterprise-rag-systems',
] as const;
