const fs = require('fs');
const path = require('path');
const servicesPath = path.join(__dirname, 'app/data/servicesData.json');
const services = JSON.parse(fs.readFileSync(servicesPath, 'utf8'));

const newServices = [
  { "id": "ai-email-encryption-engine", "title": "AI Email Encryption Engine", "description": "End-to-end encryption for sensitive emails with automatic detection, PGP/S/MIME support, and compliance logging. Protects SSN, credit cards, passwords, and financial data.", "category": "Security Services", "icon": "🔐", "price": "$89/month", "features": ["Auto-encryption", "PGP/S/MIME", "Sensitive data detection", "Compliance logging"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }},
  { "id": "secure-email-gateway", "title": "Secure Email Gateway Pro", "description": "Enterprise-grade email security gateway with encryption, DLP, and threat protection. Blocks 99.9% of threats and ensures compliance.", "category": "Security Services", "icon": "🛡️", "price": "$129/month", "features": ["Threat protection", "DLP", "Encryption", "Compliance"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }},
  { "id": "ai-email-scheduling-pro", "title": "AI Email Scheduling Pro", "description": "Advanced AI scheduling with optimal send times, timezone coordination, and recipient behavior analysis. Increases response rates by 40%.", "category": "Productivity Services", "icon": "⏰", "price": "$59/month", "features": ["Optimal timing", "Timezone coordination", "Behavior analysis", "Calendar sync"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }},
  { "id": "smart-email-scheduler", "title": "Smart Email Scheduler", "description": "AI-powered email scheduling that learns recipient patterns and sends at optimal times. Integrates with all major calendars.", "category": "Productivity Services", "icon": "📅", "price": "$44/month", "features": ["AI scheduling", "Pattern learning", "Calendar integration", "Timezone support"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }},
  { "id": "ai-email-analytics-dashboard", "title": "AI Email Analytics Dashboard", "description": "Real-time email performance metrics with AI insights. Track open rates, response times, engagement scores, and get actionable recommendations.", "category": "Analytics Services", "icon": "📊", "price": "$79/month", "features": ["Real-time metrics", "AI insights", "Engagement scoring", "Trend analysis"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }},
  { "id": "email-performance-tracker", "title": "Email Performance Tracker", "description": "Comprehensive email performance tracking with detailed analytics, A/B testing results, and ROI calculations.", "category": "Analytics Services", "icon": "📈", "price": "$69/month", "features": ["Performance tracking", "A/B testing", "ROI calculation", "Detailed reports"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }},
  { "id": "ai-email-template-generator", "title": "AI Email Template Generator", "description": "AI-powered email template generation with personalization, A/B variants, and best practices. Create professional emails in seconds.", "category": "AI Services", "icon": "📝", "price": "$49/month", "features": ["AI generation", "Personalization", "A/B variants", "Best practices"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }},
  { "id": "email-template-library-pro", "title": "Email Template Library Pro", "description": "500+ professional email templates for every business scenario. Customizable with AI assistance and performance tracking.", "category": "Productivity Services", "icon": "📄", "price": "$39/month", "features": ["500+ templates", "AI customization", "Performance tracking", "Multi-category"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }},
  { "id": "ai-email-collaboration-hub", "title": "AI Email Collaboration Hub", "description": "Team email collaboration with shared inbox, comments, assignments, and workflow tracking. Perfect for sales, support, and project teams.", "category": "Collaboration Services", "icon": "👥", "price": "$89/month", "features": ["Shared inbox", "Team comments", "Task assignments", "Workflow tracking"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }},
  { "id": "team-email-workspace", "title": "Team Email Workspace", "description": "Collaborative email workspace for teams. Share, comment, assign, and track emails together. Reduces response times by 50%.", "category": "Collaboration Services", "icon": "🤝", "price": "$79/month", "features": ["Team collaboration", "Shared threads", "Mentions", "Activity tracking"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }},
  { "id": "email-collaboration-platform", "title": "Email Collaboration Platform", "description": "Enterprise email collaboration with advanced workflows, approval chains, and integration with project management tools.", "category": "Enterprise Services", "icon": "🏢", "price": "$129/month", "features": ["Approval workflows", "Project integration", "Advanced permissions", "Audit trails"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }}
];

let added = 0;
for (const svc of newServices) {
  if (!services.find(s => s.id === svc.id)) { services.push(svc); added++; }
}
fs.writeFileSync(servicesPath, JSON.stringify(services, null, 2));
console.log(`✅ Added ${added} new services. Total: ${services.length}`);
