const fs = require('fs');
const tsFile = 'app/data/servicesData.ts';
let content = fs.readFileSync(tsFile, 'utf8');
const contact = `    contactInfo: { phone: '+1 302 464 0950', email: 'kleber@ziontechgroup.com', address: '364 E Main St STE 1008, Middletown DE 19709' }`;

const entries = [
  { id: 'email-encryption-intelligence-v271', title: 'AI Email Encryption Intelligence V271', description: 'Auto-detects sensitive content and encrypts with AES-256/PGP/S/MIME.', icon: '🔐', category: 'email-intelligence', features: ['Sensitive detection', 'AES-256 encryption', 'PGP/S/MIME', 'Key management', 'HIPAA/SOX compliance', 'Field-level encryption', 'Transport encryption', 'Reply-all enforcement'], pricing: {basic:'129',pro:'379',enterprise:'1199'}, href: '/services/email-encryption-intelligence-v271', popular: true, industry: 'Email Intelligence' },
  { id: 'email-performance-analytics-v272', title: 'AI Email Performance Analytics V272', description: 'Tracks response times, open rates, engagement. Team dashboards and predictive volume analytics.', icon: '📊', category: 'email-intelligence', features: ['Response time tracking', 'Open rate analytics', 'Team dashboards', 'Volume forecasting', 'Engagement metrics', 'Benchmarking', 'Trend analysis', 'Reply-all enforcement'], pricing: {basic:'79',pro:'229',enterprise:'799'}, href: '/services/email-performance-analytics-v272', popular: true, industry: 'Email Intelligence' },
  { id: 'email-campaign-optimizer-v273', title: 'AI Email Campaign Optimizer V273', description: 'A/B tests campaigns automatically, optimizes send times and content, tracks conversions and ROI.', icon: '🎯', category: 'email-intelligence', features: ['A/B testing', 'Send time optimization', 'Content optimization', 'Conversion tracking', 'ROI attribution', 'Campaign analytics', 'Audience segmentation', 'Reply-all enforcement'], pricing: {basic:'99',pro:'279',enterprise:'949'}, href: '/services/email-campaign-optimizer-v273', popular: true, industry: 'Email Intelligence' },
  { id: 'email-search-intelligence-v274', title: 'AI Email Search Intelligence V274', description: 'Semantic search across all emails with natural language queries, smart filters, and relevance ranking.', icon: '🔍', category: 'email-intelligence', features: ['Semantic search', 'NL queries', 'Smart filters', 'Saved searches', 'Entity extraction', 'Relevance ranking', 'Cross-mailbox', 'Reply-all enforcement'], pricing: {basic:'69',pro:'199',enterprise:'699'}, href: '/services/email-search-intelligence-v274', popular: true, industry: 'Email Intelligence' },
  { id: 'email-collaboration-hub-v275', title: 'AI Email Collaboration Hub V275', description: 'Shared inboxes with smart routing, team mentions, assignments, collaborative drafting, approval workflows.', icon: '🤝', category: 'email-intelligence', features: ['Shared inboxes', 'Smart routing', 'Team mentions', 'Assignments', 'Collab drafting', 'Approval workflows', 'Priority mgmt', 'Reply-all enforcement'], pricing: {basic:'89',pro:'249',enterprise:'849'}, href: '/services/email-collaboration-hub-v275', popular: true, industry: 'Email Intelligence' },
  { id: 'ai-conversational-search', title: 'AI Conversational Search Engine', description: 'Natural language search across enterprise data with conversational follow-ups and context retention.', icon: '💬', category: 'ai', features: ['NL search', 'Follow-ups', 'Multi-source answers', 'Context retention', 'Citations', 'Access control', 'Feedback learning', 'API access'], pricing: {basic:'299',pro:'899',enterprise:'2999'}, href: '/services/ai-conversational-search', popular: true, industry: 'Search AI' },
  { id: 'ai-document-intelligence', title: 'AI Document Intelligence Platform', description: 'Extract, classify, and analyze documents. PDFs, scanned images, handwritten text, complex layouts.', icon: '📄', category: 'ai', features: ['Multi-format extraction', 'Handwriting recognition', 'Layout analysis', 'Table extraction', 'Classification', 'Validation', 'Workflow integration', 'API'], pricing: {basic:'199',pro:'599',enterprise:'1999'}, href: '/services/ai-document-intelligence', popular: true, industry: 'Document AI' },
  { id: 'ai-decision-intelligence', title: 'AI Decision Intelligence Platform', description: 'Augment decisions with AI recommendations, scenario analysis, risk assessment, and outcome prediction.', icon: '🧭', category: 'ai', features: ['Recommendations', 'Scenario analysis', 'Risk assessment', 'Outcome prediction', 'What-if modeling', 'Audit trail', 'Bias detection', 'Collaboration'], pricing: {basic:'499',pro:'1499',enterprise:'4999'}, href: '/services/ai-decision-intelligence', popular: true, industry: 'Decision AI' },
  { id: 'it-observability-aiops', title: 'AIOps Observability Platform', description: 'AI-powered IT operations with anomaly detection, root cause analysis, auto-remediation, predictive alerting.', icon: '🔭', category: 'it', features: ['AI anomaly detection', 'Root cause analysis', 'Auto-remediation', 'Predictive alerting', 'Log analytics', 'Metric correlation', 'Topology mapping', 'ITSM integration'], pricing: {basic:'399',pro:'1199',enterprise:'3499'}, href: '/services/it-observability-aiops', popular: true, industry: 'IT Operations' },
  { id: 'it-digital-workspace', title: 'Digital Workspace Platform', description: 'Unified digital workspace with virtual desktops, app orchestration, collaboration tools, security policies.', icon: '🖥️', category: 'it', features: ['Virtual desktops', 'App orchestration', 'Collaboration', 'Security policies', 'BYOD support', 'Offline access', 'Analytics', 'Cost optimization'], pricing: {basic:'15',pro:'35',enterprise:'75'}, href: '/services/it-digital-workspace', popular: true, industry: 'Digital Workspace' },
  { id: 'security-ai-siem', title: 'AI-Powered SIEM Platform', description: 'Next-gen SIEM with AI threat detection, automated investigation, SOAR, compliance reporting.', icon: '🛡️', category: 'security', features: ['AI threat detection', 'Auto investigation', 'SOAR integration', 'Compliance reporting', 'UEBA', 'Threat intel', 'Case management', 'Real-time alerting'], pricing: {basic:'1999',pro:'5999',enterprise:'14999'}, href: '/services/security-ai-siem', popular: true, industry: 'SIEM' },
  { id: 'security-api-security', title: 'API Security Platform', description: 'Discover, protect, and monitor all APIs. Runtime protection, schema validation, rate limiting.', icon: '🔌', category: 'security', features: ['API discovery', 'Runtime protection', 'Schema validation', 'Rate limiting', 'Threat detection', 'Authentication', 'Audit logging', 'Compliance'], pricing: {basic:'499',pro:'1499',enterprise:'4499'}, href: '/services/security-api-security', popular: true, industry: 'API Security' },
  { id: 'data-ai-data-catalog', title: 'AI Data Catalog Platform', description: 'AI-powered data discovery with metadata extraction, lineage tracking, quality scoring, self-service.', icon: '📚', category: 'data', features: ['AI discovery', 'Metadata extraction', 'Lineage tracking', 'Quality scoring', 'Self-service', 'Glossary', 'Access recommendations', 'Collaboration'], pricing: {basic:'399',pro:'1199',enterprise:'3499'}, href: '/services/data-ai-data-catalog', popular: true, industry: 'Data Discovery' },
  { id: 'data-streaming-platform', title: 'Real-Time Streaming Analytics', description: 'Process streaming data with sub-ms latency. Complex event processing, windowed aggregations, ML.', icon: '🌊', category: 'data', features: ['Sub-ms latency', 'Event processing', 'Windowed aggregations', 'ML integration', 'Schema registry', 'Exactly-once', 'Multi-cloud', 'Monitoring'], pricing: {basic:'499',pro:'1499',enterprise:'4499'}, href: '/services/data-streaming-platform', popular: true, industry: 'Stream Processing' },
  { id: 'cloud-ai-infrastructure', title: 'AI Infrastructure Platform', description: 'GPU/TPU cloud for AI training and inference. Auto-scaling, cost optimization, managed ML.', icon: '🧠', category: 'cloud', features: ['GPU/TPU clusters', 'Auto-scaling', 'Cost optimization', 'Managed ML', 'Spot instances', 'Data pipelines', 'Model registry', 'Monitoring'], pricing: {basic:'599',pro:'1799',enterprise:'5499'}, href: '/services/cloud-ai-infrastructure', popular: true, industry: 'AI Infrastructure' },
  { id: 'cloud-data-lakehouse', title: 'Cloud Data Lakehouse Platform', description: 'Unified lakehouse: data lake flexibility with warehouse performance. ACID, time travel.', icon: '🏔️', category: 'cloud', features: ['ACID transactions', 'Time travel', 'Schema evolution', 'Batch/streaming', 'Data sharing', 'Cost optimization', 'Multi-cloud', 'Governance'], pricing: {basic:'499',pro:'1499',enterprise:'4999'}, href: '/services/cloud-data-lakehouse', popular: true, industry: 'Data Platform' },
  { id: 'micro-saas-ai-scheduling', title: 'AI Smart Scheduling Assistant', description: 'AI finds optimal meeting times, handles rescheduling, manages conflicts, learns preferences.', icon: '📅', category: 'micro-saas', features: ['AI time optimization', 'Conflict resolution', 'Auto-rescheduling', 'Preference learning', 'Multi-calendar sync', 'Timezone handling', 'Buffer management', 'Team scheduling'], pricing: {basic:'9',pro:'25',enterprise:'59'}, href: '/services/micro-saas-ai-scheduling', popular: true, industry: 'Productivity' },
  { id: 'micro-saas-ai-note-taking', title: 'AI Note-Taking & Knowledge Base', description: 'AI-powered notes with auto-organization, smart linking, knowledge graph, team collaboration.', icon: '📝', category: 'micro-saas', features: ['AI organization', 'Smart linking', 'Knowledge graph', 'Team collaboration', 'Voice notes', 'OCR scanning', 'Templates', 'Search'], pricing: {basic:'8',pro:'19',enterprise:'49'}, href: '/services/micro-saas-ai-note-taking', popular: true, industry: 'Productivity' },
  { id: 'micro-saas-ai-lead-scoring', title: 'AI Lead Scoring & Qualification', description: 'Automatically score and qualify leads with AI. Behavioral analysis, fit scoring, sales-ready alerts.', icon: '🎯', category: 'micro-saas', features: ['AI lead scoring', 'Behavioral analysis', 'Fit scoring', 'Sales-ready alerts', 'Pipeline analytics', 'CRM integration', 'Custom models', 'A/B testing'], pricing: {basic:'39',pro:'99',enterprise:'349'}, href: '/services/micro-saas-ai-lead-scoring', popular: true, industry: 'Sales Tech' },
  { id: 'micro-saas-ai-social-listening', title: 'AI Social Listening Platform', description: 'Monitor brand mentions, sentiment, trends across social media with AI analysis and alerting.', icon: '👂', category: 'micro-saas', features: ['Brand monitoring', 'Sentiment analysis', 'Trend detection', 'Competitor tracking', 'Influencer ID', 'Crisis alerting', 'Report generation', 'API access'], pricing: {basic:'29',pro:'79',enterprise:'249'}, href: '/services/micro-saas-ai-social-listening', popular: true, industry: 'Social Media' },
  { id: 'automation-ai-workflow-builder', title: 'AI Workflow Builder', description: 'Build workflows with natural language. AI generates automation logic, tests, and deploys.', icon: '🏗️', category: 'automation', features: ['NL builder', 'AI logic generation', 'Auto-testing', 'Production deploy', 'Visual editor', 'Error handling', 'Version control', 'Monitoring'], pricing: {basic:'149',pro:'449',enterprise:'1299'}, href: '/services/automation-ai-workflow-builder', popular: true, industry: 'Workflow Automation' },
  { id: 'automation-data-quality-platform', title: 'AI Data Quality Platform', description: 'Automated data quality with anomaly detection, rule engine, profiling, remediation workflows.', icon: '✅', category: 'automation', features: ['Anomaly detection', 'Rule engine', 'Data profiling', 'Remediation', 'Quality dashboards', 'Lineage', 'Alerting', 'API access'], pricing: {basic:'299',pro:'899',enterprise:'2499'}, href: '/services/automation-data-quality-platform', popular: true, industry: 'Data Quality' },
  { id: 'devops-ai-release-management', title: 'AI Release Management Platform', description: 'AI-powered releases with risk assessment, canary analysis, automated rollbacks, deployment insights.', icon: '🚀', category: 'devops', features: ['Risk assessment', 'Canary analysis', 'Auto-rollback', 'Deploy insights', 'Release trains', 'Feature flags', 'Env management', 'Audit trail'], pricing: {basic:'199',pro:'599',enterprise:'1799'}, href: '/services/devops-ai-release-management', popular: true, industry: 'Release Management' },
  { id: 'devops-cost-intelligence', title: 'DevOps Cost Intelligence Platform', description: 'Track, optimize, forecast infrastructure costs. Right-sizing, waste detection, budget alerting.', icon: '💰', category: 'devops', features: ['Cost tracking', 'Right-sizing', 'Waste detection', 'Budget alerting', 'Forecasting', 'Team attribution', 'RI planning', 'Multi-cloud'], pricing: {basic:'149',pro:'449',enterprise:'1299'}, href: '/services/devops-cost-intelligence', popular: true, industry: 'FinOps' },
  { id: 'iot-industrial-analytics', title: 'Industrial IoT Analytics Platform', description: 'Real-time manufacturing analytics with OEE tracking, quality monitoring, energy optimization.', icon: '🏭', category: 'iot', features: ['OEE tracking', 'Quality monitoring', 'Energy optimization', 'Predictive alerts', 'Production analytics', 'ML integration', 'Dashboard builder', 'API access'], pricing: {basic:'699',pro:'2099',enterprise:'6499'}, href: '/services/iot-industrial-analytics', popular: true, industry: 'Industrial IoT' },
  { id: 'iot-connected-vehicle', title: 'Connected Vehicle Platform', description: 'IoT for connected vehicles: real-time tracking, telematics, OTA updates, fleet analytics.', icon: '🚗', category: 'iot', features: ['Real-time tracking', 'Telematics', 'OTA updates', 'Fleet analytics', 'Driver behavior', 'Fuel optimization', 'Predictive maintenance', 'Geofencing'], pricing: {basic:'399',pro:'1199',enterprise:'3499'}, href: '/services/iot-connected-vehicle', popular: true, industry: 'Automotive IoT' }
];

const tsEntries = entries.map(s => `  {
    id: '${s.id}',
    title: '${s.title}',
    description: '${s.description}',
    icon: '${s.icon}',
    category: '${s.category}',
    features: [${s.features.map(f => `'${f}'`).join(', ')}],
    pricing: { basic: '${s.pricing.basic}', pro: '${s.pricing.pro}', enterprise: '${s.pricing.enterprise}' },
    href: '${s.href}',
    popular: ${s.popular},
    industry: '${s.industry}',
${contact}
  }`).join(',\n');

const closingPattern = /\n\];\s*\nexport const getServiceById/;
const match = content.match(closingPattern);
if (match) {
  content = content.replace(closingPattern, ',\n' + tsEntries + '\n];\n\nexport const getServiceById');
  fs.writeFileSync(tsFile, content);
  console.log('Added ' + entries.length + ' entries to TypeScript');
} else {
  console.log('ERROR: insertion point not found');
}
