const fs = require('fs');
const tsFile = 'app/data/servicesData.ts';
let content = fs.readFileSync(tsFile, 'utf8');

const contact = `    contactInfo: { phone: '+1 302 464 0950', email: 'kleber@ziontechgroup.com', address: '364 E Main St STE 1008, Middletown DE 19709' }`;

const newEntries = [
  { id: 'email-workflow-automation-v256', title: 'AI Email Workflow Automation V256', description: 'Detects repetitive email patterns and automates workflows. Triggers actions based on content, chains multiple actions, self-learning suggestions.', icon: '🔄', category: 'email-intelligence', features: ['Pattern detection', 'Automated actions', 'Workflow chaining', 'Self-learning', 'Ticket creation', 'CRM updates', 'Meeting scheduling', 'Reply-all enforcement'], pricing: {basic:'79',pro:'229',enterprise:'799'}, href: '/services/email-workflow-automation-v256', popular: true, industry: 'Email Intelligence' },
  { id: 'email-intent-classifier-v257', title: 'AI Email Intent Classifier Pro V257', description: '50+ intent categories with ML classification, multi-intent detection, confidence scoring, and custom intent training.', icon: '🎯', category: 'email-intelligence', features: ['50+ intent categories', 'Multi-intent detection', 'Confidence scoring', 'Custom training', 'Real-time classification', 'Intent history', 'Accuracy tracking', 'Reply-all enforcement'], pricing: {basic:'89',pro:'249',enterprise:'849'}, href: '/services/email-intent-classifier-v257', popular: true, industry: 'Email Intelligence' },
  { id: 'email-dlp-guardian-v258', title: 'AI Email Data Loss Prevention V258', description: 'Scans for sensitive data (PII, financial, credentials), auto-redacts before sending, enforces GDPR/HIPAA/SOX/PCI-DSS compliance.', icon: '🔐', category: 'email-intelligence', features: ['Sensitive data scanning', 'Auto-redaction', 'GDPR compliance', 'HIPAA compliance', 'SOX compliance', 'PCI-DSS compliance', 'Violation alerts', 'Reply-all enforcement'], pricing: {basic:'149',pro:'399',enterprise:'1299'}, href: '/services/email-dlp-guardian-v258', popular: true, industry: 'Email Intelligence' },
  { id: 'email-analytics-dashboard-v259', title: 'AI Email Analytics & Insights V259', description: 'Track response rates, email volume trends, peak hours, team performance metrics, and predictive email analytics.', icon: '📊', category: 'email-intelligence', features: ['Response rate tracking', 'Volume trend analysis', 'Peak hour detection', 'Team performance', 'Predictive analytics', 'Custom dashboards', 'Export reports', 'Reply-all enforcement'], pricing: {basic:'69',pro:'199',enterprise:'699'}, href: '/services/email-analytics-dashboard-v259', popular: true, industry: 'Email Intelligence' },
  { id: 'email-multi-stakeholder-v260', title: 'AI Multi-Stakeholder Coordinator V260', description: 'Handles complex multi-party threads, tracks who said what, extracts per-person action items, detects consensus.', icon: '👥', category: 'email-intelligence', features: ['Thread tracking', 'Per-person action items', 'Consensus detection', 'Thread splitting', 'Decision tracking', 'Stakeholder mapping', 'Meeting coordination', 'Reply-all enforcement'], pricing: {basic:'99',pro:'279',enterprise:'949'}, href: '/services/email-multi-stakeholder-v260', popular: true, industry: 'Email Intelligence' },
  { id: 'ai-video-analytics', title: 'AI Video Analytics Platform', description: 'Analyze video content with object detection, activity recognition, sentiment analysis, and automated tagging.', icon: '🎥', category: 'ai', features: ['Object detection', 'Activity recognition', 'Sentiment analysis', 'Auto-tagging', 'Real-time processing', 'Face recognition', 'Scene understanding', 'API integration'], pricing: {basic:'399',pro:'1199',enterprise:'3499'}, href: '/services/ai-video-analytics', popular: true, industry: 'Computer Vision' },
  { id: 'ai-fraud-detection', title: 'AI Fraud Detection System', description: 'Real-time fraud detection with ML anomaly detection, behavioral analysis, transaction scoring, and automated alerts.', icon: '🛡️', category: 'ai', features: ['ML anomaly detection', 'Behavioral analysis', 'Transaction scoring', 'Real-time alerts', 'Pattern recognition', 'Risk assessment', 'Compliance reporting', 'API integration'], pricing: {basic:'799',pro:'2499',enterprise:'7999'}, href: '/services/ai-fraud-detection', popular: true, industry: 'FinTech' },
  { id: 'ai-personalization-engine', title: 'AI Personalization Engine', description: 'Deliver personalized experiences with real-time recommendations, dynamic content, A/B testing, and journey optimization.', icon: '🎨', category: 'ai', features: ['Real-time recommendations', 'Dynamic content', 'A/B testing', 'Journey optimization', 'Segmentation', 'Behavioral targeting', 'Multi-channel', 'Analytics'], pricing: {basic:'299',pro:'899',enterprise:'2999'}, href: '/services/ai-personalization-engine', popular: true, industry: 'Marketing' },
  { id: 'it-endpoint-management', title: 'Unified Endpoint Management (UEM)', description: 'Manage all devices from single console. Zero-touch provisioning, security policies, app deployment.', icon: '💻', category: 'it', features: ['Multi-platform support', 'Zero-touch provisioning', 'Security policies', 'App deployment', 'Patch management', 'Remote wipe', 'Compliance monitoring', 'Analytics'], pricing: {basic:'8',pro:'15',enterprise:'25'}, href: '/services/it-endpoint-management', popular: true, industry: 'Device Management' },
  { id: 'it-service-desk-ai', title: 'AI-Powered IT Service Desk', description: 'Intelligent ticket routing, auto-resolution, knowledge base suggestions, chatbot support, and SLA management.', icon: '🎫', category: 'it', features: ['AI ticket routing', 'Auto-resolution', 'Knowledge base AI', 'Chatbot support', 'SLA management', 'Self-service portal', 'Analytics', 'Integration hub'], pricing: {basic:'15',pro:'35',enterprise:'75'}, href: '/services/it-service-desk-ai', popular: true, industry: 'IT Support' },
  { id: 'security-identity-governance', title: 'Identity Governance & Administration (IGA)', description: 'Manage user identities, access rights, role-based access control, automated provisioning, and compliance reporting.', icon: '🔑', category: 'security', features: ['Identity lifecycle', 'RBAC', 'Automated provisioning', 'Access reviews', 'SoD enforcement', 'Compliance reporting', 'Self-service', 'Analytics'], pricing: {basic:'12',pro:'25',enterprise:'50'}, href: '/services/security-identity-governance', popular: true, industry: 'Identity Security' },
  { id: 'security-threat-intelligence', title: 'Threat Intelligence Platform', description: 'Aggregate threat feeds, correlate indicators, prioritize risks, and automate threat response.', icon: '🎯', category: 'security', features: ['Threat feed aggregation', 'Indicator correlation', 'Risk prioritization', 'Automated response', 'Threat hunting', 'IOC management', 'Intelligence sharing', 'Reporting'], pricing: {basic:'1999',pro:'5999',enterprise:'14999'}, href: '/services/security-threat-intelligence', popular: true, industry: 'Threat Intelligence' },
  { id: 'data-master-data-management', title: 'Master Data Management (MDM)', description: 'Single source of truth for critical data. Data quality, deduplication, governance, and multi-domain MDM.', icon: '🎯', category: 'data', features: ['Multi-domain MDM', 'Data quality', 'Deduplication', 'Governance workflows', 'Data stewardship', 'Match & merge', 'Hierarchy management', 'API access'], pricing: {basic:'999',pro:'2999',enterprise:'8999'}, href: '/services/data-master-data-management', popular: true, industry: 'Data Management' },
  { id: 'data-privacy-management', title: 'Data Privacy Management Platform', description: 'Automate GDPR/CCPA compliance. Consent management, data mapping, DSAR automation, privacy impact assessments.', icon: '🔒', category: 'data', features: ['Consent management', 'Data mapping', 'DSAR automation', 'Privacy assessments', 'Breach notification', 'Policy management', 'Vendor risk', 'Reporting'], pricing: {basic:'499',pro:'1499',enterprise:'4499'}, href: '/services/data-privacy-management', popular: true, industry: 'Privacy' },
  { id: 'cloud-kubernetes-management', title: 'Kubernetes Management Platform', description: 'Multi-cluster Kubernetes management with auto-scaling, cost optimization, security policies, and observability.', icon: '☸️', category: 'cloud', features: ['Multi-cluster', 'Auto-scaling', 'Cost optimization', 'Security policies', 'Observability', 'GitOps', 'Service mesh', 'Backup & DR'], pricing: {basic:'299',pro:'899',enterprise:'2499'}, href: '/services/cloud-kubernetes-management', popular: true, industry: 'Container Orchestration' },
  { id: 'cloud-serverless-platform', title: 'Serverless Application Platform', description: 'Deploy and manage serverless applications across AWS Lambda, Azure Functions, and Google Cloud Functions.', icon: '⚡', category: 'cloud', features: ['Multi-cloud serverless', 'Deployment automation', 'Monitoring & debugging', 'Cost tracking', 'Performance optimization', 'Cold start reduction', 'Security scanning', 'CI/CD integration'], pricing: {basic:'149',pro:'449',enterprise:'1299'}, href: '/services/cloud-serverless-platform', popular: true, industry: 'Serverless' },
  { id: 'micro-saas-form-builder', title: 'Advanced Form Builder & Surveys', description: 'Create complex forms with conditional logic, file uploads, payments, e-signatures, and advanced analytics.', icon: '📝', category: 'micro-saas', features: ['Conditional logic', 'File uploads', 'Payment integration', 'E-signatures', 'Advanced analytics', '100+ templates', 'Workflow automation', 'API access'], pricing: {basic:'19',pro:'49',enterprise:'149'}, href: '/services/micro-saas-form-builder', popular: true, industry: 'Forms & Surveys' },
  { id: 'micro-saas-time-tracking', title: 'AI Time Tracking & Productivity', description: 'Automatic time tracking, productivity insights, project budgeting, team analytics, and 100+ integrations.', icon: '⏱️', category: 'micro-saas', features: ['Auto time tracking', 'Productivity insights', 'Project budgeting', 'Team analytics', '100+ integrations', 'Invoicing', 'Reporting', 'Mobile apps'], pricing: {basic:'9',pro:'19',enterprise:'39'}, href: '/services/micro-saas-time-tracking', popular: true, industry: 'Productivity' },
  { id: 'micro-saas-chatbot-builder', title: 'AI Chatbot Builder Platform', description: 'Build intelligent chatbots with NLP, multi-channel deployment, conversation flows, analytics, and CRM integration.', icon: '💬', category: 'micro-saas', features: ['NLP-powered', 'Multi-channel', 'Conversation flows', 'Analytics', 'CRM integration', 'Custom training', 'A/B testing', 'Live chat handoff'], pricing: {basic:'39',pro:'99',enterprise:'299'}, href: '/services/micro-saas-chatbot-builder', popular: true, industry: 'Customer Engagement' },
  { id: 'micro-saas-ecommerce-platform', title: 'AI E-commerce Platform', description: 'Complete e-commerce solution with AI product recommendations, inventory management, payment processing, and marketing automation.', icon: '🛒', category: 'micro-saas', features: ['AI recommendations', 'Inventory management', 'Payment processing', 'Marketing automation', 'Multi-channel selling', 'Analytics', 'SEO optimization', 'Mobile app'], pricing: {basic:'49',pro:'149',enterprise:'499'}, href: '/services/micro-saas-ecommerce-platform', popular: true, industry: 'E-commerce' },
  { id: 'automation-document-processing', title: 'Intelligent Document Processing (IDP)', description: 'Extract data from documents with AI OCR, classify documents, validate data, and integrate with business systems.', icon: '📄', category: 'automation', features: ['AI OCR', 'Document classification', 'Data extraction', 'Validation rules', 'Multi-format support', 'Human-in-the-loop', 'API integration', 'Audit trail'], pricing: {basic:'299',pro:'899',enterprise:'2499'}, href: '/services/automation-document-processing', popular: true, industry: 'Document Processing' },
  { id: 'automation-testing-platform', title: 'AI Test Automation Platform', description: 'Automated testing with AI test generation, visual testing, cross-browser testing, and CI/CD integration.', icon: '🧪', category: 'automation', features: ['AI test generation', 'Visual testing', 'Cross-browser testing', 'CI/CD integration', 'Parallel execution', 'Test analytics', 'Flaky test detection', 'Self-healing tests'], pricing: {basic:'199',pro:'599',enterprise:'1799'}, href: '/services/automation-testing-platform', popular: true, industry: 'QA & Testing' },
  { id: 'devops-infrastructure-as-code', title: 'Infrastructure as Code (IaC) Platform', description: 'Manage infrastructure with Terraform, Pulumi, and CloudFormation. Policy as code, drift detection, cost estimation.', icon: '🏗️', category: 'devops', features: ['Multi-tool support', 'Policy as code', 'Drift detection', 'Cost estimation', 'GitOps workflows', 'State management', 'Security scanning', 'Collaboration'], pricing: {basic:'149',pro:'449',enterprise:'1299'}, href: '/services/devops-infrastructure-as-code', popular: true, industry: 'Infrastructure' },
  { id: 'devops-observability-platform', title: 'Full-Stack Observability Platform', description: 'Unified monitoring with logs, metrics, traces, and APM. AI-powered anomaly detection and root cause analysis.', icon: '📈', category: 'devops', features: ['Logs, metrics, traces', 'APM', 'AI anomaly detection', 'Root cause analysis', 'SLO management', 'Distributed tracing', 'Custom dashboards', 'Alerting'], pricing: {basic:'99',pro:'299',enterprise:'899'}, href: '/services/devops-observability-platform', popular: true, industry: 'Monitoring' },
  { id: 'iot-fleet-management', title: 'IoT Fleet Management Platform', description: 'Manage 100,000+ IoT devices with remote monitoring, OTA updates, security policies, and real-time analytics.', icon: '📡', category: 'iot', features: ['Device management', 'OTA updates', 'Security policies', 'Real-time analytics', 'Geofencing', 'Alerting', 'API access', 'Device simulator'], pricing: {basic:'499',pro:'1499',enterprise:'4499'}, href: '/services/iot-fleet-management', popular: true, industry: 'IoT' },
  { id: 'iot-edge-computing', title: 'IoT Edge Computing Platform', description: 'Process data at the edge with low latency, offline capabilities, AI inference, and secure device-to-cloud communication.', icon: '⚡', category: 'iot', features: ['Edge processing', 'Low latency', 'Offline capabilities', 'AI inference', 'Secure communication', 'Container support', 'Remote management', 'Analytics'], pricing: {basic:'299',pro:'899',enterprise:'2499'}, href: '/services/iot-edge-computing', popular: true, industry: 'Edge Computing' }
];

const tsEntries = newEntries.map(s => `  {
    id: '${s.id}',
    title: '${s.title}',
    description: '${s.description}',
    icon: '${s.icon}',
    category: '${s.category}',
    features: [${s.features.map(f => `'${f}'`).join(', ')}],
    pricing: {
      basic: '${s.pricing.basic}',
      pro: '${s.pricing.pro}',
      enterprise: '${s.pricing.enterprise}'
    },
    href: '${s.href}',
    popular: ${s.popular},
    industry: '${s.industry}',
${contact}
  }`).join(',\n');

const closingPattern = /\n\];\s*\nexport const getServiceById/;
const match = content.match(closingPattern);
if (match) {
  content = content.replace(closingPattern, ',\n' + tsEntries + '\n];\n\nexport const getServiceById');
  fs.writeFileSync(tsFile, content);
  console.log('Added ' + newEntries.length + ' entries to TypeScript file');
} else {
  console.log('ERROR: Could not find insertion point');
}
