const fs = require('fs');
const path = require('path');
const servicesPath = path.join(__dirname, 'app/data/servicesData.json');
const services = JSON.parse(fs.readFileSync(servicesPath, 'utf8'));

const newServices = [
  { "id": "ai-email-signature-manager", "title": "AI Email Signature Manager", "description": "Dynamic, branded email signatures with tracking pixels, legal disclaimers, and A/B testing. Ensures brand consistency across all team members.", "category": "Marketing Services", "icon": "✍️", "price": "$29/month", "features": ["Dynamic signatures", "Brand consistency", "Tracking pixels", "Legal compliance"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }},
  { "id": "professional-email-signatures", "title": "Professional Email Signatures Pro", "description": "Create and manage professional email signatures for your entire organization. Includes social links, tracking, and compliance features.", "category": "Micro-SaaS", "icon": "📝", "price": "$19/month", "features": ["Team management", "Template library", "Analytics", "Social links"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }},
  { "id": "ai-unsubscribe-manager", "title": "AI Email Unsubscribe Manager", "description": "Smart unsubscribe handling with preference centers, list hygiene, and GDPR/CCPA compliance. Protects sender reputation.", "category": "Compliance Services", "icon": "🚫", "price": "$39/month", "features": ["Auto-unsubscribe", "Preference center", "List hygiene", "Compliance"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }},
  { "id": "email-list-cleaning-service", "title": "Email List Cleaning Service", "description": "Automated email list cleaning and validation. Removes invalid addresses, prevents bounces, and maintains sender reputation.", "category": "Marketing Services", "icon": "🧹", "price": "$49/month", "features": ["Bounce prevention", "Validation", "Reputation protection", "Automation"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }},
  { "id": "ai-email-forwarding-router", "title": "AI Email Forwarding Router", "description": "Intelligent email routing based on content analysis and expertise matching. Prevents forwarding chains and ensures emails reach the right person.", "category": "IT Services", "icon": "🔀", "price": "$59/month", "features": ["Smart routing", "Expertise matching", "Chain prevention", "Auto-forwarding"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }},
  { "id": "email-routing-automation", "title": "Email Routing Automation Pro", "description": "Automate email routing with custom rules, AI-powered decisions, and workflow integration. Reduces manual forwarding by 80%.", "category": "Automation Services", "icon": "⚡", "price": "$69/month", "features": ["Custom rules", "AI decisions", "Workflow integration", "Analytics"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }},
  { "id": "ai-email-archival-system", "title": "AI Email Archival System", "description": "Smart email archiving with retention policies, searchable tags, and compliance-ready storage. Meets legal and regulatory requirements.", "category": "IT Services", "icon": "🗄️", "price": "$79/month", "features": ["Smart archiving", "Retention policies", "Searchable tags", "Compliance"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }},
  { "id": "email-compliance-archive", "title": "Email Compliance Archive", "description": "Compliance-focused email archiving for regulated industries. Immutable storage, legal hold support, and audit trails.", "category": "Compliance Services", "icon": "⚖️", "price": "$99/month", "features": ["Immutable storage", "Legal hold", "Audit trails", "GDPR/HIPAA"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }},
  { "id": "ai-email-accessibility-checker", "title": "AI Email Accessibility Checker", "description": "Ensures emails are accessible to all recipients including those with disabilities. WCAG 2.1 compliant with screen reader optimization.", "category": "Compliance Services", "icon": "♿", "price": "$44/month", "features": ["WCAG compliance", "Screen reader friendly", "Alt text validation", "Color contrast"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }},
  { "id": "accessible-email-optimizer", "title": "Accessible Email Optimizer", "description": "Optimize emails for accessibility with AI-powered suggestions. Ensures compliance with ADA, Section 508, and WCAG standards.", "category": "AI Services", "icon": "🔍", "price": "$39/month", "features": ["AI suggestions", "ADA compliance", "Section 508", "Real-time checks"], "contactInfo": { "phone": "+1 302 464 0950", "email": "kleber@ziontechgroup.com", "address": "364 E Main St STE 1008 Middletown DE 19709" }}
];

let added = 0;
for (const svc of newServices) {
  if (!services.find(s => s.id === svc.id)) { services.push(svc); added++; }
}
fs.writeFileSync(servicesPath, JSON.stringify(services, null, 2));
console.log(`✅ Added ${added} new services. Total: ${services.length}`);
