#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'app/data/servicesData.json');
const services = JSON.parse(fs.readFileSync(filePath, 'utf8'));

const contactInfo = {
  mobile: "+1 302 464 0950",
  email: "kleber@ziontechgroup.com",
  address: "364 E Main St STE 1008, Middletown, DE 19709"
};

const newServices = [
  // AI Services (5)
  {id:"v546-predictive-email-routing",title:"Predictive Email Routing AI",description:"ML-powered email routing that analyzes content and automatically directs to the optimal team member with 95%+ accuracy.",icon:"🔀",category:"ai",features:["ML content analysis","Auto-routing to teams","Priority detection","SLA estimation","Learning from corrections"],pricing:{starter:"$59/mo",professional:"$179/mo",enterprise:"$449/mo"},contactInfo},
  {id:"v547-clv-predictor",title:"Customer Lifetime Value Predictor",description:"AI engine that calculates customer lifetime value from email engagement patterns and predicts future revenue potential.",icon:"💎",category:"ai",features:["CLV calculation","Engagement scoring","Purchase intent detection","Segment classification","Retention risk assessment"],pricing:{starter:"$79/mo",professional:"$229/mo",enterprise:"$599/mo"},contactInfo},
  {id:"v548-churn-prevention",title:"Churn Prevention Engine",description:"Proactive churn detection from email patterns with automated retention actions and risk scoring for at-risk customers.",icon:"🛡️",category:"ai",features:["Churn risk scoring","Negative signal detection","Competitor mention alerts","Retention automation","Success team triggers"],pricing:{starter:"$89/mo",professional:"$259/mo",enterprise:"$649/mo"},contactInfo},
  {id:"v549-multi-channel-orchestrator",title:"Multi-Channel Orchestrator",description:"Unified communication platform coordinating email, Slack, Teams, and SMS for seamless customer engagement.",icon:"🌐",category:"automation",features:["Multi-channel coordination","Urgency-based routing","Escalation paths","Timeline management","Channel preference learning"],pricing:{starter:"$99/mo",professional:"$299/mo",enterprise:"$749/mo"},contactInfo},
  {id:"v550-executive-dashboard",title:"Executive Dashboard Generator",description:"Auto-generates C-suite summaries from email communications with key metrics, insights, and actionable recommendations.",icon:"📊",category:"data",features:["Auto executive summaries","KPI dashboards","Risk indicators","Opportunity identification","Action item generation"],pricing:{starter:"$129/mo",professional:"$399/mo",enterprise:"$999/mo"},contactInfo},

  // IT Services (5)
  {id:"v546-infrastructure-monitoring-ai",title:"Infrastructure Monitoring AI",description:"AI-powered infrastructure monitoring with predictive alerting, anomaly detection, and automated incident response.",icon:"🖥️",category:"it",features:["Predictive alerting","Anomaly detection","Auto-remediation","Root cause analysis","Multi-cloud support"],pricing:{starter:"$199/mo",professional:"$599/mo",enterprise:"$1,499/mo"},contactInfo},
  {id:"v547-network-optimization",title:"Network Performance Optimizer",description:"Intelligent network optimization with traffic analysis, bandwidth management, and latency reduction across global networks.",icon:"🌍",category:"it",features:["Traffic analysis","Bandwidth optimization","Latency reduction","CDN integration","Real-time monitoring"],pricing:{starter:"$149/mo",professional:"$449/mo",enterprise:"$1,199/mo"},contactInfo},
  {id:"v548-database-performance",title:"Database Performance Tuner",description:"AI-driven database optimization with query analysis, index recommendations, and automated performance tuning.",icon:"🗄️",category:"it",features:["Query optimization","Index suggestions","Performance profiling","Auto-tuning","Multi-database support"],pricing:{starter:"$129/mo",professional:"$399/mo",enterprise:"$999/mo"},contactInfo},
  {id:"v549-incident-response-ai",title:"AI Incident Response Platform",description:"Automated incident response with AI-driven triage, escalation, and resolution workflows for IT operations.",icon:"🚨",category:"it",features:["Auto-triage","Smart escalation","Runbook automation","Post-mortem generation","SLA tracking"],pricing:{starter:"$179/mo",professional:"$549/mo",enterprise:"$1,399/mo"},contactInfo},
  {id:"v550-asset-management-pro",title:"IT Asset Management Pro",description:"Complete IT asset lifecycle management with discovery, tracking, compliance, and cost optimization.",icon:"📦",category:"it",features:["Auto-discovery","Lifecycle tracking","License compliance","Cost optimization","Depreciation scheduling"],pricing:{starter:"$79/mo",professional:"$249/mo",enterprise:"$649/mo"},contactInfo},

  // Micro-SaaS (5)
  {id:"v546-proposal-generator-ai",title:"AI Proposal Generator",description:"Automated business proposal creation with client analysis, pricing optimization, and professional templates.",icon:"📝",category:"micro-saas",features:["Client analysis","Smart pricing","Template library","Auto-customization","Approval workflows"],pricing:{starter:"$49/mo",professional:"$149/mo",enterprise:"$349/mo"},contactInfo},
  {id:"v547-contract-management-ai",title:"Contract Management AI",description:"Intelligent contract lifecycle management with clause extraction, risk analysis, and automated compliance checking.",icon:"📋",category:"micro-saas",features:["Clause extraction","Risk scoring","Compliance checking","Renewal tracking","E-signature integration"],pricing:{starter:"$59/mo",professional:"$179/mo",enterprise:"$449/mo"},contactInfo},
  {id:"v548-knowledge-base-builder",title:"Knowledge Base Builder AI",description:"AI-powered knowledge base creation from emails, documents, and support tickets with smart search and auto-updates.",icon:"📚",category:"micro-saas",features:["Auto-content extraction","Smart categorization","Search optimization","Auto-updates","Multi-source ingestion"],pricing:{starter:"$39/mo",professional:"$119/mo",enterprise:"$299/mo"},contactInfo},
  {id:"v549-client-onboarding-pro",title:"Client Onboarding Automation",description:"Streamlined client onboarding with automated workflows, document collection, and progress tracking.",icon:"🎯",category:"micro-saas",features:["Workflow automation","Document collection","Progress tracking","Welcome sequences","Integration setup"],pricing:{starter:"$29/mo",professional:"$89/mo",enterprise:"$229/mo"},contactInfo},
  {id:"v550-time-tracking-ai",title:"AI Time Tracking & Billing",description:"Intelligent time tracking with automatic project detection, billing integration, and productivity insights.",icon:"⏱️",category:"micro-saas",features:["Auto time capture","Project detection","Invoice generation","Productivity reports","Team analytics"],pricing:{starter:"$15/mo",professional:"$45/mo",enterprise:"$119/mo"},contactInfo},

  // Security Services (5)
  {id:"v546-threat-intelligence",title:"Threat Intelligence Platform",description:"Real-time threat intelligence aggregation with AI-powered correlation and automated security response.",icon:"🔒",category:"security",features:["Threat aggregation","AI correlation","Auto-response","IOC feeds","Vulnerability mapping"],pricing:{starter:"$249/mo",professional:"$749/mo",enterprise:"$1,999/mo"},contactInfo},
  {id:"v547-siem-enhancement",title:"SIEM Enhancement AI",description:"AI-enhanced SIEM with noise reduction, automated investigation, and intelligent alert prioritization.",icon:"🛡️",category:"security",features:["Alert prioritization","Noise reduction","Auto-investigation","Threat hunting","Compliance reporting"],pricing:{starter:"$299/mo",professional:"$899/mo",enterprise:"$2,299/mo"},contactInfo},
  {id:"v548-data-loss-prevention",title:"Advanced DLP Suite",description:"Enterprise data loss prevention with content inspection, policy enforcement, and automated remediation.",icon:"🔐",category:"security",features:["Content inspection","Policy enforcement","Auto-remediation","Endpoint protection","Cloud DLP"],pricing:{starter:"$199/mo",professional:"$599/mo",enterprise:"$1,499/mo"},contactInfo},
  {id:"v549-penetration-testing",title:"Automated Penetration Testing",description:"Continuous automated penetration testing with AI-driven vulnerability exploitation and remediation guidance.",icon:"🎯",category:"security",features:["Continuous testing","AI exploitation","Remediation guidance","Compliance mapping","Executive reporting"],pricing:{starter:"$399/mo",professional:"$1,199/mo",enterprise:"$2,999/mo"},contactInfo},
  {id:"v550-access-governance",title:"Access Governance Platform",description:"Enterprise access governance with automated provisioning, certification campaigns, and privileged access management.",icon:"👥",category:"security",features:["Auto-provisioning","Access certification","PAM integration","SoD enforcement","Audit readiness"],pricing:{starter:"$149/mo",professional:"$449/mo",enterprise:"$1,199/mo"},contactInfo},

  // Cloud & Data (5)
  {id:"v546-multi-cloud-manager",title:"Multi-Cloud Management Platform",description:"Unified management across AWS, Azure, and GCP with cost optimization, security, and compliance automation.",icon:"☁️",category:"cloud",features:["Cross-cloud visibility","Cost optimization","Security automation","Compliance monitoring","Resource orchestration"],pricing:{starter:"$299/mo",professional:"$899/mo",enterprise:"$2,499/mo"},contactInfo},
  {id:"v547-data-lake-optimizer",title:"Data Lake Optimizer AI",description:"AI-powered data lake optimization with storage tiering, query acceleration, and cost reduction strategies.",icon:"🏊",category:"data",features:["Storage tiering","Query acceleration","Cost reduction","Data quality checks","Schema evolution"],pricing:{starter:"$199/mo",professional:"$599/mo",enterprise:"$1,499/mo"},contactInfo},
  {id:"v548-stream-processing",title:"Real-Time Stream Processing",description:"Scalable stream processing engine with sub-second latency, complex event processing, and ML integration.",icon:"🌊",category:"data",features:["Sub-second processing","Complex events","ML integration","Auto-scaling","Multi-source ingestion"],pricing:{starter:"$249/mo",professional:"$749/mo",enterprise:"$1,999/mo"},contactInfo},
  {id:"v549-data-mesh-platform",title:"Data Mesh Platform",description:"Enterprise data mesh implementation with domain ownership, self-serve platform, and federated governance.",icon:"🕸️",category:"data",features:["Domain ownership","Self-serve platform","Federated governance","Data products","Observability"],pricing:{starter:"$349/mo",professional:"$1,049/mo",enterprise:"$2,799/mo"},contactInfo},
  {id:"v550-edge-computing-ai",title:"Edge Computing AI Platform",description:"Distributed edge computing with AI inference, real-time analytics, and IoT device management at scale.",icon:"📡",category:"iot",features:["Edge AI inference","Real-time analytics","Device management","Auto-scaling","Offline capability"],pricing:{starter:"$179/mo",professional:"$549/mo",enterprise:"$1,399/mo"},contactInfo}
];

services.push(...newServices);
fs.writeFileSync(filePath, JSON.stringify(services, null, 2));
console.log(`Added ${newServices.length} services. Total: ${services.length}`);
