#!/usr/bin/env python3
"""Add 30 new differentiated micro-SaaS services to servicesData.ts"""

import re

with open('app/data/servicesData.ts', 'r') as f:
    content = f.read()

# ---- AI SERVICES (insert before aiServices ];) ----
ai_new = """,
  {
    id: 'ai-prompt-optimization-engine',
    title: 'AI Prompt Optimization Engine',
    description: 'Automatically refine and optimize LLM prompts for higher accuracy, lower token usage, and consistent output quality across models. Benchmarks before/after performance and suggests structural improvements.',
    features: ['Automatic prompt refinement via meta-prompting','Token cost reduction analysis','A/B prompt benchmarking across models','Structured output template enforcement','Prompt version control and rollback'],
    benefits: [],
    pricing: {basic:'$99/mo', pro:'$299/mo', enterprise:'$999/mo'},
    contactInfo: {website:'/services/ai-prompt-optimization-engine', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '🎯',
    href: '/services/ai-prompt-optimization-engine',
    popular: true,
    category: 'ai',
    industry: 'Technology',
  },
  {
    id: 'ai-multimodal-content-factory',
    title: 'AI Multimodal Content Factory',
    description: 'Generate coordinated text, image, and short-video assets from a single natural language brief. Maintains brand consistency across all modalities with style-transfer guardrails.',
    features: ['Single-brief multi-format generation','Brand style enforcement across modalities','Automatic aspect-ratio adaptation','Content calendar integration','Quality scoring per output modality'],
    benefits: [],
    pricing: {basic:'$199/mo', pro:'$599/mo', enterprise:'$1,999/mo'},
    contactInfo: {website:'/services/ai-multimodal-content-factory', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '🎨',
    href: '/services/ai-multimodal-content-factory',
    popular: true,
    category: 'ai',
    industry: 'Marketing',
  },
  {
    id: 'ai-code-review-sentinel',
    title: 'AI Code Review Sentinel',
    description: 'Automated deep code review combining security vulnerability detection, performance anti-pattern identification, and architecture quality scoring. Integrates with PR workflows for shift-left quality.',
    features: ['Security vulnerability detection (OWASP top 10)','Performance anti-pattern identification','Architecture quality scoring','PR comment integration with fix suggestions','Custom rule engine for team conventions'],
    benefits: [],
    pricing: {basic:'$149/mo', pro:'$449/mo', enterprise:'$1,499/mo'},
    contactInfo: {website:'/services/ai-code-review-sentinel', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '🛡️',
    href: '/services/ai-code-review-sentinel',
    popular: false,
    category: 'ai',
    industry: 'Technology',
  },
  {
    id: 'ai-synthetic-data-generator',
    title: 'AI Synthetic Data Generator',
    description: 'Produce privacy-safe, statistically faithful synthetic datasets for ML training and testing. Preserves column correlations and distribution shapes while guaranteeing no real PII leakage.',
    features: ['Differential privacy guarantees','Correlation-preserving generation','Schema-aware tabular + time-series output','Bias detection and mitigation tools','Benchmark fidelity scoring vs real data'],
    benefits: [],
    pricing: {basic:'$199/mo', pro:'$599/mo', enterprise:'$1,999/mo'},
    contactInfo: {website:'/services/ai-synthetic-data-generator', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '🎲',
    href: '/services/ai-synthetic-data-generator',
    popular: false,
    category: 'ai',
    industry: 'Healthcare',
  },
  {
    id: 'ai-workflow-memory-layer',
    title: 'AI Workflow Memory Layer',
    description: 'Persistent episodic and semantic memory for multi-step AI agents. Stores decision context across sessions with automatic summarization, relevance retrieval, and memory decay policies.',
    features: ['Episodic + semantic dual memory store','Automatic context summarization','Relevance-ranked retrieval for agent prompts','Configurable memory decay and archival','Cross-agent shared memory namespaces'],
    benefits: [],
    pricing: {basic:'$149/mo', pro:'$449/mo', enterprise:'$1,499/mo'},
    contactInfo: {website:'/services/ai-workflow-memory-layer', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '🧠',
    href: '/services/ai-workflow-memory-layer',
    popular: false,
    category: 'ai',
    industry: 'Technology',
  },
"""

# ---- IT SERVICES ----
it_new = """,
  {
    id: 'it-asset-lifecycle-manager',
    title: 'IT Asset Lifecycle Manager',
    description: 'End-to-end tracking of hardware and software assets from procurement through retirement. Automates depreciation, license compliance, and disposal workflows with full audit trail.',
    features: ['Procurement-to-retirement tracking','Automated depreciation calculations','Software license compliance alerts','Disposal and e-waste workflow','Full audit trail and reporting'],
    benefits: [],
    pricing: {basic:'$199/mo', pro:'$599/mo', enterprise:'$1,999/mo'},
    contactInfo: {website:'/services/it-asset-lifecycle-manager', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '📦',
    href: '/services/it-asset-lifecycle-manager',
    popular: true,
    category: 'it',
    industry: 'Finance',
  },
  {
    id: 'it-runbook-automation-platform',
    title: 'IT Runbook Automation Platform',
    description: 'Convert manual operations runbooks into executable auto-remediation playbooks. Human-approval gates for destructive actions with full execution logging and rollback capability.',
    features: ['Runbook-to-playbook converter','Human-approval gates for risky actions','Automatic rollback on failure','Execution logging and audit trail','Integration with PagerDuty and ServiceNow'],
    benefits: [],
    pricing: {basic:'$299/mo', pro:'$799/mo', enterprise:'$2,499/mo'},
    contactInfo: {website:'/services/it-runbook-automation-platform', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: ' playbook',
    href: '/services/it-runbook-automation-platform',
    popular: true,
    category: 'it',
    industry: 'Technology',
  },
  {
    id: 'it-sla-compliance-monitor',
    title: 'IT SLA Compliance Monitor',
    description: 'Continuously measure service level metrics against contractual SLAs and alert on breaches with trend analysis and breach prediction to prevent violations before they occur.',
    features: ['Real-time SLA metric tracking','Breach prediction with trend analysis','Automatic stakeholder alerts','SLA report generation for customers','Remediation time tracking and escalation'],
    benefits: [],
    pricing: {basic:'$299/mo', pro:'$799/mo', enterprise:'$2,499/mo'},
    contactInfo: {website:'/services/it-sla-compliance-monitor', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '📊',
    href: '/services/it-sla-compliance-monitor',
    popular: false,
    category: 'it',
    industry: 'Finance',
  },
  {
    id: 'it-change-advisory-board-engine',
    title: 'IT Change Advisory Board Engine',
    description: 'Digitize and automate CAB workflows with risk auto-assessment, impact analysis, and approval routing. Reduces change lead time while maintaining governance and compliance.',
    features: ['Automated risk and impact assessment','Smart approval routing by risk tier','Calendar conflict detection for changes','Post-change validation verification','Compliance evidence auto-collection'],
    benefits: [],
    pricing: {basic:'$399/mo', pro:'$999/mo', enterprise:'$2,999/mo'},
    contactInfo: {website:'/services/it-change-advisory-board-engine', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '🏛️',
    href: '/services/it-change-advisory-board-engine',
    popular: false,
    category: 'it',
    industry: 'Finance',
  },
  {
    id: 'it-config-drift-detector',
    title: 'IT Configuration Drift Detector',
    description: 'Detect and alert on infrastructure configuration drift from baseline policies. Compare live state against IaC definitions and auto-remediate approved changes with diff visualization.',
    features: ['Continuous drift detection scanning','IaC-vs-live state diff visualization','Auto-remediation for approved drifts','Drift severity classification','Integration with Terraform, Pulumi, Ansible'],
    benefits: [],
    pricing: {basic:'$299/mo', pro:'$799/mo', enterprise:'$2,499/mo'},
    contactInfo: {website:'/services/it-config-drift-detector', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '🔍',
    href: '/services/it-config-drift-detector',
    popular: false,
    category: 'it',
    industry: 'Technology',
  },
"""

# ---- CLOUD SERVICES ----
cloud_new = """,
  {
    id: 'cloud-cost-anomaly-detector',
    title: 'Cloud Cost Anomaly Detector',
    description: 'Detect cloud spending spikes and anomalies in real-time with root-cause attribution. Auto-suggests rightsizing and reserved-instance optimizations to reduce waste.',
    features: ['Real-time spending anomaly detection','Root-cause attribution per service','Auto-rightsizing recommendations','Reserved instance coverage optimizer','Budget enforcement with auto-pause'],
    benefits: [],
    pricing: {basic:'$299/mo', pro:'$799/mo', enterprise:'$2,499/mo'},
    contactInfo: {website:'/services/cloud-cost-anomaly-detector', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '💰',
    href: '/services/cloud-cost-anomaly-detector',
    popular: true,
    category: 'cloud',
    industry: 'Finance',
  },
  {
    id: 'cloud-multi-tenant-isolation-validator',
    title: 'Cloud Multi-Tenant Isolation Validator',
    description: 'Continuously verify tenant separation in multi-tenant SaaS deployments. Tests IAM policies, network segmentation, and data boundaries to prevent cross-tenant access.',
    features: ['IAM policy boundary verification','Network segmentation testing','Data isolation validation','Cross-tenant access attempt detection','Compliance report generation (SOC2, ISO27001)'],
    benefits: [],
    pricing: {basic:'$499/mo', pro:'$1,499/mo', enterprise:'$4,999/mo'},
    contactInfo: {website:'/services/cloud-multi-tenant-isolation-validator', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '🔒',
    href: '/services/cloud-multi-tenant-isolation-validator',
    popular: true,
    category: 'cloud',
    industry: 'Healthcare',
  },
  {
    id: 'cloud-migration-readiness-scanner',
    title: 'Cloud Migration Readiness Scanner',
    description: 'Assess on-premises workloads for cloud migration feasibility with dependency mapping, cost modeling, and risk scoring. Generates prioritized migration waves and runbooks.',
    features: ['Workload dependency mapping','Cloud-fit risk scoring per application','TCO modeling for target cloud','Migration wave grouping and sequencing','Automated runbook generation per app'],
    benefits: [],
    pricing: {basic:'$399/mo', pro:'$999/mo', enterprise:'$2,999/mo'},
    contactInfo: {website:'/services/cloud-migration-readiness-scanner', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '🚀',
    href: '/services/cloud-migration-readiness-scanner',
    popular: false,
    category: 'cloud',
    industry: 'General',
  },
  {
    id: 'cloud-spot-instance-orchestrator',
    title: 'Cloud Spot Instance Orchestrator',
    description: 'Maximize cloud savings by intelligently managing spot/preemptible instances with checkpoint-based interruption handling, automatic fallback to on-demand, and capacity-aware bidding.',
    features: ['Checkpoint-based interruption recovery','Automatic on-demand fallback','Capacity-aware bid pricing','Workload-aware instance selection','Savings dashboard with utilization metrics'],
    benefits: [],
    pricing: {basic:'$199/mo', pro:'$599/mo', enterprise:'$1,999/mo'},
    contactInfo: {website:'/services/cloud-spot-instance-orchestrator', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '⚡',
    href: '/services/cloud-spot-instance-orchestrator',
    popular: false,
    category: 'cloud',
    industry: 'Technology',
  },
  {
    id: 'cloud-vpn-mesh-manager',
    title: 'Cloud VPN Mesh Manager',
    description: 'Deploy and manage zero-trust mesh VPN networks across multi-cloud and edge locations. Automated peering, certificate rotation, and performance monitoring for secure connectivity.',
    features: ['Zero-trust mesh peering automation','Automatic certificate rotation','Cross-cloud connectivity management','Latency and throughput monitoring','Split-tunnel policy management'],
    benefits: [],
    pricing: {basic:'$299/mo', pro:'$799/mo', enterprise:'$2,499/mo'},
    contactInfo: {website:'/services/cloud-vpn-mesh-manager', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '🌐',
    href: '/services/cloud-vpn-mesh-manager',
    popular: false,
    category: 'cloud',
    industry: 'Technology',
  },
"""

# ---- SECURITY SERVICES ----
security_new = """,
  {
    id: 'security-api-key-rotator',
    title: 'Security API Key Rotator',
    description: 'Automate API key and secret rotation on configurable schedules with zero-downtime dual-key strategies. Full audit trail of rotations with integration into vaults and CI/CD pipelines.',
    features: ['Scheduled and on-demand rotation','Zero-downtime dual-key strategy','Vault integration (HashiCorp, AWS Secrets)','CI/CD pipeline key injection','Full rotation audit trail'],
    benefits: [],
    pricing: {basic:'$299/mo', pro:'$799/mo', enterprise:'$2,499/mo'},
    contactInfo: {website:'/services/security-api-key-rotator', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '🔑',
    href: '/services/security-api-key-rotator',
    popular: true,
    category: 'security',
    industry: 'Finance',
  },
  {
    id: 'security-deception-grid',
    title: 'Security Deception Grid',
    description: 'Deploy and manage honeypots, honeyfiles, and canary tokens across your infrastructure. Alert on attacker interaction with decoys and map lateral movement paths in real-time.',
    features: ['Honeypot deployment and management','Canary token distribution (API keys, AWS keys, DB creds)','Attacker interaction alerting','Lateral movement path visualization','Integration with SIEM and SOAR platforms'],
    benefits: [],
    pricing: {basic:'$499/mo', pro:'$1,299/mo', enterprise:'$3,999/mo'},
    contactInfo: {website:'/services/security-deception-grid', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '🎭',
    href: '/services/security-deception-grid',
    popular: true,
    category: 'security',
    industry: 'Finance',
  },
  {
    id: 'security-zero-trust-policy-engine',
    title: 'Security Zero-Trust Policy Engine',
    description: 'Define, test, and enforce microsegmentation policies as code. Validates identity, device posture, and context before allowing any network or application access.',
    features: ['Policy-as-code microsegmentation rules','Identity + device posture validation','Context-aware access decisions','Policy simulation and testing sandbox','Enforcement across cloud, on-prem, and edge'],
    benefits: [],
    pricing: {basic:'$599/mo', pro:'$1,499/mo', enterprise:'$4,999/mo'},
    contactInfo: {website:'/services/security-zero-trust-policy-engine', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '🚧',
    href: '/services/security-zero-trust-policy-engine',
    popular: false,
    category: 'security',
    industry: 'Finance',
  },
  {
    id: 'security-sbom-generator',
    title: 'Security SBOM Generator',
    description: 'Automatically generate Software Bill of Materials (SBOM) in SPDX and CycloneDX formats for your entire dependency tree. Continuous vulnerability scanning with CVE alerting.',
    features: ['SPDX and CycloneDX SBOM generation','Full transitive dependency tree mapping','Continuous CVE vulnerability scanning','License compliance checking','Integration with build pipelines and repositories'],
    benefits: [],
    pricing: {basic:'$199/mo', pro:'$599/mo', enterprise:'$1,999/mo'},
    contactInfo: {website:'/services/security-sbom-generator', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '📋',
    href: '/services/security-sbom-generator',
    popular: false,
    category: 'security',
    industry: 'Technology',
  },
  {
    id: 'security-incident-playbook-runner',
    title: 'Security Incident Playbook Runner',
    description: 'Execute automated incident response playbooks with containment, eradication, and recovery steps. Human-in-the-loop for critical actions with evidence preservation and timeline generation.',
    features: ['Automated containment actions','Evidence preservation chain of custody','Human-in-the-loop approval for critical steps','Incident timeline auto-generation','Post-incident review report builder'],
    benefits: [],
    pricing: {basic:'$499/mo', pro:'$1,299/mo', enterprise:'$3,999/mo'},
    contactInfo: {website:'/services/security-incident-playbook-runner', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '🚨',
    href: '/services/security-incident-playbook-runner',
    popular: false,
    category: 'security',
    industry: 'General',
  },
"""

# ---- DATA SERVICES ----
data_new = """,
  {
    id: 'data-lineage-tracker',
    title: 'Data Lineage Tracker',
    description: 'Map end-to-end data flow paths from source through transformations to consumption. Supports impact analysis for schema changes and regulatory compliance attestation.',
    features: ['End-to-end data flow visualization','Schema change impact analysis','Column-level lineage tracking','Regulatory compliance attestation reports','Integration with dbt, Spark, Airflow'],
    benefits: [],
    pricing: {basic:'$299/mo', pro:'$799/mo', enterprise:'$2,499/mo'},
    contactInfo: {website:'/services/data-lineage-tracker', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '🔗',
    href: '/services/data-lineage-tracker',
    popular: true,
    category: 'data',
    industry: 'Finance',
  },
  {
    id: 'data-quality-firewall',
    title: 'Data Quality Firewall',
    description: 'Validate data at ingestion boundaries with schema checks, range validation, referential integrity, and custom business rules. Rejects or quarantines bad data before it enters your warehouse.',
    features: ['Schema validation at ingest','Range and null checks','Referential integrity enforcement','Custom business rule engine','Quarantine and rejection with reason codes'],
    benefits: [],
    pricing: {basic:'$199/mo', pro:'$599/mo', enterprise:'$1,999/mo'},
    contactInfo: {website:'/services/data-quality-firewall', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '🧱',
    href: '/services/data-quality-firewall',
    popular: true,
    category: 'data',
    industry: 'Healthcare',
  },
  {
    id: 'data-catalog-auto-discovery',
    title: 'Data Catalog Auto-Discovery',
    description: 'Automatically discover, classify, and index data assets across databases, file stores, and APIs. AI-powered metadata enrichment with PII detection and usage statistics.',
    features: ['Automatic data source scanning','PII and sensitivity classification','AI-powered metadata enrichment','Usage statistics and popularity ranking','Self-service search and discovery portal'],
    benefits: [],
    pricing: {basic:'$299/mo', pro:'$799/mo', enterprise:'$2,499/mo'},
    contactInfo: {website:'/services/data-catalog-auto-discovery', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '📚',
    href: '/services/data-catalog-auto-discovery',
    popular: false,
    category: 'data',
    industry: 'General',
  },
  {
    id: 'data-pipeline-retry-engine',
    title: 'Data Pipeline Retry Engine',
    description: 'Intelligent retry management for data pipelines with exponential backoff, error classification, and dead-letter handling. Learns from failure patterns to optimize retry strategies.',
    features: ['Error classification and categorization','Adaptive exponential backoff','Dead-letter queue management','Failure pattern learning and optimization','Retry budget and circuit breaker controls'],
    benefits: [],
    pricing: {basic:'$149/mo', pro:'$449/mo', enterprise:'$1,499/mo'},
    contactInfo: {website:'/services/data-pipeline-retry-engine', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '🔄',
    href: '/services/data-pipeline-retry-engine',
    popular: false,
    category: 'data',
    industry: 'Technology',
  },
  {
    id: 'data-compression-optimizer',
    title: 'Data Compression Optimizer',
    description: 'Optimize storage costs with intelligent columnar encoding, adaptive compression selection, and tiered storage policies. Benchmarks compression ratios vs query performance trade-offs.',
    features: ['Adaptive compression algorithm selection','Columnar encoding optimization','Query performance vs compression trade-off analysis','Tiered storage policy automation','Storage savings dashboard and reporting'],
    benefits: [],
    pricing: {basic:'$199/mo', pro:'$599/mo', enterprise:'$1,999/mo'},
    contactInfo: {website:'/services/data-compression-optimizer', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '🗜️',
    href: '/services/data-compression-optimizer',
    popular: false,
    category: 'data',
    industry: 'Technology',
  },
"""

# ---- AUTOMATION SERVICES ----
automation_new = """,
  {
    id: 'automation-digital-twin-simulator',
    title: 'Automation Digital Twin Simulator',
    description: 'Create digital twins of business processes for simulation and optimization before real deployment. Test automation changes safely with what-if scenarios and performance predictions.',
    features: ['Process digital twin creation','What-if scenario simulation','Performance prediction and bottleneck detection','Safe testing before production deployment','Continuous sync with live process metrics'],
    benefits: [],
    pricing: {basic:'$399/mo', pro:'$999/mo', enterprise:'$2,999/mo'},
    contactInfo: {website:'/services/automation-digital-twin-simulator', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '👯',
    href: '/services/automation-digital-twin-simulator',
    popular: true,
    category: 'automation',
    industry: 'Manufacturing',
  },
  {
    id: 'automation-event-correlator',
    title: 'Automation Event Correlator',
    description: 'Deduplicate, correlate, and enrich operational events to reduce alert noise by 90%. Groups related events into incidents with root-cause hints and smart escalation rules.',
    features: ['Event deduplication and suppression','Cross-source correlation engine','Root-cause hint generation','Smart escalation rules by severity','Alert noise reduction metrics and dashboard'],
    benefits: [],
    pricing: {basic:'$299/mo', pro:'$799/mo', enterprise:'$2,499/mo'},
    contactInfo: {website:'/services/automation-event-correlator', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '📡',
    href: '/services/automation-event-correlator',
    popular: true,
    category: 'automation',
    industry: 'Technology',
  },
  {
    id: 'automation-approval-chain-engine',
    title: 'Automation Approval Chain Engine',
    description: 'Configure multi-level approval workflows with conditional routing, delegation rules, and SLA timers. Supports parallel and sequential approvals with audit logging.',
    features: ['Multi-level sequential and parallel approvals','Conditional routing by amount, risk, or type','Delegation and out-of-office rules','SLA timers and escalation on timeout','Full audit trail and approval analytics'],
    benefits: [],
    pricing: {basic:'$149/mo', pro:'$449/mo', enterprise:'$1,499/mo'},
    contactInfo: {website:'/services/automation-approval-chain-engine', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '✅',
    href: '/services/automation-approval-chain-engine',
    popular: false,
    category: 'automation',
    industry: 'Finance',
  },
  {
    id: 'automation-patch-window-optimizer',
    title: 'Automation Patch Window Optimizer',
    description: 'Schedule and optimize patch deployment windows based on system criticality, user traffic patterns, and dependency ordering. Minimizes risk while maintaining compliance deadlines.',
    features: ['Traffic-pattern-aware scheduling','Dependency-ordered patch sequencing','Risk scoring per patch and target','Compliance deadline tracking','Canary deployment with automatic rollback'],
    benefits: [],
    pricing: {basic:'$199/mo', pro:'$599/mo', enterprise:'$1,999/mo'},
    contactInfo: {website:'/services/automation-patch-window-optimizer', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '🩹',
    href: '/services/automation-patch-window-optimizer',
    popular: false,
    category: 'automation',
    industry: 'General',
  },
  {
    id: 'automation-chatops-gateway',
    title: 'Automation ChatOps Gateway',
    description: 'Centralized hub for operational commands via Slack, Microsoft Teams, and Discord. Role-based command access, audit logging, and integration with CI/CD, monitoring, and incident tools.',
    features: ['Multi-platform support (Slack, Teams, Discord)','Role-based command access control','Command audit logging and replay','CI/CD pipeline trigger and monitoring','Incident management integration'],
    benefits: [],
    pricing: {basic:'$149/mo', pro:'$449/mo', enterprise:'$1,499/mo'},
    contactInfo: {website:'/services/automation-chatops-gateway', email:'commercial@ziontechgroup.com', phone:'+1 302 464 0950'},
    icon: '💬',
    href: '/services/automation-chatops-gateway',
    popular: false,
    category: 'automation',
    industry: 'Technology',
  },
"""

# Now insert before the closing `];` of each array
# Find the closing brackets by searching for the pattern

def insert_before_array_close(content, array_name, new_entries):
    # Find the export line for the NEXT array after this one
    arrays_order = ['aiServices', 'itServices', 'cloudServices', 'securityServices', 'dataServices', 'automationServices', 'allServices']
    current_idx = arrays_order.index(array_name)
    next_array = arrays_order[current_idx + 1]
    
    # Find the position of the next array's export
    next_export = f"export const {next_array}"
    next_pos = content.find(next_export)
    if next_pos == -1:
        raise ValueError(f"Could not find {next_export}")
    
    # The closing ]; is just before the next export (possibly with whitespace)
    # Find the ]; going backwards from next_pos
    before_next = content[:next_pos]
    close_pos = before_next.rfind('];')
    if close_pos == -1:
        raise ValueError(f"Could not find closing ]; for {array_name}")
    
    # Insert new_entries before the ];
    # Strip leading comma from new_entries since we're inserting before ];
    new_content = content[:close_pos] + new_entries.rstrip() + "\n" + content[close_pos:]
    return new_content

# Apply insertions in REVERSE order (from bottom to top) to preserve line positions
content = insert_before_array_close(content, 'automationServices', automation_new)
content = insert_before_array_close(content, 'dataServices', data_new)
content = insert_before_array_close(content, 'securityServices', security_new)
content = insert_before_array_close(content, 'cloudServices', cloud_new)
content = insert_before_array_close(content, 'itServices', it_new)
content = insert_before_array_close(content, 'aiServices', ai_new)

with open('app/data/servicesData.ts', 'w') as f:
    f.write(content)

print("✅ Added 30 new services (5 per category)")
