#!/usr/bin/env python3
"""Fill remaining 46 stub services with real descriptions based on their ID"""

STUB_MAP = {
    'ai-genomic-analysis': ("AI-powered genomic data analysis for variant calling, pathway enrichment, and drug response prediction. Handles WGS, WES, and RNA-seq with HIPAA-compliant infrastructure.", ["Variant calling and annotation","Pathway enrichment analysis","Drug response prediction","HIPAA-compliant processing","Population-scale cohort analysis"], '🧬', 'Healthcare'),
    'ai-glassdoor-review-analyzer': ("Mine employee reviews for actionable culture and compensation insights. NLP-driven sentiment tracking, topic clustering, and competitive benchmarking.", ["Sentiment tracking over time","Topic clustering and extraction","Compensation benchmarking","Culture dimension scoring","Competitive employer analysis"], '🏢', 'HR'),
    'ai-governance-compliance': ("Automated governance framework enforcement for AI/ML systems. Model registry, bias auditing, and regulatory compliance tracking for responsible AI deployment.", ["Model registry and version tracking","Automated bias auditing","Regulatory compliance mapping","Approval workflow enforcement","Risk assessment documentation"], '⚖️', 'Finance'),
    'ai-hiring-pipeline-optimizer': ("Optimize every stage of the hiring funnel with AI-driven sourcing, screening, and interview scheduling. Reduce time-to-hire by 40% while improving candidate quality.", ["AI sourcing and candidate matching","Resume screening with bias checks","Interview scheduling optimization","Pipeline analytics and bottleneck detection","Diversity and inclusion metrics"], '👥', 'HR'),
    'ai-infra-provisioner': ("Intelligent infrastructure provisioning that translates natural language requirements into Terraform/Pulumi code. Cost-optimized defaults with security hardening built in.", ["Natural language to IaC translation","Cost-optimized default configurations","Security hardening templates","Multi-cloud provisioning (AWS/GCP/Azure)","Drift detection and auto-remediation"], '🏗️', 'Technology'),
    'ai-insurance-claims': ("Automate insurance claims processing with document extraction, fraud detection, and adjudication decision support. Reduces processing time from weeks to hours.", ["Document data extraction","Fraud risk scoring","Adjudication decision support","Payment authorization workflow","Regulatory compliance validation"], '📋', 'Finance'),
    'ai-interview-conduct-bot': ("AI-conducted initial screening interviews with adaptive questioning, response scoring, and candidate ranking. Consistent evaluation with debiasing guardrails.", ["Adaptive question selection","Response quality scoring","Candidate ranking and comparison","Debiasing guardrails","Interview summary generation"], '🤖', 'HR'),
    'ai-knowledge-base-rag': ("Production RAG system with intelligent chunking, hybrid search, citation tracking, and freshness management. Connects to wikis, docs, and databases.", ["Intelligent document chunking","Hybrid vector + keyword search","Citation and source tracking","Knowledge freshness management","Multi-source connector framework"], '📚', 'General'),
    'ai-kubernetes-optimizer': ("Optimize Kubernetes resource requests/limits, rightsize pods, and recommend scheduling policies. Reduces cluster costs while maintaining SLOs.", ["Resource rightsizing recommendations","HPA/VPA policy suggestions","Cost allocation per namespace","SLO-aware optimization","Unused resource cleanup"], '☸️', 'Technology'),
    'ai-kyc-aml-compliance': ("Automated KYC/AML screening with document verification, PEP/sanctions checking, and suspicious activity monitoring. End-to-end compliance with audit trail.", ["Identity document verification","PEP and sanctions screening","Transaction monitoring and alerting","Suspicious activity reporting","Regulatory audit trail"], '🏛️', 'Finance'),
    'ai-llm-router-pro': ("Intelligently route LLM requests to the optimal model based on task complexity, latency requirements, and cost budget. Automatic fallback and load balancing.", ["Task complexity classification","Cost-optimized model routing","Latency-aware load balancing","Automatic fallback on failure","Usage analytics and budget tracking"], '🔀', 'Technology'),
    'ai-load-testing': ("AI-generated load tests that simulate realistic user behavior patterns. Automatic scenario creation from production traffic with intelligent ramp strategies.", ["AI-generated test scenarios","Production traffic replay","Intelligent ramp strategies","Performance bottleneck detection","Comparison against SLOs"], '💪', 'Technology'),
    'ai-log-analysis': ("Intelligent log analysis with anomaly detection, pattern clustering, and root-cause correlation. Turns millions of log lines into actionable incidents.", ["Anomaly detection in log streams","Pattern clustering and extraction","Root-cause correlation across services","Automatic incident creation","Search and filtered exploration"], '📜', 'Technology'),
    'ai-low-code-integration': ("AI-assisted low-code integration builder that generates connectors, mappings, and transformations from natural language descriptions of data flows.", ["Natural language integration design","Auto-generated API connectors","Smart field mapping suggestions","Error handling and retry logic","Pre-built template library"], '🧩', 'General'),
    'ai-medical-image-diagnosis': ("AI-assisted medical image analysis for radiology, pathology, and dermatology. FDA 510(k)-cleared algorithms with radiologist-in-the-loop validation.", ["Multi-modality image analysis","FDA-cleared detection algorithms","Radiologist validation workflow","DICOM integration and PACS compatible","Priority case flagging"], '🏥', 'Healthcare'),
    'ai-metadata-management': ("Automated metadata extraction, classification, and governance for enterprise data. Auto-tags columns with business glossary terms and sensitivity labels.", ["Automatic metadata extraction","Business glossary auto-tagging","Sensitivity classification","Data catalog integration","Lineage and impact tracking"], '🏷️', 'Technology'),
    'ai-nutrition-meal-planner': ("Personalized meal planning based on dietary restrictions, health goals, and biometric data. Generates recipes with macro tracking and grocery lists.", ["Dietary restriction accommodation","Health goal alignment","Recipe generation with macros","Grocery list optimization","Biometric-informed adjustments"], '🥗', 'Healthcare'),
    'ai-observability-turbo': ("Turbocharged observability with AI-driven alert noise reduction, SLO tracking, and error budget management. Correlates traces, metrics, and logs automatically.", ["Alert noise reduction via correlation","SLO and error budget tracking","Trace-metric-log correlation","Anomaly detection with context","Performance regression detection"], '🔭', 'Technology'),
    'ai-personal-finance-coach': ("AI personal finance advisor that analyzes spending, optimizes budgets, and suggests savings strategies. Plaid-powered account aggregation with goal tracking.", ["Spending analysis and categorization","Budget optimization","Savings strategy suggestions","Account aggregation via Plaid","Goal tracking and milestones"], '💰', 'Finance'),
    'ai-privilege-access-manager': ("AI-enhanced PAM with just-in-time access elevation, session recording, and anomaly detection on privileged sessions. Zero standing privileges by default.", ["Just-in-time access elevation","Session recording and audit","Anomalous session detection","Zero standing privileges enforcement","Credential rotation automation"], '🔑', 'Security'),
    'ai-product-photo-enhancer': ("Enhance and optimize product photos for e-commerce with background removal, color correction, and lifestyle scene generation. Batch processing with brand consistency.", ["Background removal and replacement","Color correction and white balance","Lifestyle scene generation","Batch processing with brand rules","Multi-market format adaptation"], '📷', 'E-Commerce'),
    'ai-profitability-dashboard': ("Real-time profitability analytics with contribution margin tracking, customer cohort analysis, and pricing optimization recommendations.", ["Contribution margin tracking","Customer cohort profitability","Pricing optimization suggestions","Revenue and cost attribution","Scenario modeling for price changes"], '💹', 'Finance'),
    'ai-quality-inspection': ("AI-powered visual quality inspection for manufacturing lines. Detects defects with sub-millimeter accuracy and integrates with PLC/SCADA for real-time rejection.", ["Sub-millimeter defect detection","PLC/SCADA integration","Multi-camera inspection coordination","Defect classification and severity","Yield analytics and trend tracking"], '🔬', 'Manufacturing'),
    'ai-quantum-optimizer': ("Quantum-inspired optimization algorithms for combinatorial problems: vehicle routing, scheduling, and portfolio optimization. No quantum hardware required.", ["Quantum-inspired annealing algorithms","Vehicle routing optimization","Portfolio optimization","Job scheduling optimization","Classical fallback with benchmarking"], '⚛️', 'Technology'),
    'ai-reinforcement-learning-ops': ("MLOps platform for reinforcement learning: environment management, policy training, simulation, and safe deployment with performance monitoring.", ["Environment and simulator management","Policy training and evaluation","Safe deployment with guardrails","A/B policy comparison","Reward function debugging"], '🎮', 'Technology'),
    'ai-rpa-platform': ("AI-enhanced RPA with intelligent document processing, exception handling, and self-healing bots that adapt to UI changes without reprogramming.", ["Intelligent document processing","Self-healing UI adaptation","Exception handling and escalation","Bot orchestration and scheduling","Process mining and discovery"], '🤖', 'General'),
    'ai-secrets-management': ("Centralized secrets management with automated rotation, just-in-time access, and zero-knowledge encryption. Integrates with all major cloud vaults and CI/CD.", ["Automated secret rotation","Just-in-time access delivery","Zero-knowledge encryption","Cloud vault integration","CI/CD secret injection"], '🔐', 'Security'),
    'ai-seo-content-optimizer': ("AI SEO optimizer that analyzes content for keyword optimization, internal linking, schema markup, and E-E-A-T signals. Provides actionable improvement scores.", ["Keyword optimization scoring","Internal linking suggestions","Schema markup recommendations","E-E-A-T signal analysis","Competitor content gap identification"], '🔎', 'Marketing'),
    'ai-serverless-platform': ("AI-optimized serverless platform with cold-start prediction, function rightsizing, and cost-optimized provisioning across Lambda, Cloud Functions, and Azure Functions.", ["Cold-start prediction and mitigation","Function rightsizing","Cost-optimized provisioning","Multi-cloud function deployment","Observability and tracing"], '⚡', 'Technology'),
    'ai-smart-document-redactor': ("Automatically redact PII, PHI, and sensitive information from documents while preserving document structure. Supports PDF, DOCX, and images.", ["PII and PHI detection and redaction","Structure-preserving redaction","Configurable redaction policies","Audit trail of all redactions","Bulk processing with validation"], '✂️', 'Legal'),
    'ai-tax-compliance-calculator': ("AI tax compliance calculator for multi-jurisdiction sales tax, VAT, and GST. Real-time rate lookup with nexus tracking and filing automation.", ["Multi-jurisdiction tax rate lookup","Economic nexus tracking","Sales tax calculation and validation","Filing deadline management","Audit-ready reporting"], '🧮', 'Finance'),
    'ai-test-automation-framework': ("AI test automation that generates test cases from requirements, maintains test suites through UI changes, and provides intelligent failure triage.", ["AI-generated test cases from specs","Self-healing test maintenance","Intelligent failure triage","Visual regression detection","Cross-browser parallel execution"], '🧪', 'Technology'),
    'ai-threat-intelligence': ("Curated AI-powered threat intelligence with automated IOC ingestion, adversary profiling, and actionable alert enrichment for your security stack.", ["Automated IOC ingestion and scoring","Adversary profiling and tracking","Alert enrichment with context","Threat hunting query generation","MITRE ATT&CK mapping"], '🎯', 'Security'),
    'ai-trading-signal-engine': ("ML-driven trading signal generation with backtesting, risk management, and multi-factor model composition. Paper trading mode for validation before live deployment.", ["Multi-factor signal generation","Backtesting with slippage modeling","Risk management and position sizing","Paper trading validation","Real-time signal distribution"], '📊', 'Finance'),
    'ai-tutoring-platform': ("Adaptive AI tutoring that personalizes learning paths, assesses knowledge gaps, and provides interactive explanations. Supports K-12 through university curricula.", ["Personalized learning paths","Knowledge gap assessment","Interactive concept explanations","Progress tracking and reporting","Curriculum alignment mapping"], '🎓', 'Education'),
    'ai-voice-agent-builder': ("Build conversational voice agents with natural TTS, STT, and dialogue management. Deploy to phone, web, and smart speakers with analytics.", ["Natural TTS and STT integration","Dialogue flow builder","Multi-channel deployment","Conversation analytics","Transfer to human agent"], '🎙️', 'General'),
    'ai-voice-brand-consistency': ("Ensure brand-consistent voice experiences with pronunciation guides, tone enforcement, and persona validation across all voice AI touchpoints.", ["Custom pronunciation dictionary","Tone and style enforcement","Persona consistency scoring","Voice experience auditing","Cross-channel consistency checks"], '🗣️', 'Marketing'),
    'ai-voice-cloning-studio': ("Professional voice cloning with consent management, quality scoring, and style variation. Create custom voices for TTS with commercial licensing.", ["Voice cloning with consent management","Quality scoring and validation","Style and emotion variation","Commercial licensing support","Real-time TTS synthesis"], '🎵', 'Media'),
    'ai-vpc-zero-trust': ("Zero-trust network security for cloud VPCs with identity-based access, microsegmentation, and encrypted service meshes. No VPNs required.", ["Identity-based access control","Microsegmentation policy engine","Encrypted service mesh","Continuous posture verification","No VPN architecture"], '🛡️', 'Security'),
    'secure-file-transfer': ("Enterprise secure file transfer with end-to-end encryption, DLP scanning, and compliance audit trails. Replaces legacy FTP with modern API-first architecture.", ["End-to-end encryption","DLP content scanning","Compliance audit trails","API-first architecture","Ad hoc and scheduled transfers"], '📁', 'General'),
    'it-api-gateway-ai': ("AI-enhanced API gateway with intelligent rate limiting, threat detection, and request optimization. Learns traffic patterns for proactive protection.", ["AI-driven rate limiting","API threat detection","Traffic pattern learning","Request/response caching","Analytics and developer portal"], '🚪', 'Technology'),
    'it-api-performance-testing': ("Automated API performance testing with contract validation, load simulation, and latency regression detection across environments.", ["Contract validation testing","Realistic load simulation","Latency regression detection","Multi-environment comparison","Performance SLA enforcement"], '⏱️', 'Technology'),
    'it-cloud-cost-governance': ("Cloud cost governance with budget policies, chargeback automation, and anomaly detection. FinOps platform for multi-cloud cost optimization.", ["Budget policy enforcement","Chargeback and showback","Cost anomaly detection","Reserved instance management","FinOps maturity assessment"], '💵', 'Finance'),
    'it-incident-response-simulator': ("Simulate security incidents for training and procedural validation. Tabletop exercise automation with realistic scenario generation and response scoring.", ["Realistic scenario generation","Response action scoring","Procedural validation","Team training and certification","After-action report generation"], '🎬', 'Security'),
    'it-observability-logging': ("Unified observability logging with intelligent log routing, retention management, and cost-optimized storage tiers. Structured logging standards enforcement.", ["Intelligent log routing","Cost-optimized storage tiering","Structured logging enforcement","Retention policy automation","Cross-service log correlation"], '📋', 'Technology'),
    'it-synthetic-monitoring': ("Synthetic monitoring with multi-step user journeys, API health checks, and visual regression detection. Global probe network with SLA dashboards.", ["Multi-step user journey monitoring","API health check automation","Visual regression detection","Global probe network","SLA dashboard and alerting"], '🌐', 'Technology'),
}

import re

with open('app/data/servicesData.ts', 'r') as f:
    content = f.read()

count = 0
for sid, (desc, features, icon, industry) in STUB_MAP.items():
    id_pattern = f"id: '{sid}',"
    id_pos = content.find(id_pattern)
    if id_pos == -1:
        print(f"⚠️  Not found: {sid}")
        continue
    
    # Replace description
    old_desc = "description: 'Service description.',"
    pos = content.find(old_desc, id_pos)
    if pos != -1 and pos < id_pos + 600:
        new_desc = f"description: '{desc}',"
        content = content[:pos] + new_desc + content[pos+len(old_desc):]
    
    # Replace features
    old_feat = "features: ['Core functionality','Professional support','Scalable deployment'],"
    pos = content.find(old_feat, id_pos)
    if pos != -1 and pos < id_pos + 800:
        feat_strs = [f"'{f}'" for f in features]
        new_feat = f"features: [{','.join(feat_strs)}],"
        content = content[:pos] + new_feat + content[pos+len(old_feat):]
    
    count += 1

with open('app/data/servicesData.ts', 'w') as f:
    f.write(content)

print(f"✅ Upgraded {count} more stub services")
print(f"Remaining stubs: {content.count('Service description.')}")
