#!/usr/bin/env python3
"""
Client Onboarding Checklist Generator — Zion Tech Group

Watches for first-time client domains in inbox and creates a Google Doc
checklist with standard onboarding steps (contract, access provisioning,
welcome email, etc.). Adds 'Onboarding' label to the triggering email.

Usage:
  python3 client_onboarding.py [--execute]   # Create checklists (default dry-run)
  python3 client_onboarding.py --limit 50    # Max unread emails to scan
"""

import sys, os, re, json, datetime, argparse, urllib.request, urllib.parse
from pathlib import Path

WORKSPACE = Path('/root/.openclaw/workspace')
sys.path.insert(0, str(WORKSPACE / 'zion.app' / 'lib'))
sys.path.insert(0, str(WORKSPACE / 'zion.app' / 'commands'))

from google_workspace import gmail_search, gmail_get, gmail_get_or_create_label_id, gmail_batch_modify
from llm_client import chat

# ── Configuration ────────────────────────────────────────────────────────────

BATCH_SIZE = 50
ONBOARDING_LABEL = 'Onboarding'
STATE_FILE = WORKSPACE / 'zion.app' / 'data' / 'onboarding_state.json'  # tracks seen domains

def sender_domain(from_header: str) -> str:
    m = re.search(r'@([a-zA-Z0-9.\-]+)', from_header)
    return m.group(1).lower() if m else ''

def load_seen_domains() -> set:
    if STATE_FILE.exists():
        return set(json.loads(STATE_FILE.read_text()))
    return set()

def save_seen_domains(domains: set):
    STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(json.dumps(sorted(list(domains)), indent=2))

def is_client_domain(domain: str, vendor_domains: list) -> bool:
    """Heuristic: not internal, not known vendor, looks like a client org."""
    if not domain or domain.endswith('ziontechgroup.com'):
        return False
    vendor_patterns = ['mailchimp', 'sendgrid', 'beehiiv', 'substack', 'github', 'notion',
                      'intercom', 'zapier', 'google.com', 'cloudflare', 'godaddy']
    for vp in vendor_patterns:
        if vp in domain:
            return False
    return True  # treat anything not internal/vendor as potential client

def fetch_vendor_domains() -> list:
    """Reuse sender_reputation logic to get known vendor domains."""
    # Inline a small list; could be expanded
    return ['mailchimp.com', 'sendgrid.com', 'beehiiv.com', 'substack.com',
            'convertkit.com', 'buttondown.com', 'morningbrew.com',
            'github.com', 'notion.so', 'stytch.com', 'intercom.com', 'zapier.com',
            'revue.com', 'theinformation.com']

def generate_checklist_doc(domain: str, email_info: dict) -> str:
    """Create Google Doc with onboarding checklist; return doc ID."""
    # For now, create a Markdown file in reports/ then upload as .md to Drive.
    # Simpler: Create Doc via Drive API with simple HTML? Google Docs API requires
    # separate service. We'll create a .md file in reports and add link to Gmail draft.
    # Later can evolve to proper Doc.
    today = datetime.date.today().isoformat()
    filename = f"Onboarding — {domain} — {today}"
    report_dir = WORKSPACE / 'zion.app' / 'reports'
    report_dir.mkdir(parents=True, exist_ok=True)
    filepath = report_dir / f"{filename}.md"

    body = f"""# Client Onboarding Checklist

**Client:** {domain}
**First seen:** {today}
**Trigger email:** {email_info.get('subject','(unknown)')}

## ✅ Setup Steps

- [ ] Send welcome email (template: "Welcome to Zion Tech Group")
- [ ] Request signed contract/NDA if not already
- [ ] Create client folder in Drive: `Clients/{domain}/`
- [ ] Add to rate card (if applicable)
- [ ] Configure any required API keys / credentials
- [ ] Set up calendar sharing (if needed)
- [ ] Add to monthly invoice roster
- [ ] Assign account manager (Kleber by default)
- [ ] Schedule kickoff call (within 48h)
- [ ] Create shared workspace (if collaboration needed)
- [ ] Document special requirements

## Notes

(Add any client-specific details here)

---

*Auto-generated by Client Onboarding Agent on {today}*
"""
    filepath.write_text(body)
    print(f"   📝 Onboarding checklist saved to {filepath}")
    # Return a fake "doc ID" — the file path
    return str(filepath)

def draft_intro_email(domain: str, checklist_path: str, email_info: dict):
    """Create a Gmail draft to self with onboarding link."""
    subject = f"New Client Onboarding: {domain}"
    body = (
        f"A new client domain appeared in your inbox:\n\n"
        f"From: {email_info.get('from','')}\n"
        f"Subject: {email_info.get('subject','')}\n\n"
        f"Here's your onboarding checklist:\n{checklist_path}\n\n"
        f"— Automated by Zion Assistant"
    )
    import base64, json
    raw = f"Subject: {subject}\r\nTo: kleber@ziontechgroup.com\r\n\r\n{body}"
    encoded = base64.urlsafe_b64encode(raw.encode()).decode().rstrip('=')
    url = 'https://gmail.googleapis.com/gmail/v1/users/me/drafts'
    payload = json.dumps({'message': {'raw': encoded}}).encode()
    from google_workspace import gog_headers
    req = urllib.request.Request(url, data=payload, headers=gog_headers(), method='POST')
    resp = json.loads(urllib.request.urlopen(req).read())
    return resp.get('id')

def cmd_run(dry_run: bool, limit: int):
    print("👋 Client Onboarding scanning unread emails…")
    msgs = gmail_search('is:unread', limit=limit)
    print(f"📥 Fetched {len(msgs)} emails")

    seen = load_seen_domains()
    vendor_domains = fetch_vendor_domains()
    new_clients = []  # list of (domain, email_info)
    processed = 0

    for m in msgs:
        msg = gmail_get(m['id'])
        headers = {h['name']: h['value'] for h in msg.get('payload', {}).get('headers', [])}
        from_hdr = headers.get('From', '')
        subject = headers.get('Subject', '(no subject)')

        domain = sender_domain(from_hdr)
        if not is_client_domain(domain, vendor_domains):
            continue

        if domain in seen:
            continue  # already onboarded

        new_clients.append({'domain': domain, 'email': {'from': from_hdr, 'subject': subject}, 'msg_id': m['id']})
        processed += 1

    if not new_clients:
        print("✅ No new client domains detected.")
        return

    print(f"🆕 Found {len(new_clients)} new client domain(s):")
    for c in new_clients:
        print(f"   • {c['domain']}")

    if dry_run:
        print(f"\n💡 Add --execute to create onboarding checklists and draft intro emails.")
        return

    for c in new_clients:
        domain = c['domain']
        email_info = c['email']
        msg_id = c['msg_id']

        # Create checklist
        doc_ref = generate_checklist_doc(domain, email_info)
        try:
            draft_id = draft_intro_email(domain, doc_ref, email_info)
            print(f"✅ Draft intro email created (ID: {draft_id[:8]}…)")
        except Exception as e:
            print(f"❌ Draft failed: {e}")

        # Label email as onboarding-processed
        lbl_id = gmail_get_or_create_label_id(ONBOARDING_LABEL)
        gmail_batch_modify({'ids': [msg_id]}, addLabelIds=[lbl_id])

        # Record domain as seen
        seen.add(domain)

    save_seen_domains(seen)
    print(f"\n✅ Processed {len(new_clients)} new client(s). State saved.")

    # Telegram summary
    try:
        lines = ["📋 *New Client Onboarding*\n"]
        for c in new_clients:
            lines.append(f"• {c['domain']}")
        message(action='send', target='telegram', message='\n'.join(lines))
    except Exception:
        pass

def main():
    parser = argparse.ArgumentParser(description='Client Onboarding Checklist Generator')
    parser.add_argument('--execute', action='store_true', help='Create docs/drafts (default dry-run)')
    parser.add_argument('--limit', type=int, default=BATCH_SIZE, help='Max emails to scan')
    args = parser.parse_args()
    cmd_run(dry_run=not args.execute, limit=args.limit)

if __name__ == '__main__':
    main()
