#!/usr/bin/env python3
"""
Email-to-Task Converter — Zion Tech Group

Scans unread emails for actionable items, extracts task details via LLM,
and creates a Google Calendar event (1h block by default). Marks email
with 'Task-Created' label for traceability. Sends Telegram notification.

Usage:
  python3 email_to_task.py --execute   # Create tasks (default dry-run)
  python3 email_to_task.py --limit 10  # Max emails to scan
"""

import sys, os, re, json, datetime, argparse, urllib.request, urllib.parse
from pathlib import Path

WORKSPACE = Path('/root/.openclaw/workspace')
sys.path.insert(0, str(WORKSPACE / 'zion.app' / 'lib'))
sys.path.insert(0, str(WORKSPACE / 'zion.app' / 'commands'))

from google_workspace import gmail_search, gmail_get, gmail_get_or_create_label_id, gmail_batch_modify, calendar_create_event
from llm_client import chat

# ── Configuration ────────────────────────────────────────────────────────────

BATCH_SIZE = 10
TASK_LABEL = 'Task-Created'
DEFAULT_DURATION_MINUTES = 60
TIMEZONE_OFFSET = -3  # America/Sao_Paulo

# Action-trigger patterns (emails likely to contain tasks)
ACTION_PATTERNS = [
    r'\b(please|kindly|can you|could you|would you)\s+(do|send|provide|prepare|check|review|fix|update|create|schedule|call|meet)\b',
    r'\b(need|requires|must|should)\s+(to be|be)?\s+(done|completed|finished|sent|prepared)\b',
    r'\b(action\s+item|to-?do|next\s+steps?|follow[-\s]?up)\b',
    r'\b(deadline|due|by\s+(monday|tuesday|wednesday|thursday|friday|saturday|sunday| tomorrow|next week))\b',
]

# date keywords for LLM hint
DATE_HINTS = ['today', 'tomorrow', 'next monday', 'this friday', 'by next week', 'end of day', 'EOD', 'ASAP']

def looks_actionable(subject: str, body_preview: str) -> bool:
    text = (subject + ' ' + body_preview).lower()
    for pat in ACTION_PATTERNS:
        if re.search(pat, text, re.IGNORECASE):
            return True
    return False

def extract_task_via_llm(email: dict) -> dict:
    """Ask LLM to extract task: title, description, due date (ISO), duration (minutes)."""
    prompt = f"""Extract a task from this email. Return JSON only, with keys:
- "title": short task name (max 8 words)
- "description": 1–2 sentence summary
- "due": ISO date (YYYY-MM-DD) or "today" or "tomorrow" if relative; if unclear, use today
- "duration": estimated minutes (default 60)

Email:
Subject: {email['subject']}
From: {email['from']}
Body (first 500 chars):
{email['body_preview'][:500]}

Return JSON:"""
    resp = chat([{"role": "user", "content": prompt}], provider="auto")
    content = resp['content'].strip()
    try:
        # Strip markdown code fences if present
        if content.startswith('```'):
            content = re.sub(r'^```[a-z]*\n?', '', content).strip()
            content = re.sub(r'\n?```$', '', content)
        task = json.loads(content)
    except Exception as e:
        raise ValueError(f"LLM did not return valid JSON: {e}\nContent: {content[:200]}")
    # Normalize due date
    due_str = task.get('due', 'today').lower()
    today = datetime.date.today()
    if due_str in ('today', 'now', 'today'):
        due_date = today
    elif due_str in ('tomorrow', 'tmrw'):
        due_date = today + datetime.timedelta(days=1)
    elif due_str.startswith('next ') and any(day in due_str for day in ['monday','tuesday','wednesday','thursday','friday','saturday','sunday']):
        # Parse like "next monday"
        day_map = {'monday':0,'tuesday':1,'wednesday':2,'thursday':3,'friday':4,'saturday':5,'sunday':6}
        day_name = due_str.split()[1][:3]
        target_wd = day_map.get(day_name, 0)
        days_ahead = (target_wd - today.weekday()) % 7
        due_date = today + datetime.timedelta(days=days_ahead if days_ahead else 7)
    else:
        try:
            due_date = datetime.datetime.strptime(due_str[:10], '%Y-%m-%d').date()
        except Exception:
            due_date = today
    task['due_date'] = due_date.isoformat()
    task['duration'] = int(task.get('duration', DEFAULT_DURATION_MINUTES))
    return task

def create_calendar_event(task: dict, email: dict) -> str:
    """Create a calendar event; return event ID."""
    # Determine start/end times
    due_date = datetime.date.fromisoformat(task['due_date'])
    # Default to 10am local, convert to UTC for API
    start_dt = datetime.datetime(due_date.year, due_date.month, due_date.day, 10, 0, 0)
    # Apply timezone offset naive handling: send as UTC with 'Z'
    # Better: we can send with timeZone parameter; using UTC for simplicity
    end_dt = start_dt + datetime.timedelta(minutes=task['duration'])
    start_iso = start_dt.isoformat() + 'Z'
    end_iso = end_dt.isoformat() + 'Z'

    event = {
        'summary': task['title'],
        'description': (
            f"From email: {email['subject']}\n"
            f"Sender: {email['from']}\n\n"
            f"{task.get('description','')}\n\n"
            "— Auto-generated by Email-to-Task"
        ),
        'start': {'dateTime': start_iso},
        'end':   {'dateTime': end_iso},
    }
    return calendar_create_event(event)

def cmd_run(dry_run: bool, limit: int):
    print("🔎 Email-to-Task scanning unread emails…")
    msgs = gmail_search('is:unread', limit=limit)
    print(f"📥 Fetched {len(msgs)} emails")

    processed = 0
    created = 0
    for msg_meta in msgs:
        msg_id = msg_meta['id']
        msg = gmail_get(msg_id)
        headers = msg.get('payload', {}).get('headers', [])
        subject = next((h['value'] for h in headers if h['name'] == 'Subject'), '(no subject)')
        from_header = next((h['value'] for h in headers if h['name'] == 'From'), '')
        from_match = re.search(r'<(.+?)>', from_header)
        from_addr = from_match.group(1) if from_match else from_header
        body = extract_body_from_gmail_message(msg)
        preview = body[:800]

        email = {'id': msg_id, 'subject': subject, 'from': from_addr, 'body_preview': preview}

        if not looks_actionable(subject, preview):
            continue

        print(f"\n   📧 {subject[:60]}")
        print(f"      From: {from_addr}")

        if dry_run:
            print(f"      [DRY-RUN] Would extract task via LLM")
            created += 1
        else:
            try:
                task = extract_task_via_llm(email)
                print(f"      ✅ Task: {task['title']} (due {task['due_date']})")
                event_id = create_calendar_event(task, email)
                print(f"      📅 Calendar event created (ID: {event_id[:8]}…)")
                created += 1
            except Exception as e:
                print(f"      ❌ Task creation failed: {e}")
                continue

        # Label as processed
        label_id = gmail_get_or_create_label_id(TASK_LABEL)
        gmail_batch_modify({'ids': [msg_id]}, addLabelIds=[label_id])

        processed += 1

    print(f"\n✅ Processed {processed} actionable emails.")
    if dry_run:
        print(f"💡 Add --execute to create {created} calendar task(s).")
    else:
        print(f"📅 Created {created} calendar event(s).")
        # Optionally send Telegram summary
        try:
            message(action='send', target='telegram',
                    message=f"📅 Email-to-Task: created {created} calendar event(s) from {processed} emails.")
        except Exception:
            pass

def extract_body_from_gmail_message(msg):
    """Reuse from other scripts; safe import."""
    payload = msg.get('payload', {})
    if 'parts' in payload:
        for part in payload['parts']:
            if part.get('mimeType') == 'text/plain':
                data = part.get('body', {}).get('data', '')
                if data:
                    import base64
                    return base64.urlsafe_b64decode(data + '===').decode('utf-8', errors='replace')
    body = payload.get('body', {}).get('data', '')
    if body:
        import base64
        return base64.urlsafe_b64decode(body + '===').decode('utf-8', errors='replace')
    return ''

def main():
    parser = argparse.ArgumentParser(description='Email-to-Task Converter')
    parser.add_argument('--execute', action='store_true', help='Create calendar events (default: dry-run)')
    parser.add_argument('--limit', type=int, default=BATCH_SIZE, help='Max emails to scan')
    args = parser.parse_args()
    cmd_run(dry_run=not args.execute, limit=args.limit)

if __name__ == '__main__':
    main()
