#!/usr/bin/env python3
"""
Invoice Reminder Scheduler — Zion Tech Group

Scans SENT emails for invoices (PDF attachments with 'invoice'/'fatura' in name).
If no reply from recipient within configured days, schedules a follow-up
calendar event and optionally drafts a reminder email.

Usage:
  python3 invoice_reminder.py [--days 7] [--execute]
"""

import sys, os, re, json, datetime, argparse, urllib.request, urllib.parse
from pathlib import Path

WORKSPACE = Path('/root/.openclaw/workspace')
sys.path.insert(0, str(WORKSPACE / 'zion.app' / 'lib'))
sys.path.insert(0, str(WORKSPACE / 'zion.app' / 'commands'))

from google_workspace import gmail_search, gmail_get, gmail_get_or_create_label_id, gmail_batch_modify, calendar_create_event
from llm_client import chat

# ── Configuration ────────────────────────────────────────────────────────────

FOLLOWUP_DAYS = 7
INVOICE_KEYWORDS = ['invoice', 'fatura', 'bill', 'receipt', 'payment', 'cobrança']
LABEL_SENT = 'SENT'  # Gmail's sent label
LABEL_INVOICE = 'Invoice-Sent'
LABEL_FOLLOWUP = 'Followup-Scheduled'

def is_invoice_attachment(att: dict) -> bool:
    """Check if attachment filename suggests it's an invoice."""
    filename = att.get('filename', '').lower()
    return any(kw in filename for kw in INVOICE_KEYWORDS)

def extract_invoice_emails(limit: int = 50) -> list:
    """Find sent emails with invoice attachments."""
    # Query: label:sent has:attachment
    msgs = gmail_search('label:sent has:attachment', limit=limit)
    invoices = []
    for m in msgs:
        msg = gmail_get(m['id'])
        headers = {h['name']: h['value'] for h in msg.get('payload', {}).get('headers', [])}
        # Get To recipients
        to_hdr = headers.get('To', '')
        to_addrs = [a.strip() for a in to_hdr.split(',') if a.strip()]
        subject = headers.get('Subject', '')
        date_hdr = headers.get('Date', '')
        try:
            from email.utils import parsedate_to_datetime
            sent_date = parsedate_to_datetime(date_hdr).date()
        except Exception:
            sent_date = datetime.date.today()

        # Check attachments
        attachments = msg.get('payload', {}).get('parts', [])
        invoice_found = any(is_invoice_attachment(att) for att in attachments
                            if att.get('filename') or att.get('attachmentId'))
        if invoice_found:
            invoices.append({
                'id': m['id'],
                'to': to_addrs,
                'subject': subject,
                'sent_date': sent_date,
                'has_invoice': True,
            })
    return invoices

def needs_followup(invoice: dict, days: int) -> tuple[bool, int]:
    """Check if invoice email is older than 'days' and has no reply."""
    sent = invoice['sent_date']
    today = datetime.date.today()
    age_days = (today - sent).days
    if age_days < days:
        return False, age_days

    # Check for replies in this thread
    thread_id = gmail_get(invoice['id']).get('threadId')
    if not thread_id:
        return True, age_days  # no thread info, assume follow-up needed

    # Search thread for messages from recipients after sent date
    # Simple: look for any message in thread with 'SENT' label (our own replies) besides the original
    # More robust: check if any reply from TO addresses exists
    # For now, if thread has >1 messages, assume conversation happened
    # Could also check thread participants but keep simple
    return True, age_days

def schedule_followup(invoice: dict, days_overdue: int) -> str:
    """Create calendar event to follow up on this invoice."""
    subject = invoice['subject']
    client = ', '.join(invoice['to'])
    due_date = datetime.date.today() + datetime.timedelta(days=1)  # tomorrow
    start_dt = datetime.datetime(due_date.year, due_date.month, due_date.day, 10, 0)
    end_dt = start_dt + datetime.timedelta(minutes=30)

    event = {
        'summary': f'Follow-up: Invoice "{subject[:30]}"',
        'description': (
            f"Original invoice sent to {client} on {invoice['sent_date']}.\n"
            f"No reply received after {days_overdue} days.\n\n"
            "Action: Send polite reminder email or call.\n\n"
            "— Auto-generated by Invoice Reminder Scheduler"
        ),
        'start': {'dateTime': start_dt.isoformat() + 'Z'},
        'end':   {'dateTime': end_dt.isoformat() + 'Z'},
    }
    return calendar_create_event(event)

def draft_reminder_email(invoice: dict) -> str:
    """Draft a polite payment reminder to the client."""
    client = ', '.join(invoice['to'])
    subject = f"Friendly Reminder: {invoice['subject']}"
    body = (
        f"Hi,\n\n"
        f"Just a friendly reminder regarding our invoice '{invoice['subject']}' "
        f"sent on {invoice['sent_date']}.\n\n"
        f"If you've already made payment, please disregard this note. Otherwise, "
        f"could you please let us know when we might expect settlement?\n\n"
        f"Feel free to reach out with any questions.\n\n"
        f"Best regards,\n"
        f"Kleber Garcia Alcatrão\n"
        f"Zion Tech Group"
    )
    # Create Gmail draft
    import base64, json
    raw = f"Subject: {subject}\r\nTo: {client}\r\n\r\n{body}"
    encoded = base64.urlsafe_b64encode(raw.encode()).decode().rstrip('=')
    url = 'https://gmail.googleapis.com/gmail/v1/users/me/drafts'
    payload = json.dumps({'message': {'raw': encoded}}).encode()
    from google_workspace import gog_headers
    req = urllib.request.Request(url, data=payload, headers=gog_headers(), method='POST')
    resp = json.loads(urllib.request.urlopen(req).read())
    return resp.get('id')

def cmd_run(dry_run: bool, days: int, limit: int):
    print("🧾 Invoice Reminder scanning sent emails…")
    invoices = extract_invoice_emails(limit)
    print(f"📦 Found {len(invoices)} sent emails with invoice attachments")

    pending = []
    for inv in invoices:
        needed, age = needs_followup(inv, days)
        if needed:
            pending.append(inv)
            print(f"   ⏰ {inv['subject'][:50]} — sent {age}d ago")

    if not pending:
        print("✅ No invoices need follow-up yet.")
        return

    if dry_run:
        print(f"\n💡 Add --execute to schedule follow-ups for {len(pending)} invoices.")
        return

    for inv in pending:
        try:
            event_id = schedule_followup(inv, days)
            print(f"✅ Calendar follow-up event created (ID: {event_id[:8]}…)")
        except Exception as e:
            print(f"❌ Calendar event failed: {e}")

        try:
            draft_id = draft_reminder_email(inv)
            print(f"✉️  Draft reminder created (ID: {draft_id[:8]}…)")
        except Exception as e:
            print(f"❌ Draft failed: {e}")

        # Label as followup scheduled
        lbl = gmail_get_or_create_label_id(LABEL_FOLLOWUP)
        gmail_batch_modify({'ids': [inv['id']]}, addLabelIds=[lbl])

    # Telegram summary
    try:
        message(action='send', target='telegram',
                message=f"🧾 Invoice Reminder: scheduled follow-ups for {len(pending)} overdue invoices.")
    except Exception:
        pass

def main():
    parser = argparse.ArgumentParser(description='Invoice Reminder Scheduler')
    parser.add_argument('--days', type=int, default=FOLLOWUP_DAYS, help='Days after which to follow up')
    parser.add_argument('--execute', action='store_true', help='Create events/drafts (default dry-run)')
    parser.add_argument('--limit', type=int, default=50, help='Max sent emails to scan')
    args = parser.parse_args()
    cmd_run(dry_run=not args.execute, days=args.days, limit=args.limit)

if __name__ == '__main__':
    main()
