// Local legacy PM2 stack for scripts/automation tooling.
// Prefer ecosystem.config.cjs for the primary automation runtime.
module.exports = {
  apps: [
    {
      name: 'continuous-automation',
      script: './scripts/automation/comprehensive-continuous-automation.cjs',
      args: '--continuous',
      cwd: __dirname + '/../../',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      max_restarts: 10,
      min_uptime: '30s',
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      env: {
        NODE_ENV: 'production',
        RUN_CONTINUOUSLY: 'true',
      },
    },
    {
      name: 'error-monitor',
      script: './scripts/automation/error-monitor.cjs',
      cwd: __dirname + '/../../',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      max_restarts: 10,
      min_uptime: '20s',
      restart_delay: 4000,
      exp_backoff_restart_delay: 200,
      env: {
        NODE_ENV: 'production',
        RUN_CONTINUOUSLY: 'true',
        SCAN_INTERVAL: '5',
      },
    },
    {
      name: 'health-checker',
      script: './scripts/automation/health-checker.cjs',
      cwd: __dirname + '/../../',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      max_restarts: 10,
      min_uptime: '20s',
      restart_delay: 4000,
      exp_backoff_restart_delay: 200,
      env: {
        NODE_ENV: 'production',
        RUN_CONTINUOUSLY: 'true',
        CHECK_INTERVAL: '3',
      },
    },
    {
      name: 'auto-fixer',
      script: './scripts/automation/auto-fixer.cjs',
      cwd: __dirname + '/../../',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '384M',
      max_restarts: 8,
      min_uptime: '30s',
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      env: {
        NODE_ENV: 'production',
        RUN_CONTINUOUSLY: 'true',
        FIX_INTERVAL: '10',
        AUTO_FIX: 'false',
      },
    },
    {
      name: 'syntax-fixer',
      script: './scripts/automation/syntax-fixer.cjs',
      cwd: __dirname + '/../../',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      max_restarts: 8,
      min_uptime: '20s',
      restart_delay: 4000,
      exp_backoff_restart_delay: 200,
      env: {
        NODE_ENV: 'production',
        RUN_CONTINUOUSLY: 'true',
        FIX_INTERVAL: '15',
        FIX_ON_DETECT: 'false',
      },
    },
    {
      name: 'dependency-manager',
      script: './scripts/automation/dependency-manager.cjs',
      cwd: __dirname + '/../../',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '384M',
      max_restarts: 8,
      min_uptime: '30s',
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      env: {
        NODE_ENV: 'production',
        RUN_CONTINUOUSLY: 'true',
        CHECK_INTERVAL: '60',
      },
    },
    {
      name: 'build-monitor',
      script: './scripts/automation/build-monitor.cjs',
      cwd: __dirname + '/../../',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      max_restarts: 8,
      min_uptime: '20s',
      restart_delay: 4000,
      exp_backoff_restart_delay: 200,
      env: {
        NODE_ENV: 'production',
        MONITOR_CONTINUOUSLY: 'true',
        MONITOR_INTERVAL: '10',
      },
    },
    {
      name: 'intelligent-orchestrator',
      script: './scripts/automation/intelligent-automation-orchestrator.cjs',
      cwd: __dirname + '/../../',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      max_restarts: 8,
      min_uptime: '20s',
      restart_delay: 4000,
      exp_backoff_restart_delay: 200,
      env: {
        NODE_ENV: 'production',
        ORCHESTRATE_CONTINUOUSLY: 'true',
        ORCHESTRATE_INTERVAL: '20',
      },
    },
    {
      name: 'automation-dashboard',
      script: './scripts/automation/automation-dashboard.cjs',
      cwd: __dirname + '/../../',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      max_restarts: 8,
      min_uptime: '20s',
      restart_delay: 4000,
      exp_backoff_restart_delay: 200,
      env: {
        NODE_ENV: 'production',
        RUN_CONTINUOUSLY: 'true',
        REFRESH_INTERVAL: '30',
      },
    },
    {
      name: 'log-cleaner',
      script: './scripts/automation/log-cleaner.cjs',
      cwd: __dirname + '/../../',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '128M',
      max_restarts: 5,
      min_uptime: '20s',
      restart_delay: 3000,
      exp_backoff_restart_delay: 200,
      env: {
        NODE_ENV: 'production',
        RUN_CONTINUOUSLY: 'true',
        CLEAN_INTERVAL: '1440',
      },
    },
  ],
};
