// app/constants/navigation.ts
// Navigation link registry for Zion Tech Group
// All /services/{slug} hrefs match servicesData.ts (425 built services)
export type NavigationLink = {
  name: string;
  href: string;
  aliases?: readonly string[];
};

// ─── ROOT PAGE ROUTES ────────────────────────────────────────────────────────
const HOME: NavigationLink             = { name: 'Home',            href: '/' };
const SERVICES: NavigationLink          = { name: 'Services',        href: '/services' };
const SOLUTIONS: NavigationLink         = { name: 'Solutions',       href: '/solutions' };
const PRICING: NavigationLink           = { name: 'Pricing',         href: '/pricing' };
const CONTACT: NavigationLink           = { name: 'Contact',         href: '/contact' };
const SEARCH: NavigationLink            = { name: 'Search',          href: '/search' };
const INIT: NavigationLink              = { name: 'Industries',      href: '/industries' };
const PORTAL: NavigationLink            = { name: 'Client Portal',   href: '/portal' };

export const PRIMARY_NAV_LINKS: readonly NavigationLink[] = [
  HOME, SOLUTIONS, SERVICES, PRICING, CONTACT,
];

export const SOLUTION_LINKS: readonly NavigationLink[] = [
  { name: 'All Solutions',        href: '/solutions' },
  { name: 'Healthcare',           href: '/industry-solutions#healthcare' },
  { name: 'Financial Services',   href: '/industry-solutions#financial-services' },
  { name: 'Manufacturing & Industrial', href: '/industry-solutions#manufacturing' },
  { name: 'E‑Commerce & Retail',  href: '/industry-solutions#ecommerce' },
  { name: 'Technology & SaaS',    href: '/industry-solutions#technology' },
  { name: 'Logistics & Supply Chain', href: '/industry-solutions#logistics' },
  { name: 'Government & Public Sector', href: '/industry-solutions#government' },
  { name: 'Insurance',            href: '/industry-solutions#insurance' },
  INIT,
];

export const RESOURCE_LINKS: readonly NavigationLink[] = [
  SEARCH,
  { name: 'Pricing Calculator',   href: '/pricing-calculator' },
  { name: 'Proposal Generator',   href: '/proposal-generator' },
  { name: 'Service Comparison',   href: '/tools/service-comparison' },
  { name: 'Service Recommender',  href: '/tools/service-recommender' },
  PORTAL,
];

// ─── FEATURED AI SERVICES ───────────────────────────────────────────────────
// Top 8 most-requested AI services
export const FEATURED_AI_SERVICE_LINKS: readonly NavigationLink[] = [
  { name: 'AI Agentic Workflows',              href: '/services/ai-agentic-workflows' },
  { name: 'AI Customer Support',                href: '/services/ai-customer-support' },
  { name: 'AI Content Generation',              href: '/services/ai-content-generation' },
  { name: 'AI Voice Assistant',                  href: '/services/ai-voice-assistant' },
  { name: 'AI Compliance Reporting',             href: '/services/ai-compliance' },
  { name: 'AI Document Intelligence',            href: '/services/ai-document-qa' },
  { name: 'AI Lead Generation & Enrichment',     href: '/services/ai-lead-enricher' },
  { name: 'AI Knowledge Management',             href: '/services/ai-knowledge-graph-builder' },
];

// ─── CORE FEATURED PRODUCTS ─────────────────────────────────────────────────
export const FEATURED_PRODUCT_LINKS: readonly NavigationLink[] = [
  { name: 'Zion Analytics Pro',           href: '/zion-analytics-pro' },
  { name: 'Zion CRM Intelligence',        href: '/zion-crm-intelligence' },
  { name: 'Zion Content Studio',          href: '/zion-content-studio' },
  { name: 'Zion Project Master',          href: '/zion-project-master' },
  { name: 'Zion Performance Monitor',     href: '/zion-performance-monitor' },
  { name: 'Zion Lead Magnet',             href: '/zion-lead-magnet' },
  { name: 'Zion Invoice Genius',          href: '/zion-invoice-genius' },
  { name: 'Zion Data Sync',               href: '/zion-data-sync' },
  { name: 'Autonomous Media Prompt Studio',    href: '/ai-lab/autonomous-media-prompt-studio' },
  { name: 'Autonomous RAG Knowledge Workspace', href: '/ai-lab/autonomous-rag-knowledge-workspace' },
];

// ─── SERVICE CATALOG NAVIGATION ────────────────────────────────────────────
// All 425 services, deduplicated. Per-category arrays for component use.
// Shared by search configurator, compare tool, homepage showcase.

export const AI_SERVICE_LINKS: readonly NavigationLink[] = [
  { name: 'Accessibility & WCAG Compliance', href: '/services/accessibility-compliance' },
  { name: 'Advanced AI & Enterprise Intelligence Hub', href: '/services/advanced-ai-enterprise-intelligence-hub' },
  { name: 'Agentic Workflow Orchestrator', href: '/services/agentic-workflow-orchestrator' },
  { name: 'AI 1:1 Tutor for K–12 & Higher Ed', href: '/services/ai-education-tutor' },
  { name: 'Ai 3D Asset Generator', href: '/services/ai-3d-asset-generator' },
  { name: 'AI Accessibility Auditor', href: '/services/ai-accessibility-auditor' },
  { name: 'AI Accessibility Content Optimizer', href: '/services/ai-accessibility-optimizer' },
  { name: 'Ai Ad Copy Generator', href: '/services/ai-ad-copy-generator' },
  { name: 'AI Adaptive Tutoring System', href: '/services/ai-education-adaptive-tutor' },
  { name: 'Ai Agent Safety Evaluation', href: '/services/ai-agent-safety-evaluation' },
  { name: 'AI Agent Tool Builder', href: '/services/ai-agent-tool-builder' },
  { name: 'AI Agentic Workflow Automation', href: '/services/ai-agentic-workflows' },
  { name: 'AI Agents & Autonomous Workflows', href: '/services/ai-agents-autonomous' },
  { name: 'AI Analytics & BI', href: '/services/ai-analytics' },
  { name: 'Ai Api Orchestration Layer', href: '/services/ai-api-orchestration-layer' },
  { name: 'AI Automation', href: '/services/ai-automation' },
  { name: 'AI BDR/SDR Agent', href: '/services/ai-bdr-sdr' },
  { name: 'AI BOM & Procurement Optimiser', href: '/services/ai-bom-procurement' },
  { name: 'AI Brand Voice Guardian', href: '/services/ai-brand-voice-guardian' },
  { name: 'Ai Bug To Issue Router', href: '/services/ai-bug-to-issue-router' },
  { name: 'AI Call Center Voice Analytics', href: '/services/ai-call-center-voice-analytics' },
  { name: 'AI Campaign Performance Predictor', href: '/services/ai-campaign-predictor' },
  { name: 'Ai Carbon Optimizer', href: '/services/ai-carbon-optimizer' },
  { name: 'AI Chatbot Builder Pro', href: '/services/ai-chatbot-builder-pro' },
  { name: 'AI Cloud Cost Optimizer', href: '/services/ai-cloud-cost-optimizer' },
  { name: 'AI Code Assistant (Enterprise)', href: '/services/ai-code-assistant-enterprise' },
  { name: 'AI Code Audit & Security Scanner', href: '/services/ai-code-audit-security' },
  { name: 'AI Code Migration & Legacy Modernization', href: '/services/ai-code-migration' },
  { name: 'AI Code Migration & Modernization', href: '/services/ai-code-migration-modernization' },
  { name: 'AI Code Migration Assistant', href: '/services/ai-code-migration-assistant' },
  { name: 'AI Code Review Assistant', href: '/services/ai-code-review-assistant' },
  { name: 'Ai Code Reviewer', href: '/services/ai-code-reviewer' },
  { name: 'AI Code Reviewer Pro', href: '/services/ai-code-reviewer-pro' },
  { name: 'AI Codebase Documentation Generator', href: '/services/ai-codebase-doc-generator' },
  { name: 'AI Competitive Intel Engine', href: '/services/ai-competitive-intel-engine' },
  { name: 'Ai Competitive Price Tracker', href: '/services/ai-competitive-price-tracker' },
  { name: 'AI Compliance & Regulatory', href: '/services/ai-compliance' },
  { name: 'AI Computer Vision', href: '/services/ai-computer-vision' },
  { name: 'AI Content Generation', href: '/services/ai-content-generation' },
  { name: 'AI Content Localization & Cultural Adaptation', href: '/services/ai-content-localization' },
  { name: 'AI Content Moderation Platform', href: '/services/ai-content-moderation-platform' },
  { name: 'AI Content Moderation Platform', href: '/services/ai-content-moderation' },
  { name: 'Ai Context Engineering Enterprise', href: '/services/ai-context-engineering-enterprise' },
  { name: 'Ai Contract Lifecycle Intelligence', href: '/services/ai-contract-lifecycle-intelligence' },
  { name: 'AI Contract Manager', href: '/services/ai-contract-manager' },
  { name: 'AI Contract Review Assistant', href: '/services/ai-contract-review' },
  { name: 'AI Copilot & Enterprise Assistants', href: '/services/ai-copilot-enterprise' },
  { name: 'AI Copywriting & Content Studio', href: '/services/generative-ai-copywriting' },
  { name: 'Ai Credit Underwriting', href: '/services/ai-credit-underwriting' },
  { name: 'Ai Cro Optimizer', href: '/services/ai-cro-optimizer' },
  { name: 'Ai Cross Lingual Bridge', href: '/services/ai-cross-lingual-bridge' },
  { name: 'Ai Cross Lingual Meeting Bridge', href: '/services/ai-cross-lingual-meeting-bridge' },
  { name: 'AI Cultural Fit Screener', href: '/services/ai-cultural-fit-screener' },
  { name: 'AI Customer Sentiment Analytics', href: '/services/ai-customer-sentiment-analytics' },
  { name: 'AI Customer Sentiment Tracker', href: '/services/ai-customer-sentiment-tracker' },
  { name: 'AI Customer Support', href: '/services/ai-customer-support' },
  { name: 'AI Customer Support Agent', href: '/services/ai-customer-support-agent' },
  { name: 'AI Cyber Threat Hunting & Incident Response', href: '/services/ai-cyber-threat-hunting' },
  { name: 'AI Cyber Threat Intelligence Platform', href: '/services/cyber-threat-intelligence' },
  { name: 'Ai Dashboard Designer', href: '/services/ai-dashboard-designer' },
  { name: 'AI Data Quality & Enforcement Engine', href: '/services/ai-data-quality-engine' },
  { name: 'Ai Data Quality Fabric', href: '/services/ai-data-quality-fabric' },
  { name: 'Ai Data Quality Guardian', href: '/services/ai-data-quality-guardian' },
  { name: 'Ai Deepfake Detection', href: '/services/ai-deepfake-detection' },
  { name: 'AI DevOps Chatbot', href: '/services/ai-devops-chatbot' },
  { name: 'Ai Digital Twin Platform', href: '/services/ai-digital-twin-platform' },
  { name: 'AI Document Classifier', href: '/services/ai-document-classifier' },
  { name: 'AI Document Intelligence', href: '/services/ai-document-intelligence' },
  { name: 'AI Document Q&A Engine', href: '/services/ai-document-qa' },
  { name: 'AI Drug Discovery & Molecular Design', href: '/services/ai-drug-discovery' },
  { name: 'Ai Drug Discovery Platform', href: '/services/ai-drug-discovery-platform' },
  { name: 'AI Drug Interaction Checker', href: '/services/ai-drug-interaction-checker' },
  { name: 'Ai Dyslexia Assist', href: '/services/ai-dyslexia-assist' },
  { name: 'Ai Ecommerce Smart Search', href: '/services/ai-ecommerce-smart-search' },
  { name: 'AI Edge & Real-Time Inference', href: '/services/ai-edge-realtime-inference' },
  { name: 'AI Email Marketing', href: '/services/ai-email-marketing' },
  { name: 'AI Employee Experience Platform', href: '/services/ai-employee-experience' },
  { name: 'AI Energy Optimization & Sustainability', href: '/services/ai-energy-optimization' },
  { name: 'AI Ethics Audit & Bias Assessment', href: '/services/ai-ethics-audit-1' },
  { name: 'AI Ethics, Safety & Governance Framework', href: '/services/ai-ethics-governance' },
  { name: 'AI ETL Pipeline Builder', href: '/services/ai-etl-pipeline-builder' },
  { name: 'Ai Exam Proctoring', href: '/services/ai-exam-proctoring' },
  { name: 'AI Expense Categorisation & Audit', href: '/services/ai-expense-audit' },
  { name: 'Ai Feature Store', href: '/services/ai-feature-store' },
  { name: 'Ai Federated Learning', href: '/services/ai-federated-learning' },
  { name: 'AI FedRAMP Compliance Assistant', href: '/services/ai-fedrisk-compliance' },
  { name: 'AI Financial Forecasting & Planning', href: '/services/ai-financial-forecasting' },
  { name: 'AI Financial Fraud Detection & Prevention', href: '/services/ai-financial-fraud-detection' },
  { name: 'Ai Finetuning Alignment Pipelines', href: '/services/ai-finetuning-alignment-pipelines' },
  { name: 'Ai Fintech Fraud Graph', href: '/services/ai-fintech-fraud-graph' },
  { name: 'AI for Regulated Industries', href: '/services/ai-regulated-industries' },
  { name: 'AI for Sustainable Operations (Green AI)', href: '/services/ai-sustainable-ops' },
  { name: 'Ai Form Filler Intelligence', href: '/services/ai-form-filler-intelligence' },
  { name: 'AI Foundation Models & Custom Training', href: '/services/ai-foundation-models-custom-training' },
  { name: 'AI Fraud Detection', href: '/services/ai-fraud-detection' },
  { name: 'AI Fraud Detection for Finance', href: '/services/ai-fraud-detection-finance' },
  { name: 'AI Fraud Pattern Analyzer', href: '/services/ai-fraud-pattern-analyzer' },
  { name: 'AI Full-Stack Test Generator', href: '/services/ai-fullstack-test-generator' },
  { name: 'Ai Genomic Analysis', href: '/services/ai-genomic-analysis' },
  { name: 'Ai Glassdoor Review Analyzer', href: '/services/ai-glassdoor-review-analyzer' },
  { name: 'AI Governance & Trust', href: '/services/ai-governance-trust' },
  { name: 'Ai Governance Compliance', href: '/services/ai-governance-compliance' },
  { name: 'AI Grant & Funding Opportunity Matcher', href: '/services/ai-grant-matcher' },
  { name: 'AI Growth Intelligence Platform', href: '/services/ai-growth-intelligence' },
  { name: 'Ai Hiring Pipeline Optimizer', href: '/services/ai-hiring-pipeline-optimizer' },
  { name: 'AI HR Assistant', href: '/services/ai-hr-assistant' },
  { name: 'Ai Infra Provisioner', href: '/services/ai-infra-provisioner' },
  { name: 'Ai Insurance Claims', href: '/services/ai-insurance-claims' },
  { name: 'AI Insurance Pricing Advisor', href: '/services/ai-insurance-pricing' },
  { name: 'AI Integration & APIs', href: '/services/ai-integration-apis' },
  { name: 'AI Intelligent Document Processing & Routing', href: '/services/ai-intelligent-routing' },
  { name: 'Ai Interview Conduct Bot', href: '/services/ai-interview-conduct-bot' },
  { name: 'AI Invoice Processing & Auto-Posting', href: '/services/invoice-ai-automation' },
  { name: 'AI IT Helpdesk & Support', href: '/services/ai-it-helpdesk' },
  { name: 'AI Job Description & Interview Kit', href: '/services/ai-job-description-kit' },
  { name: 'AI Job Matcher & Career Path', href: '/services/ai-job-matcher' },
  { name: 'AI Knowledge Base & Knowledge Graph Agent', href: '/services/ai-knowledge-base-agent' },
  { name: 'Ai Knowledge Base Rag', href: '/services/ai-knowledge-base-rag' },
  { name: 'AI Knowledge Graph Builder', href: '/services/ai-knowledge-graph' },
  { name: 'Ai Knowledge Graph Search Deep', href: '/services/ai-knowledge-graph-search-deep' },
  { name: 'Ai Knowledge Graph Search Engine', href: '/services/ai-knowledge-graph-search-engine' },
  { name: 'AI Knowledge Management', href: '/services/ai-knowledge-management' },
  { name: 'Ai Kubernetes Optimizer', href: '/services/ai-kubernetes-optimizer' },
  { name: 'Ai Kyc Aml Compliance', href: '/services/ai-kyc-aml-compliance' },
  { name: 'AI Lead Generation & Enrichment', href: '/services/ai-lead-generation' },
  { name: 'AI Lead Richness Scorer & Enricher', href: '/services/ai-lead-enricher' },
  { name: 'AI Legal Contract Redaction', href: '/services/ai-legal-contract-redaction' },
  { name: 'AI Legal Document Analysis & Contract Review', href: '/services/ai-legal-document-analysis' },
  { name: 'AI Legal Document Redlining & Review', href: '/services/ai-legal-redline' },
  { name: 'AI Legal Document Review', href: '/services/ai-legal-doc-review' },
  { name: 'AI Legal Document Review & Risk Analysis', href: '/services/legal-doc-review-ai' },
  { name: 'AI Legal Research Engine', href: '/services/ai-legal-research' },
  { name: 'Ai Llm Router Pro', href: '/services/ai-llm-router-pro' },
  { name: 'Ai Load Testing', href: '/services/ai-load-testing' },
  { name: 'Ai Log Analysis', href: '/services/ai-log-analysis' },
  { name: 'Ai Low Code Integration', href: '/services/ai-low-code-integration' },
  { name: 'AI Marketing Copy Generator', href: '/services/ai-marketing-copy-generator' },
  { name: 'AI Media & News Monitoring', href: '/services/ai-media-monitoring' },
  { name: 'Ai Medical Image Diagnosis', href: '/services/ai-medical-image-diagnosis' },
  { name: 'AI Medical Imaging & Diagnostics', href: '/services/ai-medical-imaging' },
  { name: 'AI Meeting Assistant Pro', href: '/services/ai-meeting-assistant-pro' },
  { name: 'AI Meeting Notes & Summary Platform', href: '/services/ai-meeting-notes-summary' },
  { name: 'AI Meeting Pre-read Generator', href: '/services/ai-meeting-preread' },
  { name: 'AI Meeting Summarizer & Action Tracker', href: '/services/ai-meeting-summarizer-pro' },
  { name: 'Ai Memory Agents Long Horizon', href: '/services/ai-memory-agents-long-horizon' },
  { name: 'AI Mental Health Companion', href: '/services/ai-mental-health-chatbot' },
  { name: 'Ai Metadata Management', href: '/services/ai-metadata-management' },
  { name: 'AI Model Orchestration', href: '/services/ai-model-orchestration' },
  { name: 'AI Multimodal Intelligence', href: '/services/ai-multimodal-intelligence' },
  { name: 'Ai Multimodal Video Understanding', href: '/services/ai-multimodal-video-understanding' },
  { name: 'AI Newsletter Engagement Analyser', href: '/services/ai-newsletter-engagement' },
  { name: 'Ai Nutrition Meal Planner', href: '/services/ai-nutrition-meal-planner' },
  { name: 'AI Observability & MLOps', href: '/services/ai-observability-mlops' },
  { name: 'Ai Observability Turbo', href: '/services/ai-observability-turbo' },
  { name: 'AI Omnichannel Chatbot', href: '/services/ai-chatbot-omnichannel' },
  { name: 'AI Omnichannel Chatbot Platform', href: '/services/ai-omnichannel-chatbot' },
  { name: 'AI PDF Document Engine', href: '/services/ai-pdf-engine' },
  { name: 'Ai Personal Finance Coach', href: '/services/ai-personal-finance-coach' },
  { name: 'AI Personalization & Recommendation Engine', href: '/services/ai-personalization-engine' },
  { name: 'AI Personalized Learning Platform', href: '/services/ai-personalized-learning' },
  { name: 'AI Post-Purchase Customer Care Agent', href: '/services/ai-post-purchase-care' },
  { name: 'AI PRD & User Story Generator', href: '/services/ai-prd-story-gen' },
  { name: 'AI Predictive Churn & Retention', href: '/services/ai-predictive-churn' },
  { name: 'AI Predictive Maintenance & Asset Monitoring', href: '/services/ai-predictive-maintenance' },
  { name: 'Ai Predictive Maintenance Advisor', href: '/services/ai-predictive-maintenance-advisor' },
  { name: 'AI Predictive Workforce Planning', href: '/services/ai-predictive-workforce-planning' },
  { name: 'AI Presentation & Pitch Deck Maker', href: '/services/ai-presentation-maker' },
  { name: 'AI Privacy Policy & Compliance Generator', href: '/services/ai-compliance-generator' },
  { name: 'Ai Privilege Access Manager', href: '/services/ai-privilege-access-manager' },
  { name: 'AI Procurement Intelligence', href: '/services/ai-procurement' },
  { name: 'AI Product Analytics & Anomaly Detection', href: '/services/ai-product-analytics' },
  { name: 'Ai Product Photo Enhancer', href: '/services/ai-product-photo-enhancer' },
  { name: 'Ai Profitability Dashboard', href: '/services/ai-profitability-dashboard' },
  { name: 'AI Project Planning & Scheduling', href: '/services/ai-project-planning' },
  { name: 'Ai Quality Inspection', href: '/services/ai-quality-inspection' },
  { name: 'Ai Quantum Optimizer', href: '/services/ai-quantum-optimizer' },
  { name: 'AI RAG & Knowledge Systems', href: '/services/ai-rag-knowledge-systems' },
  { name: 'AI Real Estate Valuation & Analytics', href: '/services/ai-real-estate-valuation' },
  { name: 'AI Red Team Automation', href: '/services/ai-red-team-automation' },
  { name: 'AI Regulatory Compliance Monitor', href: '/services/ai-regulatory-compliance-monitor' },
  { name: 'Ai Reinforcement Learning Ops', href: '/services/ai-reinforcement-learning-ops' },
  { name: 'AI Resume Optimizer', href: '/services/ai-resume-optimizer' },
  { name: 'AI Retail Personalization Engine', href: '/services/ai-retail-personalization' },
  { name: 'AI Retail Recommendation Engine', href: '/services/ai-retail-recommendation-engine' },
  { name: 'AI Revenue Clarity & Forecasting', href: '/services/ai-revenue-clarity' },
  { name: 'AI Revenue Operations (RevOps)', href: '/services/ai-revenue-ops' },
  { name: 'AI Revenue Optimization & Pricing Intelligence', href: '/services/ai-revenue-optimization' },
  { name: 'AI Robotic Process Automation (RPA)', href: '/services/ai-rpa-automation' },
  { name: 'AI Robotics Integration & Autonomous Systems', href: '/services/ai-robotics-integration' },
  { name: 'Ai Rpa Platform', href: '/services/ai-rpa-platform' },
  { name: 'AI Sales Coach & Call Analysis', href: '/services/ai-sales-coach' },
  { name: 'AI Sales Intelligence', href: '/services/ai-sales-intelligence' },
  { name: 'Ai Secrets Management', href: '/services/ai-secrets-management' },
  { name: 'AI Security & Responsible AI', href: '/services/ai-security-responsible-ai' },
  { name: 'AI Self-Healing Infrastructure', href: '/services/ai-self-healing-infra' },
  { name: 'AI Sentiment & Brand Pulse Monitor', href: '/services/ai-sentiment-brand-pulse' },
  { name: 'AI Sentiment Analysis & Brand Monitoring', href: '/services/ai-sentiment-analysis' },
  { name: 'AI SEO Content Optimizer', href: '/services/ai-seo-optimizer' },
  { name: 'Ai Seo Content Optimizer', href: '/services/ai-seo-content-optimizer' },
  { name: 'Ai Serverless Platform', href: '/services/ai-serverless-platform' },
  { name: 'Ai Smart Document Redactor', href: '/services/ai-smart-document-redactor' },
  { name: 'AI Social Scheduler & Content Composer', href: '/services/ai-social-scheduler' },
  { name: 'AI Spatial Computing & AR/VR Analytics', href: '/services/ai-spatial-computing' },
  { name: 'AI Speech & Voice Solutions', href: '/services/ai-speech-voice-solutions' },
  { name: 'AI Strategy & Roadmap', href: '/services/ai-strategy-roadmap' },
  { name: 'AI Strategy & Roadmap Consulting', href: '/services/ai-roadmap-strategy' },
  { name: 'AI Supply & Demand Planner', href: '/services/ai-supply-demand-planner' },
  { name: 'AI Supply Chain Intelligence', href: '/services/ai-supply-chain-intelligence' },
  { name: 'AI Supply Chain Optimization', href: '/services/ai-supply-chain' },
  { name: 'AI Supply Chain Optimization & Demand Forecasting', href: '/services/ai-supply-chain-optimizer' },
  { name: 'AI Supply Chain Predictor', href: '/services/ai-supply-chain-predictor' },
  { name: 'AI Supply Chain Visibility Platform', href: '/services/ai-supply-chain-visibility' },
  { name: 'AI Sustainability & Carbon Tracker', href: '/services/ai-sustainability-carbon-tracker' },
  { name: 'Ai Sustainable Supply Chain Radar', href: '/services/ai-sustainable-supply-chain-radar' },
  { name: 'AI Talent Acquisition & Hiring Intelligence', href: '/services/ai-talent-acquisition' },
  { name: 'AI Talent Acquisition Platform', href: '/services/ai-talent-acquisition-platform' },
  { name: 'Ai Tax Compliance Calculator', href: '/services/ai-tax-compliance-calculator' },
  { name: 'Ai Test Automation Framework', href: '/services/ai-test-automation-framework' },
  { name: 'AI Testing & Quality Assurance', href: '/services/ai-testing-qa' },
  { name: 'AI Threat Hunting & Investigation', href: '/services/ai-threat-hunting' },
  { name: 'Ai Threat Intelligence', href: '/services/ai-threat-intelligence' },
  { name: 'Ai Trading Signal Engine', href: '/services/ai-trading-signal-engine' },
  { name: 'AI Training Data Platform', href: '/services/ai-training-data-platform' },
  { name: 'AI Translation & Localization', href: '/services/ai-translation-services' },
  { name: 'Ai Tutoring Platform', href: '/services/ai-tutoring-platform' },
  { name: 'AI Video Analytics', href: '/services/ai-video-analytics' },
  { name: 'AI Video Generation & Editing', href: '/services/ai-video-generation' },
  { name: 'AI Video Generator & Editor', href: '/services/ai-video-generator' },
  { name: 'AI Visual Inspection & Quality Control', href: '/services/ai-visual-inspection' },
  { name: 'AI Voice Agent (Phone)', href: '/services/ai-voice-agent' },
  { name: 'Ai Voice Agent Builder', href: '/services/ai-voice-agent-builder' },
  { name: 'AI Voice Agent Platform', href: '/services/ai-voice-agent-platform' },
  { name: 'AI Voice Assistant', href: '/services/ai-voice-assistant' },
  { name: 'Ai Voice Brand Consistency', href: '/services/ai-voice-brand-consistency' },
  { name: 'AI Voice Clone + Text-to-Speech Engine', href: '/services/ai-tts-voice-clone' },
  { name: 'AI Voice Cloning & Synthesis', href: '/services/ai-voice-cloning' },
  { name: 'AI Voice Cloning for Marketing', href: '/services/ai-voice-cloning-marketing' },
  { name: 'Ai Voice Cloning Studio', href: '/services/ai-voice-cloning-studio' },
  { name: 'Ai Voice First Crm', href: '/services/ai-voice-first-crm' },
  { name: 'Ai Vpc Zero Trust', href: '/services/ai-vpc-zero-trust' },
  { name: 'AI-AIOps Anomaly Detection', href: '/services/ai-aiops-anomaly-detection' },
  { name: 'AI-Assisted Code Migration & Refactoring', href: '/services/ai-for-code-migration' },
  { name: 'AI-Driven API Design Assistant', href: '/services/ai-driven-api-design-assistant' },
  { name: 'AI-Driven Customer Segmentation & Persona Engine', href: '/services/ai-driven-customer-segmentation' },
  { name: 'AI-Powered Application Development', href: '/services/ai-gen-app-dev-1' },
  { name: 'AI-Powered Incident Postmortem Generator', href: '/services/ai-powered-incident-postmortem' },
  { name: 'AI-Powered Log Anomaly Detection', href: '/services/ai-powered-log-anomaly-detection' },
  { name: 'AI-Powered Office Automation', href: '/services/ai-office-automation' },
  { name: 'AI-Powered Passwordless Authentication', href: '/services/ai-powered-passwordless-auth' },
  { name: 'AI-Powered PR Drafting & Description', href: '/services/ai-powered-pr-drafting' },
  { name: 'AI-Powered SEO Content Optimizer', href: '/services/ai-powered-seo-optimizer' },
  { name: 'AI-Powered Tech Debt Quantifier', href: '/services/ai-powered-tech-debt-quantifier' },
  { name: 'AI-Powered Test Suite Generator', href: '/services/ai-powered-test-generation' },
  { name: 'AI-Powered UI Generator (Text-to-UI)', href: '/services/ai-powered-ui-generator' },
  { name: 'AIOps: Observability Automation', href: '/services/observability-aiops' },
  { name: 'Analytics Attribution & Marketing Mix Modeling', href: '/services/analytics-attribution-mix' },
  { name: 'API Development & Integration', href: '/services/api-integration' },
  { name: 'API Development & Integration', href: '/services/api-development' },
  { name: 'API Gateway & Management', href: '/services/api-gateway-management' },
  { name: 'API Management & Developer Gateway', href: '/services/api-management-gateway' },
  { name: 'APM Application Performance', href: '/services/apm-application-performance' },
  { name: 'Attack Surface Management (ASM)', href: '/services/attack-surface-management' },
  { name: 'Automated Data Labeling for Computer Vision & NLP', href: '/services/automated-data-labeling' },
  { name: 'Automated Penetration Testing', href: '/services/automated-pen-testing' },
  { name: 'Automated Reporting Engine', href: '/services/ai-automated-reporting' },
  { name: 'Autonomous Code Deployment Agent', href: '/services/ai-autonomous-code-deployment' },
  { name: 'Autonomous Code Review Agent', href: '/services/autonomous-code-review-agent' },
  { name: 'Autonomous Growth Intelligence', href: '/services/autonomous-growth-intelligence' },
  { name: 'Autonomous QA Engineering Platform', href: '/services/ai-autonomous-qa-engineering' },
  { name: 'AWS Serverless Migration', href: '/services/aws-serverless-migration' },
  { name: 'Backup & Disaster Recovery', href: '/services/backup-disaster-recovery' },
  { name: 'Batch ETL Platform', href: '/services/batch-etl-platform' },
  { name: 'Brand Monitoring & Fake Domain Detection', href: '/services/brand-monitoring' },
  { name: 'Business Intelligence', href: '/services/business-intelligence' },
  { name: 'Business Process Analysis (BPA)', href: '/services/bpa-process-analysis' },
  { name: 'Caption & Subtitle Generator', href: '/services/ai-caption-subtitle-generator' },
  { name: 'CDN & Edge Cache', href: '/services/cdn-edge-cache' },
  { name: 'Chaos Engineering & Resilience Testing', href: '/services/chaos-engineering-svc' },
  { name: 'Cloud Security Posture Management (CSPM)', href: '/services/cspm-cloud-posture' },
  { name: 'Competitor Intelligence Engine', href: '/services/ai-competitor-intelligence' },
  { name: 'Compliance Automation', href: '/services/compliance-automation' },
  { name: 'Compliance Automation Engine', href: '/services/compliance-automation-engine' },
  { name: 'Computer Vision Quality Inspection', href: '/services/ai-vision-quality-inspection' },
  { name: 'Computer Vision Quality Inspection', href: '/services/computer-vision-inspection' },
  { name: 'Computer Vision Shelf Monitoring', href: '/services/ai-computer-vision-shelf-monitoring' },
  { name: 'Container & Kubernetes Security', href: '/services/container-security-lifecycle' },
  { name: 'Container Orchestration & Kubernetes Management', href: '/services/kubernetes-management' },
  { name: 'Container Security Runtime', href: '/services/container-security-runtime' },
  { name: 'Content Generation', href: '/services/content-generation' },
  { name: 'Contract Analyzer Pro', href: '/services/ai-contract-analyzer-pro' },
  { name: 'Conversation Intelligence & Call Coach', href: '/services/ai-conversation-intelligence' },
  { name: 'Customer 360 Unified Profile', href: '/services/ai-customer-360' },
  { name: 'Customer Experience', href: '/services/customer-experience' },
  { name: 'Customer Success Predictor', href: '/services/ai-customer-success-predictor' },
  { name: 'Cybersecurity & Penetration Testing', href: '/services/cybersecurity' },
  { name: 'Cybersecurity Audit', href: '/services/cybersecurity-audit' },
  { name: 'Database Migration Service', href: '/services/db-migration-service' },
  { name: 'Database Optimization & Management', href: '/services/database-optimization' },
  { name: 'DevOps & CI/CD Automation', href: '/services/devops-cicd' },
  { name: 'DevOps Consulting & Implementation', href: '/services/devops-consulting' },
  { name: 'DevSecOps Pipeline Automation', href: '/services/devsecops-pipeline' },
  { name: 'Digital Rights Management', href: '/services/digital-rights-management' },
  { name: 'Digital Workplace Solutions', href: '/services/digital-workplace' },
  { name: 'Disaster Recovery & Business Continuity', href: '/services/disaster-recovery-services' },
  { name: 'Disaster Recovery Platform', href: '/services/disaster-recovery-platform' },
  { name: 'Document Processing', href: '/services/document-processing' },
  { name: 'Edge Computing & Edge AI Deployment', href: '/services/edge-computing-deploy' },
  { name: 'Edge Computing Platform', href: '/services/edge-computing-platform' },
  { name: 'Email Campaign Generator', href: '/services/ai-email-campaign-generator' },
  { name: 'Energy Management', href: '/services/energy-management' },
  { name: 'Enterprise AI Question Answering (Internal Knowledge)', href: '/services/ai-powered-question-answering' },
  { name: 'Enterprise Backup & Disaster Recovery', href: '/services/enterprise-backup-dr' },
  { name: 'Enterprise Data Loss Prevention (DLP)', href: '/services/enterprise-dlp' },
  { name: 'Enterprise Network Infrastructure', href: '/services/network-infrastructure' },
  { name: 'ETL Pipeline Optimization & Modernization', href: '/services/etl-pipeline-optimization' },
  { name: 'Event-Driven Architecture (EDA) Platform', href: '/services/event-driven-architecture' },
  { name: 'Event-Driven Orchestration', href: '/services/event-driven-orchestration' },
  { name: 'EVM Smart Contract Audit', href: '/services/evm-smart-contract-audit' },
  { name: 'Feature Engineering Platform', href: '/services/feature-engineering-platform' },
  { name: 'FinOps Cloud Governance', href: '/services/fn-finops-platform' },
  { name: 'Fraud Detection', href: '/services/fraud-detection' },
  { name: 'Full-Stack Observability Platform', href: '/services/observability-platform' },
  { name: 'GCP Data Analytics Platform', href: '/services/gcp-data-analytics-platform' },
  { name: 'Generative AI Document Summarizer', href: '/services/generative-ai-summarization' },
  { name: 'Generative AI Enterprise', href: '/services/generative-ai-enterprise' },
  { name: 'Generative AI for DevOps & CI/CD', href: '/services/devops-gen-ai-ci-cd' },
  { name: 'Generative AI Legal Document Review', href: '/services/generative-ai-legal-review' },
  { name: 'Generative AI Video Editor', href: '/services/generative-ai-video-editor' },
  { name: 'Generative AI Voice Agent', href: '/services/generative-ai-voice-agent' },
  { name: 'Generative Data Synthesis for Model Training', href: '/services/generative-data-synthesis' },
  { name: 'Generative UX Research Synthesis', href: '/services/generative-ux-research-synthesis' },
  { name: 'Graph Database & Analytics', href: '/services/graph-database-analytics' },
  { name: 'HR Analytics', href: '/services/hr-analytics' },
  { name: 'Hybrid Multi-Cloud Networking', href: '/services/hybrid-multi-cloud-net' },
  { name: 'IAM & Identity Platform', href: '/services/iam-identity-platform' },
  { name: 'Identity & Access Management (IAM)', href: '/services/identity-access-management' },
  { name: 'Incident Response Retainer (IR)', href: '/services/incident-response-retainer' },
  { name: 'Intelligent Document Processing v2', href: '/services/doc-intelligence-v2' },
  { name: 'Intelligent Load Balancer', href: '/services/load-balancer-service' },
  { name: 'Knowledge Graph Builder', href: '/services/ai-knowledge-graph-builder' },
  { name: 'Kubernetes GitOps Enterprise Platform', href: '/services/k8s-gitops-enterprise' },
  { name: 'Legacy App Refactoring & Strangler Fig', href: '/services/legacy-app-refactor' },
  { name: 'Legacy System Modernization & Re-Platforming', href: '/services/legacy-system-modernization' },
  { name: 'Log Aggregation & Search', href: '/services/log-aggregation-platform' },
  { name: 'Low-Code Platform Customization & Integration', href: '/services/low-code-platform-customization' },
  { name: 'Low-Code Workflow Builder', href: '/services/low-code-workflow-builder' },
  { name: 'Machine Translation Quality Engine', href: '/services/ai-machine-translation-quality' },
  { name: 'Mainframe Modernization', href: '/services/mainframe-modernization' },
  { name: 'Managed EDR + SIEM SOC Service', href: '/services/managed-edr-siem' },
  { name: 'Managed SOC & Security Operations', href: '/services/managed-soc-security' },
  { name: 'Managed SOC & Threat Intelligence', href: '/services/managed-soc-threat-intelligence' },
  { name: 'Marketing Automation', href: '/services/marketing-automation' },
  { name: 'Marketing Automation Platform', href: '/services/marketing-automation-svc' },
  { name: 'Meeting AI Assistant (Record, Transcribe, Summarize)', href: '/services/meeting-ai-assistant' },
  { name: 'MISP Threat Intelligence Platform', href: '/services/misp-threat-intel' },
  { name: 'MLOps Platform', href: '/services/mlops-platform' },
  { name: 'Mobile App Development', href: '/services/mobile-development' },
  { name: 'Monitoring & Observability', href: '/services/monitoring-observability' },
  { name: 'Network Architecture & SD-WAN', href: '/services/network-architecture-sdwan' },
  { name: 'Network Performance Monitoring', href: '/services/network-performance-monitoring' },
  { name: 'Network Security Operations Center', href: '/services/network-security-operations' },
  { name: 'Node.js Performance Tuning & Profiling', href: '/services/nodejs-performance-tuning' },
  { name: 'Object Detection Surveillance', href: '/services/object-detection-surveillance' },
  { name: 'Observability Data Lakehouse', href: '/services/observability-lakehouse' },
  { name: 'Passwordless Authentication', href: '/services/passwordless-auth' },
  { name: 'Patch Management', href: '/services/patch-management' },
  { name: 'Payment Compliance Gateway', href: '/services/payment-compliance-gateway' },
  { name: 'Penetration Testing & Red Team', href: '/services/pentest-redteam' },
  { name: 'Performance Engineering as a Service', href: '/services/performance-engineering' },
  { name: 'Predictive Churn Risk Scoring', href: '/services/predictive-churn-risk' },
  { name: 'Predictive Lead Scoring Model', href: '/services/predictive-lead-scoring' },
  { name: 'Predictive Maintenance', href: '/services/predictive-maintenance' },
  { name: 'Predictive Maintenance for Manufacturing', href: '/services/ai-predictive-maintenance-factory' },
  { name: 'Predictive Supply Chain Optimizer', href: '/services/ai-predictive-supply-chain-optimizer' },
  { name: 'Privacy Program & Data Governance', href: '/services/privacy-program' },
  { name: 'Privileged Access Management', href: '/services/privileged-access-management' },
  { name: 'Product Analytics & AI Insights', href: '/services/ai-product-analytics-insights' },
  { name: 'Quality Assurance', href: '/services/quality-assurance' },
  { name: 'Quantum-Ready Cryptography & Security Assessment', href: '/services/quantum-ready-security' },
  { name: 'Queue & Messaging Platform', href: '/services/queue-messaging-platform' },
  { name: 'Ransomware Recovery & IR for Insurers', href: '/services/ransomware-recovery' },
  { name: 'Real-Time Fraud Detection', href: '/services/ai-fraud-detection-real-time' },
  { name: 'Real-Time Personalisation Engine', href: '/services/ai-personalisation-engine-realtime' },
  { name: 'Real-Time Streaming Analytics', href: '/services/streaming-realtime-analytics' },
  { name: 'Real-Time Translation Engine', href: '/services/ai-realtime-translation' },
  { name: 'Reinforcement Learning Optimiser', href: '/services/ai-reinforcement-learning-optimiser' },
  { name: 'Reliability Platform & SRE Enablement', href: '/services/reliability-sre' },
  { name: 'Remote IT Support & Helpdesk Outsourcing', href: '/services/remote-it-support' },
  { name: 'Revenue Optimization Engine', href: '/services/ai-revenue-optimizer' },
  { name: 'Rx Prior-Auth Automation', href: '/services/ai-rx-prior-auth' },
  { name: 'Rx Prior-Auth Automation', href: '/services/rx-prior-auth' },
  { name: 'SaaS Product Development', href: '/services/saas-development' },
  { name: 'Secure File Transfer', href: '/services/secure-file-transfer' },
  { name: 'Security Operations Center as a Service (SOCaaS)', href: '/services/soc-as-a-service' },
  { name: 'Self-Service Analytics Platform', href: '/services/self-service-analytics' },
  { name: 'Serverless API Production Platform', href: '/services/serverless-api-platform' },
  { name: 'SIEM Security Platform', href: '/services/siem-security-platform' },
  { name: 'Social Sentiment Tracker', href: '/services/ai-social-sentiment-tracker' },
  { name: 'Software Supply Chain Security', href: '/services/software-supply-chain-sec' },
  { name: 'Sovereign & Regulated Cloud Hosting', href: '/services/sovereign-cloud-hosting' },
  { name: 'Spatial Computing 3D Scene Generator', href: '/services/ai-spatial-computing-3d-scene' },
  { name: 'Streaming ETL Pipeline', href: '/services/etl-streaming-pipeline' },
  { name: 'Streaming Fraud Detection (Real-Time)', href: '/services/ai-predictive-fraud-detection-streaming' },
  { name: 'Supply Chain', href: '/services/supply-chain' },
  { name: 'Supply Chain Management Platform', href: '/services/supply-chain-management-service' },
  { name: 'Supply Chain Visibility', href: '/services/supply-chain-visibility' },
  { name: 'Technical Writing & Developer Documentation', href: '/services/tech-writing-docs' },
  { name: 'Unified Endpoint Management (UEM)', href: '/services/endpoint-management' },
  { name: 'Vector Database', href: '/services/vector-database' },
  { name: 'Virtual Private Cloud', href: '/services/virtual-private-cloud' },
  { name: 'Voice Assistant Pro', href: '/services/ai-voice-assistant-pro' },
  { name: 'Voice-to-Action Platform', href: '/services/ai-voice-to-action-platform' },
  { name: 'Vulnerability Assessment & Penetration Testing', href: '/services/vulnerability-assessment-penetration-testing' },
  { name: 'Workflow Automation & Integration Platform', href: '/services/workflow-automation' },
  { name: 'Zero Trust Access Gateway', href: '/services/zero-trust-access' },
  { name: 'Zero-Trust Network Access (ZTNA)', href: '/services/zero-trust-network-access' },
];



export const IT_SERVICE_LINKS: readonly NavigationLink[] = [
  { name: '5G Network Planning & Deployment', href: '/services/it-5g-network-deployment' },
  { name: 'AI-Powered Observability & SRE', href: '/services/it-observability-1' },
  { name: 'API Management Platform & Developer Portal', href: '/services/it-api-management' },
  { name: 'API Security Testing', href: '/services/it-apisec-testing' },
  { name: 'Automated Incident Response (SOAR)', href: '/services/it-automated-incident-response' },
  { name: 'Backup & Disaster Recovery Platform', href: '/services/it-backup-disaster-recovery' },
  { name: 'Blockchain Development & Smart Contract Auditing', href: '/services/it-blockchain-development' },
  { name: 'Business Continuity & Disaster Recovery', href: '/services/it-business-continuity-dr' },
  { name: 'Business Intelligence Cockpit', href: '/services/it-business-intelligence-cockpit' },
  { name: 'Cloud Cost Management Platform', href: '/services/it-cloud-cost-management-platform' },
  { name: 'Cloud-Native Storage Optimizer', href: '/services/it-cloud-native-storage' },
  { name: 'Container Orchestration & Kubernetes Management', href: '/services/it-kubernetes-management' },
  { name: 'Data Lakehouse Governance', href: '/services/it-data-lakehouse-governance' },
  { name: 'Data Mesh & Modern Data Platform Architecture', href: '/services/it-data-mesh-implementation' },
  { name: 'Data Warehouse Modernization', href: '/services/it-data-warehouse-modernization' },
  { name: 'Database-as-a-Service & Managed Data Platforms', href: '/services/it-database-as-a-service' },
  { name: 'DevOps Platform & Unified Toolchain', href: '/services/it-devops-platform-toolchain' },
  { name: 'DevSecOps & Security Automation', href: '/services/it-devsecops-1' },
  { name: 'Digital Twin & IoT Platform Development', href: '/services/it-digital-twin-platform' },
  { name: 'Digital Workplace Platform', href: '/services/it-digital-workplace-platform' },
  { name: 'Disaster Recovery & Business Continuity', href: '/services/it-disaster-recovery' },
  { name: 'E-Commerce Platform Advisor', href: '/services/it-e-commerce-platform-advisor' },
  { name: 'Edge Computing & IoT Infrastructure', href: '/services/it-edge-computing-solutions' },
  { name: 'Edge Computing Deployment', href: '/services/it-edge-computing-deploy' },
  { name: 'Edge Computing Orchestration', href: '/services/it-edge-computing-orchestration' },
  { name: 'Endpoint Management (macOS & Windows)', href: '/services/it-endpoint-management-macos-windows' },
  { name: 'Enterprise IoT Device Management', href: '/services/it-iot-device-management' },
  { name: 'ESG Compliance Automation', href: '/services/it-esg-compliance-automation' },
  { name: 'Identity & Access Management (IAM) Platform', href: '/services/it-identity-access-management' },
  { name: 'Identity & Access Management (SSO/MFA)', href: '/services/it-identity-access-management-sso' },
  { name: 'Identity Governance & Administration', href: '/services/it-identity-governance' },
  { name: 'Incident Response & Security Operations Center', href: '/services/it-incident-response' },
  { name: 'Internal Developer Platform (IDP) Engineering', href: '/services/it-platform-engineering-1' },
  { name: 'It Api Gateway Ai', href: '/services/it-api-gateway-ai' },
  { name: 'It Api Gateway Management', href: '/services/it-api-gateway-management' },
  { name: 'It Api Gateway Openapi', href: '/services/it-api-gateway-openapi' },
  { name: 'It Api Management Gateway', href: '/services/it-api-management-gateway' },
  { name: 'It Api Performance Testing', href: '/services/it-api-performance-testing' },
  { name: 'IT Asset Lifecycle Manager', href: '/services/it-asset-lifecycle' },
  { name: 'IT Asset Management & Lifecycle', href: '/services/it-asset-management' },
  { name: 'IT Automation & Orchestration Platform', href: '/services/it-automation-orchestrator' },
  { name: 'It Backup Disaster Recovery Solution', href: '/services/it-backup-disaster-recovery-solution' },
  { name: 'It Backup Dr Bc As A Service', href: '/services/it-backup-dr-bc-as-a-service' },
  { name: 'IT Capacity Planning & Resource Forecasting', href: '/services/it-capacity-planning' },
  { name: 'IT Change Risk Analyser', href: '/services/it-change-risk-analyser' },
  { name: 'It Cicd Security Gate As Service', href: '/services/it-cicd-security-gate-as-service' },
  { name: 'IT Cloud Compliance Scanner', href: '/services/it-cloud-compliance-scanner' },
  { name: 'It Cloud Cost Governance', href: '/services/it-cloud-cost-governance' },
  { name: 'It Code Quality Governance', href: '/services/it-code-quality-governance' },
  { name: 'It Code Quality Pre Merge', href: '/services/it-code-quality-pre-merge' },
  { name: 'It Endpoint Security Compliance', href: '/services/it-endpoint-security-compliance' },
  { name: 'It Endpoint Security Compliance Monitor', href: '/services/it-endpoint-security-compliance-monitor' },
  { name: 'IT Help Desk (AI-Powered)', href: '/services/it-help-desk-glucidex' },
  { name: 'It Incident Response Simulator', href: '/services/it-incident-response-simulator' },
  { name: 'It Observability Logging', href: '/services/it-observability-logging' },
  { name: 'IT Service Asset & Configuration Management', href: '/services/it-sam-platform' },
  { name: 'IT Service Catalog Builder', href: '/services/it-service-catalog-builder' },
  { name: 'IT Service Desk & Help Desk', href: '/services/it-service-desk' },
  { name: 'IT Service Desk Automation', href: '/services/it-service-desk-automation' },
  { name: 'IT Strategy & Digital Transformation Consulting', href: '/services/it-consulting' },
  { name: 'It Synthetic Monitoring', href: '/services/it-synthetic-monitoring' },
  { name: 'It Unified Endpoint Management', href: '/services/it-unified-endpoint-management' },
  { name: 'IT Vendor & Contract Management', href: '/services/it-vendor-contract-mgmt' },
  { name: 'IT Vendor Risk & Trust Portal', href: '/services/it-vendor-trust-portal' },
  { name: 'ITIL Service Management (ITSM) Platform', href: '/services/it-itil-service-management' },
  { name: 'Kubernetes Multi-Cloud Management', href: '/services/it-kubernetes-multicloud' },
  { name: 'Legacy App Containerization', href: '/services/it-legacy-app-containerization' },
  { name: 'Low-Code Platform Integration', href: '/services/it-low-code-platform-integration' },
  { name: 'Mainframe Modernization Service', href: '/services/it-mainframe-modernization' },
  { name: 'Managed Endpoint Detection & Response (EDR)', href: '/services/it-endpoint-detection-response' },
  { name: 'Managed SOC + Threat Intelligence as a Service', href: '/services/it-managed-soc' },
  { name: 'Microservices Architecture & API Gateway Design', href: '/services/it-microservices-architecture' },
  { name: 'Multi-Cloud Cost Governance', href: '/services/it-multi-cloud-cost-governance' },
  { name: 'Multi-Cloud Networking', href: '/services/it-multi-cloud-networking' },
  { name: 'Network Automation & SD-WAN Management', href: '/services/it-network-automation' },
  { name: 'Network Security Monitoring & SIEM', href: '/services/it-network-security-monitoring' },
  { name: 'Next-Generation Firewall', href: '/services/it-network-firewall-next-generation' },
  { name: 'Observability Platform & SRE Consulting', href: '/services/it-observability-platform' },
  { name: 'PCI DSS Compliance Suite', href: '/services/it-pcii-compliance-suite' },
  { name: 'Penetration Testing & Vulnerability Assessment', href: '/services/it-penetration-testing' },
  { name: 'Platform Engineering & Internal Developer Portal', href: '/services/it-platform-engineering' },
  { name: 'Quantum Computing Readiness Assessment', href: '/services/it-quantum-readiness' },
  { name: 'Remote Collaboration Suite', href: '/services/it-remote-collaboration-suites' },
  { name: 'SAP Integration Hub', href: '/services/it-sap-integration-hub' },
  { name: 'Secrets Management as a Service', href: '/services/it-secrets-management' },
  { name: 'Secure File Transfer (MFT)', href: '/services/it-secure-file-transfer' },
  { name: 'Serverless API Gateway', href: '/services/it-serverless-api-gateway' },
  { name: 'Serverless Architecture & Function-as-a-Service', href: '/services/it-serverless-architecture' },
  { name: 'Unified Observability Platform', href: '/services/it-observability-unified' },
  { name: 'Voice Infrastructure & Contact Center Solutions', href: '/services/it-voice-infrastructure' },
  { name: 'Wireless Network Design & Optimization', href: '/services/it-wireless-network-design' },
  { name: 'Zero Trust Security Architecture', href: '/services/it-zero-trust-architecture' },
  { name: 'Zero Trust Security Implementation', href: '/services/it-zero-trust-1' },
];



export const CLOUD_SERVICE_LINKS: readonly NavigationLink[] = [
  { name: 'AI Cloud Cost Optimizer', href: '/services/cloud-cost-ai-optimizer' },
  { name: 'AI/MLOps Cloud Platform', href: '/services/cloud-ai-mlops-platform' },
  { name: 'Cloud BOM & Dependency Visualiser', href: '/services/cloud-bom-visualiser' },
  { name: 'Cloud Chaos Engineering Platform', href: '/services/cloud-chaos-engineering-platform' },
  { name: 'Cloud Cost Anomaly Detector', href: '/services/cloud-cost-anomaly-detector' },
  { name: 'Cloud Cost Optimization (FinOps)', href: '/services/cloud-cost-optimization-service' },
  { name: 'Cloud Data Lakehouse Platform', href: '/services/cloud-data-lakehouse-platform' },
  { name: 'Cloud Disaster Recovery Orchestration', href: '/services/cloud-disaster-recovery-orchestration' },
  { name: 'Cloud Edge Ai Deployment Platform', href: '/services/cloud-edge-ai-deployment-platform' },
  { name: 'Cloud Event Driven Microservices', href: '/services/cloud-event-driven-microservices' },
  { name: 'Cloud FinOps & Cost Intelligence', href: '/services/cloud-finops-1' },
  { name: 'Cloud Hybrid Multi Cloud Orchestrator', href: '/services/cloud-hybrid-multi-cloud-orchestrator' },
  { name: 'Cloud Hybrid Multicloud Networking', href: '/services/cloud-hybrid-multicloud-networking' },
  { name: 'Cloud Kubernetes Cost Optimizer', href: '/services/cloud-kubernetes-cost-optimizer' },
  { name: 'Cloud Kubernetes Gitops Platform', href: '/services/cloud-kubernetes-gitops-platform' },
  { name: 'Cloud Migration & Modernization', href: '/services/cloud-migration' },
  { name: 'Cloud Migration Readiness Score', href: '/services/cloud-migration-readiness' },
  { name: 'Cloud Serverless Api Platform', href: '/services/cloud-serverless-api-platform' },
  { name: 'Cloud Spot Instance Optimizer', href: '/services/cloud-spot-instance-optimizer' },
  { name: 'Cloud Storage Lifecycle & Compliance', href: '/services/cloud-storage-lifecycle-policy' },
  { name: 'Cloud Storage Tiering Intelligence', href: '/services/cloud-storage-tiering' },
  { name: 'Cloud-Native Application Development', href: '/services/cloud-native-app-dev' },
  { name: 'Container Registry + Trivy Scan', href: '/services/cloud-container-registry-trivy-scan' },
  { name: 'Enterprise API Gateway', href: '/services/cloud-api-gateway-enterprise' },
  { name: 'GitOps Enterprise Platform', href: '/services/cloud-gitops-enterprise-platform' },
  { name: 'Global Edge Computing Network', href: '/services/cloud-edge-computing-global' },
  { name: 'Intelligent Blob Storage Tiering', href: '/services/cloud-blob-intelligent-tiering' },
  { name: 'Observability Stack as a Service', href: '/services/cloud-observability-stack' },
  { name: 'Serverless Framework Deployment', href: '/services/cloud-serverless-framework-deploy' },
  { name: 'Zero Trust Access Platform', href: '/services/cloud-zero-trust-access-platform' },
];



export const SECURITY_SERVICE_LINKS: readonly NavigationLink[] = [
  { name: 'API Security Gateway', href: '/services/security-api-security-gateway' },
  { name: 'Cloud Threat Detection & Response', href: '/services/security-cloud-threat-detection' },
  { name: 'Compliance & Audit Automation', href: '/services/security-compliance-audit-platform' },
  { name: 'Identity Governance & Administration (IGA)', href: '/services/security-identity-governance-igac' },
  { name: 'Network Segmentation & Zero Trust', href: '/services/security-network-segmentation-zero-trust' },
  { name: 'Privacy Program Automation', href: '/services/security-privacy-program-automation' },
  { name: 'Proactive Remediation (PRM)', href: '/services/security-vulnerability-management-pra' },
  { name: 'Secrets Management & Vault', href: '/services/security-secrets-management-vault' },
  { name: 'Security Ai Threat Hunter', href: '/services/security-ai-threat-hunter' },
  { name: 'Security Awareness Training Platform', href: '/services/security-security-awareness-training' },
  { name: 'Security Breach & Attack Simulation Platform', href: '/services/security-bas-platform' },
  { name: 'Security Browser Isolation', href: '/services/security-browser-isolation' },
  { name: 'Security Browser Isolation Platform', href: '/services/security-browser-isolation-platform' },
  { name: 'Security Cloud Zero Trust Access', href: '/services/security-cloud-zero-trust-access' },
  { name: 'Security Log Orchestration & Correlation', href: '/services/security-log-orchestration' },
  { name: 'Security Privacy Enhancing Technologies', href: '/services/security-privacy-enhancing-technologies' },
  { name: 'Security Privileged Access Management', href: '/services/security-privileged-access-management' },
  { name: 'Security Sbom Supply Chain', href: '/services/security-sbom-supply-chain' },
  { name: 'Security Supply Chain Sbom', href: '/services/security-supply-chain-sbom' },
  { name: 'Security Supply Chain Sbom Manager', href: '/services/security-supply-chain-sbom-manager' },
  { name: 'Security Web Application Firewall', href: '/services/security-web-application-firewall' },
  { name: 'Threat Intelligence Platform', href: '/services/security-threat-intelligence-platform' },
];



export const DATA_SERVICE_LINKS: readonly NavigationLink[] = [
  { name: 'AI Data Warehouse Modernization', href: '/services/data-warehouse-modernization' },
  { name: 'Analytics Engineering Platform', href: '/services/data-analytics-engineering-platform' },
  { name: 'Data Cost Governance & FinOps', href: '/services/data-cost-finops' },
  { name: 'Data Engineering & ETL Pipelines', href: '/services/data-engineering' },
  { name: 'Data Governance & Catalog', href: '/services/data-governance-platform' },
  { name: 'Data Graph Analytics Engine', href: '/services/data-graph-analytics-engine' },
  { name: 'Data Graph Analytics Platform', href: '/services/data-graph-analytics-platform' },
  { name: 'Data Image Video Search', href: '/services/data-image-video-search' },
  { name: 'Data Image Video Search Engine', href: '/services/data-image-video-search-engine' },
  { name: 'Data Lakehouse Platform', href: '/services/data-lakehouse' },
  { name: 'Data Observability & Quality Monitor', href: '/services/data-observability-monitor' },
  { name: 'Data Pipeline Architecture & Engineering', href: '/services/data-pipeline-architecture' },
  { name: 'Data Product Catalog & Lineage', href: '/services/data-product-catalog-svc' },
  { name: 'Data Realtime Time Series Analytics', href: '/services/data-realtime-time-series-analytics' },
  { name: 'Data Realtime Trending Aggregator', href: '/services/data-realtime-trending-aggregator' },
  { name: 'Data Realtime Trending Analytics', href: '/services/data-realtime-trending-analytics' },
  { name: 'Data Reconciliation Engine', href: '/services/data-data-reconciliation-engine' },
  { name: 'Data Science Platform (Managed)', href: '/services/data-science-platform' },
  { name: 'Data Sync & Change Capture', href: '/services/data-sync-engineering' },
  { name: 'Data Synthetic Data Generator', href: '/services/data-synthetic-data-generator' },
  { name: 'Data Unstructured Data Lake', href: '/services/data-unstructured-data-lake' },
  { name: 'Document Intelligence + Vector Search', href: '/services/data-document-vector-search' },
  { name: 'Event Sourcing & CQRS Platform', href: '/services/data-event-sourcing-platform' },
  { name: 'Feature Store Platform', href: '/services/data-feature-store-platform' },
  { name: 'Geospatial Analytics Engine', href: '/services/data-geospatial-analytics-engine' },
  { name: 'Log Analytics & SIP Platform', href: '/services/data-log-analytics-platform' },
  { name: 'PII Scanner & Classifier', href: '/services/data-pii-scanner-classifier' },
  { name: 'Predictive Maintenance (Time-Series)', href: '/services/data-predictive-maintenance-timeseries' },
  { name: 'Real-Time Operational Analytics', href: '/services/data-real-time-operational-analytics' },
];



export const AUTOMATION_SERVICE_LINKS: readonly NavigationLink[] = [
  { name: 'Automation Commercial Leasing Tour Scheduler', href: '/services/automation-commercial-leasing-tour-scheduler' },
  { name: 'Automation Document Intelligence Pipeline', href: '/services/automation-document-intelligence-pipeline' },
  { name: 'Automation Education Student Lifecycle Manager', href: '/services/automation-education-student-lifecycle-manager' },
  { name: 'Automation Integrated Commerce Automation', href: '/services/automation-integrated-commerce-automation' },
  { name: 'Automation Integrated Commerce Flows', href: '/services/automation-integrated-commerce-flows' },
  { name: 'Automation Invoice Purchase Order Processing', href: '/services/automation-invoice-purchase-order-processing' },
  { name: 'Automation Legal Document Preparation', href: '/services/automation-legal-document-preparation' },
  { name: 'Automation Multi Channel Campaign Manager', href: '/services/automation-multi-channel-campaign-manager' },
  { name: 'Automation Multi Channel Campaign Orchestrator', href: '/services/automation-multi-channel-campaign-orchestrator' },
  { name: 'Automation Process Mining Deep Dive', href: '/services/automation-process-mining-deep-dive' },
  { name: 'Automation Process Mining Intelligence', href: '/services/automation-process-mining-intelligence' },
  { name: 'Automation Social Media Content Hub', href: '/services/automation-social-media-content-hub' },
];



// ─── AUTOMATION HUB ROUTES ───────────────────────────────────────────────────
// Top-level automation hub pages (not /services/, direct app routes)
export const AUTOMATION_LINKS: readonly NavigationLink[] = [
  { name: 'Automation',                  href: '/automation' },
  { name: 'Workflow Automation',          href: '/workflow-automation' },
  { name: 'Email Automation',             href: '/services/marketing-automation' },
  { name: 'AI Marketing Automation',      href: '/services/marketing-automation' },
  { name: 'DevOps & CI/CD',               href: '/services/ai-observability-mlops' },
  { name: 'AI Workflow Automator',        href: '/services/ai-agentic-workflows' },
  { name: 'AI Workflow Automator Pro',    href: '/services/ai-agentic-workflows' },
  { name: 'Robotic Process Automation',   href: '/services/low-code-workflow-builder' },
  { name: 'IoT & Digital Twin Platform',  href: '/services/it-digital-twin-platform' },
  { name: 'Process Automation',           href: '/services/low-code-workflow-builder' },
  ...AUTOMATION_SERVICE_LINKS,
];

// ─── GENERIC BRAND / PRODUCT ENTRIES ─────────────────────────────────────────
// Collapsed into FEATURED_PRODUCT_LINKS (productCards section uses that array)
export const PRODUCT_LINKS: readonly NavigationLink[] = [
  ...FEATURED_PRODUCT_LINKS,
];
