#!/usr/bin/env bash
# ------------------------------------------------------------
# Periodic Task Adder – adds a placeholder task every minute
# ------------------------------------------------------------
# This script is intended to run as a GitHub Actions cron job (* * * * *)
# It appends a new numbered task to tasks.md, ensuring a continuous
# stream of work items for OpenClaw to process.
# ------------------------------------------------------------
set -euo pipefail

TASK_FILE="$HOME/.openclaw/workspace/tasks.md"

# Ensure tasks file exists
mkdir -p "$(dirname "$TASK_FILE")"
if [[ ! -f "$TASK_FILE" ]]; then
  echo "# OpenClaw Task Queue" > "$TASK_FILE"
  echo "" >> "$TASK_FILE"
fi

# Determine next task number based on existing tasks
NEXT=$(grep -c "^- \[ \]" "$TASK_FILE" || echo 0)
NEXT=$((NEXT + 1))

# Create a simple placeholder task – you can replace this with real logic
NEW_TASK="- [ ] periodic-task-${NEXT} – autogenerated at $(date -u '+%Y-%m-%dT%H:%M:%SZ')"

echo "$NEW_TASK" >> "$TASK_FILE"

echo "✅ Added task: $NEW_TASK"
