const fs = require('fs');
const services = JSON.parse(fs.readFileSync('app/data/servicesData.json', 'utf8'));
const newServices = [
  // ===== AI EMAIL INTELLIGENCE V204-V208 COMPANION SERVICES =====
  {id:'ai-email-priority-escalation-v204',title:'AI Email Priority Escalation Engine (V204)',description:'Detect when email threads need urgent escalation using sentiment decay tracking, response delay analysis, executive mention detection, and deadline proximity scoring. Automatically routes to the right people at the right time.',icon:'🚨',features:['Sentiment decay tracking across threads','Response delay risk scoring','Executive & stakeholder mention detection','Deadline proximity analysis','Legal/compliance keyword detection','5-level escalation (Normal→Critical)','Auto-notify escalation chain','Reply-all enforcement guaranteed'],benefits:['Never miss a critical escalation again','Respond to urgent issues in minutes','Protect executive relationships','Avoid legal and compliance risks'],pricing:{basic:'399',pro:'899',enterprise:'2299'},contactInfo:{website:'/services/ai-email-priority-escalation-v204',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-email-priority-escalation-v204',category:'ai',popular:true,industry:'Enterprise Communication'},

  {id:'ai-email-knowledge-extraction-v205',title:'AI Email Knowledge Extraction Engine (V205)',description:'Automatically extract decisions, action items, deadlines, commitments, and metrics from every email thread into a searchable knowledge base with full audit trail.',icon:'🧠',features:['Decision extraction with context','Action item detection & assignment','Deadline & commitment tracking','Metric and number extraction','Searchable knowledge base','Full audit trail per thread','Stakeholder mapping per fact','Reply-all enforcement for knowledge sharing'],benefits:['Build organizational knowledge automatically','Never lose a decision or commitment','Search any email fact instantly','Track who promised what and when'],pricing:{basic:'349',pro:'799',enterprise:'1999'},contactInfo:{website:'/services/ai-email-knowledge-extraction-v205',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-email-knowledge-extraction-v205',category:'ai',popular:true,industry:'Knowledge Management'},

  {id:'ai-stakeholder-relationship-mapper-v206',title:'AI Stakeholder Relationship Mapper (V206)',description:'Map organizational relationships from email patterns. Identify decision-makers, influencers, gatekeepers, and champions with influence scoring and communication cluster detection.',icon:'🕸️',features:['Organizational relationship mapping','Influence scoring per stakeholder','Decision-maker identification','Gatekeeper and champion detection','Communication cluster analysis','Strategic engagement recommendations','Role detection (8 categories)','Relationship strength scoring'],benefits:['Understand org dynamics instantly','Target the right decision-makers','Leverage internal champions','Avoid relationship risks'],pricing:{basic:'449',pro:'999',enterprise:'2499'},contactInfo:{website:'/services/ai-stakeholder-relationship-mapper-v206',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-stakeholder-relationship-mapper-v206',category:'ai',popular:true,industry:'Sales Intelligence'},

  {id:'ai-email-response-quality-grader-v207',title:'AI Email Response Quality Grader (V207)',description:'Grade every draft email before sending on clarity, tone, completeness, actionability, and professionalism. Get real-time improvement suggestions and rewrite recommendations.',icon:'⭐',features:['Clarity analysis (readability scoring)','Tone appropriateness evaluation','Completeness checking vs original points','Actionability scoring','Professionalism grading','A+ to F letter grading','Rewrite suggestions','Reply-all enforcement check'],benefits:['Send higher quality emails every time','Catch tone issues before sending','Ensure all points are addressed','Improve team communication skills'],pricing:{basic:'199',pro:'449',enterprise:'999'},contactInfo:{website:'/services/ai-email-response-quality-grader-v207',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-email-response-quality-grader-v207',category:'ai',popular:true,industry:'Communication Quality'},

  {id:'ai-email-workflow-automation-v208',title:'AI Email Workflow Automation Engine (V208)',description:'Detect repetitive email patterns and automatically create workflow rules, smart templates, auto-responses, and routing logic. Learns from history to optimize continuously.',icon:'⚙️',features:['Pattern detection (8 categories)','Auto-rule generation','Smart template creation','Intelligent email routing','Auto-response workflows','Follow-up tracking','Complaint escalation rules','Learning from email history'],benefits:['Automate 80% of repetitive email tasks','Respond to common inquiries instantly','Route emails to the right team automatically','Continuously improve from patterns'],pricing:{basic:'449',pro:'999',enterprise:'2499'},contactInfo:{website:'/services/ai-email-workflow-automation-v208',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-email-workflow-automation-v208',category:'ai',popular:true,industry:'Workflow Automation'},

  // ===== AI SERVICES =====
  {id:'ai-contract-analysis-risk-detection',title:'AI Contract Analysis & Risk Detection',description:'Analyze contracts, NDAs, MSAs, and SOWs in seconds. Detect risky clauses, missing protections, unusual terms, and benchmark against industry standards with AI-powered legal intelligence.',icon:'📜',features:['Clause-by-clause risk scoring','Missing protection detection','Industry benchmark comparison','Redline suggestion generation','Obligation tracking & alerts','Renewal date extraction','Liability cap analysis','Multi-jurisdiction compliance check'],benefits:['Review contracts 50x faster','Catch risky clauses automatically','Never miss a renewal date','Benchmark against industry standards'],pricing:{basic:'599',pro:'1299',enterprise:'3499'},contactInfo:{website:'/services/ai-contract-analysis-risk-detection',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-contract-analysis-risk-detection',category:'ai',popular:true,industry:'Legal Tech'},

  {id:'ai-meeting-minutes-action-tracker',title:'AI Meeting Minutes & Action Item Tracker',description:'Automatically generate meeting minutes from audio/video calls. Extract action items with owners and deadlines, track completion, and send follow-up reminders. Integrates with Zoom, Teams, Meet.',icon:'📝',features:['Auto-transcription (95%+ accuracy)','Speaker identification','Action item extraction with owners','Deadline detection and reminders','Decision logging','Follow-up email generation','Integration with Zoom/Teams/Meet','Search across all meeting history'],benefits:['Never take meeting notes again','Track every action item to completion','Search any past meeting instantly','Send perfect follow-ups automatically'],pricing:{basic:'149',pro:'349',enterprise:'799'},contactInfo:{website:'/services/ai-meeting-minutes-action-tracker',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-meeting-minutes-action-tracker',category:'ai',popular:true,industry:'Productivity'},

  {id:'ai-customer-churn-prediction',title:'AI Customer Churn Prediction Engine',description:'Predict which customers will churn 90 days in advance using behavioral signals, usage patterns, support ticket analysis, and engagement scoring. Trigger automated retention campaigns.',icon:'🔮',features:['90-day churn prediction','Behavioral signal analysis','Usage pattern monitoring','Support ticket sentiment tracking','Engagement scoring per account','Automated retention campaign triggers','Revenue-at-risk dashboards','Win-back opportunity identification'],benefits:['Predict churn 90 days in advance','Save 30% more at-risk accounts','Automate retention campaigns','Quantify revenue at risk'],pricing:{basic:'499',pro:'1099',enterprise:'2999'},contactInfo:{website:'/services/ai-customer-churn-prediction',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-customer-churn-prediction',category:'ai',popular:true,industry:'Customer Success'},

  {id:'ai-document-summarization-qa',title:'AI Document Summarization & Q&A Platform',description:'Upload any document (PDF, DOCX, PPTX) and get instant summaries, ask questions in natural language, extract key data points, and compare multiple documents side by side.',icon:'📖',features:['Instant document summarization','Natural language Q&A','Key data point extraction','Multi-document comparison','Cross-document search','Fact verification','Table and chart extraction','Citation and source tracking'],benefits:['Summarize 100-page docs in seconds','Ask questions about any document','Compare documents side by side','Extract data without manual reading'],pricing:{basic:'199',pro:'449',enterprise:'1099'},contactInfo:{website:'/services/ai-document-summarization-qa',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-document-summarization-qa',category:'ai',popular:true,industry:'Document Intelligence'},

  {id:'ai-competitive-intelligence-platform',title:'AI Competitive Intelligence Platform',description:'Monitor competitors across web, social, news, job postings, and patents. Get automated alerts on pricing changes, product launches, funding rounds, and key personnel moves.',icon:'🎯',features:['Multi-source competitor monitoring','Pricing change detection','Product launch tracking','Job posting analysis for strategy signals','Funding round monitoring','Patent filing tracking','Key personnel move alerts','Automated competitive briefs'],benefits:['Know competitor moves before market does','Automate competitive research','Get alerts on critical changes','Generate competitive briefs instantly'],pricing:{basic:'399',pro:'899',enterprise:'2299'},contactInfo:{website:'/services/ai-competitive-intelligence-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-competitive-intelligence-platform',category:'ai',popular:true,industry:'Business Intelligence'},

  // ===== MICRO SAAS SERVICES =====
  {id:'micro-saas-invoice-automation',title:'Invoice Automation & Payment Tracking',description:'Automate invoice creation, delivery, reminders, and payment tracking. Support recurring billing, multi-currency, tax calculation, and real-time payment status with Stripe/PayPal integration.',icon:'💰',features:['Auto invoice generation & delivery','Smart payment reminders (escalating)','Recurring billing management','Multi-currency support (135+)','Tax calculation per jurisdiction','Stripe/PayPal/ACH integration','Payment status real-time tracking','Revenue recognition automation'],benefits:['Get paid 2x faster','Eliminate manual invoicing','Reduce late payments by 60%','Support global customers easily'],pricing:{basic:'49',pro:'149',enterprise:'399'},contactInfo:{website:'/services/micro-saas-invoice-automation',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-invoice-automation',category:'micro-saas',popular:true,industry:'Finance & Accounting'},

  {id:'micro-saas-employee-onboarding',title:'Employee Onboarding Workflow Platform',description:'Streamline new hire onboarding with automated workflows, document collection, task assignments, training schedules, and compliance tracking. Reduce time-to-productivity by 40%.',icon:'👋',features:['Automated onboarding workflows','Document collection & e-signatures','Task assignment & tracking','Training schedule generation','Compliance training tracking','Equipment provisioning workflow','Buddy/mentor assignment','30-60-90 day check-in automation'],benefits:['Onboard 3x faster','Ensure 100% compliance','Reduce HR manual work by 80%','Track every onboarding milestone'],pricing:{basic:'99',pro:'249',enterprise:'599'},contactInfo:{website:'/services/micro-saas-employee-onboarding',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-employee-onboarding',category:'micro-saas',popular:true,industry:'Human Resources'},

  {id:'micro-saas-vendor-management',title:'Vendor Management & Procurement Platform',description:'Manage vendors, contracts, and procurement in one platform. Track vendor performance, automate renewals, manage budgets, and ensure compliance with procurement policies.',icon:'🤝',features:['Vendor database & performance tracking','Contract management with auto-renewals','Procurement workflow automation','Budget tracking per vendor','Vendor risk assessment','Compliance policy enforcement','Spend analytics dashboards','RFQ/RFP management'],benefits:['Reduce vendor costs by 15%','Never miss a contract renewal','Automate procurement workflows','Track vendor performance objectively'],pricing:{basic:'149',pro:'349',enterprise:'799'},contactInfo:{website:'/services/micro-saas-vendor-management',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-vendor-management',category:'micro-saas',popular:true,industry:'Procurement'},

  {id:'micro-saas-customer-portal',title:'Customer Portal & Self-Service Hub',description:'Give customers a branded self-service portal for support tickets, knowledge base, invoices, usage analytics, and account management. Reduce support volume by 40%.',icon:'🏠',features:['Branded customer portal','Self-service ticket management','Knowledge base with AI search','Invoice and payment management','Usage analytics dashboard','Account & subscription management','Custom branding & white-labeling','SSO integration (SAML/OAuth)'],benefits:['Reduce support tickets by 40%','Give customers 24/7 self-service','Increase customer satisfaction','Centralize all customer interactions'],pricing:{basic:'199',pro:'449',enterprise:'999'},contactInfo:{website:'/services/micro-saas-customer-portal',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-customer-portal',category:'micro-saas',popular:true,industry:'Customer Success'},

  {id:'micro-saas-feature-flag-management',title:'Feature Flag Management Platform',description:'Deploy features safely with feature flags, A/B testing, gradual rollouts, and instant kill switches. Target by user segment, geography, or percentage with real-time analytics.',icon:'🚩',features:['Feature flag creation & management','Gradual rollout (percentage-based)','User segment targeting','A/B testing with statistical significance','Instant kill switches','Real-time flag analytics','Multi-environment support','Audit trail for all changes'],benefits:['Deploy features without risk','A/B test every feature','Roll out gradually to users','Kill any feature instantly if issues'],pricing:{basic:'79',pro:'199',enterprise:'499'},contactInfo:{website:'/services/micro-saas-feature-flag-management',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-feature-flag-management',category:'micro-saas',popular:true,industry:'Software Development'},

  {id:'micro-saas-feedback-feature-board',title:'User Feedback & Feature Request Board',description:'Collect, organize, and prioritize user feedback and feature requests. Let users vote, comment, and track status. Integrate with product roadmap and development tools.',icon:'💬',features:['Public feedback board','User voting & commenting','Status tracking (planned/in-progress/done)','Internal prioritization tools','Roadmap integration','User segmentation of feedback','Jira/Linear/GitHub integration','Automated status update emails'],benefits:['Build what users actually want','Prioritize features by demand','Keep users informed on progress','Connect feedback to roadmap'],pricing:{basic:'49',pro:'129',enterprise:'299'},contactInfo:{website:'/services/micro-saas-feedback-feature-board',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-feedback-feature-board',category:'micro-saas',popular:true,industry:'Product Management'},

  {id:'micro-saas-subscription-dunning',title:'Subscription Management & Dunning Platform',description:'Manage subscriptions, automate billing, reduce churn with smart dunning campaigns, and optimize revenue with upgrade/downgrade analytics and retention offers.',icon:'🔄',features:['Subscription lifecycle management','Automated billing & invoicing','Smart dunning campaigns (5 stages)','Upgrade/downgrade analytics','Revenue optimization suggestions','Retention offer automation','Proration handling','MRR/ARR/churn dashboards'],benefits:['Reduce involuntary churn by 35%','Automate complex billing logic','Optimize revenue per customer','Track all subscription metrics'],pricing:{basic:'99',pro:'249',enterprise:'599'},contactInfo:{website:'/services/micro-saas-subscription-dunning',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-subscription-dunning',category:'micro-saas',popular:true,industry:'Revenue Operations'},

  {id:'micro-saas-api-analytics-ratelimiting',title:'API Usage Analytics & Rate Limiting',description:'Monitor API usage in real-time, enforce rate limits per customer, detect abuse patterns, and generate usage-based billing. Full analytics dashboard with alerting.',icon:'📡',features:['Real-time API usage monitoring','Configurable rate limiting','Abuse pattern detection','Usage-based billing generation','Per-customer analytics','Latency and error tracking','API health dashboards','Webhook alerts for anomalies'],benefits:['Prevent API abuse automatically','Bill customers based on usage','Monitor API health in real-time','Detect anomalies before they escalate'],pricing:{basic:'149',pro:'349',enterprise:'799'},contactInfo:{website:'/services/micro-saas-api-analytics-ratelimiting',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-api-analytics-ratelimiting',category:'micro-saas',popular:true,industry:'API Management'},

  {id:'micro-saas-visual-testing',title:'Automated Visual Testing & Screenshot Platform',description:'Automate visual regression testing across browsers, devices, and screen sizes. Detect UI changes, generate pixel-perfect diffs, and integrate with CI/CD pipelines.',icon:'📸',features:['Visual regression testing','Cross-browser screenshots (Chrome/Firefox/Safari)','Mobile device testing (iOS/Android)','Pixel-perfect diff generation','CI/CD pipeline integration','Baseline management','Flaky test detection','Accessibility visual audit'],benefits:['Catch UI bugs before production','Test across 50+ browser/device combos','Automate visual regression','Integrate with any CI/CD pipeline'],pricing:{basic:'99',pro:'249',enterprise:'599'},contactInfo:{website:'/services/micro-saas-visual-testing',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-visual-testing',category:'micro-saas',popular:true,industry:'Quality Assurance'},

  {id:'micro-saas-status-page-incident',title:'Status Page & Incident Management',description:'Public and internal status pages with automated incident detection, real-time updates, subscriber notifications, and post-incident analysis. Build customer trust through transparency.',icon:'🟢',features:['Public & internal status pages','Automated incident detection','Real-time status updates','Subscriber notifications (email/SMS/Slack)','Post-incident analysis reports','Uptime SLA tracking','Component-level status','Custom branding & domains'],benefits:['Build customer trust with transparency','Reduce support tickets during incidents','Automate incident communication','Track uptime SLAs automatically'],pricing:{basic:'49',pro:'149',enterprise:'349'},contactInfo:{website:'/services/micro-saas-status-page-incident',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-status-page-incident',category:'micro-saas',popular:true,industry:'Reliability Engineering'},

  // ===== IT SERVICES =====
  {id:'it-zero-trust-network-access',title:'Zero Trust Network Access (ZTNA) Platform',description:'Implement zero-trust security with identity-based access, micro-segmentation, continuous verification, and least-privilege enforcement. Replace VPNs with modern secure access.',icon:'🔐',features:['Identity-based access control','Micro-segmentation','Continuous verification','Least-privilege enforcement','Device trust scoring','VPN replacement','Application-level access','Real-time threat blocking'],benefits:['Replace legacy VPNs with ZTNA','Reduce attack surface by 80%','Verify every access request','Enforce least-privilege automatically'],pricing:{basic:'599',pro:'1299',enterprise:'3499'},contactInfo:{website:'/services/it-zero-trust-network-access',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/it-zero-trust-network-access',category:'it',popular:true,industry:'Network Security'},

  {id:'it-cloud-cost-optimization-finops',title:'Cloud Cost Optimization & FinOps Platform',description:'Optimize cloud spending across AWS, Azure, and GCP with right-sizing recommendations, reserved instance management, waste detection, and FinOps governance.',icon:'💸',features:['Multi-cloud cost analysis (AWS/Azure/GCP)','Right-sizing recommendations','Reserved instance optimization','Waste detection (idle resources)','Budget alerts and forecasting','FinOps governance workflows','Cost allocation by team/project','Automated savings plans'],benefits:['Reduce cloud costs by 30-40%','Eliminate wasted resources','Forecast cloud spending accurately','Implement FinOps culture'],pricing:{basic:'299',pro:'699',enterprise:'1799'},contactInfo:{website:'/services/it-cloud-cost-optimization-finops',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/it-cloud-cost-optimization-finops',category:'it',popular:true,industry:'Cloud FinOps'},

  {id:'it-incident-response-management',title:'Incident Response & Management Platform',description:'Streamline incident response with automated detection, on-call management, war room coordination, timeline tracking, and post-incident reviews. Reduce MTTR by 60%.',icon:'🚒',features:['Automated incident detection','On-call rotation management','War room coordination','Incident timeline tracking','Post-incident review automation','Status page integration','Runbook automation','MTTR/MTTD analytics'],benefits:['Reduce MTTR by 60%','Automate on-call management','Coordinate incidents efficiently','Learn from every incident'],pricing:{basic:'249',pro:'599',enterprise:'1399'},contactInfo:{website:'/services/it-incident-response-management',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/it-incident-response-management',category:'it',popular:true,industry:'IT Operations'},

  {id:'it-iac-security-scanner',title:'Infrastructure as Code (IaC) Security Scanner',description:'Scan Terraform, CloudFormation, Kubernetes YAML, and Helm charts for security misconfigurations, compliance violations, and drift detection before deployment.',icon:'🔍',features:['Terraform security scanning','CloudFormation analysis','Kubernetes YAML validation','Helm chart security checks','Compliance benchmarking (CIS/NIST)','Drift detection','Policy-as-code (OPA/Rego)','CI/CD pipeline integration'],benefits:['Catch IaC misconfigurations early','Enforce security policies in code','Prevent compliance violations','Detect infrastructure drift'],pricing:{basic:'199',pro:'449',enterprise:'1099'},contactInfo:{website:'/services/it-iac-security-scanner',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/it-iac-security-scanner',category:'it',popular:true,industry:'DevSecOps'},

  // ===== SECURITY SERVICES =====
  {id:'security-ai-penetration-testing',title:'AI-Powered Penetration Testing Platform',description:'Automated penetration testing using AI to discover vulnerabilities, exploit chains, and attack paths. Continuous testing with detailed remediation guidance and compliance reporting.',icon:'🎯',features:['AI-driven vulnerability discovery','Attack path mapping','Exploit chain analysis','Web/API/network testing','Continuous pentesting','Remediation guidance','Compliance reporting (PCI/SOC2)','Executive summary generation'],benefits:['Continuous pentesting without manual effort','Discover attack paths humans miss','Get detailed remediation steps','Meet compliance requirements'],pricing:{basic:'999',pro:'2499',enterprise:'5999'},contactInfo:{website:'/services/security-ai-penetration-testing',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/security-ai-penetration-testing',category:'security',popular:true,industry:'Cybersecurity'},

  {id:'security-data-loss-prevention',title:'Data Loss Prevention (DLP) Intelligence',description:'AI-powered DLP that monitors data movement across email, cloud, endpoints, and network. Detect sensitive data exfiltration, enforce policies, and prevent data breaches in real-time.',icon:'🛡️',features:['Multi-channel DLP (email/cloud/endpoint/network)','AI sensitive data classification','Real-time exfiltration detection','Policy enforcement engine','Incident investigation tools','User behavior analytics','Compliance reporting (GDPR/HIPAA)','Automated remediation actions'],benefits:['Prevent data breaches in real-time','Classify sensitive data automatically','Enforce DLP policies everywhere','Investigate incidents quickly'],pricing:{basic:'599',pro:'1299',enterprise:'3499'},contactInfo:{website:'/services/security-data-loss-prevention',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/security-data-loss-prevention',category:'security',popular:true,industry:'Data Security'},

  {id:'security-identity-governance',title:'Identity Governance & Administration Platform',description:'Manage user identities, access reviews, role-based access control, and compliance reporting. Automate joiner/mover/leaver processes and enforce least-privilege across all systems.',icon:'👤',features:['User lifecycle management (JML)','Access review campaigns','Role-based access control (RBAC)','Segregation of duties (SoD)','Privileged access management','Compliance reporting (SOX/SOC2)','Automated provisioning/deprovisioning','Access certification workflows'],benefits:['Automate identity lifecycle management','Pass access review audits easily','Enforce least-privilege everywhere','Reduce insider threat risk'],pricing:{basic:'499',pro:'1099',enterprise:'2999'},contactInfo:{website:'/services/security-identity-governance',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/security-identity-governance',category:'security',popular:true,industry:'Identity & Access'},

  // ===== DATA SERVICES =====
  {id:'data-real-time-streaming-platform',title:'Real-Time Data Streaming Platform',description:'Process millions of events per second with managed Apache Kafka, Flink, and Spark Streaming. Real-time analytics, event-driven architectures, and data pipeline management.',icon:'🌊',features:['Managed Kafka clusters','Apache Flink stream processing','Real-time analytics dashboards','Event-driven architecture support','Data pipeline management','Schema registry','Exactly-once processing','Auto-scaling based on throughput'],benefits:['Process millions of events per second','Build event-driven architectures','Get real-time analytics','Scale automatically with demand'],pricing:{basic:'499',pro:'1099',enterprise:'2999'},contactInfo:{website:'/services/data-real-time-streaming-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/data-real-time-streaming-platform',category:'data',popular:true,industry:'Data Engineering'},

  {id:'data-governance-catalog-platform',title:'Data Governance & Catalog Platform',description:'Discover, catalog, and govern all enterprise data assets. Automated data lineage, business glossary, access policies, quality rules, and compliance tracking with AI-powered classification.',icon:'📚',features:['Automated data discovery & cataloging','Data lineage visualization','Business glossary management','Access policy enforcement','Data quality rule engine','AI-powered data classification','Compliance tracking (GDPR/CCPA)','Data marketplace for self-service'],benefits:['Discover all data assets automatically','Track data lineage end-to-end','Enforce governance policies','Enable self-service data access'],pricing:{basic:'399',pro:'899',enterprise:'2299'},contactInfo:{website:'/services/data-governance-catalog-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/data-governance-catalog-platform',category:'data',popular:true,industry:'Data Governance'},

  // ===== MEGA SUITE =====
  {id:'ai-email-ultra-suite-v204-v208',title:'AI Email Ultra Suite (V204-V208)',description:'All 5 new email intelligence engines unified: Priority Escalation, Knowledge Extraction, Stakeholder Mapping, Response Quality Grading, and Workflow Automation. Case-by-case analysis with reply-all guarantee.',icon:'👑',features:['V204: Priority Escalation Engine','V205: Knowledge Extraction Engine','V206: Stakeholder Relationship Mapper','V207: Response Quality Grader','V208: Workflow Automation Engine','Case-by-case analysis for every email','100% reply-all enforcement guaranteed','Enterprise-grade security & compliance'],benefits:['Complete email intelligence in one platform','Every email analyzed and optimized','Automate repetitive email workflows','The most advanced email AI available'],pricing:{basic:'1499',pro:'3499',enterprise:'8999'},contactInfo:{website:'/services/ai-email-ultra-suite-v204-v208',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-email-ultra-suite-v204-v208',category:'ai',popular:true,industry:'Enterprise AI'},
];

const existing = new Set(services.map(s => s.id));
const toAdd = newServices.filter(s => !existing.has(s.id));
services.push(...toAdd);
fs.writeFileSync('app/data/servicesData.json', JSON.stringify(services, null, 2));
console.log('Added', toAdd.length, 'new services. Total:', services.length);
