const fs = require('fs');
const path = require('path');
const dataPath = path.join(__dirname, '..', 'app', 'data', 'servicesData.json');
const services = JSON.parse(fs.readFileSync(dataPath, 'utf8'));
const contactInfo = { phone: '+1 302 464 0950', email: 'kleber@ziontechgroup.com', address: '364 E Main St STE 1008, Middletown DE 19709' };

const newServices = [
  // V1076: Sentiment Evolution (5)
  { id: 'sentiment-evolution-tracker', name: "Sentiment Evolution Tracker", category: "AI Services", description: "Track sentiment changes across email threads over time. Detect deteriorating relationships early and predict churn risk before it happens.", price: "$599/month", features: ["Real-time sentiment tracking", "Trend analysis", "Churn risk prediction", "Relationship health scoring", "Early warning alerts"], icon: '📈', link: '/services/sentiment-evolution-tracker', contactInfo },
  { id: 'customer-churn-predictor', name: "Customer Churn Predictor", category: "AI Services", description: "Predict customer churn using AI-powered sentiment analysis. Identify at-risk accounts early and take proactive retention actions.", price: "$699/month", features: ["Churn risk scoring", "Sentiment trend alerts", "Retention recommendations", "Customer health dashboard", "Predictive analytics"], icon: '🔮', link: '/services/customer-churn-predictor', contactInfo },
  { id: 'relationship-health-monitor', name: "Relationship Health Monitor", category: "AI Services", description: "Monitor the health of business relationships through email sentiment analysis. Track engagement levels and identify opportunities.", price: "$549/month", features: ["Relationship scoring", "Engagement tracking", "Sentiment evolution", "Health trend reports", "Improvement suggestions"], icon: '💚', link: '/services/relationship-health-monitor', contactInfo },
  { id: 'sentiment-trend-analytics', name: "Sentiment Trend Analytics", category: "Analytics Services", description: "Comprehensive analytics on sentiment trends across all communications. Visualize emotional trajectories and patterns.", price: "$479/month", features: ["Trend visualization", "Multi-thread analysis", "Sentiment heatmaps", "Comparative analysis", "Custom dashboards"], icon: '📊', link: '/services/sentiment-trend-analytics', contactInfo },
  { id: 'early-warning-system', name: "Customer Early Warning System", category: "AI Services", description: "Get early warnings about deteriorating customer relationships. AI detects negative sentiment shifts and triggers interventions.", price: "$649/month", features: ["Real-time alerts", "Sentiment shift detection", "Automated escalation", "Intervention workflows", "Risk scoring"], icon: '⚠️', link: '/services/early-warning-system', contactInfo },

  // V1077: Response Quality (5)
  { id: 'response-quality-scorer', name: "Response Quality Scorer", category: "AI Services", description: "AI-powered scoring of email response quality. Evaluate clarity, tone, completeness, professionalism, and actionability.", price: "$449/month", features: ["Multi-dimensional scoring", "Real-time feedback", "Improvement suggestions", "Quality benchmarks", "Strengths identification"], icon: '🎯', link: '/services/response-quality-scorer', contactInfo },
  { id: 'email-clarity-optimizer', name: "Email Clarity Optimizer", category: "AI Services", description: "Optimize email clarity with AI-powered analysis. Improve sentence structure, reduce complexity, and ensure understanding.", price: "$349/month", features: ["Sentence analysis", "Complexity reduction", "Readability scoring", "Structure suggestions", "Plain language conversion"], icon: '📝', link: '/services/email-clarity-optimizer', contactInfo },
  { id: 'professional-tone-advisor', name: "Professional Tone Advisor", category: "AI Services", description: "Get real-time advice on email tone and professionalism. Ensure communications strike the right balance.", price: "$399/month", features: ["Tone analysis", "Professionalism scoring", "Empathy detection", "Formality adjustment", "Context-aware advice"], icon: '👔', link: '/services/professional-tone-advisor', contactInfo },
  { id: 'email-completeness-checker', name: "Email Completeness Checker", category: "AI Services", description: "Ensure your emails are complete and comprehensive. AI checks for missing elements and incomplete information.", price: "$299/month", features: ["Completeness scoring", "Question detection", "Element checking", "Gap identification", "Follow-up suggestions"], icon: '✅', link: '/services/email-completeness-checker', contactInfo },
  { id: 'actionability-enhancer', name: "Email Actionability Enhancer", category: "AI Services", description: "Make your emails more actionable with AI-powered suggestions. Add clear next steps, deadlines, and commitments.", price: "$379/month", features: ["Action item detection", "Next step suggestions", "Deadline extraction", "Commitment tracking", "Results-oriented tips"], icon: '🚀', link: '/services/actionability-enhancer', contactInfo },

  // V1078: Smart Threading (5)
  { id: 'smart-email-threading', name: "Smart Email Threading", category: "AI Services", description: "Intelligently group related emails across multiple threads. Build complete context from fragmented discussions.", price: "$529/month", features: ["Cross-thread grouping", "Context building", "Entity extraction", "Decision tracking", "Related conversation finder"], icon: '🧵', link: '/services/smart-email-threading', contactInfo },
  { id: 'conversation-context-builder', name: "Conversation Context Builder", category: "AI Services", description: "Build comprehensive context from email conversations. AI extracts key entities, decisions, and action items.", price: "$499/month", features: ["Context aggregation", "Entity indexing", "Decision logging", "Action item tracking", "Participant analysis"], icon: '🔍', link: '/services/conversation-context-builder', contactInfo },
  { id: 'email-decision-tracker', name: "Email Decision Tracker", category: "AI Services", description: "Track decisions made in email conversations. Never lose track of what was agreed upon, by whom, and when.", price: "$449/month", features: ["Decision extraction", "Commitment tracking", "Timeline visualization", "Decision history", "Accountability mapping"], icon: '📋', link: '/services/email-decision-tracker', contactInfo },
  { id: 'thread-summarizer-pro', name: "Thread Summarizer Pro", category: "AI Services", description: "Get AI-powered summaries of long email threads. Quickly understand key points without reading every message.", price: "$399/month", features: ["AI summarization", "Key point extraction", "Decision highlights", "Action item listing", "Thread timeline"], icon: '📄', link: '/services/thread-summarizer-pro', contactInfo },
  { id: 'related-conversation-finder', name: "Related Conversation Finder", category: "AI Services", description: "Find related conversations across your email history. AI identifies relevant past discussions.", price: "$349/month", features: ["Semantic search", "Entity-based matching", "Relevance scoring", "Cross-thread discovery", "Smart recommendations"], icon: '🔗', link: '/services/related-conversation-finder', contactInfo },

  // V1079: Productivity Analytics (5)
  { id: 'email-productivity-dashboard', name: "Email Productivity Dashboard", category: "Analytics Services", description: "Comprehensive analytics on email productivity. Track time spent, response patterns, and identify bottlenecks.", price: "$479/month", features: ["Productivity metrics", "Response time tracking", "Inbox health scoring", "Bottleneck identification", "Actionable insights"], icon: '📊', link: '/services/email-productivity-dashboard', contactInfo },
  { id: 'inbox-zero-tracker', name: "Inbox Zero Tracker", category: "Productivity Services", description: "Track your progress toward inbox zero. Get insights on email volume, processing speed, and strategies.", price: "$299/month", features: ["Inbox zero progress", "Email volume tracking", "Processing speed metrics", "Daily goals", "Productivity tips"], icon: '📬', link: '/services/inbox-zero-tracker', contactInfo },
  { id: 'response-time-optimizer', name: "Response Time Optimizer", category: "AI Services", description: "Optimize your email response times with AI-powered insights. Identify patterns and improve responsiveness.", price: "$399/month", features: ["Response time analysis", "Pattern detection", "Benchmark setting", "Improvement suggestions", "SLA tracking"], icon: '⏱️', link: '/services/response-time-optimizer', contactInfo },
  { id: 'email-workload-analyzer', name: "Email Workload Analyzer", category: "Analytics Services", description: "Analyze your email workload to prevent burnout. Track volume trends and optimize your schedule.", price: "$349/month", features: ["Workload tracking", "Volume trends", "Peak time identification", "Schedule optimization", "Burnout prevention"], icon: '⚖️', link: '/services/email-workload-analyzer', contactInfo },
  { id: 'communication-efficiency-tool', name: "Communication Efficiency Tool", category: "AI Services", description: "Improve communication efficiency with AI-powered insights. Reduce email volume and focus on high-impact messages.", price: "$449/month", features: ["Efficiency scoring", "Volume reduction tips", "Template suggestions", "Automation opportunities", "ROI tracking"], icon: '⚡', link: '/services/communication-efficiency-tool', contactInfo },

  // V1080: Follow-up Automation (5)
  { id: 'ai-followup-automation', name: "AI Follow-up Automation", category: "AI Services", description: "Intelligent follow-up system tracking commitments, deadlines, and unanswered emails with automated reminders.", price: "$549/month", features: ["Commitment tracking", "Deadline monitoring", "Auto follow-ups", "Escalation rules", "Template generation"], icon: '🔄', link: '/services/ai-followup-automation', contactInfo },
  { id: 'commitment-tracker', name: "Email Commitment Tracker", category: "AI Services", description: "Track all commitments made in emails. AI extracts promises, deadlines, and action items for accountability.", price: "$449/month", features: ["Commitment extraction", "Deadline tracking", "Accountability mapping", "Status updates", "Progress reports"], icon: '📌', link: '/services/commitment-tracker', contactInfo },
  { id: 'deadline-monitor', name: "Email Deadline Monitor", category: "AI Services", description: "Monitor deadlines mentioned in emails. Get timely reminders and ensure you never miss important deadlines.", price: "$399/month", features: ["Deadline extraction", "Smart reminders", "Escalation alerts", "Calendar integration", "Progress tracking"], icon: '⏰', link: '/services/deadline-monitor', contactInfo },
  { id: 'unanswered-email-tracker', name: "Unanswered Email Tracker", category: "Productivity Services", description: "Track unanswered emails and questions. Get reminders to follow up and ensure all communications are addressed.", price: "$349/month", features: ["Question detection", "Follow-up reminders", "Response tracking", "Priority sorting", "Batch processing"], icon: '❓', link: '/services/unanswered-email-tracker', contactInfo },
  { id: 'smart-escalation-system', name: "Smart Escalation System", category: "AI Services", description: "Automatically escalate overdue items and critical commitments. Ensure important matters get attention.", price: "$499/month", features: ["Automated escalation", "Priority-based routing", "Manager notifications", "SLA enforcement", "Resolution tracking"], icon: '🚨', link: '/services/smart-escalation-system', contactInfo }
];

services.push(...newServices);
fs.writeFileSync(dataPath, JSON.stringify(services, null, 2));
console.log(`Added ${newServices.length} new services. Total: ${services.length}`);
