const fs = require('fs');
const ts = fs.readFileSync('app/data/servicesData.ts', 'utf8');

// New AI services to add to aiServices array
const newAIEntries = `
  {
    id: 'ai-email-priority-escalation-v204',
    title: 'AI Email Priority Escalation Engine (V204)',
    description: 'Detect when email threads need urgent escalation using sentiment decay tracking, response delay analysis, executive mention detection, and deadline proximity scoring.',
    features: ['Sentiment decay tracking across threads', 'Response delay risk scoring', 'Executive mention detection', 'Deadline proximity analysis', 'Legal/compliance keyword detection', '5-level escalation', 'Auto-notify escalation chain', 'Reply-all enforcement guaranteed'],
    benefits: ['Never miss a critical escalation', 'Respond to urgent issues in minutes', 'Protect executive relationships', 'Avoid legal and compliance risks'],
    pricing: { basic: '$399/mo', pro: '$899/mo', enterprise: '$2299/mo' },
    contactInfo: { website: '/services/ai-email-priority-escalation-v204', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🚨',
    href: '/services/ai-email-priority-escalation-v204',
    popular: true,
    category: 'ai',
    industry: 'Enterprise Communication',
  },
  {
    id: 'ai-email-knowledge-extraction-v205',
    title: 'AI Email Knowledge Extraction Engine (V205)',
    description: 'Automatically extract decisions, action items, deadlines, commitments, and metrics from every email thread into a searchable knowledge base.',
    features: ['Decision extraction with context', 'Action item detection', 'Deadline tracking', 'Commitment extraction', 'Metric detection', 'Searchable knowledge base', 'Full audit trail', 'Reply-all enforcement'],
    benefits: ['Build knowledge automatically', 'Never lose a decision', 'Search any email fact instantly', 'Track commitments'],
    pricing: { basic: '$349/mo', pro: '$799/mo', enterprise: '$1999/mo' },
    contactInfo: { website: '/services/ai-email-knowledge-extraction-v205', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🧠',
    href: '/services/ai-email-knowledge-extraction-v205',
    popular: true,
    category: 'ai',
    industry: 'Knowledge Management',
  },
  {
    id: 'ai-stakeholder-relationship-mapper-v206',
    title: 'AI Stakeholder Relationship Mapper (V206)',
    description: 'Map organizational relationships from email patterns. Identify decision-makers, influencers, gatekeepers, and champions.',
    features: ['Relationship mapping', 'Influence scoring', 'Decision-maker identification', 'Gatekeeper detection', 'Communication clusters', 'Strategic recommendations', 'Role detection', 'Strength scoring'],
    benefits: ['Understand org dynamics', 'Target decision-makers', 'Leverage champions', 'Avoid relationship risks'],
    pricing: { basic: '$449/mo', pro: '$999/mo', enterprise: '$2499/mo' },
    contactInfo: { website: '/services/ai-stakeholder-relationship-mapper-v206', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🕸️',
    href: '/services/ai-stakeholder-relationship-mapper-v206',
    popular: true,
    category: 'ai',
    industry: 'Sales Intelligence',
  },
  {
    id: 'ai-email-response-quality-grader-v207',
    title: 'AI Email Response Quality Grader (V207)',
    description: 'Grade every draft email before sending on clarity, tone, completeness, actionability, and professionalism.',
    features: ['Clarity analysis', 'Tone evaluation', 'Completeness checking', 'Actionability scoring', 'Professionalism grading', 'A+ to F grading', 'Rewrite suggestions', 'Reply-all check'],
    benefits: ['Send higher quality emails', 'Catch tone issues early', 'Ensure all points addressed', 'Improve communication skills'],
    pricing: { basic: '$199/mo', pro: '$449/mo', enterprise: '$999/mo' },
    contactInfo: { website: '/services/ai-email-response-quality-grader-v207', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '⭐',
    href: '/services/ai-email-response-quality-grader-v207',
    popular: true,
    category: 'ai',
    industry: 'Communication Quality',
  },
  {
    id: 'ai-email-workflow-automation-v208',
    title: 'AI Email Workflow Automation Engine (V208)',
    description: 'Detect repetitive email patterns and automatically create workflow rules, smart templates, auto-responses, and routing logic.',
    features: ['Pattern detection', 'Auto-rule generation', 'Smart template creation', 'Intelligent routing', 'Auto-response workflows', 'Follow-up tracking', 'Complaint escalation', 'Learning from history'],
    benefits: ['Automate 80% of repetitive emails', 'Respond instantly', 'Route automatically', 'Continuously improve'],
    pricing: { basic: '$449/mo', pro: '$999/mo', enterprise: '$2499/mo' },
    contactInfo: { website: '/services/ai-email-workflow-automation-v208', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '⚙️',
    href: '/services/ai-email-workflow-automation-v208',
    popular: true,
    category: 'ai',
    industry: 'Workflow Automation',
  },
  {
    id: 'ai-contract-analysis-risk-detection',
    title: 'AI Contract Analysis & Risk Detection',
    description: 'Analyze contracts, NDAs, MSAs, and SOWs in seconds. Detect risky clauses, missing protections, and benchmark against industry standards.',
    features: ['Clause-by-clause risk scoring', 'Missing protection detection', 'Industry benchmark comparison', 'Redline suggestions', 'Obligation tracking', 'Renewal date extraction', 'Liability cap analysis', 'Multi-jurisdiction compliance'],
    benefits: ['Review contracts 50x faster', 'Catch risky clauses', 'Never miss a renewal', 'Benchmark against standards'],
    pricing: { basic: '$599/mo', pro: '$1299/mo', enterprise: '$3499/mo' },
    contactInfo: { website: '/services/ai-contract-analysis-risk-detection', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '📜',
    href: '/services/ai-contract-analysis-risk-detection',
    popular: true,
    category: 'ai',
    industry: 'Legal Tech',
  },
  {
    id: 'ai-meeting-minutes-action-tracker',
    title: 'AI Meeting Minutes & Action Item Tracker',
    description: 'Automatically generate meeting minutes from calls. Extract action items with owners and deadlines, track completion, and send follow-ups.',
    features: ['Auto-transcription', 'Speaker identification', 'Action item extraction', 'Deadline detection', 'Decision logging', 'Follow-up generation', 'Zoom/Teams/Meet integration', 'Meeting history search'],
    benefits: ['Never take notes again', 'Track action items to completion', 'Search past meetings', 'Send perfect follow-ups'],
    pricing: { basic: '$149/mo', pro: '$349/mo', enterprise: '$799/mo' },
    contactInfo: { website: '/services/ai-meeting-minutes-action-tracker', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '📝',
    href: '/services/ai-meeting-minutes-action-tracker',
    popular: true,
    category: 'ai',
    industry: 'Productivity',
  },
  {
    id: 'ai-customer-churn-prediction',
    title: 'AI Customer Churn Prediction Engine',
    description: 'Predict which customers will churn 90 days in advance using behavioral signals, usage patterns, and engagement scoring.',
    features: ['90-day churn prediction', 'Behavioral signal analysis', 'Usage pattern monitoring', 'Sentiment tracking', 'Engagement scoring', 'Retention campaign triggers', 'Revenue-at-risk dashboards', 'Win-back identification'],
    benefits: ['Predict churn 90 days early', 'Save 30% more accounts', 'Automate retention', 'Quantify revenue at risk'],
    pricing: { basic: '$499/mo', pro: '$1099/mo', enterprise: '$2999/mo' },
    contactInfo: { website: '/services/ai-customer-churn-prediction', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🔮',
    href: '/services/ai-customer-churn-prediction',
    popular: true,
    category: 'ai',
    industry: 'Customer Success',
  },
  {
    id: 'ai-document-summarization-qa',
    title: 'AI Document Summarization & Q&A Platform',
    description: 'Upload any document and get instant summaries, ask questions in natural language, extract key data points, and compare documents.',
    features: ['Instant summarization', 'Natural language Q&A', 'Key data extraction', 'Multi-document comparison', 'Cross-document search', 'Fact verification', 'Table/chart extraction', 'Citation tracking'],
    benefits: ['Summarize 100-page docs in seconds', 'Ask questions about any document', 'Compare side by side', 'Extract data automatically'],
    pricing: { basic: '$199/mo', pro: '$449/mo', enterprise: '$1099/mo' },
    contactInfo: { website: '/services/ai-document-summarization-qa', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '📖',
    href: '/services/ai-document-summarization-qa',
    popular: true,
    category: 'ai',
    industry: 'Document Intelligence',
  },
  {
    id: 'ai-competitive-intelligence-platform',
    title: 'AI Competitive Intelligence Platform',
    description: 'Monitor competitors across web, social, news, job postings, and patents with automated alerts on critical changes.',
    features: ['Multi-source monitoring', 'Pricing change detection', 'Product launch tracking', 'Job posting analysis', 'Funding monitoring', 'Patent tracking', 'Personnel move alerts', 'Competitive briefs'],
    benefits: ['Know competitor moves first', 'Automate research', 'Get critical alerts', 'Generate briefs instantly'],
    pricing: { basic: '$399/mo', pro: '$899/mo', enterprise: '$2299/mo' },
    contactInfo: { website: '/services/ai-competitive-intelligence-platform', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🎯',
    href: '/services/ai-competitive-intelligence-platform',
    popular: true,
    category: 'ai',
    industry: 'Business Intelligence',
  },
  {
    id: 'ai-email-ultra-suite-v204-v208',
    title: 'AI Email Ultra Suite (V204-V208)',
    description: 'All 5 new email intelligence engines unified. Priority Escalation, Knowledge Extraction, Stakeholder Mapping, Response Quality, and Workflow Automation.',
    features: ['V204: Priority Escalation', 'V205: Knowledge Extraction', 'V206: Stakeholder Mapper', 'V207: Response Quality Grader', 'V208: Workflow Automation', 'Case-by-case analysis', 'Reply-all guaranteed', 'Enterprise security'],
    benefits: ['Complete email intelligence', 'Every email optimized', 'Automate workflows', 'Most advanced email AI'],
    pricing: { basic: '$1499/mo', pro: '$3499/mo', enterprise: '$8999/mo' },
    contactInfo: { website: '/services/ai-email-ultra-suite-v204-v208', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '👑',
    href: '/services/ai-email-ultra-suite-v204-v208',
    popular: true,
    category: 'ai',
    industry: 'Enterprise AI',
  },`;

// New IT services
const newITEntries = `
  {
    id: 'it-zero-trust-network-access',
    title: 'Zero Trust Network Access (ZTNA) Platform',
    description: 'Implement zero-trust security with identity-based access, micro-segmentation, continuous verification, and least-privilege enforcement.',
    features: ['Identity-based access control', 'Micro-segmentation', 'Continuous verification', 'Least-privilege enforcement', 'Device trust scoring', 'VPN replacement', 'Application-level access', 'Real-time threat blocking'],
    benefits: ['Replace legacy VPNs', 'Reduce attack surface by 80%', 'Verify every access', 'Enforce least-privilege'],
    pricing: { basic: '$599/mo', pro: '$1299/mo', enterprise: '$3499/mo' },
    contactInfo: { website: '/services/it-zero-trust-network-access', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🔐',
    href: '/services/it-zero-trust-network-access',
    popular: true,
    category: 'it',
    industry: 'Network Security',
  },
  {
    id: 'it-cloud-cost-optimization-finops',
    title: 'Cloud Cost Optimization & FinOps Platform',
    description: 'Optimize cloud spending across AWS, Azure, and GCP with right-sizing, reserved instances, waste detection, and FinOps governance.',
    features: ['Multi-cloud cost analysis', 'Right-sizing recommendations', 'Reserved instance optimization', 'Waste detection', 'Budget alerts', 'FinOps governance', 'Cost allocation', 'Automated savings plans'],
    benefits: ['Reduce cloud costs 30-40%', 'Eliminate waste', 'Forecast accurately', 'Implement FinOps'],
    pricing: { basic: '$299/mo', pro: '$699/mo', enterprise: '$1799/mo' },
    contactInfo: { website: '/services/it-cloud-cost-optimization-finops', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '💸',
    href: '/services/it-cloud-cost-optimization-finops',
    popular: true,
    category: 'it',
    industry: 'Cloud FinOps',
  },
  {
    id: 'it-incident-response-management',
    title: 'Incident Response & Management Platform',
    description: 'Streamline incident response with automated detection, on-call management, war room coordination, and post-incident reviews.',
    features: ['Automated incident detection', 'On-call rotation management', 'War room coordination', 'Timeline tracking', 'Post-incident reviews', 'Status page integration', 'Runbook automation', 'MTTR/MTTD analytics'],
    benefits: ['Reduce MTTR by 60%', 'Automate on-call', 'Coordinate efficiently', 'Learn from incidents'],
    pricing: { basic: '$249/mo', pro: '$599/mo', enterprise: '$1399/mo' },
    contactInfo: { website: '/services/it-incident-response-management', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🚒',
    href: '/services/it-incident-response-management',
    popular: true,
    category: 'it',
    industry: 'IT Operations',
  },
  {
    id: 'it-iac-security-scanner',
    title: 'Infrastructure as Code (IaC) Security Scanner',
    description: 'Scan Terraform, CloudFormation, K8s YAML, and Helm charts for security misconfigurations and compliance violations.',
    features: ['Terraform scanning', 'CloudFormation analysis', 'Kubernetes YAML validation', 'Helm chart checks', 'CIS/NIST benchmarking', 'Drift detection', 'Policy-as-code', 'CI/CD integration'],
    benefits: ['Catch misconfigurations early', 'Enforce security in code', 'Prevent violations', 'Detect drift'],
    pricing: { basic: '$199/mo', pro: '$449/mo', enterprise: '$1099/mo' },
    contactInfo: { website: '/services/it-iac-security-scanner', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🔍',
    href: '/services/it-iac-security-scanner',
    popular: true,
    category: 'it',
    industry: 'DevSecOps',
  },`;

// New security services
const newSecurityEntries = `
  {
    id: 'security-ai-penetration-testing',
    title: 'AI-Powered Penetration Testing Platform',
    description: 'Automated penetration testing using AI to discover vulnerabilities, exploit chains, and attack paths with continuous testing.',
    features: ['AI-driven vulnerability discovery', 'Attack path mapping', 'Exploit chain analysis', 'Web/API/network testing', 'Continuous pentesting', 'Remediation guidance', 'PCI/SOC2 reporting', 'Executive summaries'],
    benefits: ['Continuous pentesting', 'Discover hidden attack paths', 'Detailed remediation', 'Meet compliance'],
    pricing: { basic: '$999/mo', pro: '$2499/mo', enterprise: '$5999/mo' },
    contactInfo: { website: '/services/security-ai-penetration-testing', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🎯',
    href: '/services/security-ai-penetration-testing',
    popular: true,
    category: 'security',
    industry: 'Cybersecurity',
  },
  {
    id: 'security-data-loss-prevention',
    title: 'Data Loss Prevention (DLP) Intelligence',
    description: 'AI-powered DLP monitoring across email, cloud, endpoints, and network. Detect exfiltration, enforce policies, prevent breaches.',
    features: ['Multi-channel DLP', 'AI sensitive data classification', 'Real-time exfiltration detection', 'Policy enforcement', 'Incident investigation', 'User behavior analytics', 'GDPR/HIPAA reporting', 'Automated remediation'],
    benefits: ['Prevent breaches in real-time', 'Classify data automatically', 'Enforce policies everywhere', 'Investigate quickly'],
    pricing: { basic: '$599/mo', pro: '$1299/mo', enterprise: '$3499/mo' },
    contactInfo: { website: '/services/security-data-loss-prevention', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🛡️',
    href: '/services/security-data-loss-prevention',
    popular: true,
    category: 'security',
    industry: 'Data Security',
  },
  {
    id: 'security-identity-governance',
    title: 'Identity Governance & Administration Platform',
    description: 'Manage user identities, access reviews, RBAC, and compliance reporting. Automate joiner/mover/leaver processes.',
    features: ['User lifecycle management', 'Access review campaigns', 'RBAC', 'Segregation of duties', 'Privileged access management', 'SOX/SOC2 reporting', 'Auto provisioning', 'Certification workflows'],
    benefits: ['Automate identity lifecycle', 'Pass audits easily', 'Enforce least-privilege', 'Reduce insider risk'],
    pricing: { basic: '$499/mo', pro: '$1099/mo', enterprise: '$2999/mo' },
    contactInfo: { website: '/services/security-identity-governance', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '👤',
    href: '/services/security-identity-governance',
    popular: true,
    category: 'security',
    industry: 'Identity & Access',
  },`;

// New data services
const newDataEntries = `
  {
    id: 'data-real-time-streaming-platform',
    title: 'Real-Time Data Streaming Platform',
    description: 'Process millions of events per second with managed Kafka, Flink, and Spark Streaming. Real-time analytics and event-driven architectures.',
    features: ['Managed Kafka clusters', 'Apache Flink processing', 'Real-time analytics', 'Event-driven architecture', 'Pipeline management', 'Schema registry', 'Exactly-once processing', 'Auto-scaling'],
    benefits: ['Process millions per second', 'Build event-driven systems', 'Get real-time analytics', 'Scale automatically'],
    pricing: { basic: '$499/mo', pro: '$1099/mo', enterprise: '$2999/mo' },
    contactInfo: { website: '/services/data-real-time-streaming-platform', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🌊',
    href: '/services/data-real-time-streaming-platform',
    popular: true,
    category: 'data',
    industry: 'Data Engineering',
  },
  {
    id: 'data-governance-catalog-platform',
    title: 'Data Governance & Catalog Platform',
    description: 'Discover, catalog, and govern all enterprise data assets with automated lineage, business glossary, and compliance tracking.',
    features: ['Automated data discovery', 'Data lineage visualization', 'Business glossary', 'Access policy enforcement', 'Quality rule engine', 'AI classification', 'GDPR/CCPA tracking', 'Data marketplace'],
    benefits: ['Discover data automatically', 'Track lineage end-to-end', 'Enforce governance', 'Enable self-service'],
    pricing: { basic: '$399/mo', pro: '$899/mo', enterprise: '$2299/mo' },
    contactInfo: { website: '/services/data-governance-catalog-platform', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '📚',
    href: '/services/data-governance-catalog-platform',
    popular: true,
    category: 'data',
    industry: 'Data Governance',
  },`;

// New micro-saas/automation services
const newAutomationEntries = `
  {
    id: 'micro-saas-invoice-automation',
    title: 'Invoice Automation & Payment Tracking',
    description: 'Automate invoice creation, delivery, reminders, and payment tracking with recurring billing and multi-currency support.',
    features: ['Auto invoice generation', 'Smart payment reminders', 'Recurring billing', 'Multi-currency (135+)', 'Tax calculation', 'Stripe/PayPal integration', 'Payment tracking', 'Revenue recognition'],
    benefits: ['Get paid 2x faster', 'Eliminate manual invoicing', 'Reduce late payments 60%', 'Support global customers'],
    pricing: { basic: '$49/mo', pro: '$149/mo', enterprise: '$399/mo' },
    contactInfo: { website: '/services/micro-saas-invoice-automation', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '💰',
    href: '/services/micro-saas-invoice-automation',
    popular: true,
    category: 'micro-saas',
    industry: 'Finance & Accounting',
  },
  {
    id: 'micro-saas-employee-onboarding',
    title: 'Employee Onboarding Workflow Platform',
    description: 'Streamline new hire onboarding with automated workflows, document collection, task assignments, and compliance tracking.',
    features: ['Automated workflows', 'Document collection', 'Task assignments', 'Training schedules', 'Compliance tracking', 'Equipment provisioning', 'Buddy assignment', '30-60-90 day check-ins'],
    benefits: ['Onboard 3x faster', '100% compliance', 'Reduce HR work 80%', 'Track milestones'],
    pricing: { basic: '$99/mo', pro: '$249/mo', enterprise: '$599/mo' },
    contactInfo: { website: '/services/micro-saas-employee-onboarding', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '👋',
    href: '/services/micro-saas-employee-onboarding',
    popular: true,
    category: 'micro-saas',
    industry: 'Human Resources',
  },
  {
    id: 'micro-saas-vendor-management',
    title: 'Vendor Management & Procurement Platform',
    description: 'Manage vendors, contracts, and procurement in one platform with performance tracking and automated renewals.',
    features: ['Vendor database', 'Contract management', 'Procurement workflows', 'Budget tracking', 'Risk assessment', 'Compliance enforcement', 'Spend analytics', 'RFQ/RFP management'],
    benefits: ['Reduce costs 15%', 'Never miss renewals', 'Automate procurement', 'Track performance'],
    pricing: { basic: '$149/mo', pro: '$349/mo', enterprise: '$799/mo' },
    contactInfo: { website: '/services/micro-saas-vendor-management', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🤝',
    href: '/services/micro-saas-vendor-management',
    popular: true,
    category: 'micro-saas',
    industry: 'Procurement',
  },
  {
    id: 'micro-saas-customer-portal',
    title: 'Customer Portal & Self-Service Hub',
    description: 'Branded self-service portal for support tickets, knowledge base, invoices, usage analytics, and account management.',
    features: ['Branded portal', 'Ticket management', 'Knowledge base', 'Invoice management', 'Usage analytics', 'Account management', 'White-labeling', 'SSO integration'],
    benefits: ['Reduce tickets 40%', '24/7 self-service', 'Increase satisfaction', 'Centralize interactions'],
    pricing: { basic: '$199/mo', pro: '$449/mo', enterprise: '$999/mo' },
    contactInfo: { website: '/services/micro-saas-customer-portal', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🏠',
    href: '/services/micro-saas-customer-portal',
    popular: true,
    category: 'micro-saas',
    industry: 'Customer Success',
  },
  {
    id: 'micro-saas-feature-flag-management',
    title: 'Feature Flag Management Platform',
    description: 'Deploy features safely with feature flags, A/B testing, gradual rollouts, and instant kill switches.',
    features: ['Flag management', 'Gradual rollouts', 'User segment targeting', 'A/B testing', 'Kill switches', 'Real-time analytics', 'Multi-environment', 'Audit trail'],
    benefits: ['Deploy without risk', 'A/B test everything', 'Roll out gradually', 'Kill instantly'],
    pricing: { basic: '$79/mo', pro: '$199/mo', enterprise: '$499/mo' },
    contactInfo: { website: '/services/micro-saas-feature-flag-management', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🚩',
    href: '/services/micro-saas-feature-flag-management',
    popular: true,
    category: 'micro-saas',
    industry: 'Software Development',
  },
  {
    id: 'micro-saas-feedback-feature-board',
    title: 'User Feedback & Feature Request Board',
    description: 'Collect, organize, and prioritize user feedback with voting, comments, status tracking, and roadmap integration.',
    features: ['Public feedback board', 'Voting & commenting', 'Status tracking', 'Prioritization tools', 'Roadmap integration', 'User segmentation', 'Jira/Linear integration', 'Status update emails'],
    benefits: ['Build what users want', 'Prioritize by demand', 'Keep users informed', 'Connect to roadmap'],
    pricing: { basic: '$49/mo', pro: '$129/mo', enterprise: '$299/mo' },
    contactInfo: { website: '/services/micro-saas-feedback-feature-board', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '💬',
    href: '/services/micro-saas-feedback-feature-board',
    popular: true,
    category: 'micro-saas',
    industry: 'Product Management',
  },
  {
    id: 'micro-saas-subscription-dunning',
    title: 'Subscription Management & Dunning Platform',
    description: 'Manage subscriptions, automate billing, reduce churn with smart dunning, and optimize revenue with upgrade analytics.',
    features: ['Subscription lifecycle', 'Automated billing', 'Smart dunning (5 stages)', 'Upgrade analytics', 'Retention offers', 'Proration handling', 'MRR/ARR dashboards', 'Churn analytics'],
    benefits: ['Reduce churn 35%', 'Automate billing', 'Optimize revenue', 'Track all metrics'],
    pricing: { basic: '$99/mo', pro: '$249/mo', enterprise: '$599/mo' },
    contactInfo: { website: '/services/micro-saas-subscription-dunning', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🔄',
    href: '/services/micro-saas-subscription-dunning',
    popular: true,
    category: 'micro-saas',
    industry: 'Revenue Operations',
  },
  {
    id: 'micro-saas-api-analytics-ratelimiting',
    title: 'API Usage Analytics & Rate Limiting',
    description: 'Monitor API usage, enforce rate limits, detect abuse, and generate usage-based billing with full analytics.',
    features: ['Real-time monitoring', 'Rate limiting', 'Abuse detection', 'Usage billing', 'Per-customer analytics', 'Latency tracking', 'Health dashboards', 'Webhook alerts'],
    benefits: ['Prevent abuse', 'Bill by usage', 'Monitor health', 'Detect anomalies'],
    pricing: { basic: '$149/mo', pro: '$349/mo', enterprise: '$799/mo' },
    contactInfo: { website: '/services/micro-saas-api-analytics-ratelimiting', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '📡',
    href: '/services/micro-saas-api-analytics-ratelimiting',
    popular: true,
    category: 'micro-saas',
    industry: 'API Management',
  },
  {
    id: 'micro-saas-visual-testing',
    title: 'Automated Visual Testing & Screenshot Platform',
    description: 'Visual regression testing across browsers and devices with pixel-perfect diffs and CI/CD integration.',
    features: ['Visual regression testing', 'Cross-browser screenshots', 'Mobile device testing', 'Pixel-perfect diffs', 'CI/CD integration', 'Baseline management', 'Flaky test detection', 'Accessibility audit'],
    benefits: ['Catch UI bugs early', 'Test 50+ browsers', 'Automate regression', 'Integrate with CI/CD'],
    pricing: { basic: '$99/mo', pro: '$249/mo', enterprise: '$599/mo' },
    contactInfo: { website: '/services/micro-saas-visual-testing', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '📸',
    href: '/services/micro-saas-visual-testing',
    popular: true,
    category: 'micro-saas',
    industry: 'Quality Assurance',
  },
  {
    id: 'micro-saas-status-page-incident',
    title: 'Status Page & Incident Management',
    description: 'Public and internal status pages with automated incident detection, real-time updates, and subscriber notifications.',
    features: ['Status pages', 'Incident detection', 'Real-time updates', 'Subscriber notifications', 'Post-incident reports', 'Uptime SLA tracking', 'Component status', 'Custom branding'],
    benefits: ['Build trust', 'Reduce support during incidents', 'Automate communication', 'Track SLAs'],
    pricing: { basic: '$49/mo', pro: '$149/mo', enterprise: '$349/mo' },
    contactInfo: { website: '/services/micro-saas-status-page-incident', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🟢',
    href: '/services/micro-saas-status-page-incident',
    popular: true,
    category: 'micro-saas',
    industry: 'Reliability Engineering',
  },`;

let updated = ts;

// Insert AI entries before the closing of aiServices
const aiClose = updated.indexOf('\n];\n\nexport const itServices');
if (aiClose > -1) {
  updated = updated.slice(0, aiClose) + '\n' + newAIEntries + updated.slice(aiClose);
  console.log('Added AI entries');
}

// Insert IT entries before the closing of itServices
const itClose = updated.indexOf('\n];\n\nexport const cloudServices');
if (itClose > -1) {
  updated = updated.slice(0, itClose) + '\n' + newITEntries + updated.slice(itClose);
  console.log('Added IT entries');
}

// Insert security entries before closing of securityServices
const secClose = updated.indexOf('\n];\n\nexport const dataServices');
if (secClose > -1) {
  updated = updated.slice(0, secClose) + '\n' + newSecurityEntries + updated.slice(secClose);
  console.log('Added security entries');
}

// Insert data entries before closing of dataServices
const dataClose = updated.indexOf('\n];\n\nexport const automationServices');
if (dataClose > -1) {
  updated = updated.slice(0, dataClose) + '\n' + newDataEntries + updated.slice(dataClose);
  console.log('Added data entries');
}

// Insert automation/micro-saas entries before closing of automationServices
const autoClose = updated.indexOf('\n];\n\nexport const allServices');
if (autoClose > -1) {
  updated = updated.slice(0, autoClose) + '\n' + newAutomationEntries + updated.slice(autoClose);
  console.log('Added automation/micro-saas entries');
}

fs.writeFileSync('app/data/servicesData.ts', updated);
console.log('servicesData.ts updated successfully');
