const fs = require('fs');
const path = require('path');

const contactInfo = {
  phone: "+1 302 464 0950",
  email: "kleber@ziontechgroup.com",
  address: "364 E Main St STE 1008 Middletown DE 19709"
};

const newServices = [
  // Digital Twin & Simulation (5)
  {id:"digital-twin-platform-v851",name:"Digital Twin Platform",category:"Digital Twins",description:"AI-powered digital twin platform with real-time system modeling, predictive maintenance, scenario testing, and IoT integration for manufacturing, energy, and logistics.",price:"$8,500/mo",features:["Real-time system modeling","Predictive maintenance","Scenario testing","IoT sensor integration","Performance optimization"],icon:"🏭",contactInfo,link:"/services/digital-twin-platform-v851"},
  {id:"predictive-maintenance-ai-v851",name:"Predictive Maintenance AI",category:"Digital Twins",description:"AI-driven predictive maintenance with sensor data analysis, failure prediction, maintenance scheduling optimization, and cost avoidance tracking.",price:"$5,500/mo",features:["Sensor data analysis","Failure prediction","Maintenance scheduling","Cost avoidance tracking","Equipment health scoring"],icon:"🔧",contactInfo,link:"/services/predictive-maintenance-ai-v851"},
  {id:"process-simulation-engine-v851",name:"Process Simulation Engine",category:"Digital Twins",description:"Advanced process simulation with what-if scenario testing, optimization recommendations, and throughput improvement analysis.",price:"$6,000/mo",features:["What-if scenarios","Process optimization","Throughput analysis","Resource simulation","Risk assessment"],icon:"📊",contactInfo,link:"/services/process-simulation-engine-v851"},
  {id:"iot-data-integration-platform-v851",name:"IoT Data Integration Platform",category:"Digital Twins",description:"Comprehensive IoT data integration with multi-protocol support, edge computing, real-time analytics, and data quality monitoring.",price:"$4,200/mo",features:["Multi-protocol support","Edge computing","Real-time analytics","Data quality monitoring","Sensor management"],icon:"📡",contactInfo,link:"/services/iot-data-integration-platform-v851"},
  {id:"anomaly-detection-iot-v851",name:"Anomaly Detection for IoT",category:"Digital Twins",description:"AI-powered anomaly detection for IoT systems with real-time monitoring, fault detection, deviation alerting, and root cause analysis.",price:"$3,800/mo",features:["Real-time monitoring","Fault detection","Deviation alerting","Root cause analysis","Pattern recognition"],icon:"🔍",contactInfo,link:"/services/anomaly-detection-iot-v851"},

  // Blockchain & Web3 (5)
  {id:"smart-contract-auditing-v852",name:"Smart Contract Auditing",category:"Blockchain & Web3",description:"Comprehensive smart contract auditing with vulnerability detection, gas optimization, security scoring, and remediation recommendations across Ethereum, Polygon, BSC, and Solana.",price:"$12,000/mo",features:["Vulnerability detection","Gas optimization","Security scoring","Multi-chain support","Remediation guidance"],icon:"🔒",contactInfo,link:"/services/smart-contract-auditing-v852"},
  {id:"defi-protocol-analytics-v852",name:"DeFi Protocol Analytics",category:"Blockchain & Web3",description:"AI-powered DeFi protocol analytics with TVL monitoring, risk assessment, yield optimization, and cross-protocol performance tracking.",price:"$7,500/mo",features:["TVL monitoring","Risk assessment","Yield optimization","Cross-protocol tracking","Smart money analysis"],icon:"💰",contactInfo,link:"/services/defi-protocol-analytics-v852"},
  {id:"blockchain-compliance-platform-v852",name:"Blockchain Compliance Platform",category:"Blockchain & Web3",description:"Automated blockchain compliance with KYC/AML screening, sanctions checking, transaction monitoring, and regulatory reporting.",price:"$8,000/mo",features:["KYC/AML screening","Sanctions checking","Transaction monitoring","Regulatory reporting","Risk scoring"],icon:"⚖️",contactInfo,link:"/services/blockchain-compliance-platform-v852"},
  {id:"nft-marketplace-intelligence-v852",name:"NFT Marketplace Intelligence",category:"Blockchain & Web3",description:"AI-powered NFT marketplace analytics with floor price prediction, collection analysis, wash trading detection, and portfolio management.",price:"$4,500/mo",features:["Floor price prediction","Collection analysis","Wash trading detection","Portfolio management","Market trends"],icon:"🎨",contactInfo,link:"/services/nft-marketplace-intelligence-v852"},
  {id:"cross-chain-bridge-monitor-v852",name:"Cross-Chain Bridge Monitor",category:"Blockchain & Web3",description:"Real-time cross-chain bridge monitoring with security alerts, liquidity tracking, transaction analysis, and exploit detection.",price:"$6,500/mo",features:["Security alerts","Liquidity tracking","Transaction analysis","Exploit detection","Multi-bridge support"],icon:"🌉",contactInfo,link:"/services/cross-chain-bridge-monitor-v852"},

  // Quantum Computing (5)
  {id:"quantum-readiness-assessment-v853",name:"Quantum Readiness Assessment",category:"Quantum Computing",description:"Comprehensive quantum computing readiness assessment with algorithm identification, quantum advantage analysis, and future-proofing recommendations.",price:"$15,000/mo",features:["Algorithm identification","Quantum advantage analysis","Future-proofing","Cost-benefit modeling","Migration roadmap"],icon:"⚛️",contactInfo,link:"/services/quantum-readiness-assessment-v853"},
  {id:"post-quantum-cryptography-v853",name:"Post-Quantum Cryptography Migration",category:"Quantum Computing",description:"Automated post-quantum cryptography migration with system inventory, algorithm selection, implementation planning, and compliance verification.",price:"$18,000/mo",features:["System inventory","Algorithm selection","Implementation planning","Compliance verification","Risk assessment"],icon:"🔐",contactInfo,link:"/services/post-quantum-cryptography-v853"},
  {id:"quantum-algorithm-optimizer-v853",name:"Quantum Algorithm Optimizer",category:"Quantum Computing",description:"AI-powered quantum algorithm optimization with problem mapping, circuit optimization, noise mitigation, and hybrid classical-quantum workflows.",price:"$12,000/mo",features:["Problem mapping","Circuit optimization","Noise mitigation","Hybrid workflows","Performance benchmarking"],icon:"🧮",contactInfo,link:"/services/quantum-algorithm-optimizer-v853"},
  {id:"quantum-hardware-evaluation-v853",name:"Quantum Hardware Evaluation",category:"Quantum Computing",description:"Multi-platform quantum hardware evaluation with performance benchmarking, cost comparison, and provider recommendation across IBM, Google, D-Wave, and IonQ.",price:"$8,500/mo",features:["Multi-platform benchmarking","Cost comparison","Provider recommendation","Error rate analysis","Coherence evaluation"],icon:"💻",contactInfo,link:"/services/quantum-hardware-evaluation-v853"},
  {id:"quantum-simulation-platform-v853",name:"Quantum Simulation Platform",category:"Quantum Computing",description:"Quantum simulation platform for molecular modeling, material science, drug discovery, and financial modeling with hybrid classical-quantum approaches.",price:"$20,000/mo",features:["Molecular modeling","Material science","Drug discovery","Financial modeling","Hybrid approaches"],icon:"🔬",contactInfo,link:"/services/quantum-simulation-platform-v853"},

  // AI Ethics & Governance (5)
  {id:"ai-bias-detection-platform-v854",name:"AI Bias Detection Platform",category:"AI Ethics & Governance",description:"Comprehensive AI bias detection with fairness auditing across gender, race, age, and socioeconomic dimensions, with automated mitigation recommendations.",price:"$6,500/mo",features:["Fairness auditing","Multi-dimension bias detection","Automated mitigation","Model scoring","Continuous monitoring"],icon:"⚖️",contactInfo,link:"/services/ai-bias-detection-platform-v854"},
  {id:"eu-ai-act-compliance-v854",name:"EU AI Act Compliance Platform",category:"AI Ethics & Governance",description:"Automated EU AI Act compliance with risk classification, gap analysis, remediation planning, and regulatory reporting.",price:"$9,000/mo",features:["Risk classification","Gap analysis","Remediation planning","Regulatory reporting","Audit trail"],icon:"🇪🇺",contactInfo,link:"/services/eu-ai-act-compliance-v854"},
  {id:"ai-transparency-reporting-v854",name:"AI Transparency Reporting",category:"AI Ethics & Governance",description:"Automated AI transparency reporting with model cards, data sheets, explainability documentation, and stakeholder impact assessments.",price:"$4,800/mo",features:["Model cards","Data sheets","Explainability docs","Impact assessments","Stakeholder reports"],icon:"📋",contactInfo,link:"/services/ai-transparency-reporting-v854"},
  {id:"ai-governance-framework-v854",name:"AI Governance Framework",category:"AI Ethics & Governance",description:"Enterprise AI governance framework with policy management, risk assessment, approval workflows, and compliance monitoring across NIST AI RMF and IEEE standards.",price:"$7,500/mo",features:["Policy management","Risk assessment","Approval workflows","Compliance monitoring","Governance dashboards"],icon:"🏛️",contactInfo,link:"/services/ai-governance-framework-v854"},
  {id:"responsible-ai-certification-v854",name:"Responsible AI Certification",category:"AI Ethics & Governance",description:"Comprehensive responsible AI certification program with audit preparation, documentation review, and ongoing compliance monitoring.",price:"$12,000/mo",features:["Audit preparation","Documentation review","Compliance monitoring","Certification badge","Annual reassessment"],icon:"✅",contactInfo,link:"/services/responsible-ai-certification-v854"},

  // Autonomous Systems (5)
  {id:"multi-agent-orchestrator-v855",name:"Multi-Agent Orchestrator",category:"Autonomous Systems",description:"Enterprise multi-agent orchestration with task delegation, conflict resolution, performance monitoring, and human-in-the-loop oversight.",price:"$10,000/mo",features:["Task delegation","Conflict resolution","Performance monitoring","Human oversight","Auto-scaling"],icon:"🤖",contactInfo,link:"/services/multi-agent-orchestrator-v855"},
  {id:"agent-performance-analytics-v855",name:"Agent Performance Analytics",category:"Autonomous Systems",description:"AI agent performance analytics with throughput monitoring, latency tracking, efficiency scoring, and automated retraining recommendations.",price:"$5,500/mo",features:["Throughput monitoring","Latency tracking","Efficiency scoring","Retraining recommendations","Benchmarking"],icon:"📈",contactInfo,link:"/services/agent-performance-analytics-v855"},
  {id:"autonomous-workflow-builder-v855",name:"Autonomous Workflow Builder",category:"Autonomous Systems",description:"Visual autonomous workflow builder with drag-and-drop agent composition, conditional logic, error handling, and deployment automation.",price:"$7,000/mo",features:["Visual builder","Agent composition","Conditional logic","Error handling","Deployment automation"],icon:"🔧",contactInfo,link:"/services/autonomous-workflow-builder-v855"},
  {id:"agent-conflict-resolution-v855",name:"Agent Conflict Resolution AI",category:"Autonomous Systems",description:"AI-powered agent conflict resolution with resource contention handling, priority management, deadlock prevention, and automated escalation.",price:"$4,500/mo",features:["Resource contention","Priority management","Deadlock prevention","Automated escalation","Conflict analytics"],icon:"⚡",contactInfo,link:"/services/agent-conflict-resolution-v855"},
  {id:"human-ai-collaboration-platform-v855",name:"Human-AI Collaboration Platform",category:"Autonomous Systems",description:"Human-AI collaboration platform with approval workflows, context sharing, feedback loops, and trust scoring for seamless human-agent interaction.",price:"$6,000/mo",features:["Approval workflows","Context sharing","Feedback loops","Trust scoring","Collaboration analytics"],icon:"🤝",contactInfo,link:"/services/human-ai-collaboration-platform-v855"},

  // Innovative Micro-SaaS (5)
  {id:"ai-legal-assistant-saas-v855",name:"AI Legal Assistant",category:"Micro-SaaS",description:"AI-powered legal assistant with contract analysis, legal research, document drafting, and compliance checking for small businesses and startups.",price:"$199/mo",features:["Contract analysis","Legal research","Document drafting","Compliance checking","Template library"],icon:"⚖️",contactInfo,link:"/services/ai-legal-assistant-saas-v855"},
  {id:"crypto-portfolio-tracker-v855",name:"Crypto Portfolio Tracker Pro",category:"Micro-SaaS",description:"Advanced crypto portfolio tracking with DeFi integration, tax reporting, risk analysis, and automated rebalancing recommendations.",price:"$49/mo",features:["DeFi integration","Tax reporting","Risk analysis","Rebalancing","Multi-wallet support"],icon:"📊",contactInfo,link:"/services/crypto-portfolio-tracker-v855"},
  {id:"ai-content-moderation-v855",name:"AI Content Moderation",category:"Micro-SaaS",description:"AI-powered content moderation with multi-language support, custom policy enforcement, real-time filtering, and appeal management.",price:"$299/mo",features:["Multi-language","Custom policies","Real-time filtering","Appeal management","Analytics dashboard"],icon:"🛡️",contactInfo,link:"/services/ai-content-moderation-v855"},
  {id:"smart-inventory-saas-v855",name:"Smart Inventory Management",category:"Micro-SaaS",description:"AI-powered inventory management with demand forecasting, reorder optimization, multi-location tracking, and supplier management.",price:"$149/mo",features:["Demand forecasting","Reorder optimization","Multi-location","Supplier management","Cost tracking"],icon:"📦",contactInfo,link:"/services/smart-inventory-saas-v855"},
  {id:"ai-pricing-optimizer-v855",name:"AI Pricing Optimizer",category:"Micro-SaaS",description:"Dynamic AI pricing optimization with competitor monitoring, demand elasticity analysis, A/B testing, and revenue maximization.",price:"$249/mo",features:["Competitor monitoring","Elasticity analysis","A/B testing","Revenue maximization","Price recommendations"],icon:"💲",contactInfo,link:"/services/ai-pricing-optimizer-v855"}
];

const filePath = path.join(__dirname, '..', 'app', 'data', 'servicesData.json');
const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
const existingIds = new Set(data.map(s => s.id));
let added = 0;
for (const svc of newServices) {
  if (!existingIds.has(svc.id)) {
    data.push(svc);
    existingIds.add(svc.id);
    added++;
  }
}
fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
console.log(`Added ${added} services. Total: ${data.length}`);
