#!/usr/bin/env python3
"""Add Wave 128-129: 20 new real services to Zion Tech Group catalog."""
import json, os, sys

DATA_FILE = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'app', 'data', 'servicesData.json')

SERVICES = [
    # Wave 128: Micro-SaaS (5)
    {"id":"w128-ai-code-review","title":"AI Code Review Platform","description":"Automated pull request reviews with security scanning, style enforcement, and intelligent suggestions. Integrates with GitHub, GitLab, and Azure DevOps.","features":["Automated PR reviews","Security vulnerability detection","Style enforcement","Intelligent code suggestions","Multi-language support (Python, JS, Go, Rust, Java)","CI/CD integration","Custom rule engine"],"benefits":["80% faster code reviews","Catch bugs before production","Consistent code quality","Reduce tech debt"],"pricing":{"starter":"297","pro":"997","enterprise":"1997"},"icon":"🔍","category":"micro-saas","popular":True,"industry":"technology-and-saas","href":"/services/w128-ai-code-review"},
    {"id":"w128-invoice-recon","title":"Smart Invoice Reconciliation","description":"AI-powered invoice matching and reconciliation. Auto-matches invoices to payments, flags discrepancies, and syncs with accounting systems.","features":["AI invoice matching","Discrepancy detection","Multi-currency support","Accounting system sync (QuickBooks, Xero, SAP)","Exception handling dashboard","Bulk processing"],"benefits":["95% reduction in manual work","Eliminate payment errors","Real-time reconciliation","Faster month-end close"],"pricing":{"starter":"197","pro":"597","enterprise":"1297"},"icon":"🧾","category":"micro-saas","popular":False,"industry":"financial-services","href":"/services/w128-invoice-recon"},
    {"id":"w128-meeting-minutes","title":"AI Meeting Minutes Generator","description":"Real-time transcription, action item extraction, and meeting summaries. Integrates with Zoom, Teams, and Google Meet.","features":["Real-time transcription","Action item extraction","Meeting summaries","Speaker identification","Searchable archive","Calendar integration"],"benefits":["Never miss action items","Searchable meeting history","50% less note-taking time","Better follow-through"],"pricing":{"starter":"97","pro":"297","enterprise":"697"},"icon":"📝","category":"micro-saas","popular":True,"industry":"technology-and-saas","href":"/services/w128-meeting-minutes"},
    {"id":"w128-feedback-analyzer","title":"Customer Feedback Analyzer","description":"NLP-powered analysis of customer reviews, surveys, and support tickets. Identifies trends, sentiment, and actionable insights.","features":["Sentiment analysis","Trend detection","Topic clustering","Survey analysis","Support ticket classification","Executive dashboards"],"benefits":["Understand customers at scale","Identify product issues early","Data-driven decisions","Reduce churn"],"pricing":{"starter":"397","pro":"1297","enterprise":"2497"},"icon":"💬","category":"micro-saas","popular":False,"industry":"retail-and-ecommerce","href":"/services/w128-feedback-analyzer"},
    {"id":"w128-compliance-reporter","title":"Automated Compliance Reporting","description":"SOC 2, HIPAA, GDPR, and PCI-DSS compliance report generation. Continuous monitoring with automated evidence collection.","features":["SOC 2 Type II reports","HIPAA compliance","GDPR data mapping","PCI-DSS assessments","Automated evidence collection","Audit trail"],"benefits":["80% faster audits","Continuous compliance","Reduce audit costs","Avoid penalties"],"pricing":{"starter":"1497","pro":"4997","enterprise":"9997"},"icon":"📋","category":"micro-saas","popular":False,"industry":"legal-and-compliance","href":"/services/w128-compliance-reporter"},
    # Wave 128: IT Services (5)
    {"id":"w128-mdr","title":"Managed Detection & Response (MDR)","description":"24/7 threat monitoring, detection, and response. SOC-as-a-service with AI-powered threat hunting and incident response.","features":["24/7 SOC monitoring","AI threat hunting","Incident response","Threat intelligence","Digital forensics","Vulnerability management"],"benefits":["Reduce breach risk by 75%","24/7 expert monitoring","Faster incident response","Compliance-ready"],"pricing":{"starter":"4997","pro":"14997","enterprise":"29997"},"icon":"🛡️","category":"it-services","popular":True,"industry":"cybersecurity","href":"/services/w128-mdr"},
    {"id":"w128-finops","title":"Cloud Cost Optimization Consulting","description":"FinOps consulting to reduce cloud spend by 30-50%. Reserved instance management, rightsizing, and waste elimination.","features":["Cloud spend analysis","Reserved instance strategy","Rightsizing recommendations","Waste elimination","FinOps training","Monthly optimization"],"benefits":["30-50% cloud cost reduction","Better resource utilization","FinOps culture","Ongoing optimization"],"pricing":{"starter":"2997","pro":"8997","enterprise":"18997"},"icon":"💰","category":"it-services","popular":False,"industry":"cloud-services","href":"/services/w128-finops"},
    {"id":"w128-zero-trust","title":"Zero Trust Network Architecture","description":"Identity-based security with microsegmentation, continuous verification, and least-privilege access across all resources.","features":["Identity-based access","Microsegmentation","Continuous verification","Least-privilege access","Device trust scoring","Encrypted communications"],"benefits":["Eliminate lateral movement","Reduce attack surface","Compliance alignment","Remote work security"],"pricing":{"starter":"7997","pro":"24997","enterprise":"49997"},"icon":"🔐","category":"it-services","popular":False,"industry":"cybersecurity","href":"/services/w128-zero-trust"},
    {"id":"w128-dlp","title":"Data Loss Prevention (DLP)","description":"Comprehensive DLP across endpoints, cloud, email, and network. AI-powered classification and policy enforcement.","features":["Endpoint DLP","Cloud DLP","Email DLP","Network DLP","AI data classification","Policy automation"],"benefits":["Prevent data exfiltration","Regulatory compliance","Insider threat protection","Automated classification"],"pricing":{"starter":"3497","pro":"10997","enterprise":"22997"},"icon":"🔒","category":"it-services","popular":False,"industry":"cybersecurity","href":"/services/w128-dlp"},
    {"id":"w128-it-asset","title":"IT Asset Discovery & Management","description":"Automated network discovery, CMDB management, and IT asset lifecycle tracking. Real-time visibility into all hardware and software assets.","features":["Auto-discovery scanning","CMDB management","Software license tracking","Lifecycle management","Compliance reporting","Integration with ITSM"],"benefits":["100% asset visibility","License compliance","Reduced audit costs","Better procurement decisions"],"pricing":{"starter":"1997","pro":"5997","enterprise":"12997"},"icon":"📡","category":"it-services","popular":False,"industry":"it-infrastructure","href":"/services/w128-it-asset"},
    # Wave 129: AI Services (5)
    {"id":"w129-synthetic-data","title":"AI Synthetic Data Generator","description":"GDPR-compliant synthetic data generation for ML training. Preserves statistical properties without exposing real data.","features":["Tabular data generation","Time series synthesis","Image synthesis","Text generation","Privacy guarantees","Statistical validation"],"benefits":["Unlimited training data","GDPR compliance","Rare edge case generation","Faster ML development"],"pricing":{"starter":"997","pro":"2997","enterprise":"6997"},"icon":"🎲","category":"ai-services","popular":False,"industry":"ai-and-ml","href":"/services/w129-synthetic-data"},
    {"id":"w129-multimodal-search","title":"Multimodal AI Search","description":"Search across text, images, video, and audio with a single query. Powers next-generation enterprise search and discovery.","features":["Text search","Image search","Video search","Audio search","Cross-modal retrieval","Semantic understanding"],"benefits":["Find anything instantly","Unify siloed content","Better knowledge discovery","Improved productivity"],"pricing":{"starter":"2497","pro":"7997","enterprise":"16997"},"icon":"🔍","category":"ai-services","popular":True,"industry":"ai-and-ml","href":"/services/w129-multimodal-search"},
    {"id":"w129-agent-orchestrator","title":"AI Agent Orchestrator","description":"Manage, monitor, and scale autonomous AI agents. Provides guardrails, task routing, and performance analytics for agent fleets.","features":["Agent lifecycle management","Task routing","Performance analytics","Guardrail enforcement","Multi-agent coordination","Audit logging"],"benefits":["Scale AI safely","Monitor agent behavior","Prevent runaway agents","Optimize agent costs"],"pricing":{"starter":"4997","pro":"14997","enterprise":"34997"},"icon":"🤖","category":"ai-services","popular":True,"industry":"ai-and-ml","href":"/services/w129-agent-orchestrator"},
    {"id":"w129-predictive-maintenance","title":"Predictive Maintenance AI","description":"IoT sensor analysis with ML failure prediction. Reduces unplanned downtime by 73% and extends equipment life.","features":["IoT sensor processing","Failure prediction","Anomaly detection","Maintenance scheduling","Root cause analysis","Digital twin integration"],"benefits":["73% less downtime","Extended equipment life","Optimized maintenance costs","Improved safety"],"pricing":{"starter":"3997","pro":"12997","enterprise":"24997"},"icon":"🔧","category":"ai-services","popular":True,"industry":"manufacturing-industrial","href":"/services/w129-predictive-maintenance"},
    {"id":"w129-legal-ai","title":"AI Legal Document Analyzer","description":"Contract review, clause extraction, and risk scoring. Reduces legal review time by 65% with 99%+ accuracy.","features":["Contract review","Clause extraction","Risk scoring","Obligation tracking","Date tracking","Redline suggestions"],"benefits":["65% faster reviews","Never miss deadlines","Consistent quality","Reduce legal costs"],"pricing":{"starter":"1997","pro":"5997","enterprise":"14997"},"icon":"⚖️","category":"ai-services","popular":False,"industry":"legal-and-compliance","href":"/services/w129-legal-ai"},
    # Wave 129: Industry Solutions (5)
    {"id":"w129-healthcare-diagnostics","title":"Healthcare AI Diagnostics Assistant","description":"Medical imaging analysis, clinical decision support, and patient risk stratification. FDA-cleared AI models for radiology, pathology, and cardiology.","features":["Medical imaging AI","Clinical decision support","Risk stratification","EHR integration","HIPAA compliance","FDA-cleared models"],"benefits":["94% diagnostic accuracy","Faster patient care","Reduced physician burnout","Better outcomes"],"pricing":{"starter":"9997","pro":"34997","enterprise":"69997"},"icon":"🏥","category":"healthcare-it","popular":True,"industry":"healthcare-and-life-sciences","href":"/services/w129-healthcare-diagnostics"},
    {"id":"w129-fintech-fraud","title":"FinTech Fraud Detection Engine","description":"Real-time transaction monitoring with behavioral analytics and anomaly detection. Processes 1M+ transactions per second.","features":["Real-time monitoring","Behavioral analytics","Anomaly detection","AML compliance","Chargeback prevention","Multi-bank support"],"benefits":["94% fraud detection","<50ms latency","AML compliance","Reduced chargebacks"],"pricing":{"starter":"7997","pro":"24997","enterprise":"49997"},"icon":"💳","category":"fintech","popular":True,"industry":"financial-services","href":"/services/w129-fintech-fraud"},
    {"id":"w129-retail-personalization","title":"Smart Retail Personalization Platform","description":"Real-time product recommendations, dynamic pricing, and inventory optimization. Omnichannel personalization across web, mobile, and in-store.","features":["Product recommendations","Dynamic pricing","Inventory optimization","Customer segmentation","A/B testing","Omnichannel personalization"],"benefits":["340% conversion lift","28% higher AOV","62% less abandonment","Real-time optimization"],"pricing":{"starter":"4997","pro":"14997","enterprise":"32997"},"icon":"🛒","category":"retail-tech","popular":True,"industry":"retail-and-ecommerce","href":"/services/w129-retail-personalization"},
    {"id":"w129-digital-twin","title":"Manufacturing Digital Twin Platform","description":"Process simulation, optimization, and what-if analysis. Reduces operational costs by 25% through predictive modeling.","features":["Process simulation","Optimization engine","What-if analysis","Real-time monitoring","Predictive modeling","Energy optimization"],"benefits":["25% cost reduction","Improved throughput","Energy savings","Risk-free experimentation"],"pricing":{"starter":"12997","pro":"44997","enterprise":"89997"},"icon":"🏭","category":"manufacturing-tech","popular":False,"industry":"manufacturing-industrial","href":"/services/w129-digital-twin"},
    {"id":"w129-edtech-adaptive","title":"EdTech Adaptive Learning Engine","description":"Personalized curricula, progress tracking, and assessments. Adapts to each student's learning style and pace.","features":["Personalized curricula","Progress tracking","Adaptive assessments","Learning analytics","Gamification","LMS integration"],"benefits":["40% better outcomes","Personalized learning","Reduced dropout","Teacher insights"],"pricing":{"starter":"3997","pro":"12997","enterprise":"24997"},"icon":"🎓","category":"edtech","popular":False,"industry":"education-and-research","href":"/services/w129-edtech-adaptive"},
]

def main():
    with open(DATA_FILE, 'r') as f:
        data = json.load(f)
    
    existing_ids = {s['id'] for s in data}
    added = 0
    skipped = 0
    
    for svc in SERVICES:
        if svc['id'] in existing_ids:
            skipped += 1
            continue
        # Add contact info
        svc['contactInfo'] = {
            'website': f"https://ziontechgroup.com{svc['href']}",
            'email': 'kleber@ziontechgroup.com',
            'phone': '+1 302 464 0950'
        }
        data.append(svc)
        added += 1
    
    with open(DATA_FILE, 'w') as f:
        json.dump(data, f, indent=2)
    
    print(f"✅ Added {added} services, skipped {skipped} (already exist)")
    print(f"📊 Total services: {len(data)}")

if __name__ == "__main__":
    main()
