const fs = require('fs');
const services = JSON.parse(fs.readFileSync('app/data/servicesData.json', 'utf8'));
const newServices = [
  // V209-V213 Email Intelligence companion services
  {id:'ai-email-translation-hub-v209',title:'AI Email Translation Hub (V209)',description:'Real-time translation of emails into 40+ languages with cultural context adaptation, formality level matching, and terminology consistency.',icon:'🌍',features:['40+ language translation','Cultural context adaptation','Formality level matching','Terminology consistency','Language auto-detection','Regional dialect support','Glossary management','Reply-all enforcement'],benefits:['Communicate globally without barriers','Maintain cultural sensitivity','Ensure consistent terminology','Auto-detect source language'],pricing:{basic:'299',pro:'699',enterprise:'1799'},contactInfo:{website:'/services/ai-email-translation-hub-v209',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-email-translation-hub-v209',category:'ai',popular:true,industry:'Global Communication'},
  
  {id:'ai-email-revenue-attribution-v210',title:'AI Email Revenue Attribution (V210)',description:'Track how email conversations drive revenue with pipeline attribution, deal influence scoring, and ROI dashboards.',icon:'💰',features:['Pipeline touchpoint detection','Deal influence scoring','5 attribution models','Revenue ROI dashboards','Engagement signal analysis','Deal value extraction','Position-based attribution','Reply-all enforcement'],benefits:['Quantify email revenue impact','Track deal influence accurately','Optimize sales email strategy','Prove email ROI to stakeholders'],pricing:{basic:'499',pro:'1099',enterprise:'2999'},contactInfo:{website:'/services/ai-email-revenue-attribution-v210',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-email-revenue-attribution-v210',category:'ai',popular:true,industry:'Revenue Operations'},
  
  {id:'ai-email-disaster-recovery-v211',title:'AI Email Disaster Recovery (V211)',description:'Automated backup, corruption detection, and recovery of critical email data with point-in-time restore and integrity verification.',icon:'🔄',features:['Automated email backup','Corruption detection','Point-in-time restore','Integrity verification','Deduplication','Compression optimization','Recovery point management','Health scoring'],benefits:['Never lose critical email data','Detect corruption automatically','Restore to any point in time','99.99% data integrity'],pricing:{basic:'199',pro:'449',enterprise:'1099'},contactInfo:{website:'/services/ai-email-disaster-recovery-v211',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-email-disaster-recovery-v211',category:'ai',popular:true,industry:'Data Protection'},
  
  {id:'ai-email-gamification-v212',title:'AI Email Gamification Platform (V212)',description:'Gamify email responsiveness with leaderboards, badges, streaks, and team performance metrics to boost engagement.',icon:'🏆',features:['Leaderboards & rankings','10+ achievement badges','Streak tracking','Level progression','Team competitions','Response time scoring','Quality metrics','Reply-all enforcement'],benefits:['Boost team email productivity 3x','Improve response times','Gamify quality standards','Track team performance'],pricing:{basic:'149',pro:'349',enterprise:'799'},contactInfo:{website:'/services/ai-email-gamification-v212',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-email-gamification-v212',category:'ai',popular:true,industry:'Team Productivity'},
  
  {id:'ai-email-competitive-intel-v213',title:'AI Email Competitive Intelligence (V213)',description:'Detect competitor mentions, pricing comparisons, and switch risks in customer emails with battle cards and win/loss analysis.',icon:'🎯',features:['Competitor mention detection','Switch risk analysis','Competitive battle cards','Win/loss analysis','Pain point extraction','Risk scoring','Recommended actions','Reply-all enforcement'],benefits:['Detect churn risks early','Build winning battle cards','Track competitive landscape','Prevent customer switching'],pricing:{basic:'399',pro:'899',enterprise:'2299'},contactInfo:{website:'/services/ai-email-competitive-intel-v213',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-email-competitive-intel-v213',category:'ai',popular:true,industry:'Competitive Intelligence'},
  
  {id:'ai-email-mega-suite-v209-v213',title:'AI Email Intelligence Mega Suite (V209-V213)',description:'All 5 new email intelligence engines unified: Translation Hub, Revenue Attribution, Disaster Recovery, Gamification, and Competitive Intel.',icon:'👑',features:['V209: Translation Hub (40+ languages)','V210: Revenue Attribution','V211: Disaster Recovery','V212: Gamification Platform','V213: Competitive Intelligence','Case-by-case analysis','Reply-all guaranteed','Enterprise security'],benefits:['Complete email intelligence suite','1500% average ROI','Zero data loss guarantee','The definitive email AI platform'],pricing:{basic:'1299',pro:'2999',enterprise:'7999'},contactInfo:{website:'/services/ai-email-mega-suite-v209-v213',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-email-mega-suite-v209-v213',category:'ai',popular:true,industry:'Enterprise AI'},

  // AI Services
  {id:'ai-video-conference-intelligence',title:'AI Video Conference Intelligence',description:'Auto-generate meeting summaries, extract action items, and analyze participant engagement from Zoom, Teams, and Meet recordings.',icon:'📹',features:['Auto-transcription (98% accuracy)','Speaker diarization','Action item extraction','Engagement scoring','Meeting summaries','Sentiment analysis','Follow-up generation','Calendar integration'],benefits:['Never miss a meeting insight','Track engagement automatically','Generate perfect summaries','Extract every action item'],pricing:{basic:'199',pro:'449',enterprise:'1099'},contactInfo:{website:'/services/ai-video-conference-intelligence',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-video-conference-intelligence',category:'ai',popular:true,industry:'Meeting Intelligence'},
  
  {id:'ai-supply-chain-optimizer',title:'AI Supply Chain Optimizer',description:'Optimize supply chain operations with demand forecasting, inventory optimization, supplier risk assessment, and logistics planning.',icon:'🚛',features:['Demand forecasting','Inventory optimization','Supplier risk scoring','Route optimization','Cost reduction analysis','Lead time prediction','Disruption alerts','Scenario planning'],benefits:['Reduce inventory costs 25%','Improve forecast accuracy 40%','Optimize logistics routes','Prevent supply disruptions'],pricing:{basic:'699',pro:'1499',enterprise:'3999'},contactInfo:{website:'/services/ai-supply-chain-optimizer',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-supply-chain-optimizer',category:'ai',popular:true,industry:'Supply Chain'},
  
  {id:'ai-fraud-detection-platform',title:'AI Fraud Detection Platform',description:'Real-time fraud detection with ML models, anomaly detection, behavioral biometrics, and automated case management for financial transactions.',icon:'🔍',features:['Real-time transaction monitoring','ML fraud models','Anomaly detection','Behavioral biometrics','Case management','Alert prioritization','Regulatory reporting','Model retraining'],benefits:['Detect fraud in milliseconds','Reduce false positives 60%','Automate case management','Meet compliance requirements'],pricing:{basic:'999',pro:'2499',enterprise:'5999'},contactInfo:{website:'/services/ai-fraud-detection-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-fraud-detection-platform',category:'ai',popular:true,industry:'Financial Services'},
  
  {id:'ai-code-review-assistant',title:'AI Code Review Assistant',description:'Automated code review with security scanning, performance analysis, best practice enforcement, and AI-powered suggestions for improvements.',icon:'💻',features:['Security vulnerability scanning','Performance bottleneck detection','Code smell identification','Best practice enforcement','AI improvement suggestions','PR review automation','Documentation generation','Test coverage analysis'],benefits:['Review code 10x faster','Catch security issues early','Enforce coding standards','Improve code quality'],pricing:{basic:'149',pro:'349',enterprise:'799'},contactInfo:{website:'/services/ai-code-review-assistant',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-code-review-assistant',category:'ai',popular:true,industry:'Software Development'},
  
  {id:'ai-legal-document-drafting',title:'AI Legal Document Drafting',description:'Draft contracts, NDAs, MSAs, and policies with AI assistance. Template library, clause suggestions, risk analysis, and compliance checking.',icon:'📋',features:['AI-powered drafting','Template library (200+)','Clause suggestions','Risk analysis','Compliance checking','Version control','Collaboration tools','E-signature integration'],benefits:['Draft documents 5x faster','Reduce legal review time','Ensure compliance','Minimize contract risks'],pricing:{basic:'399',pro:'899',enterprise:'2299'},contactInfo:{website:'/services/ai-legal-document-drafting',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-legal-document-drafting',category:'ai',popular:true,industry:'Legal Tech'},

  // IT Services
  {id:'it-kubernetes-management-platform',title:'Kubernetes Management Platform',description:'Enterprise Kubernetes management with multi-cluster orchestration, cost optimization, security hardening, and observability.',icon:'☸️',features:['Multi-cluster management','Cost optimization','Security hardening','Observability stack','GitOps workflows','Service mesh integration','Backup & disaster recovery','Compliance automation'],benefits:['Manage K8s at scale','Reduce cloud costs 30%','Harden security posture','Full observability'],pricing:{basic:'499',pro:'1099',enterprise:'2999'},contactInfo:{website:'/services/it-kubernetes-management-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/it-kubernetes-management-platform',category:'it',popular:true,industry:'Cloud Native'},
  
  {id:'it-edge-computing-platform',title:'Edge Computing Platform',description:'Deploy and manage edge workloads with low-latency processing, offline sync, and centralized management for IoT and real-time applications.',icon:'📡',features:['Edge workload deployment','Low-latency processing','Offline synchronization','Centralized management','Container orchestration','Security enforcement','Monitoring & alerting','OTA updates'],benefits:['Process data at the edge','Reduce latency to milliseconds','Operate offline reliably','Manage thousands of nodes'],pricing:{basic:'399',pro:'899',enterprise:'2299'},contactInfo:{website:'/services/it-edge-computing-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/it-edge-computing-platform',category:'it',popular:true,industry:'Edge Computing'},
  
  {id:'it-database-performance-tuning',title:'Database Performance Tuning',description:'Automated database performance optimization with query analysis, index recommendations, connection pooling, and predictive scaling.',icon:'🗄️',features:['Query performance analysis','Index recommendations','Connection pooling','Predictive scaling','Slow query detection','Deadlock analysis','Cache optimization','Replication monitoring'],benefits:['Improve query speed 5x','Reduce database costs 40%','Prevent performance issues','Scale automatically'],pricing:{basic:'299',pro:'699',enterprise:'1799'},contactInfo:{website:'/services/it-database-performance-tuning',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/it-database-performance-tuning',category:'it',popular:true,industry:'Database Management'},
  
  {id:'it-network-observability',title:'Network Observability Platform',description:'Deep network visibility with flow analysis, packet inspection, latency monitoring, and anomaly detection across hybrid infrastructure.',icon:'🌐',features:['Network flow analysis','Deep packet inspection','Latency monitoring','Anomaly detection','Topology mapping','Bandwidth optimization','Security monitoring','Compliance reporting'],benefits:['See entire network topology','Detect issues before outages','Optimize bandwidth usage','Secure network traffic'],pricing:{basic:'399',pro:'899',enterprise:'2299'},contactInfo:{website:'/services/it-network-observability',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/it-network-observability',category:'it',popular:true,industry:'Network Operations'},

  // Security Services
  {id:'security-cloud-posture-management',title:'Cloud Security Posture Management (CSPM)',description:'Continuous cloud security monitoring with misconfiguration detection, compliance benchmarking, and automated remediation across AWS, Azure, GCP.',icon:'☁️',features:['Multi-cloud monitoring','Misconfiguration detection','CIS benchmark compliance','Automated remediation','Risk prioritization','Compliance reporting','Asset inventory','Threat detection'],benefits:['Secure multi-cloud environments','Detect misconfigurations instantly','Meet compliance requirements','Automate remediation'],pricing:{basic:'499',pro:'1099',enterprise:'2999'},contactInfo:{website:'/services/security-cloud-posture-management',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/security-cloud-posture-management',category:'security',popular:true,industry:'Cloud Security'},
  
  {id:'security-api-security-platform',title:'API Security Platform',description:'Protect APIs with discovery, testing, monitoring, and runtime protection. Detect OWASP API vulnerabilities and prevent data exfiltration.',icon:'🔌',features:['API discovery & inventory','OWASP API security testing','Runtime protection','Rate limiting','Authentication enforcement','Data exfiltration prevention','API analytics','Compliance monitoring'],benefits:['Discover shadow APIs','Test for OWASP vulnerabilities','Protect APIs in runtime','Prevent data breaches'],pricing:{basic:'399',pro:'899',enterprise:'2299'},contactInfo:{website:'/services/security-api-security-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/security-api-security-platform',category:'security',popular:true,industry:'API Security'},
  
  {id:'security-threat-intelligence-platform',title:'Threat Intelligence Platform',description:'Aggregate, analyze, and operationalize threat intelligence from multiple sources with automated IOC enrichment and hunting.',icon:'🕵️',features:['Multi-source intelligence','IOC enrichment','Threat hunting','Automated correlation','Risk scoring','Integration with SIEM','Campaign tracking','Dark web monitoring'],benefits:['Stay ahead of threats','Automate IOC enrichment','Hunt threats proactively','Correlate intelligence'],pricing:{basic:'599',pro:'1299',enterprise:'3499'},contactInfo:{website:'/services/security-threat-intelligence-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/security-threat-intelligence-platform',category:'security',popular:true,industry:'Threat Intelligence'},

  // Data Services
  {id:'data-feature-store-platform',title:'ML Feature Store Platform',description:'Centralized feature management for ML with real-time serving, batch computation, feature sharing, and monitoring for production ML systems.',icon:'🧮',features:['Feature registry','Real-time serving','Batch computation','Feature sharing','Version control','Monitoring & alerting','Integration with MLflow/Kubeflow','Data quality checks'],benefits:['Reuse features across models','Serve features in milliseconds','Share features across teams','Monitor feature drift'],pricing:{basic:'399',pro:'899',enterprise:'2299'},contactInfo:{website:'/services/data-feature-store-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/data-feature-store-platform',category:'data',popular:true,industry:'MLOps'},
  
  {id:'data-data-mesh-platform',title:'Data Mesh Platform',description:'Implement data mesh architecture with domain-oriented data products, self-serve infrastructure, and federated governance.',icon:'🕸️',features:['Domain data products','Self-serve platform','Federated governance','Data product catalog','Quality SLAs','Interoperability standards','Observability','Cost allocation'],benefits:['Scale data ownership','Enable self-service analytics','Federate governance','Treat data as product'],pricing:{basic:'599',pro:'1299',enterprise:'3499'},contactInfo:{website:'/services/data-data-mesh-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/data-data-mesh-platform',category:'data',popular:true,industry:'Data Architecture'},

  // Micro-SaaS Services
  {id:'micro-saas-changelog-management',title:'Changelog & Release Notes Platform',description:'Automate changelog generation, publish release notes, notify users, and track feature adoption with a beautiful public changelog.',icon:'📝',features:['Auto changelog generation','Public changelog page','User notifications','Feature adoption tracking','Segmented announcements','Custom branding','RSS feed','API integration'],benefits:['Automate release notes','Keep users informed','Track feature adoption','Beautiful public page'],pricing:{basic:'49',pro:'129',enterprise:'299'},contactInfo:{website:'/services/micro-saas-changelog-management',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-changelog-management',category:'micro-saas',popular:true,industry:'Product Communication'},
  
  {id:'micro-saas-uptime-monitoring',title:'Uptime Monitoring & Alerting',description:'Monitor websites, APIs, and services from 100+ global locations with instant alerts, status pages, and SLA tracking.',icon:'📊',features:['100+ monitoring locations','Multi-protocol checks','Instant alerts (SMS/email/Slack)','Status pages','SLA tracking','Performance monitoring','SSL monitoring','Incident management'],benefits:['Detect outages instantly','Monitor from anywhere','Beautiful status pages','Track SLA compliance'],pricing:{basic:'29',pro:'79',enterprise:'199'},contactInfo:{website:'/services/micro-saas-uptime-monitoring',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-uptime-monitoring',category:'micro-saas',popular:true,industry:'Monitoring'},
  
  {id:'micro-saas-ab-testing-platform',title:'A/B Testing & Experimentation Platform',description:'Run A/B tests and experiments with statistical significance, feature flags, user segmentation, and detailed analytics.',icon:'🧪',features:['Visual experiment builder','Statistical significance','Feature flags','User segmentation','Multi-variate testing','Conversion tracking','Revenue attribution','Bayesian analysis'],benefits:['Make data-driven decisions','Test everything safely','Segment users precisely','Prove ROI statistically'],pricing:{basic:'99',pro:'249',enterprise:'599'},contactInfo:{website:'/services/micro-saas-ab-testing-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-ab-testing-platform',category:'micro-saas',popular:true,industry:'Product Analytics'},
  
  {id:'micro-saas-document-signing',title:'Electronic Document Signing',description:'Secure e-signature platform with workflow automation, template management, compliance (ESIGN/UETA/eIDAS), and audit trails.',icon:'✍️',features:['Legally binding e-signatures','Workflow automation','Template management','Compliance (ESIGN/UETA/eIDAS)','Audit trails','Bulk sending','API integration','Custom branding'],benefits:['Sign documents 10x faster','Automate approval workflows','Meet compliance requirements','Full audit trail'],pricing:{basic:'29',pro:'79',enterprise:'199'},contactInfo:{website:'/services/micro-saas-document-signing',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-document-signing',category:'micro-saas',popular:true,industry:'Document Management'},
  
  {id:'micro-saas-team-scheduling',title:'Team Scheduling & Calendar Platform',description:'Smart scheduling for teams with availability matching, timezone handling, buffer management, and meeting room booking.',icon:'📅',features:['Smart availability matching','Timezone handling','Buffer management','Meeting room booking','Recurring meetings','Calendar sync (Google/Outlook)','No-show tracking','Meeting analytics'],benefits:['Schedule meetings 5x faster','Eliminate timezone confusion','Optimize meeting rooms','Track meeting effectiveness'],pricing:{basic:'19',pro:'49',enterprise:'129'},contactInfo:{website:'/services/micro-saas-team-scheduling',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-team-scheduling',category:'micro-saas',popular:true,industry:'Team Productivity'},
  
  {id:'micro-saas-error-tracking',title:'Error Tracking & Crash Reporting',description:'Real-time error tracking with stack traces, user context, release tracking, and automatic alerting for web and mobile applications.',icon:'🐛',features:['Real-time error tracking','Full stack traces','User context capture','Release tracking','Alert rules','Error grouping','Performance monitoring','Source map support'],benefits:['Catch errors instantly','Debug with full context','Track errors per release','Alert the right team'],pricing:{basic:'49',pro:'129',enterprise:'349'},contactInfo:{website:'/services/micro-saas-error-tracking',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-error-tracking',category:'micro-saas',popular:true,industry:'Application Monitoring'},
  
  {id:'micro-saas-knowledge-base-builder',title:'Knowledge Base & Help Center Builder',description:'Build beautiful help centers with AI-powered search, article analytics, feedback collection, and multi-language support.',icon:'📚',features:['Beautiful help center','AI-powered search','Article analytics','Feedback collection','Multi-language support','Version history','SEO optimization','Custom domains'],benefits:['Reduce support tickets 40%','Beautiful documentation','AI-powered search','Track article performance'],pricing:{basic:'39',pro:'99',enterprise:'249'},contactInfo:{website:'/services/micro-saas-knowledge-base-builder',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-knowledge-base-builder',category:'micro-saas',popular:true,industry:'Customer Support'},
];

const existing = new Set(services.map(s => s.id));
const toAdd = newServices.filter(s => !existing.has(s.id));
services.push(...toAdd);
fs.writeFileSync('app/data/servicesData.json', JSON.stringify(services, null, 2));
console.log('Added', toAdd.length, 'new services. Total:', services.length);
