const fs = require('fs');
const services = JSON.parse(fs.readFileSync('app/data/servicesData.json', 'utf8'));
const newServices = [
  // V221-V225 companion services
  {id:'ai-thread-summarizer-pro-v221',title:'AI Thread Summarizer Pro (V221)',description:'Executive summaries of long email threads with key decisions, action items, open questions, and sentiment overview.',icon:'📝',features:['Executive summary generation','Key decision extraction','Action item tracking','Open question detection','Sentiment overview','Participant analysis','Date range tracking','Reply-all enforcement'],benefits:['Catch up on threads in 30 seconds','Never miss a decision','Track all action items','Understand thread sentiment'],pricing:{basic:'199',pro:'449',enterprise:'999'},contactInfo:{website:'/services/ai-thread-summarizer-pro-v221',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-thread-summarizer-pro-v221',category:'ai',popular:true,industry:'Productivity'},
  
  {id:'ai-compliance-auto-checker-v222',title:'AI Compliance Auto-Checker (V222)',description:'Check emails against GDPR, HIPAA, SOC2, PCI-DSS with PII detection, consent verification, and data retention compliance.',icon:'🔒',features:['GDPR compliance checking','HIPAA PHI detection','SOC2 secret scanning','PCI-DSS card data detection','PII auto-detection (6 types)','Risk scoring','Remediation recommendations','Reply-all enforcement'],benefits:['Prevent compliance violations','Detect PII before sending','Meet GDPR/HIPAA requirements','Reduce legal risk'],pricing:{basic:'399',pro:'899',enterprise:'2299'},contactInfo:{website:'/services/ai-compliance-auto-checker-v222',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-compliance-auto-checker-v222',category:'security',popular:true,industry:'Compliance'},
  
  {id:'ai-tone-adapter-v223',title:'AI Email Tone Adapter (V223)',description:'Automatically adjust email tone based on recipient relationship, urgency, and cultural context with real-time suggestions.',icon:'🎨',features:['5 recipient profiles','Formality level adaptation','Directness adjustment','Urgency calibration','Cultural tone matching','Real-time suggestions','Tone fit scoring','Reply-all enforcement'],benefits:['Perfect tone every time','Adapt to any recipient','Avoid tone missteps','Improve communication effectiveness'],pricing:{basic:'149',pro:'349',enterprise:'799'},contactInfo:{website:'/services/ai-tone-adapter-v223',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-tone-adapter-v223',category:'ai',popular:true,industry:'Communication'},
  
  {id:'ai-meeting-scheduler-v224',title:'AI Meeting Scheduler Intelligence (V224)',description:'Detect scheduling intent, propose optimal times across timezones, generate calendar invites, and send preparation reminders.',icon:'📅',features:['Scheduling intent detection','Timezone-aware proposals','Duration optimization','Meeting type classification','Calendar invite generation','Agenda suggestions','Conflict detection','Reply-all enforcement'],benefits:['Schedule meetings 10x faster','Eliminate timezone confusion','Optimal meeting duration','Never double-book'],pricing:{basic:'149',pro:'349',enterprise:'799'},contactInfo:{website:'/services/ai-meeting-scheduler-v224',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-meeting-scheduler-v224',category:'ai',popular:true,industry:'Productivity'},
  
  {id:'ai-attachment-intelligence-v225',title:'AI Attachment Intelligence (V225)',description:'Scan attachments for sensitive data, detect malware risks, generate summaries, and suggest cloud storage alternatives.',icon:'📎',features:['Malware risk detection','Sensitive data scanning','File size optimization','Cloud alternative suggestions','PII detection in files','Risk level assessment','File type analysis','Reply-all enforcement'],benefits:['Prevent malware attacks','Detect sensitive data leaks','Reduce email size 60%','Secure file sharing'],pricing:{basic:'199',pro:'449',enterprise:'1099'},contactInfo:{website:'/services/ai-attachment-intelligence-v225',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-attachment-intelligence-v225',category:'security',popular:true,industry:'Email Security'},
  
  {id:'ai-email-complete-suite-v221-v225',title:'AI Email Complete Suite (V221-V225)',description:'All 5 new engines: Thread Summarizer, Compliance Checker, Tone Adapter, Meeting Scheduler, and Attachment Intelligence.',icon:'👑',features:['V221 Thread Summarizer Pro','V222 Compliance Auto-Checker','V223 Tone Adapter','V224 Meeting Scheduler','V225 Attachment Intelligence','Case-by-case analysis','Reply-all guaranteed','Enterprise compliance'],benefits:['Complete email AI suite','Compliance guaranteed','Perfect tone always','Maximum productivity'],pricing:{basic:'999',pro:'2299',enterprise:'5999'},contactInfo:{website:'/services/ai-email-complete-suite-v221-v225',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-email-complete-suite-v221-v225',category:'ai',popular:true,industry:'Enterprise AI'},

  // AI Services
  {id:'ai-digital-twin-platform',title:'AI Digital Twin Platform',description:'Create virtual replicas of physical systems for simulation, optimization, and predictive maintenance across manufacturing, energy, and logistics.',icon:'🏭',features:['3D digital twin modeling','Real-time sensor sync','Predictive simulation','What-if scenario analysis','Performance optimization','Anomaly detection','Energy consumption modeling','IoT integration'],benefits:['Simulate before building','Optimize operations 30%','Predict failures accurately','Reduce downtime 50%'],pricing:{basic:'799',pro:'1699',enterprise:'4499'},contactInfo:{website:'/services/ai-digital-twin-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-digital-twin-platform',category:'ai',popular:true,industry:'Industrial AI'},
  
  {id:'ai-workforce-planning',title:'AI Workforce Planning & Optimization',description:'Predict staffing needs, optimize schedules, forecast attrition, and align workforce capacity with business demand using ML.',icon:'👥',features:['Demand forecasting','Schedule optimization','Attrition prediction','Skills gap analysis','Capacity planning','Scenario modeling','Cost optimization','Integration with HRIS'],benefits:['Right-size workforce','Reduce overtime 25%','Predict attrition early','Optimize labor costs'],pricing:{basic:'399',pro:'899',enterprise:'2299'},contactInfo:{website:'/services/ai-workforce-planning',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-workforce-planning',category:'ai',popular:true,industry:'HR Technology'},
  
  {id:'ai-content-moderation-suite',title:'AI Content Moderation Suite',description:'Automated content moderation for UGC, social media, and marketplaces with multi-language support and custom policy enforcement.',icon:'🛡️',features:['Text moderation (toxicity/hate/spam)','Image moderation (NSFW/violence)','Video moderation','Custom policy engine','Multi-language (40+)','Appeals workflow','Moderator dashboard','Real-time filtering'],benefits:['Moderate content at scale','Reduce manual review 80%','Enforce custom policies','Protect brand safety'],pricing:{basic:'299',pro:'699',enterprise:'1799'},contactInfo:{website:'/services/ai-content-moderation-suite',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-content-moderation-suite',category:'ai',popular:true,industry:'Trust & Safety'},
  
  {id:'ai-pricing-optimization',title:'AI Dynamic Pricing Optimization',description:'Real-time pricing optimization using demand signals, competitor monitoring, elasticity modeling, and revenue maximization.',icon:'💲',features:['Dynamic pricing engine','Competitor price monitoring','Price elasticity modeling','Demand forecasting','Revenue optimization','A/B testing','Margin protection','Multi-channel pricing'],benefits:['Increase revenue 15-25%','Optimize margins automatically','React to market changes','Outprice competitors'],pricing:{basic:'499',pro:'1099',enterprise:'2999'},contactInfo:{website:'/services/ai-pricing-optimization',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-pricing-optimization',category:'ai',popular:true,industry:'Revenue Optimization'},
  
  {id:'ai-customer-journey-orchestration',title:'AI Customer Journey Orchestration',description:'Orchestrate personalized customer journeys across all touchpoints with real-time decisioning, next-best-action, and journey analytics.',icon:'🗺️',features:['Journey mapping','Real-time decisioning','Next-best-action engine','Cross-channel orchestration','Journey analytics','A/B testing','Segmentation','Personalization at scale'],benefits:['Personalize every interaction','Increase conversion 40%','Reduce churn 25%','Orchestrate across channels'],benefits:['Personalize every touchpoint','Increase conversion 40%','Reduce churn 25%','Orchestrate cross-channel'],pricing:{basic:'599',pro:'1299',enterprise:'3499'},contactInfo:{website:'/services/ai-customer-journey-orchestration',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-customer-journey-orchestration',category:'ai',popular:true,industry:'Customer Experience'},

  // IT Services
  {id:'it-service-mesh-platform',title:'Service Mesh Platform',description:'Deploy and manage service mesh with traffic management, security policies, observability, and multi-cluster support.',icon:'🕸️',features:['Traffic management','mTLS encryption','Circuit breaking','Rate limiting','Distributed tracing','Canary deployments','Multi-cluster mesh','Policy enforcement'],benefits:['Secure microservice communication','Zero-trust networking','Observe all traffic','Deploy safely'],pricing:{basic:'399',pro:'899',enterprise:'2299'},contactInfo:{website:'/services/it-service-mesh-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/it-service-mesh-platform',category:'it',popular:true,industry:'Cloud Native'},
  
  {id:'it-serverless-platform',title:'Serverless Computing Platform',description:'Deploy functions and applications without managing infrastructure. Auto-scaling, event-driven, and pay-per-use.',icon:'⚡',features:['Function-as-a-Service','Event-driven architecture','Auto-scaling','Multi-runtime support','Cold start optimization','Monitoring & logging','Cost optimization','CI/CD integration'],benefits:['Zero infrastructure management','Scale to zero','Pay only for usage','Deploy in seconds'],pricing:{basic:'99',pro:'299',enterprise:'799'},contactInfo:{website:'/services/it-serverless-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/it-serverless-platform',category:'it',popular:true,industry:'Cloud Computing'},
  
  {id:'it-api-monetization',title:'API Monetization & Developer Portal',description:'Monetize APIs with usage-based billing, developer portal, API marketplace, and analytics for API-as-a-product businesses.',icon:'💰',features:['Usage-based billing','Developer portal','API marketplace','Analytics dashboard','Rate limiting','Developer onboarding','Revenue tracking','Self-service provisioning'],benefits:['Turn APIs into revenue','Attract developers','Track API economics','Scale API business'],pricing:{basic:'299',pro:'699',enterprise:'1799'},contactInfo:{website:'/services/it-api-monetization',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/it-api-monetization',category:'it',popular:true,industry:'API Economy'},

  // Security
  {id:'security-ransomware-protection',title:'Ransomware Protection Platform',description:'Multi-layer ransomware protection with behavioral detection, file integrity monitoring, automated rollback, and threat intelligence.',icon:'🔐',features:['Behavioral detection','File integrity monitoring','Automated rollback','Threat intelligence','Network segmentation','Backup protection','Endpoint isolation','Incident response'],benefits:['Prevent ransomware attacks','Auto-rollback encrypted files','Protect backups','Minimize blast radius'],pricing:{basic:'599',pro:'1299',enterprise:'3499'},contactInfo:{website:'/services/security-ransomware-protection',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/security-ransomware-protection',category:'security',popular:true,industry:'Cybersecurity'},
  
  {id:'security-browser-isolation',title:'Browser Isolation Platform',description:'Isolate web browsing in secure containers to prevent malware, phishing, and data exfiltration from reaching endpoints.',icon:'🌐',features:['Remote browser isolation','Container-based isolation','Phishing protection','Malware prevention','Data loss prevention','Policy enforcement','Session recording','Zero-trust browsing'],benefits:['Eliminate browser-based attacks','Prevent phishing','Stop data exfiltration','Zero-trust web access'],pricing:{basic:'199',pro:'449',enterprise:'1099'},contactInfo:{website:'/services/security-browser-isolation',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/security-browser-isolation',category:'security',popular:true,industry:'Endpoint Security'},

  // Data
  {id:'data-lakehouse-platform',title:'Data Lakehouse Platform',description:'Unified data lakehouse combining data lake flexibility with data warehouse performance. ACID transactions, schema enforcement, time travel.',icon:'🏗️',features:['ACID transactions','Schema enforcement','Time travel queries','Unified batch/streaming','Data versioning','Query optimization','Multi-engine support','Governance integration'],benefits:['One platform for all data','ACID reliability','Query historical data','Optimize query performance'],pricing:{basic:'499',pro:'1099',enterprise:'2999'},contactInfo:{website:'/services/data-lakehouse-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/data-lakehouse-platform',category:'data',popular:true,industry:'Data Architecture'},
  
  {id:'data-mlops-platform',title:'MLOps Platform',description:'End-to-end ML lifecycle management with experiment tracking, model registry, automated retraining, and deployment pipelines.',icon:'🧪',features:['Experiment tracking','Model registry','Automated retraining','Deployment pipelines','Model monitoring','A/B testing','Feature store integration','Drift detection'],benefits:['Ship ML models faster','Track all experiments','Automate retraining','Monitor model performance'],pricing:{basic:'399',pro:'899',enterprise:'2299'},contactInfo:{website:'/services/data-mlops-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/data-mlops-platform',category:'data',popular:true,industry:'MLOps'},

  // Micro-SaaS
  {id:'micro-saas-crm-lightweight',title:'Lightweight CRM for Startups',description:'Simple, fast CRM designed for startups and small teams. Pipeline management, contact tracking, email integration, and deal analytics.',icon:'🎯',features:['Pipeline management','Contact tracking','Email integration','Deal analytics','Task management','Team collaboration','Mobile app','API access'],benefits:['Simple and fast','Designed for startups','Track every deal','Collaborate easily'],pricing:{basic:'19',pro:'49',enterprise:'99'},contactInfo:{website:'/services/micro-saas-crm-lightweight',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-crm-lightweight',category:'micro-saas',popular:true,industry:'Sales'},
  
  {id:'micro-saas-form-builder',title:'Smart Form Builder & Analytics',description:'Build beautiful forms with conditional logic, file uploads, payment collection, and conversion analytics. GDPR compliant.',icon:'📋',features:['Drag-and-drop builder','Conditional logic','File uploads','Payment collection','Conversion analytics','GDPR compliance','Webhook integrations','Custom branding'],benefits:['Build forms in minutes','Increase conversions','Collect payments','GDPR compliant'],pricing:{basic:'19',pro:'49',enterprise:'129'},contactInfo:{website:'/services/micro-saas-form-builder',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-form-builder',category:'micro-saas',popular:true,industry:'Forms & Surveys'},
  
  {id:'micro-saas-link-shortener',title:'Link Shortener & Analytics',description:'Shorten links with custom domains, UTM tracking, QR codes, and detailed click analytics. Enterprise-grade reliability.',icon:'🔗',features:['Custom short domains','UTM tracking','QR code generation','Click analytics','Geographic data','Device detection','A/B testing','API access'],benefits:['Track every click','Custom branding','QR codes included','Detailed analytics'],pricing:{basic:'9',pro:'29',enterprise:'79'},contactInfo:{website:'/services/micro-saas-link-shortener',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-link-shortener',category:'micro-saas',popular:true,industry:'Marketing'},
  
  {id:'micro-saas-time-tracking',title:'Time Tracking & Invoicing',description:'Track time across projects, generate invoices automatically, and manage team productivity with beautiful reports.',icon:'⏱️',features:['Time tracking','Project management','Auto-invoicing','Team management','Productivity reports','Integrations','Mobile app','Client portal'],benefits:['Track time effortlessly','Invoice automatically','Manage projects','Boost productivity'],pricing:{basic:'9',pro:'29',enterprise:'69'},contactInfo:{website:'/services/micro-saas-time-tracking',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-time-tracking',category:'micro-saas',popular:true,industry:'Productivity'},
  
  {id:'micro-saas-social-proof',title:'Social Proof & Testimonials Widget',description:'Display real-time social proof notifications, customer testimonials, and trust badges to increase conversions.',icon:'⭐',features:['Real-time notifications','Testimonial carousel','Trust badges','Star ratings','Conversion analytics','Custom styling','A/B testing','No-code embed'],benefits:['Increase conversions 15%','Build trust instantly','Show real social proof','No-code integration'],pricing:{basic:'19',pro:'49',enterprise:'129'},contactInfo:{website:'/services/micro-saas-social-proof',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-social-proof',category:'micro-saas',popular:true,industry:'Conversion Optimization'},
  
  {id:'micro-saas-survey-platform',title:'Customer Survey & NPS Platform',description:'Beautiful surveys with NPS, CSAT, CES templates, logic branching, and automated insights for customer feedback.',icon:'📊',features:['NPS/CSAT/CES templates','Logic branching','Automated insights','Response analytics','Multi-channel distribution','White-labeling','API access','Integration hub'],benefits:['Measure satisfaction','Get actionable insights','Automate feedback collection','Track trends over time'],pricing:{basic:'29',pro:'79',enterprise:'199'},contactInfo:{website:'/services/micro-saas-survey-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-survey-platform',category:'micro-saas',popular:true,industry:'Customer Feedback'},
  
  {id:'micro-saas-waiting-list',title:'Waiting List & Launch Platform',description:'Build viral waiting lists with referral tracking, leaderboard, automated emails, and launch analytics for product launches.',icon:'🚀',features:['Viral referral system','Leaderboard','Automated emails','Launch analytics','Custom branding','Segment management','A/B testing','API access'],benefits:['Go viral before launch','Build anticipation','Track referrals','Launch with impact'],pricing:{basic:'29',pro:'79',enterprise:'199'},contactInfo:{website:'/services/micro-saas-waiting-list',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-waiting-list',category:'micro-saas',popular:true,industry:'Product Launch'},
];

const existing = new Set(services.map(s => s.id));
const toAdd = newServices.filter(s => !existing.has(s.id));
services.push(...toAdd);
fs.writeFileSync('app/data/servicesData.json', JSON.stringify(services, null, 2));
console.log('Added', toAdd.length, 'new services. Total:', services.length);
