const fs = require("fs");
const path = require("path");

const filePath = path.join(__dirname, "..", "app", "data", "servicesData.json");
const data = JSON.parse(fs.readFileSync(filePath, "utf8"));

const contactInfo = {
  phone: "+1 302 464 0950",
  email: "kleber@ziontechgroup.com",
  address: "364 E Main St STE 1008, Middletown, DE 19709"
};

const newServices = [
  // V1001 Persona Detection Services
  {id: "email-persona-detection", name: "Email Persona Detection", category: "AI Services", description: "Detect sender personality traits (MBTI, Big Five) to tailor responses and build better rapport with contacts.", price: "$159/month", features: ["MBTI type detection", "Big Five scoring", "Communication style analysis", "Response strategy generation", "Tone matching", "Personality reports"], icon: "🎭", link: "/services/email-persona-detection", contactInfo},
  {id: "personality-adapted-responses", name: "Personality-Adapted Email Responses", category: "AI Services", description: "AI adapts your email tone, style, and approach based on the recipient personality profile for maximum effectiveness.", price: "$139/month", features: ["Tone adaptation", "Style matching", "Directness adjustment", "Formality calibration", "Cultural sensitivity", "Effectiveness tracking"], icon: "🎯", link: "/services/personality-adapted-responses", contactInfo},
  {id: "communication-style-coach", name: "Communication Style Coach", category: "AI Services", description: "AI coaching that helps you adapt your communication style to match different personality types for better outcomes.", price: "$119/month", features: ["Style analysis", "Adaptation tips", "Practice exercises", "Progress tracking", "Team profiles", "MBTI insights"], icon: "💬", link: "/services/communication-style-coach", contactInfo},
  {id: "team-personality-mapping", name: "Team Personality Mapping", category: "Micro SaaS", description: "Map your team communication styles and personality types to optimize internal collaboration and external communication.", price: "$199/month", features: ["Team profiling", "Style mapping", "Conflict prevention", "Collaboration optimization", "Onboarding support", "Reports"], icon: "👥", link: "/services/team-personality-mapping", contactInfo},
  {id: "emotional-intelligence-email", name: "Emotional Intelligence Email Suite", category: "AI Services", description: "AI analyzes emotional tone and suggests empathetic responses that build trust and strengthen relationships.", price: "$179/month", features: ["Emotion detection", "Empathy suggestions", "Relationship scoring", "Trust building", "Conflict de-escalation", "Sentiment tracking"], icon: "💝", link: "/services/emotional-intelligence-email", contactInfo},

  // V1002 Deal Flow Services
  {id: "email-deal-flow-tracker", name: "Email Deal Flow Tracker", category: "Micro SaaS", description: "Automatically track deals, opportunities, and revenue from email conversations. Pipeline management without the CRM overhead.", price: "$249/month", features: ["Deal detection", "Stage tracking", "Revenue estimation", "Pipeline visualization", "Stakeholder mapping", "Close probability"], icon: "💼", link: "/services/email-deal-flow-tracker", contactInfo},
  {id: "sales-pipeline-intelligence", name: "Sales Pipeline Intelligence", category: "Micro SaaS", description: "AI-powered sales pipeline that extracts deal data from emails, predicts close rates, and identifies at-risk opportunities.", price: "$299/month", features: ["Pipeline automation", "Close prediction", "Risk identification", "Revenue forecasting", "Activity tracking", "Team dashboard"], icon: "📊", link: "/services/sales-pipeline-intelligence", contactInfo},
  {id: "email-revenue-attribution-pro", name: "Email Revenue Attribution Pro", category: "Micro SaaS", description: "Attribute revenue to specific email interactions. Track which conversations drive deals and optimize your sales approach.", price: "$279/month", features: ["Revenue tracking", "Deal attribution", "ROI analysis", "Sales optimization", "Performance metrics", "Forecasting"], icon: "💰", link: "/services/email-revenue-attribution-pro", contactInfo},
  {id: "competitive-intelligence-email", name: "Competitive Intelligence from Email", category: "AI Services", description: "Detect competitive situations from email conversations and generate differentiation strategies automatically.", price: "$219/month", features: ["Competitor detection", "Differentiation strategies", "Win/loss analysis", "Market positioning", "Battle cards", "Competitive alerts"], icon: "🏆", link: "/services/competitive-intelligence-email", contactInfo},
  {id: "deal-risk-advisor", name: "Deal Risk Advisor", category: "AI Services", description: "AI identifies at-risk deals from email signals and provides actionable strategies to save and close them.", price: "$189/month", features: ["Risk scoring", "Early warning", "Save strategies", "Engagement tracking", "Stakeholder analysis", "Deal coaching"], icon: "⚠️", link: "/services/deal-risk-advisor", contactInfo},

  // V1003 Anomaly Detection Services
  {id: "email-anomaly-detector", name: "Email Anomaly Detector", category: "Security Services", description: "AI detects unusual patterns, tone shifts, impersonation attempts, and fraud indicators in real-time.", price: "$229/month", features: ["Tone anomaly detection", "Impersonation alerts", "Fraud pattern matching", "Risk scoring", "Security recommendations", "Real-time alerts"], icon: "🕵️", link: "/services/email-anomaly-detector", contactInfo},
  {id: "email-fraud-prevention", name: "Email Fraud Prevention Suite", category: "Security Services", description: "Comprehensive fraud prevention: phishing, BEC, impersonation, gift card scams, and wire fraud detection.", price: "$349/month", features: ["BEC prevention", "Phishing detection", "Wire fraud alerts", "Gift card scam detection", "Identity verification", "Incident response"], icon: "🛡️", link: "/services/email-fraud-prevention", contactInfo},
  {id: "social-engineering-shield", name: "Social Engineering Shield", category: "Security Services", description: "AI-powered protection against social engineering attacks: manipulation, coercion, urgency exploitation, and pretexting.", price: "$269/month", features: ["Manipulation detection", "Urgency analysis", "Pretexting detection", "Coercion alerts", "Training modules", "Incident logging"], icon: "🔐", link: "/services/social-engineering-shield", contactInfo},
  {id: "email-identity-verification", name: "Email Identity Verification", category: "Security Services", description: "Verify sender identity using AI analysis of writing patterns, domain checks, and behavioral biometrics.", price: "$199/month", features: ["Writing pattern analysis", "Domain verification", "Behavioral biometrics", "Impersonation alerts", "SPF/DKIM/DMARC", "Trust scoring"], icon: "✅", link: "/services/email-identity-verification", contactInfo},
  {id: "executive-protection-email", name: "Executive Email Protection", category: "Security Services", description: "Specialized protection for executives: CEO fraud prevention, VIP impersonation detection, and high-value transaction monitoring.", price: "$449/month", features: ["CEO fraud prevention", "VIP impersonation detection", "Transaction monitoring", "Out-of-band verification", "Executive dashboard", "24/7 monitoring"], icon: "👔", link: "/services/executive-protection-email", contactInfo},

  // V1004 Contract Analyzer Services
  {id: "email-contract-analyzer", name: "Email Contract Analyzer", category: "AI Services", description: "Extract terms, obligations, deadlines, and risks from contract emails. AI-powered legal document intelligence.", price: "$299/month", features: ["Term extraction", "Obligation tracking", "Deadline detection", "Risk scoring", "Clause analysis", "Legal recommendations"], icon: "📝", link: "/services/email-contract-analyzer", contactInfo},
  {id: "contract-risk-assessment", name: "Contract Risk Assessment AI", category: "AI Services", description: "AI assesses contract risk level, identifies dangerous clauses, and recommends modifications before signing.", price: "$349/month", features: ["Risk scoring", "Clause analysis", "Danger detection", "Modification suggestions", "Compliance checking", "Risk reports"], icon: "⚖️", link: "/services/contract-risk-assessment", contactInfo},
  {id: "contract-obligation-tracker", name: "Contract Obligation Tracker", category: "IT Services", description: "Automatically extract and track all contract obligations, deadlines, and deliverables from email conversations.", price: "$179/month", features: ["Auto-extraction", "Deadline tracking", "Deliverable monitoring", "Compliance alerts", "Status reporting", "Team assignment"], icon: "📋", link: "/services/contract-obligation-tracker", contactInfo},
  {id: "legal-clause-library", name: "Legal Clause Intelligence Library", category: "AI Services", description: "AI-powered library of standard and non-standard contract clauses with risk ratings and negotiation suggestions.", price: "$249/month", features: ["Clause database", "Risk ratings", "Standard templates", "Negotiation tips", "Comparison tools", "Legal guidance"], icon: "📚", link: "/services/legal-clause-library", contactInfo},
  {id: "contract-compliance-monitor", name: "Contract Compliance Monitor", category: "Compliance Services", description: "Monitor ongoing contract compliance automatically. Track obligations, deadlines, and terms from email communications.", price: "$279/month", features: ["Compliance tracking", "Obligation monitoring", "Deadline alerts", "Breach detection", "Audit trails", "Compliance reports"], icon: "🔍", link: "/services/contract-compliance-monitor", contactInfo},

  // V1005 Follow-up Autopilot Services
  {id: "email-followup-autopilot", name: "Email Follow-up Autopilot", category: "AI Services", description: "Never miss a follow-up again. AI detects questions, requests, commitments, and auto-generates timely follow-ups.", price: "$169/month", features: ["Trigger detection", "Auto-scheduling", "Draft generation", "Priority ranking", "Timing optimization", "Tracking dashboard"], icon: "🔄", link: "/services/email-followup-autopilot", contactInfo},
  {id: "smart-reminder-engine", name: "Smart Reminder Engine", category: "Micro SaaS", description: "Intelligent reminders based on email context: unanswered questions, pending requests, upcoming deadlines, and commitments.", price: "$99/month", features: ["Context-aware reminders", "Priority ranking", "Smart timing", "Snooze options", "Team reminders", "Analytics"], icon: "⏰", link: "/services/smart-reminder-engine", contactInfo},
  {id: "email-response-tracker", name: "Email Response Tracker", category: "Micro SaaS", description: "Track all emails awaiting your response. AI prioritizes by urgency, importance, and deadline proximity.", price: "$119/month", features: ["Response tracking", "Priority scoring", "Deadline monitoring", "Overdue alerts", "Response time metrics", "Team visibility"], icon: "📬", link: "/services/email-response-tracker", contactInfo},
  {id: "relationship-nurturing-ai", name: "Relationship Nurturing AI", category: "AI Services", description: "AI identifies contacts that need attention and generates personalized check-in messages to maintain relationships.", price: "$189/month", features: ["Contact monitoring", "Attention scoring", "Check-in generation", "Relationship health", "Network analysis", "Engagement tracking"], icon: "🤝", link: "/services/relationship-nurturing-ai", contactInfo},
  {id: "email-cadence-optimizer", name: "Email Cadence Optimizer", category: "AI Services", description: "Optimize email follow-up cadence based on recipient behavior, engagement patterns, and relationship stage.", price: "$149/month", features: ["Cadence optimization", "Behavior analysis", "Engagement tracking", "A/B testing", "Automated sequences", "Performance analytics"], icon: "📈", link: "/services/email-cadence-optimizer", contactInfo},

  // Additional innovative services
  {id: "ai-email-decision-engine", name: "AI Email Decision Engine", category: "AI Services", description: "AI analyzes emails and recommends the best action: reply, forward, delegate, snooze, archive, or escalate.", price: "$219/month", features: ["Action recommendation", "Priority scoring", "Smart routing", "Delegation suggestions", "Snooze intelligence", "Decision analytics"], icon: "🧠", link: "/services/ai-email-decision-engine", contactInfo},
  {id: "email-productivity-analytics", name: "Email Productivity Analytics", category: "Micro SaaS", description: "Deep analytics on your email habits: response times, inbox zero rate, time spent, and productivity optimization.", price: "$129/month", features: ["Habit analysis", "Response time tracking", "Inbox zero coaching", "Time optimization", "Productivity scores", "Team benchmarks"], icon: "📊", link: "/services/email-productivity-analytics", contactInfo},
  {id: "email-workflow-automation-pro", name: "Email Workflow Automation Pro", category: "IT Services", description: "Build powerful email workflows without code: auto-route, auto-respond, auto-escalate based on intelligent rules.", price: "$299/month", features: ["Visual workflow builder", "Smart rules engine", "Auto-routing", "Auto-escalation", "Integration hub", "Workflow analytics"], icon: "⚡", link: "/services/email-workflow-automation-pro", contactInfo},
  {id: "cross-platform-email-sync", name: "Cross-Platform Email Sync", category: "IT Services", description: "Seamlessly sync emails across all platforms: Gmail, Outlook, Slack, Teams, and custom CRM with AI-powered deduplication.", price: "$159/month", features: ["Multi-platform sync", "AI deduplication", "Real-time sync", "Conflict resolution", "Platform bridge", "Sync analytics"], icon: "🔗", link: "/services/cross-platform-email-sync", contactInfo},
  {id: "email-strategic-advisor", name: "Email Strategic Advisor", category: "AI Services", description: "AI strategic advisor that analyzes your email patterns and provides actionable strategies for better communication outcomes.", price: "$249/month", features: ["Pattern analysis", "Strategy recommendations", "Outcome optimization", "Communication coaching", "Performance tracking", "Strategic insights"], icon: "🎯", link: "/services/email-strategic-advisor", contactInfo},
];

let added = 0;
const existingIds = new Set(data.map(s => s.id));

for (const svc of newServices) {
  if (!existingIds.has(svc.id)) {
    data.push(svc);
    existingIds.add(svc.id);
    added++;
  }
}

fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
console.log("Added " + added + " new services. Total: " + data.length);
