const fs = require('fs');
let ts = fs.readFileSync('app/data/servicesData.ts', 'utf8');

const hasCRLF = ts.includes('\r\n');
ts = ts.replace(/\r\n/g, '\n');

const newAIEntries = `
  {
    id: 'ai-email-translation-hub-v209',
    title: 'AI Email Translation Hub (V209)',
    description: 'Real-time translation of emails into 40+ languages with cultural context adaptation and terminology consistency.',
    features: ['40+ language translation', 'Cultural context adaptation', 'Formality level matching', 'Terminology consistency', 'Language auto-detection', 'Regional dialect support', 'Glossary management', 'Reply-all enforcement'],
    benefits: ['Communicate globally', 'Maintain cultural sensitivity', 'Ensure consistent terminology', 'Auto-detect source language'],
    pricing: { basic: '$299/mo', pro: '$699/mo', enterprise: '$1799/mo' },
    contactInfo: { website: '/services/ai-email-translation-hub-v209', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🌍',
    href: '/services/ai-email-translation-hub-v209',
    popular: true,
    category: 'ai',
    industry: 'Global Communication',
  },
  {
    id: 'ai-email-revenue-attribution-v210',
    title: 'AI Email Revenue Attribution (V210)',
    description: 'Track how email conversations drive revenue with pipeline attribution and deal influence scoring.',
    features: ['Pipeline touchpoint detection', 'Deal influence scoring', '5 attribution models', 'Revenue ROI dashboards', 'Engagement signal analysis', 'Deal value extraction', 'Position-based attribution', 'Reply-all enforcement'],
    benefits: ['Quantify email revenue', 'Track deal influence', 'Optimize sales strategy', 'Prove email ROI'],
    pricing: { basic: '$499/mo', pro: '$1099/mo', enterprise: '$2999/mo' },
    contactInfo: { website: '/services/ai-email-revenue-attribution-v210', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '💰',
    href: '/services/ai-email-revenue-attribution-v210',
    popular: true,
    category: 'ai',
    industry: 'Revenue Operations',
  },
  {
    id: 'ai-email-disaster-recovery-v211',
    title: 'AI Email Disaster Recovery (V211)',
    description: 'Automated backup, corruption detection, and recovery of critical email data with point-in-time restore.',
    features: ['Automated email backup', 'Corruption detection', 'Point-in-time restore', 'Integrity verification', 'Deduplication', 'Compression optimization', 'Recovery point management', 'Health scoring'],
    benefits: ['Never lose email data', 'Detect corruption automatically', 'Restore to any point', '99.99% data integrity'],
    pricing: { basic: '$199/mo', pro: '$449/mo', enterprise: '$1099/mo' },
    contactInfo: { website: '/services/ai-email-disaster-recovery-v211', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🔄',
    href: '/services/ai-email-disaster-recovery-v211',
    popular: true,
    category: 'ai',
    industry: 'Data Protection',
  },
  {
    id: 'ai-email-gamification-v212',
    title: 'AI Email Gamification Platform (V212)',
    description: 'Gamify email responsiveness with leaderboards, badges, streaks, and team performance metrics.',
    features: ['Leaderboards & rankings', '10+ achievement badges', 'Streak tracking', 'Level progression', 'Team competitions', 'Response time scoring', 'Quality metrics', 'Reply-all enforcement'],
    benefits: ['Boost productivity 3x', 'Improve response times', 'Gamify quality standards', 'Track team performance'],
    pricing: { basic: '$149/mo', pro: '$349/mo', enterprise: '$799/mo' },
    contactInfo: { website: '/services/ai-email-gamification-v212', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🏆',
    href: '/services/ai-email-gamification-v212',
    popular: true,
    category: 'ai',
    industry: 'Team Productivity',
  },
  {
    id: 'ai-email-competitive-intel-v213',
    title: 'AI Email Competitive Intelligence (V213)',
    description: 'Detect competitor mentions, pricing comparisons, and switch risks in customer emails with battle cards.',
    features: ['Competitor mention detection', 'Switch risk analysis', 'Competitive battle cards', 'Win/loss analysis', 'Pain point extraction', 'Risk scoring', 'Recommended actions', 'Reply-all enforcement'],
    benefits: ['Detect churn risks early', 'Build winning battle cards', 'Track competitive landscape', 'Prevent switching'],
    pricing: { basic: '$399/mo', pro: '$899/mo', enterprise: '$2299/mo' },
    contactInfo: { website: '/services/ai-email-competitive-intel-v213', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🎯',
    href: '/services/ai-email-competitive-intel-v213',
    popular: true,
    category: 'ai',
    industry: 'Competitive Intelligence',
  },
  {
    id: 'ai-email-mega-suite-v209-v213',
    title: 'AI Email Intelligence Mega Suite (V209-V213)',
    description: 'All 5 new email intelligence engines unified. Translation, Revenue, Recovery, Gamification, and Competitive Intel.',
    features: ['V209 Translation Hub', 'V210 Revenue Attribution', 'V211 Disaster Recovery', 'V212 Gamification', 'V213 Competitive Intel', 'Case-by-case analysis', 'Reply-all guaranteed', 'Enterprise security'],
    benefits: ['Complete email intelligence', '1500% average ROI', 'Zero data loss guarantee', 'Definitive email AI'],
    pricing: { basic: '$1299/mo', pro: '$2999/mo', enterprise: '$7999/mo' },
    contactInfo: { website: '/services/ai-email-mega-suite-v209-v213', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '👑',
    href: '/services/ai-email-mega-suite-v209-v213',
    popular: true,
    category: 'ai',
    industry: 'Enterprise AI',
  },
  {
    id: 'ai-video-conference-intelligence',
    title: 'AI Video Conference Intelligence',
    description: 'Auto-generate meeting summaries and extract action items from Zoom, Teams, and Meet recordings.',
    features: ['Auto-transcription', 'Speaker diarization', 'Action item extraction', 'Engagement scoring', 'Meeting summaries', 'Sentiment analysis', 'Follow-up generation', 'Calendar integration'],
    benefits: ['Never miss insights', 'Track engagement', 'Generate summaries', 'Extract action items'],
    pricing: { basic: '$199/mo', pro: '$449/mo', enterprise: '$1099/mo' },
    contactInfo: { website: '/services/ai-video-conference-intelligence', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '📹',
    href: '/services/ai-video-conference-intelligence',
    popular: true,
    category: 'ai',
    industry: 'Meeting Intelligence',
  },
  {
    id: 'ai-supply-chain-optimizer',
    title: 'AI Supply Chain Optimizer',
    description: 'Optimize supply chain with demand forecasting, inventory optimization, and supplier risk assessment.',
    features: ['Demand forecasting', 'Inventory optimization', 'Supplier risk scoring', 'Route optimization', 'Cost reduction', 'Lead time prediction', 'Disruption alerts', 'Scenario planning'],
    benefits: ['Reduce costs 25%', 'Improve forecast 40%', 'Optimize routes', 'Prevent disruptions'],
    pricing: { basic: '$699/mo', pro: '$1499/mo', enterprise: '$3999/mo' },
    contactInfo: { website: '/services/ai-supply-chain-optimizer', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🚛',
    href: '/services/ai-supply-chain-optimizer',
    popular: true,
    category: 'ai',
    industry: 'Supply Chain',
  },
  {
    id: 'ai-fraud-detection-platform',
    title: 'AI Fraud Detection Platform',
    description: 'Real-time fraud detection with ML models, anomaly detection, and behavioral biometrics.',
    features: ['Real-time monitoring', 'ML fraud models', 'Anomaly detection', 'Behavioral biometrics', 'Case management', 'Alert prioritization', 'Regulatory reporting', 'Model retraining'],
    benefits: ['Detect fraud in ms', 'Reduce false positives 60%', 'Automate cases', 'Meet compliance'],
    pricing: { basic: '$999/mo', pro: '$2499/mo', enterprise: '$5999/mo' },
    contactInfo: { website: '/services/ai-fraud-detection-platform', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🔍',
    href: '/services/ai-fraud-detection-platform',
    popular: true,
    category: 'ai',
    industry: 'Financial Services',
  },
  {
    id: 'ai-code-review-assistant',
    title: 'AI Code Review Assistant',
    description: 'Automated code review with security scanning, performance analysis, and AI-powered suggestions.',
    features: ['Security scanning', 'Performance detection', 'Code smell ID', 'Best practice enforcement', 'AI suggestions', 'PR automation', 'Doc generation', 'Test coverage'],
    benefits: ['Review 10x faster', 'Catch security issues', 'Enforce standards', 'Improve quality'],
    pricing: { basic: '$149/mo', pro: '$349/mo', enterprise: '$799/mo' },
    contactInfo: { website: '/services/ai-code-review-assistant', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '💻',
    href: '/services/ai-code-review-assistant',
    popular: true,
    category: 'ai',
    industry: 'Software Development',
  },
  {
    id: 'ai-legal-document-drafting',
    title: 'AI Legal Document Drafting',
    description: 'Draft contracts, NDAs, and policies with AI assistance, template library, and compliance checking.',
    features: ['AI-powered drafting', '200+ templates', 'Clause suggestions', 'Risk analysis', 'Compliance checking', 'Version control', 'Collaboration', 'E-signature'],
    benefits: ['Draft 5x faster', 'Reduce review time', 'Ensure compliance', 'Minimize risks'],
    pricing: { basic: '$399/mo', pro: '$899/mo', enterprise: '$2299/mo' },
    contactInfo: { website: '/services/ai-legal-document-drafting', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '📋',
    href: '/services/ai-legal-document-drafting',
    popular: true,
    category: 'ai',
    industry: 'Legal Tech',
  },`;

const newITEntries = `
  {
    id: 'it-kubernetes-management-platform',
    title: 'Kubernetes Management Platform',
    description: 'Enterprise K8s management with multi-cluster orchestration, cost optimization, and security hardening.',
    features: ['Multi-cluster management', 'Cost optimization', 'Security hardening', 'Observability', 'GitOps workflows', 'Service mesh', 'Backup & DR', 'Compliance automation'],
    benefits: ['Manage K8s at scale', 'Reduce costs 30%', 'Harden security', 'Full observability'],
    pricing: { basic: '$499/mo', pro: '$1099/mo', enterprise: '$2999/mo' },
    contactInfo: { website: '/services/it-kubernetes-management-platform', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '☸️',
    href: '/services/it-kubernetes-management-platform',
    popular: true,
    category: 'it',
    industry: 'Cloud Native',
  },
  {
    id: 'it-edge-computing-platform',
    title: 'Edge Computing Platform',
    description: 'Deploy and manage edge workloads with low-latency processing and offline sync for IoT applications.',
    features: ['Edge deployment', 'Low-latency processing', 'Offline sync', 'Centralized management', 'Container orchestration', 'Security enforcement', 'Monitoring', 'OTA updates'],
    benefits: ['Process at edge', 'Millisecond latency', 'Operate offline', 'Manage thousands'],
    pricing: { basic: '$399/mo', pro: '$899/mo', enterprise: '$2299/mo' },
    contactInfo: { website: '/services/it-edge-computing-platform', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '📡',
    href: '/services/it-edge-computing-platform',
    popular: true,
    category: 'it',
    industry: 'Edge Computing',
  },
  {
    id: 'it-database-performance-tuning',
    title: 'Database Performance Tuning',
    description: 'Automated database optimization with query analysis, index recommendations, and predictive scaling.',
    features: ['Query analysis', 'Index recommendations', 'Connection pooling', 'Predictive scaling', 'Slow query detection', 'Deadlock analysis', 'Cache optimization', 'Replication monitoring'],
    benefits: ['Improve speed 5x', 'Reduce costs 40%', 'Prevent issues', 'Scale automatically'],
    pricing: { basic: '$299/mo', pro: '$699/mo', enterprise: '$1799/mo' },
    contactInfo: { website: '/services/it-database-performance-tuning', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🗄️',
    href: '/services/it-database-performance-tuning',
    popular: true,
    category: 'it',
    industry: 'Database Management',
  },
  {
    id: 'it-network-observability',
    title: 'Network Observability Platform',
    description: 'Deep network visibility with flow analysis, packet inspection, and anomaly detection.',
    features: ['Flow analysis', 'Packet inspection', 'Latency monitoring', 'Anomaly detection', 'Topology mapping', 'Bandwidth optimization', 'Security monitoring', 'Compliance reporting'],
    benefits: ['See entire topology', 'Detect issues early', 'Optimize bandwidth', 'Secure traffic'],
    pricing: { basic: '$399/mo', pro: '$899/mo', enterprise: '$2299/mo' },
    contactInfo: { website: '/services/it-network-observability', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🌐',
    href: '/services/it-network-observability',
    popular: true,
    category: 'it',
    industry: 'Network Operations',
  },`;

const newSecurityEntries = `
  {
    id: 'security-cloud-posture-management',
    title: 'Cloud Security Posture Management (CSPM)',
    description: 'Continuous cloud security monitoring with misconfiguration detection and compliance benchmarking.',
    features: ['Multi-cloud monitoring', 'Misconfiguration detection', 'CIS benchmarks', 'Auto remediation', 'Risk prioritization', 'Compliance reporting', 'Asset inventory', 'Threat detection'],
    benefits: ['Secure multi-cloud', 'Detect misconfigs', 'Meet compliance', 'Automate remediation'],
    pricing: { basic: '$499/mo', pro: '$1099/mo', enterprise: '$2999/mo' },
    contactInfo: { website: '/services/security-cloud-posture-management', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '☁️',
    href: '/services/security-cloud-posture-management',
    popular: true,
    category: 'security',
    industry: 'Cloud Security',
  },
  {
    id: 'security-api-security-platform',
    title: 'API Security Platform',
    description: 'Protect APIs with discovery, testing, monitoring, and runtime protection against OWASP vulnerabilities.',
    features: ['API discovery', 'OWASP testing', 'Runtime protection', 'Rate limiting', 'Auth enforcement', 'Data exfiltration prevention', 'API analytics', 'Compliance monitoring'],
    benefits: ['Discover shadow APIs', 'Test OWASP vulns', 'Protect runtime', 'Prevent breaches'],
    pricing: { basic: '$399/mo', pro: '$899/mo', enterprise: '$2299/mo' },
    contactInfo: { website: '/services/security-api-security-platform', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🔌',
    href: '/services/security-api-security-platform',
    popular: true,
    category: 'security',
    industry: 'API Security',
  },
  {
    id: 'security-threat-intelligence-platform',
    title: 'Threat Intelligence Platform',
    description: 'Aggregate and operationalize threat intelligence with automated IOC enrichment and hunting.',
    features: ['Multi-source intel', 'IOC enrichment', 'Threat hunting', 'Auto correlation', 'Risk scoring', 'SIEM integration', 'Campaign tracking', 'Dark web monitoring'],
    benefits: ['Stay ahead of threats', 'Automate enrichment', 'Hunt proactively', 'Correlate intel'],
    pricing: { basic: '$599/mo', pro: '$1299/mo', enterprise: '$3499/mo' },
    contactInfo: { website: '/services/security-threat-intelligence-platform', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🕵️',
    href: '/services/security-threat-intelligence-platform',
    popular: true,
    category: 'security',
    industry: 'Threat Intelligence',
  },`;

const newDataEntries = `
  {
    id: 'data-feature-store-platform',
    title: 'ML Feature Store Platform',
    description: 'Centralized feature management for ML with real-time serving and batch computation.',
    features: ['Feature registry', 'Real-time serving', 'Batch computation', 'Feature sharing', 'Version control', 'Monitoring', 'MLflow integration', 'Data quality checks'],
    benefits: ['Reuse features', 'Serve in milliseconds', 'Share across teams', 'Monitor drift'],
    pricing: { basic: '$399/mo', pro: '$899/mo', enterprise: '$2299/mo' },
    contactInfo: { website: '/services/data-feature-store-platform', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🧮',
    href: '/services/data-feature-store-platform',
    popular: true,
    category: 'data',
    industry: 'MLOps',
  },
  {
    id: 'data-data-mesh-platform',
    title: 'Data Mesh Platform',
    description: 'Implement data mesh with domain-oriented data products and federated governance.',
    features: ['Domain data products', 'Self-serve platform', 'Federated governance', 'Data catalog', 'Quality SLAs', 'Interoperability', 'Observability', 'Cost allocation'],
    benefits: ['Scale ownership', 'Enable self-service', 'Federate governance', 'Data as product'],
    pricing: { basic: '$599/mo', pro: '$1299/mo', enterprise: '$3499/mo' },
    contactInfo: { website: '/services/data-data-mesh-platform', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🕸️',
    href: '/services/data-data-mesh-platform',
    popular: true,
    category: 'data',
    industry: 'Data Architecture',
  },`;

const newAutoEntries = `
  {
    id: 'micro-saas-changelog-management',
    title: 'Changelog & Release Notes Platform',
    description: 'Automate changelog generation and publish release notes with a beautiful public page.',
    features: ['Auto generation', 'Public changelog', 'User notifications', 'Feature tracking', 'Segmented announcements', 'Custom branding', 'RSS feed', 'API integration'],
    benefits: ['Automate notes', 'Keep users informed', 'Track adoption', 'Beautiful page'],
    pricing: { basic: '$49/mo', pro: '$129/mo', enterprise: '$299/mo' },
    contactInfo: { website: '/services/micro-saas-changelog-management', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '📝',
    href: '/services/micro-saas-changelog-management',
    popular: true,
    category: 'micro-saas',
    industry: 'Product Communication',
  },
  {
    id: 'micro-saas-uptime-monitoring',
    title: 'Uptime Monitoring & Alerting',
    description: 'Monitor websites and APIs from 100+ global locations with instant alerts and status pages.',
    features: ['100+ locations', 'Multi-protocol checks', 'Instant alerts', 'Status pages', 'SLA tracking', 'Performance monitoring', 'SSL monitoring', 'Incident management'],
    benefits: ['Detect outages instantly', 'Monitor globally', 'Beautiful status pages', 'Track SLAs'],
    pricing: { basic: '$29/mo', pro: '$79/mo', enterprise: '$199/mo' },
    contactInfo: { website: '/services/micro-saas-uptime-monitoring', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '📊',
    href: '/services/micro-saas-uptime-monitoring',
    popular: true,
    category: 'micro-saas',
    industry: 'Monitoring',
  },
  {
    id: 'micro-saas-ab-testing-platform',
    title: 'A/B Testing & Experimentation Platform',
    description: 'Run A/B tests with statistical significance, feature flags, and user segmentation.',
    features: ['Visual builder', 'Statistical significance', 'Feature flags', 'User segmentation', 'Multi-variate', 'Conversion tracking', 'Revenue attribution', 'Bayesian analysis'],
    benefits: ['Data-driven decisions', 'Test safely', 'Segment precisely', 'Prove ROI'],
    pricing: { basic: '$99/mo', pro: '$249/mo', enterprise: '$599/mo' },
    contactInfo: { website: '/services/micro-saas-ab-testing-platform', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🧪',
    href: '/services/micro-saas-ab-testing-platform',
    popular: true,
    category: 'micro-saas',
    industry: 'Product Analytics',
  },
  {
    id: 'micro-saas-document-signing',
    title: 'Electronic Document Signing',
    description: 'Secure e-signatures with workflow automation and compliance (ESIGN/UETA/eIDAS).',
    features: ['Legal e-signatures', 'Workflow automation', 'Template management', 'ESIGN/UETA/eIDAS', 'Audit trails', 'Bulk sending', 'API integration', 'Custom branding'],
    benefits: ['Sign 10x faster', 'Automate workflows', 'Meet compliance', 'Full audit trail'],
    pricing: { basic: '$29/mo', pro: '$79/mo', enterprise: '$199/mo' },
    contactInfo: { website: '/services/micro-saas-document-signing', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '✍️',
    href: '/services/micro-saas-document-signing',
    popular: true,
    category: 'micro-saas',
    industry: 'Document Management',
  },
  {
    id: 'micro-saas-team-scheduling',
    title: 'Team Scheduling & Calendar Platform',
    description: 'Smart scheduling with availability matching, timezone handling, and meeting room booking.',
    features: ['Smart availability', 'Timezone handling', 'Buffer management', 'Room booking', 'Recurring meetings', 'Calendar sync', 'No-show tracking', 'Meeting analytics'],
    benefits: ['Schedule 5x faster', 'Eliminate timezone issues', 'Optimize rooms', 'Track effectiveness'],
    pricing: { basic: '$19/mo', pro: '$49/mo', enterprise: '$129/mo' },
    contactInfo: { website: '/services/micro-saas-team-scheduling', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '📅',
    href: '/services/micro-saas-team-scheduling',
    popular: true,
    category: 'micro-saas',
    industry: 'Team Productivity',
  },
  {
    id: 'micro-saas-error-tracking',
    title: 'Error Tracking & Crash Reporting',
    description: 'Real-time error tracking with stack traces, user context, and release tracking.',
    features: ['Real-time tracking', 'Full stack traces', 'User context', 'Release tracking', 'Alert rules', 'Error grouping', 'Performance monitoring', 'Source maps'],
    benefits: ['Catch errors instantly', 'Debug with context', 'Track per release', 'Alert right team'],
    pricing: { basic: '$49/mo', pro: '$129/mo', enterprise: '$349/mo' },
    contactInfo: { website: '/services/micro-saas-error-tracking', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '🐛',
    href: '/services/micro-saas-error-tracking',
    popular: true,
    category: 'micro-saas',
    industry: 'Application Monitoring',
  },
  {
    id: 'micro-saas-knowledge-base-builder',
    title: 'Knowledge Base & Help Center Builder',
    description: 'Build beautiful help centers with AI-powered search and article analytics.',
    features: ['Beautiful help center', 'AI-powered search', 'Article analytics', 'Feedback collection', 'Multi-language', 'Version history', 'SEO optimization', 'Custom domains'],
    benefits: ['Reduce tickets 40%', 'Beautiful docs', 'AI search', 'Track performance'],
    pricing: { basic: '$39/mo', pro: '$99/mo', enterprise: '$249/mo' },
    contactInfo: { website: '/services/micro-saas-knowledge-base-builder', email: 'kleber@ziontechgroup.com', phone: '+1 302 464 0950' },
    icon: '📚',
    href: '/services/micro-saas-knowledge-base-builder',
    popular: true,
    category: 'micro-saas',
    industry: 'Customer Support',
  },`;

let count = 0;

let idx = ts.indexOf('];\n\nexport const itServices');
if (idx > -1) { ts = ts.slice(0, idx) + newAIEntries + '\n' + ts.slice(idx); count += 11; console.log('✓ Added 11 AI services'); }

idx = ts.indexOf('];\n\nexport const cloudServices');
if (idx > -1) { ts = ts.slice(0, idx) + newITEntries + '\n' + ts.slice(idx); count += 4; console.log('✓ Added 4 IT services'); }

idx = ts.indexOf('];\n\nexport const dataServices');
if (idx > -1) { ts = ts.slice(0, idx) + newSecurityEntries + '\n' + ts.slice(idx); count += 3; console.log('✓ Added 3 Security services'); }

idx = ts.indexOf('];\n\nexport const automationServices');
if (idx > -1) { ts = ts.slice(0, idx) + newDataEntries + '\n' + ts.slice(idx); count += 2; console.log('✓ Added 2 Data services'); }

idx = ts.indexOf('];\n\nexport const allServices');
if (idx > -1) { ts = ts.slice(0, idx) + newAutoEntries + '\n' + ts.slice(idx); count += 7; console.log('✓ Added 7 Micro-SaaS services'); }

if (hasCRLF) ts = ts.replace(/\n/g, '\r\n');

fs.writeFileSync('app/data/servicesData.ts', ts);
console.log('Total added:', count, 'services to TS file');
