#!/usr/bin/env python3
"""Insert 15 new services (10 AI + 5 IT) into servicesData.ts and regenerate all pages."""
import re, json, subprocess
from pathlib import Path

# ── 1. Clean slate from git ───────────────────────────────────────────────────
subprocess.run("git checkout -- app/data/servicesData.ts", shell=True, capture_output=True)
source = Path('app/data/servicesData.ts').read_text(encoding='utf-8')

orig_ids = set(re.findall(r"id\s*:\s*'([^']+)'", source) + re.findall(r'id\s*:\s*"([^"]+)"', source))
print(f"Original services: {len(orig_ids)}")

# ── 2. New services data ─────────────────────────────────────────────────────
NEW_SERVICES = [
  {"id":"ai-voice-cloning-emotion","href":"/ai-services/voice-cloning-emotion","icon":"🎭","category":"ai","title":"Emotional Voice Cloning Studio","description":"Clone any voice with full emotional control — happiness, sadness, anger, urgency — for audiobooks, games, and accessibility. Supports 40+ languages and real-time modulation.","features":["Zero-shot voice cloning from 10-second sample","Per-sentence emotion injection (8 basic + complex blends)","Real-time voice conversion during calls","Speaker diarization & multi-voice projects","Ethical consent layer & watermarking"],"benefits":["Cuts dubbing costs by 70%","Enables dynamic NPC voices in games","Restores speech for ALS patients with their own voiceprint"],"pricing":{"basic":"99","pro":"299","enterprise":"999"}},
  {"id":"ai-code-audit-security","href":"/ai-services/code-audit-security","icon":"🔐","category":"ai","title":"AI Code Audit & Security Scanner","description":"Deep static analysis that finds complex vulnerabilities (logic bugs, race conditions, crypto misuses) beyond traditional linters. Uses LLMs to understand intent.","features":["Detects business logic flaws & privilege escalation","Smart contract audit mode (EVM, Solana, Move)","Patch suggestion with fix diffs","SBOM generation & dependency risk scoring","CI/CD gate integration"],"benefits":["Prevents 90% of critical vulnerabilities before deployment","Reduces manual code review time by 60%","Meets SOC2 / ISO27001 compliance requirements"],"pricing":{"basic":"149","pro":"399","team":"1299"}},
  {"id":"ai-meeting-intelligence","href":"/ai-services/meeting-intelligence","icon":"🤖","category":"ai","title":"AI Meeting Intelligence Suite","description":"Autonomous meeting agent that joins Zoom/Teams, transcribes, summarizes decisions, extracts action items with owners & due dates, and pushes to your project tools.","features":["Real-time transcription in 60+ languages","Decision → task auto-creation (Asana, Linear, Jira)","Conflict detection on action item assignments","Voice print identification & speaker timeline","Private mode for confidential calls"],"benefits":["Saves 5–7 hours per week in meeting follow-up","Zero missed action items or unclear owners","Searchable knowledge base of all past discussions"],"pricing":{"basic":"49","pro":"149","business":"499"}},
  {"id":"ai-fraud-detection-realtime","href":"/ai-services/fraud-detection-realtime","icon":"🛡️","category":"ai","title":"Real-Time Fraud Detection Engine","description":"ML-based fraud detection for fintech, e-commerce, and marketplaces. Adapts to new fraud patterns within hours, not weeks.","features":["Custom model training on your transaction history","3D Secure-like challenge without friction","Synthetic identity detection","Chargeback evidence auto-packager","Regulatory reporting dashboard (FFIEC, PSD2)"],"benefits":["Lowers false positives by 55% vs rule-based systems","Reduces chargebacks by up to 80%","Onboards in 48 hours with existing data"],"pricing":{"starter":"199","growth":"699","enterprise":"contact"}},
  {"id":"ai-document-redaction","href":"/ai-services/document-redaction","icon":"🔒","category":"ai","title":"AI Document Redaction & PII Removal","description":"Automatically detects and redacts PII, PHI, and sensitive data in documents, PDFs, images, and transcripts. SOC2-compliant audit trail included.","features":["Named entity recognition across 50+ PII types","Image-based document OCR + redaction","Bulk processing with S3/GCS integration","Tamper-evident redaction certificates","Regex custom entity support"],"benefits":["Preps 10,000 pages for public release in under 1 hour","Eliminates manual review costs ($0.03/page vs $0.45/page)","Audit-ready for GDPR, HIPAA, CCPA violations"],"pricing":{"payg":"0.03/page","subscription":"499/mo"}},
  {"id":"ai-legal-drafting","href":"/ai-services/legal-drafting","icon":"⚖️","category":"ai","title":"AI Legal Document Drafter","description":"Draft contracts, NDAs, term sheets, and privacy policies with jurisdiction-specific clauses. Trained on actual filings from SEC, Companies House, etc.","features":["Clause library with risk scoring","Redline comparison against templates","Obligation tracker with deadline reminders","Multi-jurisdiction support (50+ countries)","Law-firm approved templates (ex. Axiom, Latham)"],"benefits":["Cuts first-draft time from 4 hours to 12 minutes","Reduces outside counsel spend by 35%","Identifies non-standard clauses before signature"],"pricing":{"startup":"299/mo","business":"899/mo","enterprise":"contact"}},
  {"id":"ai-video-dubbing","href":"/ai-services/video-dubbing","icon":"🎬","category":"ai","title":"AI Video Dubbing & Lip-Sync","description":"Translate and dub videos with AI-generated voice plus perfect lip-sync. Supports 70+ languages and preserves speaker intonation and emotion.","features":["Voice cloning per original speaker","Phoneme-aware lip movement adjustment","Background music and sound effect retention","Subtitle generation in SRT/VTT","YouTube/TikTok multi-language upload automation"],"benefits":["Expands global reach without separate shoots","Saves $15K–$50K per video vs. traditional dubbing","Maintains brand voice consistency across locales"],"pricing":{"per_minute":"12","monthly":"contact"}},
  {"id":"ai-supply-chain-predictor","href":"/ai-services/supply-chain-predictor","icon":"🚢","category":"ai","title":"AI Supply Chain Predictor","description":"Predicts supply chain disruptions 14–30 days in advance using multi-source data: weather, geopolitical events, shipping delays, and supplier health scores.","features":["Demand forecasting with 94% accuracy","Alternative routing suggestions","Supplier risk scoring","Real-time anomaly alerts"],"benefits":["Reduces stockouts by 35%","Cuts expedited shipping costs by 22%","Improves supplier negotiation leverage"],"pricing":{"basic":"299","pro":"799","enterprise":"2499"}},
  {"id":"ai-image-upscaling","href":"/ai-services/image-upscaling","icon":"🖼️","category":"ai","title":"AI Image Upscaler and Restorer","description":"Upscale images 4–16× with detail reconstruction. Removes JPEG artifacts, fixes blur, and even colorizes black and white photos with historical accuracy.","features":["Face-aware upscaling (preserves identity)","Batch processing via API (10K images/hr)","Lossless PNG optimization post-upscale","Before/after preview with quality metrics","On-premise Docker image for air-gapped environments"],"benefits":["Makes legacy asset libraries print-ready again","Saves $50K+ in reshoots for archival imagery","Improves product image conversion by 18% on e-commerce"],"pricing":{"payg":"0.05/MP","subscription":"199/mo"}},
  {"id":"ai-chatbot-builder","href":"/ai-services/chatbot-builder","icon":"💬","category":"ai","title":"No-Code AI Chatbot Builder","description":"Create custom GPT-like chatbots trained on your data (docs, FAQs, past tickets) and embed them anywhere. Fine-tune tone, guardrails, and escalation paths in minutes.","features":["Drag-and-drop conversation flow designer","Multi-channel deploy (web, WhatsApp, Slack, FB Messenger)","Human handoff with full context preservation","Analytics dashboard (resolution rate, escalation triggers)","Custom GPT actions (lookup order, create support ticket)"],"benefits":["Handles 65% of routine queries without agents","Live in <1 hour from data upload","Improves CSAT by 12 points with instant answers"],"pricing":{"starter":"99","business":"299","unlimited":"799"}},
  {"id":"it-quantum-readiness-assessment","href":"/it-services/quantum-readiness-assessment","icon":"⚛️","category":"it","title":"Quantum Readiness Assessment","description":"Evaluate your cryptographic infrastructure against future quantum threats. We inventory all PKI assets, identify vulnerable algorithms, and produce a migration roadmap to post-quantum cryptography.","features":["Automated crypto-asset discovery across clouds and data centers","PQ algorithm readiness score (NIST finalists assessment)","Migration cost estimation and phased plan","Hybrid cipher deployment guidance","Executive dashboard with risk heat map"],"benefits":["Avoids 'harvest now, decrypt later' data breaches","Meets compliance timelines (e.g., NSA CNS 2.0 deadline 2025)","Smooth transition with zero downtime"],"pricing":{"assessment":"4999","full_engagement":"contact"}},
  {"id":"it-edge-computing-deployment","href":"/it-services/edge-computing-deployment","icon":"📡","category":"it","title":"Edge Computing Deployment and Ops","description":"Deploy and manage containerized workloads on distributed edge nodes (factories, retail stores, telco sites). Unified control plane with zero-touch provisioning.","features":["Kubernetes at the edge (K3s, k0s, MicroK8s)","Over-the-air updates with rollback","Bandwidth-aware workload placement","Edge AI model serving (ONNX, TensorFlow Lite)","Offline-first operation and sync queues"],"benefits":["Reduces latency to <10ms for real-time applications","Lowers bandwidth costs by up to 60%","Enables AI inference in disconnected environments"],"pricing":{"proof_of_concept":"4999","full_deployment":"contact"}},
  {"id":"it-sustainability-dashboard","href":"/it-services/sustainability-dashboard","icon":"🌱","category":"it","title":"IT Sustainability Dashboard","description":"Track and optimize carbon footprint across your IT estate: data centers, cloud workloads, employee devices, and network. Set reduction targets and auto-generate ESG reports.","features":["Cloud carbon calculator (AWS, Azure, GCP)","Hardware lifecycle tracking (embodied carbon)","Renewable energy usage % per region","Automated sustainability recommendations","ESG report export (GRI, SASB, TCFD frameworks)"],"benefits":["Reduces carbon output by 20–35% in year 1","Meets investor ESG requirements","Saves $200K+ annually via right-sizing and reserved instance optimization"],"pricing":{"basic":"699","enterprise":"contact"}},
  {"id":"it-chaos-engineering","href":"/it-services/chaos-engineering","icon":"🌪️","category":"it","title":"Chaos Engineering as a Service","description":"Proactively test system resilience by injecting failures (VM kill, network latency, dependency outage) in production-like environments. Improve reliability before incidents happen.","features":["Custom experiment design for your architecture","Steady-state hypothesis validation","Automatic blast radius containment","Post-experiment forensic reports","Runbooks updated based on findings"],"benefits":["Reduces P0 incidents by 50% year-over-year","Builds confidence in auto-scaling and failover","Identifies single points of failure before customers do"],"pricing":{"per_experiment":"199","retainer":"2499/mo"}},
  {"id":"it-cost-optimization-platform","href":"/it-services/cost-optimization-platform","icon":"💸","category":"it","title":"Cloud Cost Optimization Platform","description":"Automated cost governance for AWS, Azure, and GCP. Right-sizes resources, eliminates waste, and enforces budgets with predictive alerts before overspend.","features":["Idle resource detection and auto-stop schedules","Reserved instance and savings plan recommendation engine","Tag-based cost allocation and showback","Anomaly detection with root-cause tagging","Custom budget thresholds with Slack and Teams alerts"],"benefits":["Saves 25–40% on cloud spend without performance hit","Prevents bill shock with 7-day spend forecast","Provides finance-grade cost reporting"],"pricing":{"basic":"299","pro":"799","enterprise":"contact"}}
]

def svc_to_block(s):
    lines = ["  {"]
    for key in ['id','href','icon','category','title','description']:
        lines.append(f'    {key}: {json.dumps(s[key], ensure_ascii=False)},')
    lines.append('    features: ' + json.dumps(s['features'], ensure_ascii=False) + ',')
    lines.append('    benefits: ' + json.dumps(s['benefits'], ensure_ascii=False) + ',')
    pricing_items = ', '.join(f"{k}: '{v}'" for k,v in s['pricing'].items())
    lines.append(f'    pricing: {{ {pricing_items} }}')
    lines.append('  }')
    return '\n'.join(lines)

ai_insert = ",\n\n" + "\n\n".join(svc_to_block(s) for s in NEW_SERVICES if s['category']=='ai')
it_insert = ",\n\n" + "\n\n".join(svc_to_block(s) for s in NEW_SERVICES if s['category']=='it')

# ── 3. Insert ─────────────────────────────────────────────────────────────────
ai_end = source.find('];', source.find('export const aiServices'))
it_end = source.find('];', source.find('export const itServices'))
source = source[:ai_end] + ai_insert + source[ai_end:]
# recalc it_end after shift
it_end = source.find('];', source.find('export const itServices'))
source = source[:it_end] + it_insert + source[it_end:]

Path('app/data/servicesData.ts').write_text(source, encoding='utf-8')

# ── 4. Verify ─────────────────────────────────────────────────────────────────
with open('app/data/servicesData.ts') as f:
    cur = f.read()
cur_ids = set(re.findall(r"id\s*:\s*'([^']+)'", cur) + re.findall(r'id\s*:\s*"([^"]+)"', cur))
newly_added = cur_ids - orig_ids
print(f"✅ New services added: {len(newly_added)}")
for nid in sorted(newly_added):
    print(f"  {nid}")
