const fs = require('fs');
const services = JSON.parse(fs.readFileSync('app/data/servicesData.json', 'utf8'));
const newServices = [
  // V214-V220 Email Intelligence companion services
  {id:'ai-sentiment-evolution-tracker-v214',title:'AI Sentiment Evolution Tracker (V214)',description:'Track sentiment changes across email threads over time. Detect relationship deterioration early with automated health scoring and proactive intervention triggers.',icon:'📈',features:['Sentiment trajectory analysis','Relationship health scoring','Trend detection (improving/declining/volatile)','Proactive intervention alerts','Emotion lexicon analysis','Predictive sentiment modeling','Multi-thread tracking','Reply-all enforcement'],benefits:['Detect relationship issues early','Score relationship health 0-100','Prevent customer churn proactively','Track sentiment trends automatically'],pricing:{basic:'349',pro:'799',enterprise:'1999'},contactInfo:{website:'/services/ai-sentiment-evolution-tracker-v214',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-sentiment-evolution-tracker-v214',category:'ai',popular:true,industry:'Relationship Intelligence'},
  
  {id:'ai-negotiation-strategist-v215',title:'AI Negotiation Strategist (V215)',description:'Real-time negotiation analysis with tactic detection, leverage scoring, BATNA assessment, and strategic counter-offer recommendations based on game theory.',icon:'♟️',features:['7 negotiation tactic detection','Leverage scoring (-1 to +1)','BATNA assessment','Optimal counter-offer generation','Concession pattern tracking','Phase detection (opening/bargaining/closing)','Game theory recommendations','Reply-all enforcement'],benefits:['Detect manipulation tactics instantly','Know your leverage position','Generate optimal counter-offers','Never accept first offer'],pricing:{basic:'499',pro:'1099',enterprise:'2999'},contactInfo:{website:'/services/ai-negotiation-strategist-v215',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-negotiation-strategist-v215',category:'ai',popular:true,industry:'Sales Intelligence'},
  
  {id:'ai-crisis-communication-v216',title:'AI Crisis Communication Engine (V216)',description:'Detect crisis situations (outages, breaches, PR, legal, financial) and auto-generate stakeholder-specific responses with escalation paths and timeline tracking.',icon:'🚨',features:['5 crisis type detection','Severity assessment (low→critical)','Auto-response generation','Stakeholder notification routing','Escalation path mapping','Key message templates','Things-to-avoid guidance','Reply-all enforcement'],benefits:['Respond to crises in minutes','Never miss a stakeholder','Follow crisis communication best practices','Meet response SLAs automatically'],pricing:{basic:'399',pro:'899',enterprise:'2499'},contactInfo:{website:'/services/ai-crisis-communication-v216',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-crisis-communication-v216',category:'ai',popular:true,industry:'Crisis Management'},
  
  {id:'ai-cultural-intelligence-v217',title:'AI Cultural Intelligence Engine (V217)',description:'Deep cultural context analysis for global communication. Detect cultural misunderstandings, suggest appropriate phrasing, and prevent cross-cultural miscommunication across 10+ regions.',icon:'🌏',features:['10+ cultural profiles','Region auto-detection','Cultural fit scoring','Taboo detection','Formality level adaptation','Communication style matching','Greeting custom guidance','Reply-all enforcement'],benefits:['Prevent cultural misunderstandings','Adapt tone per region','Build global relationships','Avoid costly cultural mistakes'],pricing:{basic:'299',pro:'699',enterprise:'1799'},contactInfo:{website:'/services/ai-cultural-intelligence-v217',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-cultural-intelligence-v217',category:'ai',popular:true,industry:'Global Business'},
  
  {id:'ai-decision-audit-trail-v218',title:'AI Decision Audit Trail (V218)',description:'Automatically document decisions from email threads with who decided what, when, rationale, and full audit trail for compliance (SOX, SOC2, ISO 27001).',icon:'📋',features:['Decision extraction (6 patterns)','Audit trail generation','Chain of custody logging','Compliance gap detection','Governance scoring','Rationale documentation','Approver tracking','Reply-all enforcement'],benefits:['Pass SOX/SOC2 audits easily','Never lose a decision record','Track who approved what','Identify governance gaps'],pricing:{basic:'399',pro:'899',enterprise:'2299'},contactInfo:{website:'/services/ai-decision-audit-trail-v218',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-decision-audit-trail-v218',category:'ai',popular:true,industry:'Compliance & Governance'},
  
  {id:'ai-energy-carbon-tracker-v219',title:'AI Email Energy & Carbon Tracker (V219)',description:'Calculate email carbon footprint, suggest optimization strategies, and generate ESG sustainability reports with tree-equivalent offset calculations.',icon:'🌱',features:['Per-email CO2 calculation','Attachment size optimization','Recipient list optimization','ESG score generation','Sustainability reporting','Carbon offset tracking','Waste category analysis','Reply-all enforcement'],benefits:['Measure email carbon footprint','Reduce environmental impact','Generate ESG reports automatically','Optimize email efficiency'],pricing:{basic:'149',pro:'349',enterprise:'799'},contactInfo:{website:'/services/ai-energy-carbon-tracker-v219',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-energy-carbon-tracker-v219',category:'ai',popular:true,industry:'ESG & Sustainability'},
  
  {id:'ai-influence-persuasion-v220',title:'AI Influence & Persuasion Analyzer (V220)',description:'Detect 8 persuasion techniques (Cialdini + urgency + framing), score influence effectiveness, flag ethical concerns, and suggest ethical persuasion strategies.',icon:'🎭',features:['8 persuasion technique detection','Influence effectiveness scoring','Ethical flag system','Persuasion diversity analysis','Strategic suggestions','Cialdini framework analysis','Manipulation detection','Reply-all enforcement'],benefits:['Detect persuasion tactics used on you','Improve your sales emails ethically','Score influence effectiveness','Flag manipulative techniques'],pricing:{basic:'299',pro:'699',enterprise:'1699'},contactInfo:{website:'/services/ai-influence-persuasion-v220',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-influence-persuasion-v220',category:'ai',popular:true,industry:'Sales & Negotiation'},
  
  {id:'ai-email-ultra-mega-suite-v214-v220',title:'AI Email Intelligence Ultra Mega Suite (V214-V220)',description:'All 7 breakthrough engines unified: Sentiment Evolution, Negotiation Strategy, Crisis Communication, Cultural Intelligence, Decision Audit, Carbon Tracking, and Influence Analysis.',icon:'👑',features:['V214: Sentiment Evolution','V215: Negotiation Strategist','V216: Crisis Communication','V217: Cultural Intelligence','V218: Decision Audit Trail','V219: Energy & Carbon Tracker','V220: Influence & Persuasion','Case-by-case analysis + Reply-all guaranteed'],benefits:['The most complete email AI platform','Every email analyzed and optimized','Enterprise compliance built-in','Unmatched email intelligence'],pricing:{basic:'1999',pro:'4499',enterprise:'11999'},contactInfo:{website:'/services/ai-email-ultra-mega-suite-v214-v220',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-email-ultra-mega-suite-v214-v220',category:'ai',popular:true,industry:'Enterprise AI'},

  // AI Services - Innovative
  {id:'ai-autonomous-agent-platform',title:'AI Autonomous Agent Platform',description:'Build and deploy autonomous AI agents that can plan, reason, use tools, and complete complex multi-step tasks without human intervention.',icon:'🤖',features:['Multi-agent orchestration','Tool-use framework','Memory and planning','Self-correction loops','Task decomposition','Progress monitoring','Human-in-the-loop override','Agent marketplace'],benefits:['Automate complex workflows end-to-end','Agents that reason and self-correct','Deploy specialized agents per task','Reduce manual work by 80%'],pricing:{basic:'599',pro:'1299',enterprise:'3499'},contactInfo:{website:'/services/ai-autonomous-agent-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-autonomous-agent-platform',category:'ai',popular:true,industry:'AI Automation'},
  
  {id:'ai-rag-knowledge-platform',title:'AI RAG Knowledge Platform',description:'Enterprise Retrieval-Augmented Generation with vector databases, document ingestion, semantic search, and hallucination detection for accurate AI answers.',icon:'🔍',features:['Vector database integration','Multi-format document ingestion','Semantic search','Hallucination detection','Citation tracking','Chunk optimization','Multi-model support','Access control per document'],benefits:['Accurate AI answers from your data','Zero hallucination with citations','Search across all documents instantly','Enterprise-grade access control'],pricing:{basic:'399',pro:'899',enterprise:'2299'},contactInfo:{website:'/services/ai-rag-knowledge-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-rag-knowledge-platform',category:'ai',popular:true,industry:'Knowledge AI'},
  
  {id:'ai-voice-agent-platform',title:'AI Voice Agent Platform',description:'Deploy AI voice agents for customer service, sales, and support. Natural conversations, sentiment detection, call routing, and CRM integration.',icon:'🎙️',features:['Natural voice conversations','Multi-language support','Sentiment detection','Call routing and transfer','CRM integration','Call analytics','Custom voice personas','24/7 availability'],benefits:['Handle 80% of calls automatically','Natural human-like conversations','Reduce call center costs 60%','Available 24/7 in any language'],pricing:{basic:'299',pro:'699',enterprise:'1799'},contactInfo:{website:'/services/ai-voice-agent-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-voice-agent-platform',category:'ai',popular:true,industry:'Voice AI'},
  
  {id:'ai-predictive-maintenance',title:'AI Predictive Maintenance Platform',description:'Predict equipment failures before they happen using sensor data, vibration analysis, thermal imaging, and ML models. Reduce unplanned downtime by 50%.',icon:'🔧',features:['Sensor data analysis','Vibration pattern detection','Thermal imaging analysis','Failure prediction models','Maintenance scheduling','Cost optimization','Asset health scoring','IoT integration'],benefits:['Predict failures weeks in advance','Reduce downtime by 50%','Optimize maintenance schedules','Extend equipment lifespan'],pricing:{basic:'699',pro:'1499',enterprise:'3999'},contactInfo:{website:'/services/ai-predictive-maintenance',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/ai-predictive-maintenance',category:'ai',popular:true,industry:'Industrial AI'},

  // IT Services
  {id:'it-platform-engineering',title:'Platform Engineering & IDP',description:'Build Internal Developer Platforms with self-service infrastructure, golden paths, service catalogs, and developer experience optimization.',icon:'🏗️',features:['Self-service infrastructure','Golden path templates','Service catalog','Developer portal','CI/CD pipeline templates','Environment provisioning','Cost visibility','Developer productivity metrics'],benefits:['Developers ship 3x faster','Self-service infrastructure','Standardize deployment patterns','Reduce ops toil by 70%'],pricing:{basic:'499',pro:'1099',enterprise:'2999'},contactInfo:{website:'/services/it-platform-engineering',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/it-platform-engineering',category:'it',popular:true,industry:'Developer Experience'},
  
  {id:'it-chaos-engineering',title:'Chaos Engineering Platform',description:'Proactively test system resilience with controlled chaos experiments. Inject failures, measure impact, and build confidence in production systems.',icon:'💥',features:['Controlled failure injection','Experiment design','Blast radius control','Automated rollback','Resilience scoring','Game day orchestration','Multi-cloud support','Compliance-safe testing'],benefits:['Find weaknesses before customers do','Build resilient systems','Reduce outage frequency 60%','Confidence in production stability'],pricing:{basic:'349',pro:'799',enterprise:'1999'},contactInfo:{website:'/services/it-chaos-engineering',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/it-chaos-engineering',category:'it',popular:true,industry:'Site Reliability'},
  
  {id:'it-gitops-platform',title:'GitOps Platform & Infrastructure',description:'Git-native infrastructure management with automated deployments, drift detection, policy enforcement, and multi-cluster GitOps workflows.',icon:'🔄',features:['Git-native deployments','Automated sync','Drift detection','Policy enforcement (OPA)','Multi-cluster management','Rollback automation','Audit logging','Secret management'],benefits:['Infrastructure as code done right','Zero-touch deployments','Detect drift automatically','Full audit trail in git'],pricing:{basic:'299',pro:'699',enterprise:'1699'},contactInfo:{website:'/services/it-gitops-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/it-gitops-platform',category:'it',popular:true,industry:'Infrastructure'},

  // Security Services
  {id:'security-soc-automation',title:'SOC Automation & SOAR Platform',description:'Automate Security Operations Center with playbooks, threat intelligence integration, automated triage, and incident response orchestration.',icon:'🛡️',features:['Automated triage','Playbook orchestration','Threat intel integration','Incident response automation','SIEM correlation','Case management','MTTR reduction','24/7 automated monitoring'],benefits:['Reduce MTTR by 80%','Automate 70% of SOC tasks','Correlate threats across sources','Scale SOC without headcount'],pricing:{basic:'799',pro:'1699',enterprise:'4499'},contactInfo:{website:'/services/security-soc-automation',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/security-soc-automation',category:'security',popular:true,industry:'Security Operations'},
  
  {id:'security-supply-chain-security',title:'Software Supply Chain Security',description:'Secure your software supply chain with SBOM generation, dependency scanning, build verification, and signature validation for all artifacts.',icon:'🔗',features:['SBOM generation','Dependency vulnerability scanning','Build verification','Artifact signing','License compliance','Pipeline security','Third-party risk assessment','SLSA compliance'],benefits:['Know every dependency','Prevent supply chain attacks','Verify build integrity','Meet SLSA requirements'],pricing:{basic:'399',pro:'899',enterprise:'2299'},contactInfo:{website:'/services/security-supply-chain-security',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/security-supply-chain-security',category:'security',popular:true,industry:'DevSecOps'},

  // Data Services
  {id:'data-vector-database-platform',title:'Vector Database Platform',description:'Managed vector database for AI applications with high-dimensional search, hybrid queries, auto-scaling, and multi-tenant support for RAG and semantic search.',icon:'🗂️',features:['High-dimensional vector search','Hybrid queries (vector + keyword)','Auto-scaling','Multi-tenant support','Real-time indexing','Backup and recovery','Monitoring and alerting','SDK for Python/JS/Go'],benefits:['Power AI applications with vectors','Sub-millisecond search latency','Scale to billions of vectors','Multi-tenant isolation'],pricing:{basic:'199',pro:'499',enterprise:'1299'},contactInfo:{website:'/services/data-vector-database-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/data-vector-database-platform',category:'data',popular:true,industry:'AI Infrastructure'},
  
  {id:'data-data-contracts-platform',title:'Data Contracts Platform',description:'Enforce data contracts between producers and consumers with schema validation, SLA monitoring, breaking change detection, and automated testing.',icon:'📜',features:['Schema validation','SLA monitoring','Breaking change detection','Automated testing','Contract registry','Producer-consumer agreements','Version management','Quality guarantees'],benefits:['Prevent data pipeline breaks','Enforce quality SLAs','Detect breaking changes early','Build trust in data products'],pricing:{basic:'249',pro:'549',enterprise:'1299'},contactInfo:{website:'/services/data-data-contracts-platform',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/data-data-contracts-platform',category:'data',popular:true,industry:'Data Quality'},

  // Micro-SaaS Services
  {id:'micro-saas-webhook-management',title:'Webhook Management & Delivery',description:'Reliable webhook delivery with retry logic, payload transformation, signature verification, and delivery monitoring. Never lose a webhook again.',icon:'🔗',features:['Reliable delivery (99.99%)','Automatic retries with backoff','Payload transformation','Signature verification','Delivery monitoring','Dead letter queues','Rate limiting','Webhook testing tools'],benefits:['Never lose a webhook','Transform payloads automatically','Verify webhook authenticity','Monitor delivery in real-time'],pricing:{basic:'29',pro:'79',enterprise:'199'},contactInfo:{website:'/services/micro-saas-webhook-management',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-webhook-management',category:'micro-saas',popular:true,industry:'API Infrastructure'},
  
  {id:'micro-saas-session-replay',title:'Session Replay & User Analytics',description:'Record and replay user sessions to understand behavior, debug issues, and optimize UX. Privacy-first with PII masking and consent management.',icon:'🎬',features:['Session recording','Heatmaps and clickmaps','Error tracking','Funnel analysis','PII auto-masking','Consent management','Performance metrics','User journey mapping'],benefits:['See exactly what users do','Debug issues by replaying','Optimize conversion funnels','Privacy-compliant recording'],pricing:{basic:'49',pro:'149',enterprise:'399'},contactInfo:{website:'/services/micro-saas-session-replay',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-session-replay',category:'micro-saas',popular:true,industry:'Product Analytics'},
  
  {id:'micro-saas-notification-center',title:'Notification Center & Inbox',description:'In-app notification center with multi-channel delivery (push, email, SMS, in-app), user preferences, and delivery analytics.',icon:'🔔',features:['In-app notification inbox','Multi-channel delivery','User preference management','Delivery analytics','Template builder','Segmentation','Scheduling','Read/unread tracking'],benefits:['Centralize all notifications','Let users choose channels','Improve engagement 3x','Track delivery rates'],pricing:{basic:'39',pro:'99',enterprise:'249'},contactInfo:{website:'/services/micro-saas-notification-center',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-notification-center',category:'micro-saas',popular:true,industry:'User Engagement'},
  
  {id:'micro-saas-feature-adoption',title:'Feature Adoption Analytics',description:'Track how users adopt new features with adoption funnels, cohort analysis, feature usage metrics, and automated onboarding nudges.',icon:'📊',features:['Adoption funnels','Cohort analysis','Feature usage metrics','Onboarding nudges','Feature discovery tips','Usage thresholds','Segment analysis','Revenue correlation'],benefits:['Measure feature adoption','Identify underused features','Drive adoption with nudges','Correlate features to revenue'],pricing:{basic:'79',pro:'199',enterprise:'499'},contactInfo:{website:'/services/micro-saas-feature-adoption',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-feature-adoption',category:'micro-saas',popular:true,industry:'Product Growth'},
  
  {id:'micro-saas-data-export-api',title:'Data Export & API Platform',description:'Give customers self-service data export with scheduled exports, API access, webhook notifications, and compliance-ready data portability.',icon:'📤',features:['Self-service export','Scheduled exports','REST API access','Webhook notifications','CSV/JSON/Parquet formats','Incremental exports','Data portability (GDPR)','Access control'],benefits:['Reduce data request tickets 80%','GDPR-compliant data portability','Scheduled automated exports','Full API access for customers'],pricing:{basic:'49',pro:'129',enterprise:'349'},contactInfo:{website:'/services/micro-saas-data-export-api',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-data-export-api',category:'micro-saas',popular:true,industry:'Data Management'},
  
  {id:'micro-saas-billing-portal',title:'Customer Billing Portal',description:'Self-service billing portal for customers to manage subscriptions, update payment methods, download invoices, and handle plan changes.',icon:'💳',features:['Self-service billing','Payment method management','Invoice downloads','Plan changes','Usage tracking','Tax documents','Dunning management','Revenue recognition'],benefits:['Reduce billing support 70%','Customers manage own billing','Reduce failed payments','Automated invoice delivery'],pricing:{basic:'49',pro:'129',enterprise:'299'},contactInfo:{website:'/services/micro-saas-billing-portal',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-billing-portal',category:'micro-saas',popular:true,industry:'Billing & Payments'},
  
  {id:'micro-saas-roadmap-voting',title:'Product Roadmap & Voting Platform',description:'Public product roadmap with feature voting, status updates, changelog integration, and customer-informed prioritization.',icon:'🗺️',features:['Public roadmap','Feature voting','Status tracking','Changelog integration','Customer segmentation','Priority scoring','Feedback collection','Release notifications'],benefits:['Build what customers want','Transparent product development','Reduce support inquiries','Data-driven prioritization'],pricing:{basic:'29',pro:'79',enterprise:'199'},contactInfo:{website:'/services/micro-saas-roadmap-voting',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-roadmap-voting',category:'micro-saas',popular:true,industry:'Product Management'},
  
  {id:'micro-saas-embeddable-analytics',title:'Embeddable Analytics Dashboards',title:'Embeddable Analytics Dashboards',description:'White-label analytics dashboards embeddable in your product. Custom charts, real-time data, row-level security, and custom branding.',icon:'📈',features:['Embeddable dashboards','Custom chart builder','Real-time data','Row-level security','White-label branding','Drill-down analytics','Export to PDF/CSV','Mobile responsive'],benefits:['Add analytics to your product in hours','White-label with your brand','Secure per-user data access','Real-time insights for customers'],pricing:{basic:'99',pro:'249',enterprise:'599'},contactInfo:{website:'/services/micro-saas-embeddable-analytics',email:'kleber@ziontechgroup.com',phone:'+1 302 464 0950'},href:'/services/micro-saas-embeddable-analytics',category:'micro-saas',popular:true,industry:'Analytics'},
];

const existing = new Set(services.map(s => s.id));
const toAdd = newServices.filter(s => !existing.has(s.id));
services.push(...toAdd);
fs.writeFileSync('app/data/servicesData.json', JSON.stringify(services, null, 2));
console.log('Added', toAdd.length, 'new services. Total:', services.length);
