#!/usr/bin/env python3
"""Wave 130-131: 20 new real services with quality advertising content."""
import json, os

DATA_FILE = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'app', 'data', 'servicesData.json')

SERVICES = [
    # Wave 130: Micro-SaaS (5)
    {"id":"w130-saas-revenue","title":"AI Revenue Recognition Automation","description":"Automate ASC 606 / IFRS 15 compliance with AI. Analyzes contracts, identifies performance obligations, and generates journal entries. Integrates with ERP systems.","features":["Contract analysis (ASC 606/IFRS 15)","Performance obligation identification","Automated journal entries","ERP integration (SAP, Oracle, NetSuite)","Audit trail & documentation","Multi-element arrangement handling","Variable consideration estimation","Disclosure report generation"],"benefits":["90% faster close cycles","Eliminate manual spreadsheet errors","Audit-ready documentation","Reduce compliance costs by 60%","Real-time revenue analytics"],"pricing":{"starter":"1297","pro":"3997","enterprise":"8997"},"icon":"📊","category":"micro-saas","popular":True,"industry":"financial-services","href":"/services/w130-saas-revenue","contactInfo":{"website":"https://ziontechgroup.com/services/w130-saas-revenue","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
    {"id":"w130-saas-hiring","title":"AI Hiring & Recruitment Platform","description":"End-to-end AI recruitment: JD writing, candidate sourcing, resume screening, interview scheduling, and offer management. Reduces time-to-hire by 65%.","features":["AI job description writing","Multi-platform candidate sourcing","Resume parsing & scoring","Automated interview scheduling","Video interview analysis","Offer letter generation","Onboarding automation","DEI analytics"],"benefits":["65% faster hiring","40% better quality of hire","Reduce recruiter workload by 70%","Improve candidate experience","Bias reduction in screening"],"pricing":{"starter":"597","pro":"1997","enterprise":"4997"},"icon":"👥","category":"micro-saas","popular":True,"industry":"hr-tech","href":"/services/w130-saas-hiring","contactInfo":{"website":"https://ziontechgroup.com/services/w130-saas-hiring","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
    {"id":"w130-saas-esg","title":"AI ESG Reporting Platform","description":"Automated ESG data collection, analysis, and report generation. Supports GRI, SASB, TCFD, and EU Taxonomy frameworks. Real-time ESG scoring.","features":["Multi-framework support (GRI/SASB/TCFD)","Automated data collection","Carbon footprint calculation","ESG scoring & benchmarking","Stakeholder engagement tracking","Regulatory compliance monitoring","Supply chain ESG auditing","Report generation"],"benefits":["80% faster ESG reporting","Real-time ESG scoring","Regulatory compliance","Investor-ready reports","Supply chain visibility"],"pricing":{"starter":"1497","pro":"4997","enterprise":"12997"},"icon":"🌱","category":"micro-saas","popular":False,"industry":"esg-and-sustainability","href":"/services/w130-saas-esg","contactInfo":{"website":"https://ziontechgroup.com/services/w130-saas-esg","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
    {"id":"w130-saas-knowledge","title":"AI Knowledge Management Platform","description":"Enterprise knowledge base with AI-powered search, auto-categorization, and intelligent recommendations. Connects to Slack, Teams, Confluence, and SharePoint.","features":["AI-powered search","Auto-categorization","Intelligent recommendations","Multi-source integration","Knowledge gap analysis","Expert identification","Content freshness scoring","Access control & governance"],"benefits":["Find answers 10x faster","Reduce duplicate work by 40%","Preserve institutional knowledge","Improve onboarding speed","Data-driven knowledge gaps"],"pricing":{"starter":"397","pro":"1297","enterprise":"3497"},"icon":"📚","category":"micro-saas","popular":False,"industry":"knowledge-management","href":"/services/w130-saas-knowledge","contactInfo":{"website":"https://ziontechgroup.com/services/w130-saas-knowledge","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
    {"id":"w130-saas-field","title":"AI Field Service Management","description":"Optimize field operations with AI scheduling, route optimization, and predictive maintenance. Mobile-first platform for technicians and dispatchers.","features":["AI scheduling & dispatch","Route optimization","Predictive maintenance alerts","Mobile technician app","Parts inventory management","Customer portal","SLA tracking","Photo/video documentation"],"benefits":["35% more jobs per day","25% fuel cost reduction","92% SLA compliance","Faster first-time fix rate","Improved customer satisfaction"],"pricing":{"starter":"797","pro":"2497","enterprise":"5997"},"icon":"🔧","category":"micro-saas","popular":False,"industry":"field-services","href":"/services/w130-saas-field","contactInfo":{"website":"https://ziontechgroup.com/services/w130-saas-field","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
    # Wave 130: IT Services (5)
    {"id":"w130-it-pentest","title":"AI Penetration Testing Service","description":"Continuous automated penetration testing with AI-driven vulnerability discovery. Combines automated scanning with expert manual testing for comprehensive security.","features":["Automated vulnerability scanning","AI attack simulation","Manual expert testing","Social engineering tests","Web & mobile app testing","Network penetration testing","Compliance reporting (PCI/HIPAA/SOC2)","Remediation guidance"],"benefits":["Continuous security monitoring","Catch vulnerabilities before attackers","Compliance-ready reports","Expert-guided remediation","Reduce breach risk by 80%"],"pricing":{"starter":"4997","pro":"14997","enterprise":"34997"},"icon":"🔓","category":"it-services","popular":True,"industry":"cybersecurity","href":"/services/w130-it-pentest","contactInfo":{"website":"https://ziontechgroup.com/services/w130-it-pentest","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
    {"id":"w130-it-identity","title":"Identity Governance & Administration (IGA)","description":"Automated identity lifecycle management, access governance, and compliance. AI-powered access reviews and anomaly detection for identity threats.","features":["Automated provisioning/deprovisioning","Access certification campaigns","Role-based access control (RBAC)","AI access anomaly detection","Segregation of duties (SoD)","Compliance reporting","Privileged access management","Multi-cloud identity federation"],"benefits":["95% faster provisioning","Continuous compliance","Reduce insider threat risk","Automated access reviews","Zero standing privileges"],"pricing":{"starter":"3997","pro":"12997","enterprise":"29997"},"icon":"🪪","category":"it-services","popular":False,"industry":"cybersecurity","href":"/services/w130-it-identity","contactInfo":{"website":"https://ziontechgroup.com/services/w130-it-identity","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
    {"id":"w130-it-dr","title":"Disaster Recovery as a Service (DRaaS)","description":"Cloud-based disaster recovery with automated failover, continuous replication, and sub-minute RTO. Protects against ransomware, outages, and natural disasters.","features":["Continuous data replication","Automated failover","Sub-minute RTO","Ransomware protection","Multi-cloud DR","Automated testing","Runbook automation","Compliance reporting"],"benefits":["Sub-minute recovery","Ransomware resilience","Automated testing","Multi-cloud protection","Compliance-ready"],"pricing":{"starter":"2997","pro":"9997","enterprise":"24997"},"icon":"🔄","category":"it-services","popular":False,"industry":"cloud-services","href":"/services/w130-it-dr","contactInfo":{"website":"https://ziontechgroup.com/services/w130-it-dr","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
    {"id":"w130-it-network","title":"AI Network Operations Center (NOC)","description":"24/7 AI-powered network monitoring, incident detection, and auto-remediation. Reduces MTTR by 75% with intelligent alerting and root cause analysis.","features":["24/7 network monitoring","AI incident detection","Auto-remediation","Root cause analysis","Capacity planning","Performance analytics","Multi-vendor support","SLA monitoring"],"benefits":["75% faster incident resolution","Proactive issue detection","Reduced downtime","Automated remediation","24/7 expert monitoring"],"pricing":{"starter":"3497","pro":"10997","enterprise":"27997"},"icon":"🌐","category":"it-services","popular":False,"industry":"network-operations","href":"/services/w130-it-network","contactInfo":{"website":"https://ziontechgroup.com/services/w130-it-network","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
    {"id":"w130-it-data","title":"Data Engineering & Pipeline Automation","description":"End-to-end data platform: ingestion, transformation, quality, and orchestration. Supports batch and real-time pipelines with AI-powered data quality.","features":["Data ingestion (batch/streaming)","ETL/ELT automation","Data quality monitoring","Schema management","Pipeline orchestration","Data cataloging","Lineage tracking","Cost optimization"],"benefits":["80% faster pipeline development","Automated data quality","Self-healing pipelines","Unified data catalog","Reduced cloud costs"],"pricing":{"starter":"2497","pro":"7997","enterprise":"19997"},"icon":"🔗","category":"it-services","popular":True,"industry":"data-engineering","href":"/services/w130-it-data","contactInfo":{"website":"https://ziontechgroup.com/services/w130-it-data","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
    # Wave 131: AI Services (5)
    {"id":"w131-ai-vision","title":"Computer Vision Platform","description":"Production-ready computer vision for manufacturing, retail, and security. Pre-trained models for defect detection, object recognition, and facial analysis.","features":["Defect detection","Object recognition","Facial analysis","OCR & document processing","Video analytics","Custom model training","Edge deployment","API & SDK access"],"benefits":["99.2% detection accuracy","Real-time processing","Edge deployment ready","Custom model support","Reduce manual inspection by 90%"],"pricing":{"starter":"1997","pro":"6997","enterprise":"16997"},"icon":"👁️","category":"ai-services","popular":True,"industry":"ai-and-ml","href":"/services/w131-ai-vision","contactInfo":{"website":"https://ziontechgroup.com/services/w131-ai-vision","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
    {"id":"w131-ai-nlp","title":"Enterprise NLP Platform","description":"Natural language processing for document understanding, sentiment analysis, entity extraction, and text classification. Pre-trained models for 50+ languages.","features":["Document understanding","Sentiment analysis","Entity extraction","Text classification","Summarization","Question answering","50+ language support","Custom model training"],"benefits":["Process documents 100x faster","50+ language support","Pre-trained enterprise models","Custom model training","API-first architecture"],"pricing":{"starter":"1497","pro":"4997","enterprise":"12997"},"icon":"🗣️","category":"ai-services","popular":False,"industry":"ai-and-ml","href":"/services/w131-ai-nlp","contactInfo":{"website":"https://ziontechgroup.com/services/w131-ai-nlp","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
    {"id":"w131-ai-predictive","title":"Predictive Analytics Platform","description":"No-code predictive analytics for business forecasting, demand planning, and risk assessment. AutoML with explainable AI and automated feature engineering.","features":["AutoML","Demand forecasting","Risk assessment","Customer churn prediction","Anomaly detection","Explainable AI","Automated feature engineering","What-if analysis"],"benefits":["No data science team needed","80% faster model deployment","Explainable predictions","Automated feature engineering","Real-time scoring"],"pricing":{"starter":"2497","pro":"7997","enterprise":"18997"},"icon":"🔮","category":"ai-services","popular":True,"industry":"ai-and-ml","href":"/services/w131-ai-predictive","contactInfo":{"website":"https://ziontechgroup.com/services/w131-ai-predictive","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
    {"id":"w131-ai-conversational","title":"Conversational AI Platform","description":"Build and deploy AI chatbots and voice assistants. Multi-channel support (web, mobile, WhatsApp, Slack) with NLU, dialogue management, and analytics.","features":["Natural language understanding","Multi-channel deployment","Dialogue management","Voice assistant support","Analytics dashboard","Human handoff","Multi-language support","Custom training"],"benefits":["Deploy in days, not months","80% query resolution","24/7 availability","Multi-language support","Seamless human handoff"],"pricing":{"starter":"997","pro":"3497","enterprise":"8997"},"icon":"💬","category":"ai-services","popular":True,"industry":"ai-and-ml","href":"/services/w131-ai-conversational","contactInfo":{"website":"https://ziontechgroup.com/services/w131-ai-conversational","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
    {"id":"w131-ai-mLOps","title":"MLOps & Model Management Platform","description":"End-to-end ML operations: model training, deployment, monitoring, and governance. Supports TensorFlow, PyTorch, and scikit-learn with automated retraining.","features":["Model training pipelines","Automated deployment","Model monitoring","Drift detection","Automated retraining","Model registry","A/B testing","Governance & compliance"],"benefits":["10x faster model deployment","Automated monitoring","Drift detection","Compliance-ready","Reduced ML costs"],"pricing":{"starter":"2997","pro":"9997","enterprise":"24997"},"icon":"⚙️","category":"ai-services","popular":False,"industry":"ai-and-ml","href":"/services/w131-ai-mlops","contactInfo":{"website":"https://ziontechgroup.com/services/w131-ai-mlops","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
    # Wave 131: Industry Solutions (5)
    {"id":"w131-ind-agritech","title":"AgriTech AI Platform","description":"Precision agriculture with AI: crop monitoring, yield prediction, pest detection, and irrigation optimization. Satellite and drone imagery analysis.","features":["Crop monitoring","Yield prediction","Pest detection","Irrigation optimization","Soil analysis","Weather integration","Drone imagery analysis","Farm management dashboard"],"benefits":["20% yield increase","30% water savings","Early pest detection","Data-driven decisions","Reduced pesticide use"],"pricing":{"starter":"1997","pro":"5997","enterprise":"14997"},"icon":"🌾","category":"agritech","popular":False,"industry":"agriculture","href":"/services/w131-ind-agritech","contactInfo":{"website":"https://ziontechgroup.com/services/w131-ind-agritech","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
    {"id":"w131-ind-construction","title":"Construction AI Management","description":"AI-powered construction management: progress monitoring, safety compliance, resource optimization, and predictive delay analysis. Drone and camera integration.","features":["Progress monitoring","Safety compliance detection","Resource optimization","Predict delays","Drone integration","Document management","Subcontractor management","Cost forecasting"],"benefits":["30% fewer delays","50% safer sites","15% cost savings","Real-time progress tracking","Automated compliance"],"pricing":{"starter":"3997","pro":"12997","enterprise":"29997"},"icon":"🏗️","category":"construction-tech","popular":False,"industry":"construction-and-engineering","href":"/services/w131-ind-construction","contactInfo":{"website":"https://ziontechgroup.com/services/w131-ind-construction","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
    {"id":"w131-ind-energy","title":"Energy Management AI","description":"Smart energy management for commercial buildings and industrial facilities. AI-powered optimization of HVAC, lighting, and renewable energy integration.","features":["HVAC optimization","Lighting control","Renewable integration","Demand response","Carbon tracking","Predictive maintenance","Utility bill analysis","ESG reporting"],"benefits":["25% energy cost reduction","30% carbon reduction","Predictive maintenance","Automated demand response","ESG compliance"],"pricing":{"starter":"2497","pro":"7997","enterprise":"19997"},"icon":"⚡","category":"energy-tech","popular":True,"industry":"energy-and-utilities","href":"/services/w131-ind-energy","contactInfo":{"website":"https://ziontechgroup.com/services/w131-ind-energy","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
    {"id":"w131-ind-logistics","title":"Autonomous Logistics Platform","description":"AI-powered logistics optimization: warehouse automation, last-mile delivery, fleet management, and supply chain visibility. Real-time tracking and predictive ETAs.","features":["Warehouse automation","Route optimization","Fleet management","Last-mile delivery","Real-time tracking","Predictive ETAs","Inventory optimization","Returns management"],"benefits":["35% delivery cost reduction","99.2% on-time delivery","Real-time visibility","Automated warehousing","Reduced returns"],"pricing":{"starter":"4997","pro":"14997","enterprise":"34997"},"icon":"🚛","category":"logistics-tech","popular":True,"industry":"logistics-supply-chain","href":"/services/w131-ind-logistics","contactInfo":{"website":"https://ziontechgroup.com/services/w131-ind-logistics","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
    {"id":"w131-ind-cyber","title":"Cybersecurity Operations Center (SOC)","description":"AI-powered 24/7 security operations center. Threat detection, incident response, vulnerability management, and compliance monitoring with human-in-the-loop.","features":["24/7 threat monitoring","AI threat detection","Incident response","Vulnerability management","SIEM/SOAR integration","Compliance monitoring","Threat intelligence","Digital forensics"],"benefits":["75% faster threat detection","24/7 expert monitoring","Automated incident response","Compliance-ready","Reduce breach risk by 85%"],"pricing":{"starter":"7997","pro":"24997","enterprise":"59997"},"icon":"🛡️","category":"cybersecurity","popular":True,"industry":"cybersecurity","href":"/services/w131-ind-cyber","contactInfo":{"website":"https://ziontechgroup.com/services/w131-ind-cyber","email":"kleber@ziontechgroup.com","phone":"+1 302 464 0950"}},
]

def main():
    with open(DATA_FILE, 'r') as f:
        data = json.load(f)
    existing = {s['id'] for s in data}
    added = skipped = 0
    for s in SERVICES:
        if s['id'] in existing:
            skipped += 1; continue
        data.append(s); added += 1
    with open(DATA_FILE, 'w') as f:
        json.dump(data, f, indent=2)
    print(f"✅ Added {added}, skipped {skipped}. Total: {len(data)}")

if __name__ == "__main__":
    main()
