#!/usr/bin/env python3
"""Insert Waves 69, 70, 71 — 20 new services into servicesData.json"""
import json

path = "/data/data/com.termux/files/home/zion-support.github.io/app/data/servicesData.json"
with open(path) as f:
    services = json.load(f)

def svc(sid, title, desc, features, benefits, pricing, icon, cat, pop, industry):
    return {"id": sid, "title": title, "description": desc,
            "features": features, "benefits": benefits,
            "pricing": {"basic": pricing[0], "pro": pricing[1], "enterprise": pricing[2]},
            "contactInfo": {"website": "https://ziontechgroup.com", "email": "kleber@ziontechgroup.com", "phone": "+1 302 464 0950"},
            "icon": icon, "category": cat, "popular": pop,
            "href": f"/services/{sid}", "industry": industry}

new = [
    svc("ai-customer-effort-score","AI Customer Effort Score Analyzer","Measures and reduces customer effort from email interactions. Features friction detection, resolution path analysis, and automated process improvement. Reduces effort score by 35%.",["Friction detection","Resolution path analysis","Process improvement","Journey mapping","Automated suggestions"],["35% less effort","Better CX","Reduced churn","Process optimization"],("$399/mo","$1,199/mo","Custom"),"Gauge","ai","True","Customer Experience"),
    svc("ai-knowledge-graph-builder","AI Knowledge Graph Builder","Builds enterprise knowledge graphs from email, documents, and databases. Features entity extraction, relationship mapping, and semantic search. Connects siloed organizational knowledge.",["Entity extraction","Relationship mapping","Semantic search","Document analysis","Database connection","Visual exploration"],["Connected knowledge","Faster discovery","Silo breakdown","Semantic insights"],("$999/mo","$2,999/mo","Custom"),"GitFork","ai","True","Technology"),
    svc("ai-pricing-strategy-engine","AI Pricing Strategy Engine","Optimizes B2B SaaS and service pricing using email negotiation data, market signals, and WTP analysis. Features competitive pricing, value-based modeling, and A/B price testing.",["WTP analysis","Competitive pricing","Value-based modeling","Price testing","Email negotiation data","Revenue optimization"],["12% revenue increase","Better pricing","Competitive positioning","Value capture"],("$499/mo","$1,499/mo","Custom"),"DollarSign","ai","True","Strategy"),
    svc("ai-supplier-risk-monitor","AI Supplier Risk Monitoring Platform","Real-time supplier risk scoring using news, financial data, geopolitical signals, and email intelligence. Features early warning alerts, alternative sourcing, and risk dashboards.",["Real-time risk scoring","News monitoring","Financial health","Geopolitical risk","Early warning","Alternative sourcing"],["Risk visibility","Supply chain resilience","Early warning","Alternative sources"],("$1,199/mo","$3,499/mo","Custom"),"AlertTriangle","ai","True","Supply Chain"),
    svc("ai-conversational-commerce","AI Conversational Commerce Platform","AI-powered shopping assistant for e-commerce. Features natural language product discovery, personalized recommendations, and checkout via chat. Increases conversion by 45%.",["NLP product search","Personal recommendations","Chat checkout","Order tracking","Abandoned cart recovery","Multi-platform"],["45% higher conversion","Personalized shopping","Cart recovery","24/7 support"],("$349/mo","$999/mo","Custom"),"MessageSquare","ai","True","E-Commerce"),
    svc("ai-data-retention-manager","AI Data Retention Policy Manager","Automates data lifecycle management across email, databases, and file stores. Features policy enforcement, GDPR/CCPA compliance, and cost optimization. Reduces storage costs by 40%.",["Policy enforcement","Lifecycle management","GDPR/CCPA compliance","Storage optimization","Classification automation","Audit reporting"],["40% storage savings","Compliance automation","Policy enforcement","Audit readiness"],("$599/mo","$1,799/mo","Custom"),"Database","saas","True","Compliance"),
    svc("ai-employee-onboarding-ai","AI Employee Onboarding Platform","Personalized onboarding journeys using AI. Features role-specific learning paths, automated buddy matching, progress tracking, and engagement scoring. Reduces time-to-productivity by 50%.",["Personalized journeys","Learning paths","Buddy matching","Progress tracking","Engagement scoring","HRIS integration"],["50% faster productivity","Better engagement","Personalized experience","Automated tracking"],("$29/employee/mo","$59/employee/mo","Custom"),"UserPlus","saas","True","Human Resources"),
    svc("ai-cryptocurrency-compliance","AI Cryptocurrency Compliance Platform","AML/KYC compliance platform for crypto exchanges and DeFi. Features transaction monitoring, wallet screening, and regulatory reporting across 40+ jurisdictions.",["Transaction monitoring","Wallet screening","AML/KYC","Regulatory reporting","40+ jurisdictions","Risk scoring"],["Compliance assurance","Fraud prevention","Multi-jurisdiction","Risk visibility"],("$1,999/mo","$5,999/mo","Custom"),"Wallet","saas","True","Finance"),
    svc("ai-predictive-maintenance-maritime","AI Maritime Predictive Maintenance","Predictive maintenance for ships and offshore equipment. Features engine monitoring, hull integrity analysis, and voyage-specific maintenance planning. Reduces downtime by 45%.",["Engine monitoring","Hull integrity","Voyage planning","Spare parts prediction","Dry dock optimization","Classification compliance"],["45% less downtime","Optimized maintenance","Parts prediction","Compliance"],("$2,499/mo","$7,499/mo","Custom"),"Ship","ai","True","Maritime"),
    svc("ai-voc-platform","AI Voice of Customer Platform","Analyzes customer feedback from emails, surveys, and support tickets using NLP. Features topic clustering, sentiment tracking, and actionable insight generation.",["NLP feedback analysis","Topic clustering","Sentiment tracking","Actionable insights","Survey integration","Support ticket analysis"],["Faster insight","Customer-centric","Topic visibility","Actionable feedback"],("$349/mo","$999/mo","Custom"),"MessageCircle","ai","True","Customer Experience"),
    svc("ai-edge-ml-deployer","AI Edge ML Deployment Platform","Deploy and manage ML models on edge devices (IoT, mobile, embedded). Features model optimization, OTA updates, and monitoring. Supports NVIDIA Jetson, Raspberry Pi, and custom hardware.",["Model optimization","Edge deployment","OTA updates","Monitoring","Multi-hardware","A/B model testing"],["Low latency","Offline inference","Easy deployment","Device management"],("$499/mo","$1,499/mo","Custom"),"Cpu","automation","True","Technology"),
    svc("ai-rental-property-optimizer","AI Rental Property Management Platform","ML platform for rental property optimization. Features rent pricing, tenant screening, maintenance prediction, and vacancy reduction. Increases NOI by 18%.",["Rent pricing optimization","Tenant screening","Maintenance prediction","Vacancy reduction","Lease analytics","Owner dashboards"],["18% higher NOI","Better tenants","Reduced vacancies","Predictive maintenance"],("$99/mo","$299/mo","Custom"),"Home","ai","True","Real Estate"),
    svc("ai-food-safety-compliance","AI Food Safety Compliance Platform","Computer vision and IoT platform for food safety compliance. Detects hygiene violations, monitors temperatures, and automates HACCP documentation. Reduces violations by 75%.",["Hygiene violation detection","Temperature monitoring","HACCP documentation","IoT sensors","Automated alerts","Audit trail"],["75% fewer violations","HACCP compliance","Automated documentation","Audit readiness"],("$399/mo","$1,199/mo","Custom"),"ShieldCheck","automation","True","Food and Beverage"),
    svc("ai-music-licensing-platform","AI Music Licensing and Royalty Platform","Blockchain-based music licensing with AI-powered content identification. Features automatic royalty distribution, usage tracking, and rights management for creators and publishers.",["Content ID","Royalty distribution","Usage tracking","Rights management","Blockchain licensing","Creator dashboards"],["Fair compensation","Automated licensing","Usage transparency","Creator empowerment"],("5% of licensing","3% of licensing","Custom"),"Music","saas","True","Entertainment"),
    svc("ai-cyber-insurance-assessor","AI Cyber Insurance Risk Assessor","Assesses cyber insurance risk from email security posture, infrastructure data, and incident history. Features automated underwriting and continuous risk monitoring.",["Security assessment","Automated underwriting","Continuous monitoring","Incident history","Infrastructure analysis","Risk scoring"],["Better risk selection","Automated assessment","Continuous monitoring","Accurate pricing"],("$799/mo","$2,499/mo","Custom"),"ShieldAlert","ai","True","Insurance"),
    svc("ai-veterinary-diagnostics","AI Veterinary Diagnostics Platform","Computer vision and ML platform for veterinary diagnostics. Analyzes X-rays, ultrasound, and blood work with 94% accuracy. Covers dogs, cats, horses, and livestock.",["X-ray analysis","Ultrasound","Blood work","94% accuracy","Multi-species","Treatment suggestions"],["Faster diagnosis","94% accuracy","Multi-species","Treatment support"],("$149/mo","$449/mo","Custom"),"HeartPulse","ai","True","Veterinary"),
    svc("ai-waste-reduction-platform","AI Industrial Waste Reduction Platform","ML platform that analyzes production data to minimize waste. Features material optimization, process adjustment, and circular economy scoring. Reduces waste by 35%.",["Material optimization","Process adjustment","Waste scoring","Circular economy","Production analytics","Supplier coordination"],["35% waste reduction","Cost savings","Circular metrics","Process efficiency"],("$599/mo","$1,799/mo","Custom"),"Recycle","ai","True","Manufacturing"),
    svc("ai-personalized-nutrition","AI Personalized Nutrition Platform","AI nutrition platform that creates personalized meal plans from health data, preferences, and goals. Features grocery integration, macro tracking, and dietitian collaboration.",["Personalized plans","Health data integration","Grocery integration","Macro tracking","Dietitian portal","Goal tracking"],["Better outcomes","Personalized plans","Easy tracking","Expert collaboration"],("$19/mo","$49/mo","Custom"),"Apple","saas","True","Health and Wellness"),
    svc("ai-construction-safety-v2","AI Construction Safety Platform v2","Advanced construction safety with computer vision, wearable sensors, and predictive analytics. Detects hazards in real-time and predicts incidents before they happen. Reduces incidents by 65%.",["Computer vision safety","Wearable sensors","Incident prediction","Real-time alerts","OSHA compliance","Safety scoring"],["65% fewer incidents","Real-time protection","Predictive safety","OSHA compliance"],("$799/mo","$2,499/mo","Custom"),"HardHat","automation","True","Construction"),
]

services.extend(new)
with open(path, 'w') as f:
    json.dump(services, f, indent=2)
print(f"Added {len(new)}. Total: {len(services)}")
