#!/usr/bin/env node
/**
 * pipeline-metrics.cjs – Generate a daily CI pipeline metrics report.
 *
 * The script retrieves the last 30 workflow runs for the repository,
 * calculates success/failure percentages, average duration, and
 * generates a Markdown report in `reports/ci-metrics.md`.
 *
 * It uses the GitHub REST API via @octokit/rest.
 *
 * Environment variables:
 *   GITHUB_TOKEN – PAT with repo scope
 *   REPO_OWNER   – repository owner
 *   REPO_NAME    – repository name
 */

require('dotenv').config();
const { Octokit } = require('@octokit/rest');
const fs = require('fs');
const path = require('path');

const { GITHUB_TOKEN, REPO_OWNER, REPO_NAME } = process.env;
if (!GITHUB_TOKEN || !REPO_OWNER || !REPO_NAME) {
  console.error('❌ Missing required environment variables.');
  process.exit(1);
}

const octokit = new Octokit({ auth: GITHUB_TOKEN });

async function fetchRuns() {
  console.log(`Fetching runs for ${REPO_OWNER}/${REPO_NAME}`);
  // Use listWorkflowRunsForRepo to get recent runs without specifying a workflow ID
  const { data } = await octokit.request('GET /repos/{owner}/{repo}/actions/runs', {
    owner: REPO_OWNER,
    repo: REPO_NAME,
    per_page: 30,
  });
  return data.workflow_runs;
}

function generateReport(runs) {
  const total = runs.length;
  const success = runs.filter(r => r.conclusion === 'success').length;
  const failure = runs.filter(r => r.conclusion === 'failure').length;
  const duration = runs.reduce((acc, r) => acc + (r.run_attempt || 0), 0) / total;

  const report = `# CI Pipeline Metrics Report - ${new Date().toISOString().split('T')[0]}

## Summary
- **Total Runs:** ${total}
- **Success Rate:** ${((success / total) * 100).toFixed(1)}%
- **Failure Rate:** ${((failure / total) * 100).toFixed(1)}%
- **Avg. Duration:** ${duration.toFixed(1)} seconds

## Runs
${runs.map(r => `- [${r.name}](https://github.com/${REPO_OWNER}/${REPO_NAME}/actions/runs/${r.id}) – ${r.status} (${r.conclusion || 'pending'})`).join('\n')}

---
Generated by \`pipeline-metrics.cjs\`
`;

  return report;
}

async function main() {
  try {
    const runs = await fetchRuns();
    const report = generateReport(runs);
    const reportPath = path.join(process.cwd(), 'reports', 'ci-metrics.md');
    fs.mkdirSync(path.dirname(reportPath), { recursive: true });
    fs.writeFileSync(reportPath, report);
    console.log('📊 CI metrics report generated:', reportPath);
  } catch (err) {
    console.error('❌ Error:', err.message);
    process.exit(1);
  }
}

main();