// Auto-Fix PR Generator — creates draft PRs with suggested fixes for quality issues
// Works alongside quality-audit.cjs; run after audit completes
// Uses GitHub CLI (gh) if available, otherwise writes draft PR files for manual submission
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const REPORT_DIR = path.join(process.cwd(), 'automation', 'reports', 'quality');
const PR_DIR = path.join(process.cwd(), 'automation', 'quality-prs');

function loadLatestReport() {
  const files = fs.readdirSync(REPORT_DIR).filter(f => f.startsWith('audit-')).sort().reverse();
  if (files.length === 0) throw new Error('No audit reports found');
  return JSON.parse(fs.readFileSync(path.join(REPORT_DIR, files[0]), 'utf8'));
}

function generateFixSuggestions(service, issues) {
  const fixes = [];
  const issuesSet = new Set(issues);

  if (issuesSet.has('Features section may not render')) {
    fixes.push('Ensure ServiceLayout renders features.map() — verify features prop passed correctly');
  }
  if (issuesSet.has('Benefits section may not render')) {
    fixes.push('Ensure ServiceLayout renders benefits list — check benefits prop');
  }
  if (issuesSet.has('Pricing section may not render')) {
    fixes.push('Verify pricing Object.entries loop in ServiceLayout renders all tiers');
  }
  if (issuesSet.has('Contact info may not render')) {
    fixes.push('Check contactInfo rendering: phone link with tel:, email with mailto:');
  }
  if (issuesSet.has('Missing metadata export (SEO)')) {
    fixes.push('Add `export const metadata = { title, description, icons }` to page.tsx');
  }
  if (issuesSet.has('Phone number missing')) {
    fixes.push('Ensure <Link href={`tel:+13024640950`}> displayed in contact section');
  }
  if (issuesSet.has('Email missing')) {
    fixes.push('Ensure <Link href={`mailto:kleber@ziontechgroup.com`}> displayed');
  }
  if (issues.some(i => i.includes('Broken internal link'))) {
    fixes.push('Fix broken href paths — verify target route files exist');
  }
  if (issuesSet.has('Debug statements present')) {
    fixes.push('Remove console.error / console.log / debugger statements');
  }
  if (issuesSet.has('ServiceLayout not imported/used')) {
    fixes.push('Import and wrap page content with <ServiceLayout service={service} />');
  }
  if (fixes.length === 0) {
    fixes.push('General: review page content alignment with ServiceLayout expectations');
  }
  return fixes;
}

function createPR(service, analysis, fixes) {
  const prNumber = Date.now();
  const prTitle = `fix(quality): improve quality score for ${service.title} (${analysis.score}/100)`;
  
  const body = `## Quality Audit — Fix Required

**Service:** ${service.title}
**Route:** ${service.href}
**Current Score:** ${analysis.score}/100
**Date:** ${new Date().toLocaleDateString()}

### Detected Issues
${analysis.issues.map(i => `- [ ] ${i}`).join('
')}

### Suggested Fixes
${fixes.map(f => `- ${f}`).join('
')}

### Verification Steps
1. Run local type-check: npm run type-check
2. Preview page locally at http://localhost:3000${service.href}
3. Ensure all required sections render (features, benefits, pricing, contact)
4. Confirm SEO metadata present
5. Check for no console errors in browser devtools

---
*Auto-generated by Quality Auditor*
*Automation/quality-prs/${service.id}-${prNumber}.md*`.trim();

  fs.mkdirSync(PR_DIR, { recursive: true });
  const prFile = path.join(PR_DIR, `${service.id}-${prNumber}.md`);
  fs.writeFileSync(prFile, body);
  console.log(`✓ Draft PR created: ${prFile}`);
  return prFile;
}

async function main() {
  try {
    const report = loadLatestReport();
    console.log(`Loaded audit: ${report.averageScore}/100 avg, ${report.failed} failing`);

    const failing = report.results.filter(r => r.score < 80);
    if (failing.length === 0) {
      console.log('No services need fixes — all healthy!');
      return;
    }

    console.log(`Generating fix PRs for ${failing.length} services...`);

    for (const item of failing) {
      const fixes = generateFixSuggestions(item.service, item.issues);
      createPR(item.service, item, fixes);
    }

    console.log(`Done. ${failing.length} PR drafts in ${PR_DIR}`);
  } catch (err) {
    console.error('Error:', err.message);
    process.exit(1);
  }
}

main();
