#!/usr/bin/env bash
set -e
cd $(git rev-parse --show-toplevel)
# Run npm audit in JSON mode
echo "Running npm audit..."
npm audit --json > audit.json || true
VULNS=$(jq -r '.metadata.vulnerabilities.total // 0' audit.json)
if [ "$VULNS" -eq 0 ]; then
  echo "✅ No vulnerabilities found"
  exit 0
fi
echo "⚠️ Found $VULNS vulnerabilities – attempting auto‑fix"
# Try safe fixes (patch/minor only, no major upgrades)
npm audit fix --audit-level=moderate || true
# If lockfile changed, create PR
if git diff --quiet package-lock.json; then
  echo "⚠️ Auto‑fix did not change lockfile – manual review needed"
  gh issue create -t "Dependency vulnerabilities require manual fix" -b "npm audit reported $VULNS issues. Auto‑fix did not resolve them. See audit.json for details."
else
  git checkout -B security-fix-$(date +%s)
  git add package.json package-lock.json audit.json
  git commit -m "fix: auto‑resolve dependency vulnerabilities"
  git push -f origin HEAD
  gh pr create -B main -t "fix: auto‑resolve dependency vulnerabilities" -b "Automated PR generated by security_scanner.sh"
  echo "✅ PR created for security fixes"
fi
