import { AI_LAB_TOOLS } from '../ai-lab/ai-lab-tools';

export interface WhatsNewItem {
  id: string;
  title: string;
  description: string;
  href: string;
  tag: string;
}

const aiLabWhatsNew: WhatsNewItem[] = AI_LAB_TOOLS.filter((tool) => tool.status === 'live').map((tool) => ({
  id: tool.id,
  title: tool.title,
  description: tool.shortDescription,
  href: tool.href,
  tag:
    tool.badge ??
    (tool.status === 'live' ? 'AI Lab' : tool.status === 'experimental' ? 'Experimental' : 'Planned'),
}));

const appWhatsNew: WhatsNewItem[] = [
  {
    id: 'cookie-decoder',
    title: 'Cookie Decoder & Analyzer',
    description: 'Parse HTTP Cookie and Set-Cookie headers, inspect attributes (Secure, HttpOnly, SameSite, Max-Age, Domain, Path), and audit security with critical/warning recommendations and a 0-100 security score.',
    href: '/tools/cookie-decoder',
    tag: 'New tool',
  },
  {
    id: 'json-schema-generator',
    title: 'JSON Schema Generator',
    description: 'Generate JSON Schema (2020-12 draft) and TypeScript interfaces from sample JSON data. Smart format detection for emails, URLs, dates, UUIDs, phone numbers. Configurable options and downloadable output.',
    href: '/tools/json-schema-generator',
    tag: 'New tool',
  },
  {
    id: 'json-to-zod',
    title: 'JSON to Zod Converter',
    description: 'Convert JSON to Zod validation schemas with smart type detection for emails, URLs, dates, and UUIDs. Supports strict/passthrough modes and auto-generates TypeScript types.',
    href: '/tools/json-to-zod',
    tag: 'New tool',
  },
  {
    id: 'hash-identifier',
    title: 'Hash Identifier',
    description: 'Identify hash types across 25+ algorithms with security analysis. Supports MD5, SHA family, bcrypt, Argon2, scrypt, NTLM, BLAKE2, SHA-3, and more.',
    href: '/tools/hash-identifier',
    tag: 'New tool',
  },
  {
    id: 'cron-expression-parser',
    title: 'Cron Expression Parser',
    description: 'Parse, validate, and understand cron schedule expressions with human-readable descriptions, field breakdowns, and upcoming run times. Includes 10 presets and full format reference.',
    href: '/tools/cron-expression-parser',
    tag: 'New tool',
  },
  {
    id: 'url-encoder-decoder',
    title: 'URL Encoder / Decoder',
    description: 'Encode or decode URLs, URI components, and query strings. Supports Full URL, Component, and Query String modes with batch processing, swap, and quick examples.',
    href: '/tools/url-encoder-decoder',
    tag: 'New tool',
  },
  {
    id: 'base32-encoder-decoder',
    title: 'Base32 Encoder / Decoder',
    description: 'Encode and decode text to Base32 — the standard used in TOTP 2FA secrets, DNS records, and recovery keys. Supports Base32Hex variant with examples and instant copy.',
    href: '/tools/base32-encoder-decoder',
    tag: 'New tool',
  },
  {
    id: 'css-unit-converter',
    title: 'CSS Unit Converter',
    description: 'Convert between px, rem, em, vw, vh, pt, and more with configurable root font-size and viewport dimensions. Includes presets, quick CSS copy, and unit reference.',
    href: '/tools/css-unit-converter',
    tag: 'New tool',
  },
  {
    id: 'svg-path-editor',
    title: 'SVG Path Editor',
    description: 'Edit, validate, and optimize SVG path data with live preview, command breakdown, zoom controls, and CSS/SVG export. Includes style controls and path statistics.',
    href: '/tools/svg-path-editor',
    tag: 'New tool',
  },
  {
    id: 'meta-tag-generator',
    title: 'Meta Tag Generator',
    description: 'Generate Open Graph, Twitter Card, and SEO meta tags with live social preview, SEO scoring, JSON-LD structured data, and one-click copy. Includes presets for common page types.',
    href: '/tools/meta-tag-generator',
    tag: 'New tool',
  },
  {
    id: 'xml-formatter-validator',
    title: 'XML Formatter & Validator',
    description: 'Pretty-print or minify XML with real-time validation, error details, element/attribute stats, and configurable indentation. 100% client-side.',
    href: '/tools/xml-formatter-validator',
    tag: 'New tool',
  },
  {
    id: 'hmac-generator',
    title: 'HMAC Signature Generator',
    description: 'Generate HMAC-SHA256/384/512 signatures for webhook verification, API request signing, and JWT generation. Includes verification snippets.',
    href: '/tools/hmac-generator',
    tag: 'New tool',
  },
  {
    id: 'markdown-table-generator',
    title: 'Markdown Table Generator',
    description: 'Convert CSV or TSV data to Markdown tables, ASCII tables, or HTML with live preview, alignment controls, and instant export.',
    href: '/tools/markdown-table-generator',
    tag: 'New tool',
  },
  {
    id: 'dns-lookup',
    title: 'DNS Record Lookup',
    description: 'Query DNS records for any domain — A, AAAA, MX, TXT, NS, CNAME, SOA, and CAA records. 100% client-side via Google Public DNS.',
    href: '/tools/dns-lookup',
    tag: 'New tool',
  },
  {
    id: 'string-case-converter',
    title: 'String Case Converter',
    description: 'Convert text between camelCase, snake_case, PascalCase, kebab-case, CONSTANT_CASE, and more — with instant copy.',
    href: '/tools/string-case-converter',
    tag: 'New tool',
  },
  {
    id: 'yaml-json-converter',
    title: 'YAML ↔ JSON Converter',
    description: 'Convert between YAML and JSON instantly with live preview. 100% client-side — your data never leaves the browser.',
    href: '/tools/yaml-json-converter',
    tag: 'New tool',
  },
  {
    id: 'json-to-typescript-converter',
    title: 'JSON to TypeScript Converter',
    description: 'Convert JSON data to TypeScript interfaces instantly with AI-powered type inference.',
    href: '/tools/json-to-typescript-converter',
    tag: 'New tool',
  },
  {
    id: 'regex-generator',
    title: 'Regex Generator',
    description: 'Generate regular expressions from natural language and test them with live examples.',
    href: '/tools/regex-generator',
    tag: 'New tool',
  },
  {
    id: 'json-formatter-validator',
    title: 'JSON Formatter & Validator',
    description: 'Format, validate, minify, and compare JSON data with syntax highlighting and error detection.',
    href: '/tools/json-formatter-validator',
    tag: 'New tool',
  },
  {
    id: 'ai-log-analyzer',
    title: 'AI Log Analyzer',
    description: 'AI-powered log analysis with instant error detection, pattern recognition, and debugging recommendations.',
    href: '/tools/ai-log-analyzer',
    tag: 'New tool',
  },
  {
    id: 'document-analyzer',
    title: 'AI Document Analyzer',
    description: 'Upload documents for instant AI-powered analysis and insights',
    href: '/tools/document-analyzer',
    tag: 'New tool',
  },
  {
    id: 'api-response-tester',
    title: 'API Response Time Tester',
    description: 'Test API endpoint response times and analyze performance with visual metrics.',
    href: '/tools/api-response-tester',
    tag: 'New tool',
  },
  {
    id: 'code-complexity-analyzer',
    title: 'AI Code Complexity Analyzer',
    description: 'Analyze code complexity, maintainability scores, and get AI-powered refactoring suggestions.',
    href: '/tools/code-complexity-analyzer',
    tag: 'New tool',
  },
  {
    id: 'cron-expression-explainer',
    title: 'Cron Expression Explainer',
    description: 'Understand what your cron expressions mean in plain English with visual breakdowns and examples.',
    href: '/tools/cron-expression-explainer',
    tag: 'New tool',
  },
  {
    id: 'autonomous-seo-audit-agent',
    title: 'Autonomous SEO Audit Agent',
    description: 'AI-powered SEO audits with instant scoring for meta tags, content, and performance.',
    href: '/ai-lab/autonomous-seo-audit-agent',
    tag: 'AI Lab',
  },
  {
    id: 'productivity-score-calculator',
    title: 'AI Productivity Score Calculator',
    description: 'Measure team productivity potential with AI adoption and get efficiency scoring.',
    href: '/tools/productivity-score-calculator',
    tag: 'New tool',
  },
  {
    id: 'meeting-cost-calculator',
    title: 'Meeting Cost Calculator',
    description: 'Understand the true cost of meetings and see potential savings with AI improvements.',
    href: '/tools/meeting-cost-calculator',
    tag: 'New tool',
  },
  {
    id: 'roi-calculator',
    title: 'AI ROI Calculator',
    description: 'Calculate the return on investment for implementing AI tools in your organization.',
    href: '/tools/roi-calculator',
    tag: 'New tool',
  },
  {
    id: 'zion-ai-chatbot-playground',
    title: 'Zion AI Chatbot Playground',
    description: 'In-browser conversational prototype and UX testing playground.',
    href: '/zion-ai-chatbot-playground',
    tag: 'New app',
  },
  {
    id: 'zion-ai-code-sandbox',
    title: 'Zion AI Code Sandbox',
    description: 'Interactive code analysis and prompt-to-code experimentation space.',
    href: '/zion-ai-code-sandbox',
    tag: 'New app',
  },
  {
    id: 'ai-system-health-monitor',
    title: 'AI System Health Monitor',
    description: 'Real-time system monitoring with autonomous optimization insights.',
    href: '/ai-system-health-monitor',
    tag: 'New feature',
  },
  {
    id: 'smart-analytics-dashboard',
    title: 'Smart Analytics Dashboard',
    description: 'Predictive analytics and business intelligence command center.',
    href: '/smart-analytics',
    tag: 'Analytics',
  },
  {
    id: 'ai-live-ux-auto-fix',
    title: 'AI Live Site UX Auto-Fix Agent',
    description: 'Autonomous UX issue discovery and safe implementation pipeline.',
    href: '/automation',
    tag: 'Automation',
  },
  {
    id: 'color-palette-generator',
    title: 'Color Palette Generator',
    description: 'Generate harmonious color palettes from any base color with WCAG accessibility checks and CSS/JSON export.',
    href: '/tools/color-palette-generator',
    tag: 'New tool',
  },
  {
    id: 'markdown-to-html',
    title: 'Markdown to HTML Converter',
    description: 'Convert Markdown to styled HTML instantly with live preview, copy output, and download as a complete HTML document.',
    href: '/tools/markdown-to-html',
    tag: 'New tool',
  },
  {
    id: 'diff-checker',
    title: 'Text Diff Checker',
    description: 'Compare two blocks of text side-by-side with color-coded additions, removals, and LCS-based diffing.',
    href: '/tools/diff-checker',
    tag: 'New tool',
  },
  {
    id: 'url-encoder-decoder',
    title: 'URL Encoder / Decoder',
    description: 'Encode or decode URLs and URL components instantly. Supports full URL and component modes with live output.',
    href: '/tools/url-encoder-decoder',
    tag: 'New tool',
  },
  {
    id: 'uuid-generator',
    title: 'UUID Generator',
    description: 'Generate cryptographically unique identifiers — UUID v4 (random) or v7 (time-ordered), bulk export, and format options.',
    href: '/tools/uuid-generator',
    tag: 'New tool',
  },
  {
    id: 'timestamp-converter',
    title: 'Timestamp Converter',
    description: 'Convert between Unix timestamps, ISO 8601, and human-readable dates. Live clock, auto-detect, and time difference calculator.',
    href: '/tools/timestamp-converter',
    tag: 'New tool',
  },
  {
    id: 'http-status-lookup',
    title: 'HTTP Status Code Lookup',
    description: 'Interactive reference for HTTP status codes with detailed explanations, RFC references, and usage tips.',
    href: '/tools/http-status-lookup',
    tag: 'New tool',
  },
  {
    id: 'box-shadow-generator',
    title: 'CSS Box Shadow Generator',
    description: 'Create beautiful CSS box shadows with live preview, layer support, presets, and instant export.',
    href: '/tools/box-shadow-generator',
    tag: 'New tool',
  },
  {
    id: 'color-converter',
    title: 'Color Converter',
    description: 'Convert colors between HEX, RGB, HSL, and CMYK with live preview, color harmonies, and CSS export.',
    href: '/tools/color-converter',
    tag: 'New tool',
  },
  {
    id: 'json-diff-viewer',
    title: 'JSON Diff Viewer',
    description: 'Compare two JSON objects side-by-side with structural diffing, filter by change type, and copy results.',
    href: '/tools/json-diff-viewer',
    tag: 'New tool',
  },
  {
    id: 'html-minifier-beautifier',
    title: 'HTML Minifier / Beautifier',
    description: 'Minify HTML for production or beautify for readability with live stats and size savings.',
    href: '/tools/html-minifier-beautifier',
    tag: 'New tool',
  },
  {
    id: 'password-generator',
    title: 'Password Generator',
    description: 'Generate cryptographically secure passwords with customizable length, character types, and strength meter.',
    href: '/tools/password-generator',
    tag: 'New tool',
  },
  {
    id: 'base64-encoder-decoder',
    title: 'Base64 Encoder / Decoder',
    description: 'Encode or decode text and files to/from Base64 with file upload, download, and character count stats.',
    href: '/tools/base64-encoder-decoder',
    tag: 'New tool',
  },
  {
    id: 'url-slug-generator',
    title: 'URL Slug Generator',
    description: 'Convert any text to clean, SEO-friendly URL slugs with case variants, stop word removal, and live preview.',
    href: '/tools/url-slug-generator',
    tag: 'New tool',
  },
  {
    id: 'csv-json-converter',
    title: 'CSV ↔ JSON Converter',
    description: 'Convert between CSV and JSON formats instantly with file upload, smart quoting, and download support.',
    href: '/tools/csv-json-converter',
    tag: 'New tool',
  },
  {
    id: 'env-file-parser',
    title: 'Env File Parser',
    description: 'Parse, edit, and generate .env files with auto secret detection, inline editing, and .env.example export.',
    href: '/tools/env-file-parser',
    tag: 'New tool',
  },
  {
    id: 'jwt-decoder',
    title: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens with header, payload, and signature breakdown. Expiration tracking and copy support.',
    href: '/tools/jwt-decoder',
    tag: 'New tool',
  },
  {
    id: 'cron-generator',
    title: 'Cron Expression Generator',
    description: 'Build cron expressions visually with presets, plain-English descriptions, and upcoming run time previews.',
    href: '/tools/cron-generator',
    tag: 'New tool',
  },
  {
    id: 'css-gradient-generator',
    title: 'CSS Gradient Generator',
    description: 'Create beautiful linear, radial, and conic CSS gradients with live preview, color stops, presets, and instant CSS export.',
    href: '/tools/css-gradient-generator',
    tag: 'New tool',
  },
  {
    id: 'regex-tester',
    title: 'Regex Tester',
    description: 'Test regular expressions with real-time match highlighting, capture group inspection, common pattern presets, and a quick reference cheat sheet.',
    href: '/tools/regex-tester',
    tag: 'New tool',
  },
  {
    id: 'chmod-calculator',
    title: 'Chmod Permission Calculator',
    description: 'Visually build Unix file permissions with owner/group/other controls, special bits, 12 presets, and instant chmod command output.',
    href: '/tools/chmod-calculator',
    tag: 'New tool',
  },
  {
    id: 'string-entropy-analyzer',
    title: 'String Entropy Analyzer',
    description: 'Analyze randomness and information density of any string. Character class breakdown, pattern detection, and brute-force bit estimation.',
    href: '/tools/string-entropy-analyzer',
    tag: 'New tool',
  },
  {
    id: 'dark-mode-toggle',
    title: 'Dark Mode Toggle',
    description: 'Switch between light and dark themes for comfortable browsing in any lighting condition.',
    href: '/',
    tag: 'UI Enhancement',
  },
  {
    id: 'number-base-converter',
    title: 'Number Base Converter',
    description: 'Convert between binary, octal, decimal, hex, and base-36 with live bit visualization and copy support.',
    href: '/tools/number-base-converter',
    tag: 'New tool',
  },
  {
    id: 'json-path-explorer',
    title: 'JSON Path Explorer',
    description: 'Query JSON data with JSONPath expressions — live results, tree view, filter support, and syntax reference.',
    href: '/tools/json-path-explorer',
    tag: 'New tool',
  },
  {
    id: 'color-blindness-simulator',
    title: 'Color Blindness Simulator',
    description: 'Preview how designs look with protanopia, deuteranopia, tritanopia, and achromatopsia. Includes WCAG contrast checks, palette simulation, and accessibility tips.',
    href: '/tools/color-blindness-simulator',
    tag: 'New tool',
  },
  {
    id: 'json-to-csv-converter',
    title: 'JSON to CSV Converter',
    description: 'Convert JSON arrays, nested objects, or NDJSON to CSV with custom delimiters, flattening, quoting, and live preview table. Upload files or paste directly.',
    href: '/tools/json-to-csv-converter',
    tag: 'New tool',
  },
  {
    id: 'jwt-encoder',
    title: 'JWT Encoder',
    description: 'Create and sign JSON Web Tokens with HMAC algorithms. Supports HS256/384/512, payload presets, random secret generation, and color-coded token parts.',
    href: '/tools/jwt-encoder',
    tag: 'New tool',
  },
  {
    id: 'lorem-ipsum-generator',
    title: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text for designs, prototypes, and mockups. Choose paragraphs, sentences, or words with plain text, HTML, or Markdown output formats.',
    href: '/tools/lorem-ipsum-generator',
    tag: 'New tool',
  },
  {
    id: 'curl-to-javascript',
    title: 'Curl to JavaScript Converter',
    description: 'Convert curl commands to JavaScript Fetch API, Axios, or Node Fetch code instantly. Supports auth, headers, cookies, POST data, and form encoding with live parsing.',
    href: '/tools/curl-to-javascript',
    tag: 'New tool',
  },
  {
    id: 'css-box-model',
    title: 'CSS Box Model Visualizer',
    description: 'Interactive visual exploration of the CSS box model — tweak margin, border, padding, and content with live SVG diagram, presets, and instant CSS or Tailwind output.',
    href: '/tools/css-box-model',
    tag: 'New tool',
  },
  {
    id: 'html-to-jsx',
    title: 'HTML to JSX Converter',
    description: 'Paste HTML and instantly convert it to React JSX. Handles className, htmlFor, inline styles, self-closing tags, JSX comments, and 12+ attribute conversions with conversion reference.',
    href: '/tools/html-to-jsx',
    tag: 'New tool',
  },
  {
    id: 'mock-api-generator',
    title: 'Mock API Generator',
    description: 'Generate realistic fake API data with a visual schema editor. Supports 25+ field types (uuid, email, price, etc.), JSON/curl/Fetch output, and downloadable mock responses.',
    href: '/tools/mock-api-generator',
    tag: 'New tool',
  },
];

const dedupeById = (items: WhatsNewItem[]) => {
  const seen = new Set<string>();
  return items.filter((item) => {
    if (seen.has(item.id)) return false;
    seen.add(item.id);
    return true;
  });
};

export const whatsNewItems: WhatsNewItem[] = dedupeById([...aiLabWhatsNew, ...appWhatsNew]);