'use client';

import { useState, useCallback } from 'react';
import { motion } from 'framer-motion';
import { Copy, Check, FileCode, Plus, Trash2, Download, Shield, ArrowRightLeft, Lock, Globe, Zap, RefreshCw } from 'lucide-react';

interface RedirectRule {
  source: string;
  destination: string;
  type: '301' | '302';
}

interface RewriteRule {
  pattern: string;
  replacement: string;
  flags: string;
}

interface SecurityHeader {
  name: string;
  value: string;
  enabled: boolean;
}

const PRESET_REDIRECTS: { label: string; source: string; dest: string; type: '301' | '302' }[] = [
  { label: 'HTTP → HTTPS', source: '^http://%{HTTP_HOST}/(.*)', dest: 'https://%{HTTP_HOST}/$1', type: '301' },
  { label: 'WWW → non-WWW', source: '^www\\.(.*)$', dest: 'https://$1', type: '301' },
  { label: 'non-WWW → WWW', source: '^(.*)$', dest: 'https://www.$1', type: '301' },
  { label: 'Old path → New path', source: '^/old-page$', dest: '/new-page', type: '301' },
  { label: 'Trailing slash remove', source: '^(.*)/$', dest: '$1', type: '301' },
  { label: 'Add trailing slash', source: '^([^.]*[^/])$', dest: '$1/', type: '301' },
];

const PRESET_CACHING: { label: string; ext: string; time: string }[] = [
  { label: 'Images (1 year)', ext: 'jpg jpeg png gif webp svg ico', time: '31536000' },
  { label: 'CSS/JS (1 month)', ext: 'css js', time: '2592000' },
  { label: 'Fonts (1 year)', ext: 'woff woff2 ttf eot otf', time: '31536000' },
  { label: 'HTML (1 hour)', ext: 'html htm', time: '3600' },
];

const SECURITY_PRESETS: SecurityHeader[] = [
  { name: 'X-Content-Type-Options', value: 'nosniff', enabled: true },
  { name: 'X-Frame-Options', value: 'SAMEORIGIN', enabled: true },
  { name: 'X-XSS-Protection', value: '1; mode=block', enabled: true },
  { name: 'Referrer-Policy', value: 'strict-origin-when-cross-origin', enabled: true },
  { name: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=()', enabled: false },
  { name: 'Strict-Transport-Security', value: 'max-age=31536000; includeSubDomains', enabled: false },
  { name: 'Content-Security-Policy', value: "default-src 'self'; script-src 'self' 'unsafe-inline'", enabled: false },
];

type Tab = 'redirects' | 'rewrites' | 'caching' | 'security' | 'custom';

export default function HtaccessGeneratorPage() {
  const [activeTab, setActiveTab] = useState<Tab>('redirects');
  const [rewriteEngine, setRewriteEngine] = useState(true);
  const [redirects, setRedirects] = useState<RedirectRule[]>([]);
  const [rewrites, setRewrites] = useState<RewriteRule[]>([]);
  const [securityHeaders, setSecurityHeaders] = useState<SecurityHeader[]>(SECURITY_PRESETS);
  const [cachingRules, setCachingRules] = useState<{ ext: string; time: string; enabled: boolean; label: string }[]>(
    PRESET_CACHING.map(c => ({ ...c, enabled: false }))
  );
  const [customRules, setCustomRules] = useState('');
  const [directoryIndex, setDirectoryIndex] = useState(false);
  const [errorDocs, setErrorDocs] = useState<{ code: string; page: string }[]>([
    { code: '404', page: '/404.html' },
  ]);
  const [copied, setCopied] = useState(false);
  const [denyBot, setDenyBot] = useState('');
  const [deniedBots, setDeniedBots] = useState<string[]>([]);

  const addRedirect = () => setRedirects([...redirects, { source: '', destination: '', type: '301' }]);
  const removeRedirect = (i: number) => setRedirects(redirects.filter((_, idx) => idx !== i));
  const addPresetRedirect = (preset: typeof PRESET_REDIRECTS[0]) => {
    setRedirects([...redirects, { source: preset.source, destination: preset.dest, type: preset.type }]);
  };
  const addRewrite = () => setRewrites([...rewrites, { pattern: '', replacement: '', flags: '[L,R=301]' }]);
  const removeRewrite = (i: number) => setRewrites(rewrites.filter((_, idx) => idx !== i));
  const addDeniedBot = () => {
    if (denyBot.trim() && !deniedBots.includes(denyBot.trim())) {
      setDeniedBots([...deniedBots, denyBot.trim()]);
      setDenyBot('');
    }
  };
  const removeDeniedBot = (bot: string) => setDeniedBots(deniedBots.filter(b => b !== bot));

  const addErrorDoc = () => setErrorDocs([...errorDocs, { code: '500', page: '/500.html' }]);

  const generateHtaccess = useCallback((): string => {
    const lines: string[] = [];
    lines.push('# Generated by Zion .htaccess Generator');
    lines.push(`# ${new Date().toISOString().split('T')[0]}`);
    lines.push('');

    if (rewriteEngine) {
      lines.push('RewriteEngine On');
      lines.push('');
    }

    // Redirects
    if (redirects.length > 0) {
      lines.push('# --- Redirects ---');
      for (const r of redirects) {
        if (!r.source || !r.destination) continue;
        if (r.source.startsWith('^http') || r.source.startsWith('^www')) {
          lines.push(`RewriteCond %{HTTP_HOST} ${r.source.replace(/^(\^http:\/\/%{HTTP_HOST}\/|^\^)/, '')}`);
          if (r.source.startsWith('^http')) {
            lines.unshift('RewriteCond %{HTTPS} off');
          }
          lines.push(`RewriteRule ${r.source} ${r.destination} [R=${r.type},L]`);
        } else {
          lines.push(`Redirect ${r.type} ${r.source} ${r.destination}`);
        }
      }
      lines.push('');
    }

    // Rewrite rules
    if (rewrites.length > 0) {
      lines.push('# --- Rewrite Rules ---');
      for (const r of rewrites) {
        if (!r.pattern || !r.replacement) continue;
        lines.push(`RewriteRule ${r.pattern} ${r.replacement} ${r.flags}`);
      }
      lines.push('');
    }

    // Security headers
    const enabledHeaders = securityHeaders.filter(h => h.enabled);
    if (enabledHeaders.length > 0) {
      lines.push('# --- Security Headers ---');
      for (const h of enabledHeaders) {
        lines.push(`Header always set ${h.name} "${h.value}"`);
      }
      lines.push('');
    }

    // Caching
    const enabledCaching = cachingRules.filter(c => c.enabled);
    if (enabledCaching.length > 0) {
      lines.push('# --- Browser Caching ---');
      lines.push('<IfModule mod_expires.c>');
      lines.push('  ExpiresActive On');
      for (const c of enabledCaching) {
        const exts = c.ext.split(' ');
        for (const ext of exts) {
          lines.push(`  ExpiresByType ${ext} "access plus ${c.time} seconds"`);
        }
      }
      lines.push('</IfModule>');
      lines.push('');
    }

    // Block bad bots
    if (deniedBots.length > 0) {
      lines.push('# --- Block Bad Bots ---');
      lines.push('RewriteCond %{HTTP_USER_AGENT} ^(' + deniedBots.join('|') + ') [NC]');
      lines.push('RewriteRule .* - [F,L]');
      lines.push('');
    }

    // Error documents
    if (errorDocs.length > 0) {
      lines.push('# --- Custom Error Pages ---');
      for (const e of errorDocs) {
        if (e.code && e.page) {
          lines.push(`ErrorDocument ${e.code} ${e.page}`);
        }
      }
      lines.push('');
    }

    // Directory index
    if (directoryIndex) {
      lines.push('# --- Directory Index ---');
      lines.push('DirectoryIndex index.html index.php');
      lines.push('');
    }

    // Custom rules
    if (customRules.trim()) {
      lines.push('# --- Custom Rules ---');
      lines.push(customRules.trim());
      lines.push('');
    }

    return lines.join('\n');
  }, [rewriteEngine, redirects, rewrites, securityHeaders, cachingRules, deniedBots, errorDocs, directoryIndex, customRules]);

  const htaccess = generateHtaccess();

  const copyToClipboard = async () => {
    await navigator.clipboard.writeText(htaccess);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadFile = () => {
    const blob = new Blob([htaccess], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = '.htaccess';
    a.click();
    URL.revokeObjectURL(url);
  };

  const tabs: { key: Tab; label: string; icon: React.ReactNode }[] = [
    { key: 'redirects', label: 'Redirects', icon: <ArrowRightLeft className="h-4 w-4" /> },
    { key: 'rewrites', label: 'Rewrites', icon: <RefreshCw className="h-4 w-4" /> },
    { key: 'caching', label: 'Caching', icon: <Zap className="h-4 w-4" /> },
    { key: 'security', label: 'Security', icon: <Shield className="h-4 w-4" /> },
    { key: 'custom', label: 'Custom', icon: <FileCode className="h-4 w-4" /> },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-blue-50">
      <div className="container mx-auto max-w-5xl px-4 py-12">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
          <div className="mb-8 text-center">
            <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-slate-600 to-blue-600 shadow-lg shadow-slate-500/20">
              <FileCode className="h-8 w-8 text-white" />
            </div>
            <h1 className="text-3xl font-bold text-slate-900">.htaccess Generator</h1>
            <p className="mt-2 text-slate-600">Build Apache .htaccess rules with a visual interface — redirects, rewrites, caching, and security headers</p>
          </div>
        </motion.div>

        {/* Tab Navigation */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
          className="mb-6 flex flex-wrap gap-2">
          {tabs.map(t => (
            <button key={t.key} onClick={() => setActiveTab(t.key)}
              className={`flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-medium transition ${
                activeTab === t.key
                  ? 'bg-slate-800 text-white shadow-lg'
                  : 'bg-white text-slate-600 border border-slate-200 hover:border-slate-300'
              }`}>
              {t.icon} {t.label}
            </button>
          ))}
        </motion.div>

        <div className="grid gap-6 lg:grid-cols-2">
          {/* Configuration Panel */}
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
            <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
              {/* Rewrite Engine toggle */}
              <div className="mb-5 flex items-center justify-between rounded-xl bg-slate-50 p-3">
                <div className="flex items-center gap-2">
                  <Globe className="h-4 w-4 text-slate-500" />
                  <span className="text-sm font-medium text-slate-700">RewriteEngine On</span>
                </div>
                <button onClick={() => setRewriteEngine(!rewriteEngine)}
                  className={`relative h-6 w-11 rounded-full transition ${rewriteEngine ? 'bg-blue-600' : 'bg-slate-300'}`}>
                  <span className={`absolute top-0.5 h-5 w-5 rounded-full bg-white shadow transition ${rewriteEngine ? 'left-5.5' : 'left-0.5'}`}
                    style={{ left: rewriteEngine ? '22px' : '2px' }} />
                </button>
              </div>

              {/* Redirects Tab */}
              {activeTab === 'redirects' && (
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-semibold text-slate-700 mb-2">Quick Presets</label>
                    <div className="flex flex-wrap gap-2">
                      {PRESET_REDIRECTS.map((p, i) => (
                        <button key={i} onClick={() => addPresetRedirect(p)}
                          className="rounded-lg border border-blue-200 bg-blue-50 px-3 py-1.5 text-xs font-medium text-blue-700 hover:bg-blue-100 transition">
                          {p.label}
                        </button>
                      ))}
                    </div>
                  </div>
                  <div>
                    <div className="flex items-center justify-between mb-2">
                      <label className="text-sm font-semibold text-slate-700">Redirect Rules</label>
                      <button onClick={addRedirect}
                        className="flex items-center gap-1 rounded-lg bg-blue-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-blue-700">
                        <Plus className="h-3 w-3" /> Add
                      </button>
                    </div>
                    {redirects.length === 0 && (
                      <p className="text-sm text-slate-400 py-4 text-center">No redirect rules yet. Use presets or add custom rules.</p>
                    )}
                    {redirects.map((r, i) => (
                      <div key={i} className="mb-3 rounded-xl border border-slate-200 p-3 space-y-2">
                        <div className="flex items-center gap-2">
                          <select value={r.type} onChange={e => {
                            const updated = [...redirects];
                            updated[i] = { ...r, type: e.target.value as '301' | '302' };
                            setRedirects(updated);
                          }} className="rounded-lg border border-slate-200 px-2 py-1 text-sm">
                            <option value="301">301 (Permanent)</option>
                            <option value="302">302 (Temporary)</option>
                          </select>
                          <button onClick={() => removeRedirect(i)} className="ml-auto text-slate-400 hover:text-red-500">
                            <Trash2 className="h-4 w-4" />
                          </button>
                        </div>
                        <input type="text" placeholder="Source path (e.g., /old-page)" value={r.source}
                          onChange={e => { const u = [...redirects]; u[i] = { ...r, source: e.target.value }; setRedirects(u); }}
                          className="w-full rounded-lg border border-slate-200 px-3 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
                        <input type="text" placeholder="Destination (e.g., /new-page)" value={r.destination}
                          onChange={e => { const u = [...redirects]; u[i] = { ...r, destination: e.target.value }; setRedirects(u); }}
                          className="w-full rounded-lg border border-slate-200 px-3 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Rewrites Tab */}
              {activeTab === 'rewrites' && (
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <label className="text-sm font-semibold text-slate-700">Rewrite Rules</label>
                    <button onClick={addRewrite}
                      className="flex items-center gap-1 rounded-lg bg-blue-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-blue-700">
                      <Plus className="h-3 w-3" /> Add
                    </button>
                  </div>
                  {rewrites.length === 0 && (
                    <p className="text-sm text-slate-400 py-4 text-center">No rewrite rules yet. Add custom mod_rewrite patterns.</p>
                  )}
                  {rewrites.map((r, i) => (
                    <div key={i} className="rounded-xl border border-slate-200 p-3 space-y-2">
                      <div className="flex items-center justify-between">
                        <span className="text-xs font-medium text-slate-500">Rule #{i + 1}</span>
                        <button onClick={() => removeRewrite(i)} className="text-slate-400 hover:text-red-500">
                          <Trash2 className="h-4 w-4" />
                        </button>
                      </div>
                      <input type="text" placeholder="Pattern (e.g., ^products/([0-9]+))" value={r.pattern}
                        onChange={e => { const u = [...rewrites]; u[i] = { ...r, pattern: e.target.value }; setRewrites(u); }}
                        className="w-full rounded-lg border border-slate-200 px-3 py-1.5 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-blue-500" />
                      <input type="text" placeholder="Replacement (e.g., product.php?id=$1)" value={r.replacement}
                        onChange={e => { const u = [...rewrites]; u[i] = { ...r, replacement: e.target.value }; setRewrites(u); }}
                        className="w-full rounded-lg border border-slate-200 px-3 py-1.5 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-blue-500" />
                      <input type="text" placeholder="Flags (e.g., [L,R=301])" value={r.flags}
                        onChange={e => { const u = [...rewrites]; u[i] = { ...r, flags: e.target.value }; setRewrites(u); }}
                        className="w-full rounded-lg border border-slate-200 px-3 py-1.5 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-blue-500" />
                    </div>
                  ))}
                </div>
              )}

              {/* Caching Tab */}
              {activeTab === 'caching' && (
                <div className="space-y-3">
                  <label className="text-sm font-semibold text-slate-700">Browser Caching (mod_expires)</label>
                  {cachingRules.map((c, i) => (
                    <div key={i} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3">
                      <button onClick={() => { const u = [...cachingRules]; u[i] = { ...c, enabled: !c.enabled }; setCachingRules(u); }}
                        className={`relative h-5 w-9 rounded-full transition shrink-0 ${c.enabled ? 'bg-blue-600' : 'bg-slate-300'}`}>
                        <span className="absolute top-0.5 h-4 w-4 rounded-full bg-white shadow"
                          style={{ left: c.enabled ? '18px' : '2px' }} />
                      </button>
                      <div className="flex-1">
                        <p className="text-sm font-medium text-slate-700">{c.label}</p>
                        <p className="text-xs text-slate-500">{c.ext}</p>
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {/* Security Tab */}
              {activeTab === 'security' && (
                <div className="space-y-4">
                  <label className="text-sm font-semibold text-slate-700">Security Headers</label>
                  {securityHeaders.map((h, i) => (
                    <div key={h.name} className="rounded-xl border border-slate-200 p-3">
                      <div className="flex items-center gap-3 mb-2">
                        <button onClick={() => { const u = [...securityHeaders]; u[i] = { ...h, enabled: !h.enabled }; setSecurityHeaders(u); }}
                          className={`relative h-5 w-9 rounded-full transition shrink-0 ${h.enabled ? 'bg-blue-600' : 'bg-slate-300'}`}>
                          <span className="absolute top-0.5 h-4 w-4 rounded-full bg-white shadow"
                            style={{ left: h.enabled ? '18px' : '2px' }} />
                        </button>
                        <span className="text-sm font-medium text-slate-700 font-mono">{h.name}</span>
                      </div>
                      {h.enabled && (
                        <input type="text" value={h.value}
                          onChange={e => { const u = [...securityHeaders]; u[i] = { ...h, value: e.target.value }; setSecurityHeaders(u); }}
                          className="w-full rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-mono text-slate-600 focus:outline-none focus:ring-2 focus:ring-blue-500" />
                      )}
                    </div>
                  ))}
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-2">Block User Agents</label>
                    <div className="flex gap-2 mb-2">
                      <input type="text" placeholder="Bot name (e.g., BadBot)" value={denyBot}
                        onChange={e => setDenyBot(e.target.value)}
                        onKeyDown={e => e.key === 'Enter' && addDeniedBot()}
                        className="flex-1 rounded-lg border border-slate-200 px-3 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
                      <button onClick={addDeniedBot}
                        className="rounded-lg bg-slate-800 px-3 py-1.5 text-sm font-medium text-white hover:bg-slate-700">Block</button>
                    </div>
                    {deniedBots.length > 0 && (
                      <div className="flex flex-wrap gap-2">
                        {deniedBots.map(b => (
                          <span key={b} className="flex items-center gap-1 rounded-lg bg-red-50 border border-red-200 px-2 py-1 text-xs font-medium text-red-700">
                            {b}
                            <button onClick={() => removeDeniedBot(b)} className="hover:text-red-900">×</button>
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              )}

              {/* Custom Tab */}
              {activeTab === 'custom' && (
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <label className="text-sm font-semibold text-slate-700">Directory Index</label>
                    <button onClick={() => setDirectoryIndex(!directoryIndex)}
                      className={`relative h-5 w-9 rounded-full transition ${directoryIndex ? 'bg-blue-600' : 'bg-slate-300'}`}>
                      <span className="absolute top-0.5 h-4 w-4 rounded-full bg-white shadow"
                        style={{ left: directoryIndex ? '18px' : '2px' }} />
                    </button>
                  </div>
                  <div>
                    <div className="flex items-center justify-between mb-2">
                      <label className="text-sm font-semibold text-slate-700">Custom Error Pages</label>
                      <button onClick={addErrorDoc}
                        className="flex items-center gap-1 rounded-lg bg-blue-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-blue-700">
                        <Plus className="h-3 w-3" /> Add
                      </button>
                    </div>
                    {errorDocs.map((e, i) => (
                      <div key={i} className="flex items-center gap-2 mb-2">
                        <input type="text" placeholder="404" value={e.code}
                          onChange={ev => { const u = [...errorDocs]; u[i] = { ...e, code: ev.target.value }; setErrorDocs(u); }}
                          className="w-20 rounded-lg border border-slate-200 px-3 py-1.5 text-sm text-center focus:outline-none focus:ring-2 focus:ring-blue-500" />
                        <input type="text" placeholder="/404.html" value={e.page}
                          onChange={ev => { const u = [...errorDocs]; u[i] = { ...e, page: ev.target.value }; setErrorDocs(u); }}
                          className="flex-1 rounded-lg border border-slate-200 px-3 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
                        <button onClick={() => setErrorDocs(errorDocs.filter((_, idx) => idx !== i))} className="text-slate-400 hover:text-red-500">
                          <Trash2 className="h-4 w-4" />
                        </button>
                      </div>
                    ))}
                  </div>
                  <div>
                    <label className="block text-sm font-semibold text-slate-700 mb-2">Custom Rules</label>
                    <textarea value={customRules} onChange={e => setCustomRules(e.target.value)}
                      rows={6} placeholder="# Add your custom .htaccess rules here&#10;Options -Indexes&#10;php_value memory_limit 256M"
                      className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm font-mono text-slate-700 focus:outline-none focus:ring-2 focus:ring-blue-500" />
                  </div>
                </div>
              )}
            </div>
          </motion.div>

          {/* Output Panel */}
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}>
            <div className="sticky top-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-lg font-semibold text-slate-900">Generated .htaccess</h2>
                <div className="flex gap-2">
                  <button onClick={copyToClipboard}
                    className="flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-1.5 text-sm text-slate-600 hover:bg-slate-50 transition">
                    {copied ? <Check className="h-4 w-4 text-emerald-500" /> : <Copy className="h-4 w-4" />}
                    {copied ? 'Copied!' : 'Copy'}
                  </button>
                  <button onClick={downloadFile}
                    className="flex items-center gap-1.5 rounded-lg bg-slate-800 px-3 py-1.5 text-sm text-white hover:bg-slate-700 transition">
                    <Download className="h-4 w-4" /> Download
                  </button>
                </div>
              </div>
              <pre className="max-h-[600px] overflow-auto rounded-xl bg-slate-900 p-4 text-sm text-slate-100 font-mono whitespace-pre-wrap">
                {htaccess}
              </pre>
              <p className="mt-3 text-xs text-slate-500">
                ⚠️ Always back up your existing .htaccess file before applying changes. Test in a staging environment first.
              </p>
            </div>
          </motion.div>
        </div>
      </div>
    </div>
  );
}
