#!/usr/bin/env python3
"""
composio-devops-event-agent.py
=================================
DevOps Event-Driven Agent — reage a eventos em tempo real via Composio Triggers.

 Fluxos suportados:
   - GitHub PR merged → cria release + deploy Vercel + health check + Slack + Sentry + Linear
   - GitHub commit → summary + notificação Slack
   - Sentry alert → cria issue Linear + sugere fix + notifica on-call
   - PostHog metric threshold → alerta + sugere investigação
   - Vercel deploy status → atualiza status page + Slack

 Uso:
   1. Configurar COMPOSIO_API_KEY + vars
   2. Subscrever triggers: python composio-devops-event-agent.py subscribe
   3. Ou testar localmente: python composio-devops-event-agent.py listen
   4. Ou executar fluxo manual: python composio-devops-event-agent.py run pr_merged 42

 Exemplo de trigger subscription (uma vez):
   export COMPOSIO_API_KEY="sk_..."
   python composio-devops-event-agent.py subscribe github_pr_merged
   python composio-devops-event-agent.py subscribe sentry_alert
   python composio-devops-event-agent.py subscribe posthog_threshold
   python composio-devops-event-agent.py subscribe vercel_deploy_status
"""

import os
import sys
import json
import time
from datetime import datetime
from composio import Composio

# ========== CONFIG ==========
COMPOSIO_API_KEY = os.environ.get("COMPOSIO_API_KEY", "")
GITHUB_OWNER = os.environ.get("GITHUB_OWNER", "Zion-TechGroup")
GITHUB_REPO = os.environ.get("GITHUB_REPO", "zion.app")
VERCEL_PROJECT = os.environ.get("VERCEL_PROJECT", "zion-tech-group")
SLACK_CHANNEL = os.environ.get("ZION_SLACK_CHANNEL", "#status")
SENTRY_AUTH_TOKEN = os.environ.get("SENTRY_AUTH_TOKEN", "")
POSTHOG_API_KEY = os.environ.get("POSTHOG_API_KEY", "")
POSTHOG_URL = os.environ.get("POSTHOG_URL", "https://app.posthog.com")
LINEAR_TEAM_ID = os.environ.get("ZION_LINEAR_TEAM_ID", "")
WEBHOOK_SECRET = os.environ.get("COMPOSIO_WEBHOOK_SECRET", "")
WEBHOOK_URL = os.environ.get("COMPOSIO_WEBHOOK_URL", "")

SCRIPT_DIR = "/Users/miami2/zion.app/automation/scripts"

# ========== SDK ==========
def get_sdk():
    if not COMPOSIO_API_KEY:
        print("ERRO: COMPOSIO_API_KEY não configurada")
        sys.exit(1)
    return Composio(api_key=COMPOSIO_API_KEY)

def tool_execute(sdk, tool_name, args, user_id="zion-bot"):
    try:
        return sdk.tools.execute(tool_name, arguments=args, user_id=user_id)
    except Exception as e:
        print(f"  ⚠ Erro em {tool_name}: {e}")
        return None

# ========== TRIGGER MANAGEMENT ==========
def list_triggers(sdk):
    """Lista triggers disponíveis."""
    print("\n📋 Triggers disponíveis no Composio:")
    try:
        result = sdk.triggers.list() if hasattr(sdk, 'triggers') else None
        if result:
            for t in result.get("items", []):
                print(f"  • {t.get('slug')} — {t.get('name')}")
        else:
            print("  (sem resultados ou método não disponível)")
    except Exception as e:
        print(f"  Erro: {e}")

def subscribe_trigger(sdk, trigger_slug, webhook_url=None):
    """Assina um trigger para receber eventos."""
    url = webhook_url or WEBHOOK_URL
    if not url:
        print("ERRO: COMPOSIO_WEBHOOK_URL não configurada")
        return None
    
    print(f"\n🔔 Subscrevendo trigger: {trigger_slug}")
    print(f"   Webhook URL: {url}")
    
    try:
        subscription = sdk.triggers.set_webhook_subscription(
            webhook_url=url,
            trigger_slugs=[trigger_slug],
        )
        print(f"   ✅ Subscrito! Secret: {subscription.get('secret', 'N/A')[:20]}...")
        print(f"   Armazenar secret em: export COMPOSIO_WEBHOOK_SECRET='{subscription.get('secret', '')}'")
        return subscription
    except Exception as e:
        print(f"  ⚠ Erro: {e}")
        return None

def unsubscribe_trigger(sdk, trigger_slug):
    """Desassina um trigger."""
    print(f"\n⛔ Desassinando trigger: {trigger_slug}")
    try:
        sdk.triggers.delete_webhook_subscription(trigger_slug=trigger_slug)
        print("   ✅ Desassinado")
    except Exception as e:
        print(f"  Erro: {e}")

# ========== FLUXOS (HANDLERS) ==========
def handle_pr_merged(event_data):
    """Fluxo: PR merged → release + deploy + health check + Slack + Sentry + Linear."""
    pr_number = event_data.get("pull_request_number", "")
    pr_title = event_data.get("title", "")
    print(f"\n🚀 PR #{pr_number} merged: {pr_title}")
    
    # 1. Criar release no GitHub
    print("   📦 Criando release...")
    changelog = f"## Auto Release — {datetime.now().strftime('%Y-%m-%d')}\n\n### PR #{pr_number}: {pr_title}\n\nAutomatically generated by DevOps Event Agent."
    
    release = tool_execute(sdk=get_sdk(), tool_name="GITHUB_CREATE_RELEASE", args={
        "owner": GITHUB_OWNER,
        "repo": GITHUB_REPO,
        "tag_name": f"auto-{datetime.now().strftime('%Y%m%d-%H%M')}",
        "name": f"Auto Release {datetime.now().strftime('%Y-%m-%d')}",
        "body": changelog,
        "draft": False,
    })
    
    if release:
        print(f"   ✅ Release criada: {release.get('html_url', 'OK')}")
    
    # 2. Trigger deploy Vercel
    print("   🚀 Triggering Vercel deploy...")
    deploy = tool_execute(sdk=get_sdk(), tool_name="VERCEL_CREATE_DEPLOYMENT", args={
        "projectId": VERCEL_PROJECT,
        "clean": True,
    })
    
    # 3. Health check
    print("   🏥 Health check...")
    health_url = f"https://{GITHUB_OWNER.lower().replace('-', '')}.com"
    import urllib.request
    try:
        urllib.request.urlopen(health_url, timeout=10)
        health = "✅ healthy"
        print(f"   {health}")
    except Exception as e:
        health = f"⚠️ erro: {e}"
        print(f"   {health}")
    
    # 4. Slack notification
    message = f"*🚀 Deploy—{datetime.now().strftime('%Y-%m-%d %H:%M')}*\n\n"
    message += f"PR: #{pr_number} {pr_title}\n"
    message += f"Status: {health}\n"
    if release:
        message += f"Release: {release.get('html_url', 'N/A')}\n"
    
    tool_execute(sdk=get_sdk(), tool_name="SLACK_SEND_MESSAGE", args={
        "channel": SLACK_CHANNEL,
        "text": message,
    })
    
    print("   ✅ Slack notificado")

def handle_sentry_alert(event_data):
    """Fluxo: Sentry alert → Linear issue + sugere fix + Slack on-call."""
    error_title = event_data.get("title", "Erro no Sentry")
    error_message = event_data.get("message", "")[:500]
    error_url = event_data.get("url", "")
    
    print(f"\n🚨 Sentry Alert: {error_title}")
    
    # 1. Criar issue no Linear
    issue = tool_execute(sdk=get_sdk(), tool_name="LINEAR_CREATE_ISSUE", args={
        "teamId": LINEAR_TEAM_ID,
        "title": f"🚨 {error_title[:60]}",
        "description": f"**Sentry:** [{error_title}]({error_url})\n\n{error_message}\n\nSuggested fix: investigar stack trace e logs correlacionados.",
        "priority": 1,  # urgent
        "labels": ["sentry", "bug"],
    })
    
    if issue:
        issue_id = issue.get("id", issue.get("issueId", ""))
        print(f"   ✅ Linear issue criada: {issue_id}")
    
    # 2. Slack notification
    message = f"*🚨 Sentry Alert — {datetime.now().strftime('%H:%M')}*\n\n"
    message += f"**{error_title}**\n"
    message += f"[Ver no Sentry]({error_url})\n"
    if issue:
        message += f"Linear issue: {issue_id}\n"
    
    tool_execute(sdk=get_sdk(), tool_name="SLACK_SEND_MESSAGE", args={
        "channel": "#alerts",
        "text": message,
    })
    
    print("   ✅ Slack notificado")

def handle_posthog_threshold(event_data):
    """Fluxo: PostHog metric threshold → alerta + sugere investigação."""
    metric = event_data.get("metric", "conversions")
    value = event_data.get("value", 0)
    threshold = event_data.get("threshold", 0)
    comparison = event_data.get("comparison", "below")  # below, above
    
    print(f"\n📊 PostHog Alert: {metric} {comparison} {threshold} (valor: {value})")
    
    message = f"*📊 PostHog Metric Alert — {datetime.now().strftime('%H:%M')}*\n\n"
    message += f"**{metric}** {comparison} threshold {threshold}\n"
    message += f"Valor atual: {value}\n\n"
    
    if comparison == "below":
        message += "*Ação sugerida:* Investigar causa da queda — verificar deploy recente, alterações de UX, problemas técnicos.\n"
    else:
        message += f"*Ação sugerida:* Celebrar/monitorar seu avanço.\n"
    
    tool_execute(sdk=get_sdk(), tool_name="SLACK_SEND_MESSAGE", args={
        "channel": "#metrics",
        "text": message,
    })
    
    print("   ✅ Slack notificado")

def handle_vercel_deploy_status(event_data):
    """Fluxo: Vercel deploy status → atualiza status page + Slack."""
    deploy_id = event_data.get("deployment_id", "")
    status = event_data.get("status", "")
    url = event_data.get("url", "")
    
    print(f"\n🛰️ Vercel Deploy #{deploy_id}: {status}")
    
    # Status page update
    status_icon = "✅" if status == "ready" else "⚠️ Building" if status == "building" else "🔴 Error"
    message = f"*🛰️ Vercel Deploy #{deploy_id}*\n\n"
    message += f"Status: {status_icon} {status}\n"
    if url:
        message += f"URL: {url}\n"
    message += f"Tempo: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
    
    tool_execute(sdk=get_sdk(), tool_name="SLACK_SEND_MESSAGE", args={
        "channel": SLACK_CHANNEL,
        "text": message,
    })
    
    print("   ✅ Slack notificado")

# ========== EVENT DISPATCHER ==========
EVENT_HANDLERS = {
    "GITHUB_PULL_REQUEST_MERGE": handle_pr_merged,
    "GITHUB_COMMIT_EVENT": lambda d: print(f"\n📝 Commit: {d.get('message', '')[:80]}") or None,
    "SENTRY_ALERT": handle_sentry_alert,
    "POSTHOG_METRIC_THRESHOLD": handle_posthog_threshold,
    "VERCEL_DEPLOY_STATUS": handle_vercel_deploy_status,
}

def parse_webhook(request_body, request_headers):
    """Parse webhook payload do Composio (V3)."""
    import hmac
    import hashlib
    import base64
    
    secret = WEBHOOK_SECRET
    
    # Verificar assinatura se secret configurado
    if secret:
        webhook_id = request_headers.get("webhook-id", "")
        webhook_timestamp = request_headers.get("webhook-timestamp", "")
        signature = request_headers.get("webhook-signature", "")
        
        if webhook_id and webhook_timestamp and signature:
            signing_string = f"{webhook_id}.{webhook_timestamp}.{request_body}"
            try:
                expected = base64.b64encode(
                    hmac.new(secret.encode(), signing_string.encode(), hashlib.sha256).digest()
                ).decode()
                received = signature.split(",", 1)[1] if "," in signature else signature
                if not hmac.compare_digest(expected, received):
                    print("❌ Assinatura webhook inválida")
                    return None
            except Exception as e:
                print(f"⚠ Erro ao verificar assinatura: {e}")
    
    # Parse V3 payload
    try:
        payload = json.loads(request_body)
        metadata = payload.get("metadata", {})
        trigger_slug = metadata.get("trigger_slug", "")
        data = payload.get("data", {})
        
        return {
            "trigger_slug": trigger_slug,
            "data": data,
            "timestamp": payload.get("timestamp", ""),
        }
    except Exception as e:
        print(f"❌ Erro ao parsear payload: {e}")
        return None

def handle_webhook_request(body, headers):
    """Handler principal para webhook requests."""
    event = parse_webhook(body, headers)
    if not event:
        return {"status": "error", "message": "Invalid webhook"}
    
    trigger_slug = event["trigger_slug"]
    handler = EVENT_HANDLERS.get(trigger_slug)
    
    if handler:
        print(f"\n⚡ Trigger recebido: {trigger_slug}")
        result = handler(event["data"])
        return {"status": "ok", "handler": trigger_slug}
    else:
        print(f"\n⚡ Trigger desconhecido: {trigger_slug}")
        return {"status": "ok", "handler": "unknown", "trigger": trigger_slug}

# ========== MAIN ==========
def main():
    if not COMPOSIO_API_KEY:
        print("ERRO: COMPOSIO_API_KEY não configurada")
        print("Exemplo: export COMPOSIO_API_KEY='sk_...'")
        sys.exit(1)
    
    sdk = get_sdk()
    
    if len(sys.argv) < 2:
        print("""
📋 Composio DevOps Event Agent — Uso:

  python composio-devops-event-agent.py list
      → Lista triggers disponíveis

  python composio-devops-event-agent.py subscribe <trigger_slug>
      → Assina trigger para receber eventos

  python composio-devops-event-agent.py unsubscribe <trigger_slug>
      → Desassina trigger

  python composio-devops-event-agent.py listen
      → Escuta webhooks localmente (necessita COMPOSIO_WEBHOOK_URL)

  python composio-devops-event-agent.py run <trigger_slug> <json_data>
      → Executa handler manualmente (teste)

  python composio-devops-event-agent.py handle <json_payload>
      → Handle webhook payload completo (teste)
""")
        return
    
    command = sys.argv[1]
    
    if command == "list":
        list_triggers(sdk)
    
    elif command == "subscribe":
        if len(sys.argv) < 3:
            print("Uso: python composio-devops-event-agent.py subscribe <trigger_slug>")
            print("Exemplo: python composio-devops-event-agent.py subscribe GITHUB_PULL_REQUEST_MERGE")
            return
        trigger_slug = sys.argv[2]
        subscribe_trigger(sdk, trigger_slug)
    
    elif command == "unsubscribe":
        if len(sys.argv) < 3:
            print("Uso: python composio-devops-event-agent.py unsubscribe <trigger_slug>")
            return
        trigger_slug = sys.argv[2]
        unsubscribe_trigger(sdk, trigger_slug)
    
    elif command == "listen":
        print("\n👂 Escutando webhooks em http://localhost:8000/webhooks/composio ...")
        print("   (Pressione Ctrl+C para parar)")
        print("   Configure COMPOSIO_WEBHOOK_URL=https://seu-app.com/webhooks/composio para produção")
        # Simulação — em produção usar FastAPI/Flask server
        try:
            from http.server import HTTPServer, BaseHTTPRequestHandler
            import json as json_mod
            
            class WebhookHandler(BaseHTTPRequestHandler):
                def do_POST(self):
                    content_length = int(self.headers.get('Content-Length', 0))
                    body = self.rfile.read(content_length).decode('utf-8')
                    headers = {k: v for k, v in self.headers.items()}
                    
                    result = handle_webhook_request(body, headers)
                    
                    self.send_response(200)
                    self.send_header('Content-Type', 'application/json')
                    self.end_headers()
                    self.wfile.write(json_mod.dumps(result).encode())
                
                def log_message(self, format, *args):
                    print(f"  [webhook] {args[0]}")
            
            server = HTTPServer(('localhost', 8000), WebhookHandler)
            print("   ✅ Server rodando em http://localhost:8000/webhooks/composio")
            server.serve_forever()
        except KeyboardInterrupt:
            print("\n   ⛔ Parado pelo usuário")
    
    elif command == "run":
        if len(sys.argv) < 4:
            print("Uso: python composio-devops-event-agent.py run <trigger_slug> <json_data>")
            print("Exemplo: python composio-devops-event-agent.py run GITHUB_PULL_REQUEST_MERGE '{\"pull_request_number\": 42, \"title\": \"Fix bug\"}'")
            return
        trigger_slug = sys.argv[2]
        data_str = sys.argv[3]
        try:
            data = json.loads(data_str)
        except:
            data = {"raw": data_str}
        handler = EVENT_HANDLERS.get(trigger_slug)
        if handler:
            print(f"\n⚡ Executando trigger: {trigger_slug}")
            handler(data)
        else:
            print(f"❌ Handler não encontrado para: {trigger_slug}")
    
    elif command == "handle":
        if len(sys.argv) < 3:
            print("Uso: python composio-devops-event-agent.py handle '<json_payload>'")
            return
        body = sys.argv[2]
        headers = {
            "webhook-id": os.environ.get("TEST_WEBHOOK_ID", "test-id"),
            "webhook-timestamp": datetime.now().isoformat(),
            "webhook-signature": "fake",
        }
        result = handle_webhook_request(body, headers)
        print(json.dumps(result, indent=2))
    
    else:
        print(f"❌ Comando desconhecido: {command}")

if __name__ == "__main__":
    main()
